project:
  type: website
  output-dir: docs

website:
  title: "Modelling-the-flow-of-biomass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

