{
  "hash": "0bfa8ed05500cdbfce21a8fc673c9d20",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 26: Closing Day 25's Loose Ends, and a Delay That Actually Causes a Hopf Bifurcation\"\nauthor: \"Samia\"\ndate: \"2026-07-13\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, juvenile-pileup, alpha, time-delay, hopf-bifurcation, predator-prey, blog]\ndescription: \"Day 25's three loose ends closed: a tighter alpha window, a resolved gamma dip, and a confirmed amplitude decay. Separately, delaying the prey's self-limitation (rather than the predator's conversion) is shown to genuinely produce a Hopf bifurcation, unlike either delay variant tested on Day 25.\"\n---\n\n## Where Day 25 Left Us\n\nDay 25 closed the alpha/gamma/kappa juvenile-pileup sweep and ruled out a Hopf bifurcation for the time-delay predator-prey model analytically, but left three threads open: pin down alpha's transition window more precisely, check whether the gamma = 305.8 dip was real or an under-settled transient, and confirm the tau = 40/80 amplitude climb actually decays to zero given a longer `t_max` rather than plateauing. All three are closed today, in `26_experiments.R`. Along the way, a direct question came up about the delay model itself. If a time delay usually destabilises systems, why did Day 25 find it couldn't here, which led to re-deriving the Hopf condition for two different places the delay could sit, one of which does produce one.\n\n------------------------------------------------------------------------\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\nlibrary(colorRamps)\nlibrary(future)\nlibrary(scales)\nlibrary(deSolve)\n```\n:::\n\n\nSame anchovy builder and the same `catchable_fraction_at()`/`run_param_sweep()` pair from Day 25, carried over unchanged so today's refinements are directly comparable to the sweeps that found the transition and the dip in the first place:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_second_order_params_kr <- function(lambda = 2.05, resource_decrease = 0.001,\n                                        capacity_mult = 1, second_order = TRUE,\n                                        ext_diff = 0.00, alpha = 0.1, gamma = 750,\n                                        ks = 0, kappa_override = NULL) {\n  a0    <- 100\n  kappa <- if (is.null(kappa_override)) a0 * exp(-6.9 * (lambda - 1)) else kappa_override\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = alpha, gamma = gamma, ks = ks\n  )\n\n  given_species_params(params)$D_ext <- ext_diff\n  params <- setBevertonHolt(params)\n\n  default_capacity <- getResourceCapacity(params)\n  r  <- getResourceRate(params) * resource_decrease\n  cc <- default_capacity * capacity_mult\n\n  params <- setResource(params, resource_rate = r, resource_capacity = cc,\n                        resource_dynamics = \"resource_semichemostat\",\n                        balance = FALSE)\n\n  if (second_order) {\n    second_order_w(params) <- c(flux = \"centred\", bin_average = TRUE)\n  }\n\n  params\n}\n\ncatchable_fraction_at <- function(params, t_max = 600) {\n  sim <- project(params, t_max = t_max, dt = 0.1, t_save = 0.5,\n                 progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n  last  <- dim(sim@n)[1]\n  w_mat <- params@species_params$w_mat[1]\n  w     <- sim@params@w\n  dw    <- sim@params@dw\n\n  bm_density   <- sim@n[last, 1, ] * w * dw\n  total_bm     <- sum(bm_density)\n  catchable_bm <- sum(bm_density[w >= w_mat])\n\n  data.frame(catchable_fraction = catchable_bm / total_bm, error = NA_character_)\n}\n\nrun_param_sweep <- function(param_name, param_seq, capacity_mult = 10,\n                            resource_decrease = 0.001, t_max = 600) {\n  bind_rows(lapply(param_seq, function(v) {\n    args <- list(capacity_mult = capacity_mult, resource_decrease = resource_decrease)\n    args[[param_name]] <- v\n    result <- tryCatch({\n      p <- do.call(make_second_order_params_kr, args)\n      catchable_fraction_at(p, t_max = t_max)\n    }, error = function(e) {\n      data.frame(catchable_fraction = NA_real_, error = conditionMessage(e))\n    })\n    if (!is.na(result$error)) {\n      warning(sprintf(\"%s = %.4g: %s\", param_name, v, result$error))\n    }\n    data.frame(param = param_name, value = v,\n               catchable_fraction = result$catchable_fraction,\n               error = result$error)\n  }))\n}\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Pinning Down Alpha's Transition Window\n\nDay 25's 15-point alpha sweep found the catchable fraction jumps roughly 8 orders of magnitude somewhere between `alpha = 0.057` and `alpha = 0.28`. This is a viability threshold, but the grid was never dense enough to say exactly where the steep part starts and ends. Same move as Day 24's `capacity_mult` refinement: 25 points, log-spaced, zoomed into `[0.05, 0.3]`, at the same `t_run = 600` so the two sweeps stay directly comparable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_seq_refine <- exp(seq(log(0.05), log(0.3), length.out = 25))\nalpha_refine_df  <- run_param_sweep(\"alpha\", alpha_seq_refine)\n```\n:::\n\n\nUnlike `capacity_mult`'s collapse bifurcation, there's no natural alive/dead split here. `catchable_fraction` rises smoothly (if steeply) from near-zero to a real plateau, not a bistable jump at one point. So the \"transition window\" is bracketed with two threshold crossings instead of one: where the climb clearly starts (still under 0.1%) and where it's clearly finished (already over 10%):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfind_crossing <- function(df, threshold, value_col = \"value\",\n                          metric_col = \"catchable_fraction\") {\n  df    <- df %>% arrange(.data[[value_col]])\n  below <- df %>% filter(.data[[metric_col]] < threshold)  %>% pull(.data[[value_col]])\n  above <- df %>% filter(.data[[metric_col]] >= threshold) %>% pull(.data[[value_col]])\n  data.frame(\n    threshold   = threshold,\n    below_last  = if (length(below) > 0) max(below) else NA_real_,\n    above_first = if (length(above) > 0) min(above) else NA_real_\n  )\n}\n\nLOW_THRESHOLD  <- 1e-3\nHIGH_THRESHOLD <- 0.10\n\nalpha_crossings <- bind_rows(\n  find_crossing(alpha_refine_df %>% filter(is.na(error)), LOW_THRESHOLD)  %>% mutate(edge = \"climb starts\"),\n  find_crossing(alpha_refine_df %>% filter(is.na(error)), HIGH_THRESHOLD) %>% mutate(edge = \"climb ends\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(alpha_refine_df %>% filter(is.na(error)), aes(x = value, y = catchable_fraction)) +\n  geom_line(color = \"#4C72B0\", linewidth = 1) +\n  geom_point(color = \"#4C72B0\", size = 1.5) +\n  geom_hline(yintercept = c(LOW_THRESHOLD, HIGH_THRESHOLD), linetype = \"dotted\", color = \"grey40\") +\n  geom_vline(xintercept = 0.1, linetype = \"dashed\", color = \"grey40\") +\n  scale_y_log10(labels = scales::label_scientific()) +\n  scale_x_log10() +\n  labs(x = \"alpha (assimilation efficiency)\", y = \"Catchable fraction (biomass at or above w_mat)\",\n       title = \"Refined alpha sweep: pinning down the transition window\",\n       subtitle = \"25 points over [0.05, 0.3] -- dotted = threshold crossings; dashed = anchovy's own alpha = 0.1\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-13-day-twenty-six_files/figure-html/alpha-plot-1.png){width=672}\n:::\n:::\n\n\n| edge                        | bracket                    |\n|-----------------------------|----------------------------|\n| Climb starts (crosses 0.1%) | `alpha ∈ (0.1055, 0.1137]` |\n| Climb ends (crosses 10%)    | `alpha ∈ (0.1651, 0.1779]` |\n\nThe whole steep part of the climb is compressed into a genuinely narrow window, `alpha ≈ 0.105–0.178` is much tighter than Day 25's coarse \"somewhere between 0.057 and 0.28.\" The anchovy's own `alpha = 0.1` sits at `0.0237%` catchable fraction, just below the 0.1% \"climb starts\" threshold, which confirms Day 25's \"sits right at the foot of the climb\" with an actual number behind it rather than an eyeball read.\n\n------------------------------------------------------------------------\n\n## Is the Gamma = 305.8 Dip Real, or an Under-Settled Transient?\n\nDay 25's 15-point gamma sweep found one point that breaks monotonicity: `gamma = 305.8` read `9.48e-5`, dipping below both its neighbours (`231 → 2.45e-4`, `404 → 4.03e-4`) at `t_run = 600`. Flagged at the time as possibly critical slowing down. This is the same explanation Day 24 used for its own default-species Forward-branch spike. This reruns exactly that point and its immediate neighbours (located dynamically off the original 15-point grid, not hardcoded) at increasingly long `t_run`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngamma_full_seq   <- exp(seq(log(100), log(5000), length.out = 15))\ndip_idx          <- which.min(abs(gamma_full_seq - 305.8))\nneighbour_idx    <- unique(pmax(1, pmin(length(gamma_full_seq), c(dip_idx - 1, dip_idx, dip_idx + 1))))\ngamma_check_vals <- gamma_full_seq[neighbour_idx]\n\nt_run_check_seq <- c(600, 1200, 2400, 4800)\n\ngamma_dip_check_df <- bind_rows(lapply(t_run_check_seq, function(tr) {\n  bind_rows(lapply(gamma_check_vals, function(g) {\n    p   <- make_second_order_params_kr(gamma = g, capacity_mult = 10, resource_decrease = 0.001)\n    res <- catchable_fraction_at(p, t_max = tr)\n    data.frame(gamma = g, t_run = tr, catchable_fraction = res$catchable_fraction)\n  }))\n}))\n\ndip_persistence <- gamma_dip_check_df %>%\n  group_by(t_run) %>%\n  arrange(gamma, .by_group = TRUE) %>%\n  summarise(\n    dip_still_present = catchable_fraction[2] < catchable_fraction[1] &\n                        catchable_fraction[2] < catchable_fraction[3],\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gamma_dip_check_df, aes(x = t_run, y = catchable_fraction, color = factor(round(gamma, 1)))) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 1.5) +\n  scale_x_log10() +\n  scale_y_log10(labels = scales::label_scientific()) +\n  labs(x = \"t_run\", y = \"Catchable fraction\",\n       title = \"Is the gamma = 305.8 dip real or an under-settled transient?\",\n       subtitle = \"Same point and its two neighbours, rerun at increasing t_run\", color = \"gamma\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-13-day-twenty-six_files/figure-html/gamma-dip-plot-1.png){width=672}\n:::\n:::\n\n\nThe likely explanation: `catchable_fraction_at()` doesn't average over a settled window. It instead reads a single snapshot at the last saved timestep of `t_max`. If the system at this operating point (`capacity_mult = 10`, `resource_decrease = 0.001`, the fixed baseline every juvenile-pileup sweep since Day 24 has used) is still gently oscillating rather than sitting at a true fixed point, then varying `t_max` just samples different *phases* of that oscillation, not different amounts of settling time. That's consistent with Day 22/23's own phase-diagram work: `capacity_mult = 10` sits just past where Day 23's refined `[3, 10]` grid found \"a complete reversal\" from fixed-point to oscillating. The noise floor this reveals (values bouncing 2–3x between reruns) is negligible next to alpha's 27.5-order-of-magnitude range, but it's comparable to or larger than gamma's and kappa's entire reported ranges so those two \"close to flat\" / \"modest effect\" conclusions from Day 25 may be sampling noise from an unsettled oscillation rather than a real parameter effect. Directly checking whether this operating point is actually oscillating (a real time series, not single-snapshot reads) is the natural follow-up.\n\n------------------------------------------------------------------------\n\n## Confirming the Amplitude Decay for the Conversion-Delay Model\n\nDay 25's time-delay predator-prey model (delay on the predator's conversion of intake into biomass) was proven analytically to never support a Hopf bifurcation, for any delay or parameters ,but `rel_amplitude_P` was still climbing with `tau` across the tested range (up to 0.25 at `tau = 40`), which the algebra says must eventually decay rather than plateau. Reproducing Day 25's model exactly first, to confirm the base case, then extending `t_max` well past the original 300:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredator_prey_params_delay <- list(D = 1, a = 1, e = 0.5, m = 0.3, K = 1)\n\ncheck_hopf_feasibility <- function(parms = predator_prey_params_delay) {\n  D <- parms$D; a <- parms$a; e <- parms$e; m <- parms$m; K <- parms$K\n  N_star <- m / (e * a)\n  P_star <- D * (K - N_star) / (a * N_star)\n  alpha  <- D + a * P_star\n  beta   <- a * N_star\n  gamma  <- e * a * P_star\n  data.frame(N_star = N_star, P_star = P_star, alpha = alpha, beta = beta,\n             gamma = gamma, beta_gamma = beta * gamma, two_m_alpha = 2 * m * alpha,\n             hopf_possible = (beta * gamma) > (2 * m * alpha))\n}\nhopf_check <- check_hopf_feasibility()\n\npredator_prey_rhs_delay <- function(t, state, parms) {\n  N <- max(state[1], 0); P <- max(state[2], 0)\n  D <- parms[[\"D\"]]; a <- parms[[\"a\"]]; e <- parms[[\"e\"]]\n  m <- parms[[\"m\"]]; K <- parms[[\"K\"]]; tau <- parms[[\"tau\"]]\n  N0 <- parms[[\"N0\"]]; P0 <- parms[[\"P0\"]]\n  if (t <= tau) { lag_N <- N0; lag_P <- P0\n  } else { lag <- lagvalue(t - tau); lag_N <- max(lag[1], 0); lag_P <- max(lag[2], 0) }\n  dN <- D * (K - N) - a * N * P\n  dP <- e * a * lag_N * lag_P - m * P\n  list(c(dN, dP))\n}\n\nrun_predator_prey_delay_long <- function(tau, t_max_long, state0 = c(N = 1, P = 0.1),\n                                         parms = predator_prey_params_delay) {\n  parms$tau <- tau; parms$N0 <- state0[[\"N\"]]; parms$P0 <- state0[[\"P\"]]\n  as.data.frame(dede(y = state0, times = seq(0, t_max_long, by = 0.1),\n                     func = predator_prey_rhs_delay, parms = parms))\n}\n\namplitude_at_cutoff <- function(ts_df, t_max_effective) {\n  late <- ts_df[ts_df$time > t_max_effective * 0.6 & ts_df$time <= t_max_effective, ]\n  data.frame(t_max = t_max_effective, rel_amplitude_P = (max(late$P) - min(late$P)) / mean(late$P))\n}\n\ntau_check_seq   <- c(40, 80)\nt_max_check_seq <- c(300, 600, 1200, 2400, 4800, 9600)\n\nts_long_by_tau <- setNames(\n  lapply(tau_check_seq, function(tau) run_predator_prey_delay_long(tau, max(t_max_check_seq))),\n  tau_check_seq\n)\n\ndecay_check_df <- bind_rows(lapply(tau_check_seq, function(tau) {\n  ts_long <- ts_long_by_tau[[as.character(tau)]]\n  bind_rows(lapply(t_max_check_seq, function(tm) amplitude_at_cutoff(ts_long, tm) %>% mutate(tau = tau)))\n}))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(decay_check_df, aes(x = t_max, y = rel_amplitude_P, color = factor(tau))) +\n  geom_line(linewidth = 1) + geom_point(size = 1.5) +\n  scale_x_log10() + scale_y_log10(labels = scales::label_scientific()) +\n  labs(x = \"t_max\", y = \"Relative amplitude of P, late window\",\n       title = \"Does rel_amplitude_P decay to ~0 given enough time, or plateau?\",\n       subtitle = \"tau = 40 and 80, re-windowed at longer cutoffs -- analytic prediction: decays to 0\",\n       color = \"tau\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-13-day-twenty-six_files/figure-html/decay-plot-1.png){width=672}\n:::\n:::\n\n\nBoth `tau` values decay across 15 orders of magnitude to machine-precision zero, obviously not a plateau. A separate endpoint check (distance from the trajectory's final `N, P` to the analytic equilibrium) confirms it directly: both `tau = 40` and `tau = 80` land within `3.7e-15` of `(N^*, P^*)` by `t_max = 9600`. That closes Day 25's third loose end: the climbing amplitude sweep was measuring an unfinished monotonic relaxation, not a real or growing oscillation, exactly as the algebra predicted.\n\n------------------------------------------------------------------------\n\n## Why Couldn't Delay Cause an Instability Here?\n\nDay 25's model delays the predator's *conversion* of intake into biomass, but leaves the prey's own self-limitation instantaneous:\n\n```         \ndN/dt = D(K - N(t))       - aN(t)P(t)\ndP/dt = eaN(t-tau)P(t-tau) - mP(t)\n```\n\n**Step 1: Linearise and get the characteristic equation.**\n\nLinearising around equilibrium and substituting `n, p ~ e^(lambda t)` gives the characteristic equation, with `alpha = D + aP^*`, `beta = aN^*`, `gamma = eaP^*`:\n\n```         \n(lambda+alpha)(lambda+m-me^(-lambda tau)) + beta gamma e^(-lambda tau) = 0\n```\n\n**Step 2: Find the Hopf condition.**\n\nSetting `lambda = i omega` (the only way a root can cross from stable to unstable as `tau` grows) and matching `|P(i omega)| = |Q(i omega)|` reduces this to a quadratic in `u = omega^2`:\n\n```         \nu^2 + alpha^2 u + beta gamma (2 m alpha - beta gamma) = 0\n```\n\nBy Vieta's formulas, the sum of the two roots is `-alpha^2` (always negative), so a positive root, a crossing frequency, can only exist if the *product*, `beta gamma (2 m alpha - beta gamma)`, is negative, i.e. if `beta gamma > 2 m alpha`.\n\n**Step 3: Check whether that condition can ever hold.**\n\nSubstituting the actual definitions and simplifying (using the equilibrium relation `eaN^* = m`):\n\n```         \nbeta gamma - 2 m alpha = -a m P^* - 2 m D\n```\n\nFactoring out `-mD` (after substituting `P^* = D(K-N^*)/(aN^*)`) gives a strikingly clean closed form:\n\n```         \nbeta gamma - 2 m alpha = -mD(K+N^*)/N^*\n```\n\nEvery quantity in that bracket is positive, so `D` sits as a bare positive multiplier on an unconditionally negative expression, for *any* positive `D, a, e, m, K`, this can never be positive. The undelayed prey renewal term `D` is doing all the work: it's a restoring force that acts at full strength regardless of `tau`, and it's strong enough here to prevent any Hopf bifurcation, no matter the delay.\n\nThat raised an obvious question: what if the delay sat somewhere else?\n\n------------------------------------------------------------------------\n\n## Delay Only the Predator's Intake, Not Its Own Growth\n\nA natural intermediate case: what if only `P(t-tau)` is delayed inside the predator's growth term, while `N(t)` there stays instantaneous?\n\n```         \ndN/dt = D(K - N(t))       - aN(t)P(t)\ndP/dt = eaN(t)P(t-tau)     - mP(t)\n```\n\n### The Maths\n\n**Step 1: Linearise.**\n\n`dp/dt = gamma n(t) + m p(t-tau) - m p(t)`, the `n` term loses its delay, but the `m p(t-tau)` term survives (it comes from `N^*` , a constant , multiplying the still-delayed `P(t-tau)`).\n\n**Step 2: The characteristic equation.**\n\nThis becomes, with `alpha = D+aP^*` as in the original model, but now with `beta gamma` carrying no `e^(-lambda tau)` factor at all:\n\n```         \n(lambda+alpha)(lambda+m-me^(-lambda tau)) + beta gamma = 0\n```\n\n**Step 3: Match moduli.**\n\n```         \nu^2 + (alpha^2 - 2 beta gamma) u + beta gamma(2 alpha m + beta gamma) = 0\n```\n\nThe product of roots, `beta gamma(2 alpha m + beta gamma)`, is always positive (every factor is positive). This is the same situation as the self-limitation model, so both roots share a sign and the sum decides which:\n\n```         \nHopf possible  <=>  2 beta gamma > alpha^2\n```\n\n**Step 4: Reduce to a threshold on D.**\n\nWriting `P^* = D*C` (`C = (K-N^*)/(aN^*)`, independent of `D`) and substituting through reduces this to a genuine threshold on D, unlike the absolute impossibility of the original model and unlike the self-limitation model's condition (which held outright at the reference parameters):\n\n```         \nD < 2 a m C / (1 + a C)^2\n```\n\nAt the reference parameters (`N^*=0.6, C=0.667`), that threshold works out to `~0.144`. `D=1` is far above it, so no Hopf is predicted at the reference `D`, tested below alongside `D=0.1`, comfortably under the threshold.\n\n### Confirming It Numerically\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredator_prey_rhs_pdelay <- function(t, state, parms) {\n  N <- max(state[1], 0); P <- max(state[2], 0)\n  D <- parms[[\"D\"]]; a <- parms[[\"a\"]]; e <- parms[[\"e\"]]\n  m <- parms[[\"m\"]]; K <- parms[[\"K\"]]; tau <- parms[[\"tau\"]]; P0 <- parms[[\"P0\"]]\n  lag_P <- if (t <= tau) P0 else max(lagvalue(t - tau, 2), 0)\n  dN <- D * (K - N) - a * N * P\n  dP <- e * a * N * lag_P - m * P\n  list(c(dN, dP))\n}\n\nrun_predator_prey_pdelay <- function(tau, state0 = c(N = 1, P = 0.1), t_max = 300,\n                                     parms = predator_prey_params_delay) {\n  parms$tau <- tau; parms$P0 <- state0[[\"P\"]]\n  out  <- as.data.frame(dede(y = state0, times = seq(0, t_max, by = 0.1),\n                             func = predator_prey_rhs_pdelay, parms = parms))\n  late <- out[out$time > t_max * 0.6, ]\n  data.frame(tau = tau, max_N = max(late$N), min_N = min(late$N),\n             max_P = max(late$P), min_P = min(late$P),\n             rel_amplitude_P = (max(late$P) - min(late$P)) / mean(late$P))\n}\n\nparams_small_D  <- modifyList(predator_prey_params_delay, list(D = 0.1))\ntau_seq_pdelay  <- c(0, 0.5, 1, 2, 3, 5, 7, 10, 15, 20)\n\npdelay_sweep_refD   <- bind_rows(lapply(tau_seq_pdelay, run_predator_prey_pdelay)) %>%\n  mutate(D_label = \"D = 1 (above threshold)\")\npdelay_sweep_smallD <- bind_rows(lapply(tau_seq_pdelay, run_predator_prey_pdelay,\n                                        parms = params_small_D)) %>%\n  mutate(D_label = \"D = 0.1 (below threshold)\")\npdelay_sweep_df <- bind_rows(pdelay_sweep_refD, pdelay_sweep_smallD)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pdelay_sweep_df, aes(x = tau, y = rel_amplitude_P, color = D_label)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.5) +\n  labs(x = \"tau (delay in P(t-tau) term only, N instantaneous)\", y = \"Relative amplitude of P\",\n       title = \"Delaying only P inside the intake term: a threshold on D, not an absolute block\",\n       subtitle = \"Derived threshold D < 0.144 -- tested on both sides\", color = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-13-day-twenty-six_files/figure-html/pdelay-plot-1.png){width=672}\n:::\n:::\n\n\nAt `D=1` (above threshold), `rel_amplitude_P` climbs smoothly from `1.8e-10` to `0.145` by `tau=20`.This is the same shape as the original conversion-delay model's non-Hopf climb, as expected. At `D=0.1` (below threshold, Hopf predicted), the climb is smaller and equally gradual, reaching only `0.033` by `tau=20`, with no sharp transition visible anywhere in the tested range.\n\nA persistence check at `D=0.1, tau=10` settles it: `rel_amplitude_P` at `t_max = 300, 1500, 3000` is `0.00164 → 9.18e-14 → 1.04e-15` - collapsing toward machine-precision zero. That's the exact \"critical slowing down, not real oscillation\" signature from earlier, not a sustained cycle. So even though `D=0.1` genuinely satisfies the derived existence condition, `tau=10` isn't past the real onset for this variant so the true critical `tau` must sit somewhere beyond 20, not yet located. This is a real, if unglamorous, result: the analytic threshold on `D` is correctly derived and internally consistent, but pinning down *where* (in `tau`) the bifurcation actually occurs for a given `D` needs a wider sweep than was run today.\n\n------------------------------------------------------------------------\n\n## What This All Adds Up To\n\nThree loose ends from Day 25 closed cleanly: alpha's transition window is now a precise `(0.105, 0.178)` bracket, the tau = 40/80 amplitude climb is confirmed to decay to machine-precision zero rather than plateau, and the gamma = 305.8 dip turned out to be more interesting than either \"real\" or \"transient\". Its non-monotonic flipping points at an unsettled oscillation at the sweep's own operating point, which puts a question mark over gamma and kappa's \"modest effect\" conclusions from Day 25 that alpha's huge range was never at risk from.\n\nThe deeper result is about *where* a delay sits, not whether delay can destabilise a system in general. Delaying the predator's conversion (Day 25's model) can never produce a Hopf bifurcation here, for any parameters - proven by factoring the destabilising quantity into `-mD(K+N^*)/N^*`, a bare positive `D` multiplying an unconditionally negative bracket. A delay only the predator's intake, not its own growth, derives a genuine threshold on `D` rather than an absolute block, but the specific `tau` tested wasn't far enough to actually see it.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Find the actual critical tau for the P-only-delay variant at D=0.1.** Extend `tau_seq_pdelay` well past 20 (e.g. up to 40–60) and rerun the persistence check at each candidate onset to locate where `rel_amplitude_P` stops decaying and starts holding steady.\n- **Characterise how far past onset the self-limitation model's amplitude stays biologically sensible.** `min_N` is already negative at `tau=2.4` (barely past onset) and reaches `-15.5` by `tau=20`. It's worth finding the `tau` range where `N` stays non-negative, and considering whether a saturating term (a proper functional response, rather than mass-action) would cap the amplitude the way it should.\n- **Check directly whether `capacity_mult=10, resource_decrease=0.001` is actually oscillating**, rather than reading single-timestep snapshots at different `t_max`. A real time series at this exact operating point would settle whether the gamma/kappa sweep's noise floor is genuine unsettled oscillation or something else.\n- **Rerun gamma and kappa's isolation sweeps with a windowed-average read** (the same \"late window\" convention used throughout the delay-model work) instead of a single final-timestep snapshot, to check whether their \"modest\"/\"flat\" Day 25 conclusions survive averaging out whatever phase-sampling noise today's gamma recheck exposed.\n- **Carry these toy-model findings back over to the actual size-spectrum (mizer) model.** Everything above was worked out on the abstract two-species predator-prey system, not on the anchovy model itself - the natural next step is checking which of these delay mechanisms, if any, has a real biological analogue in the size-spectrum setting, and whether it could plausibly help explain the juvenile-pileup dynamics this project has been tracking since Day 6.\n",
    "supporting": [
      "2026-07-13-day-twenty-six_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}