<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samia">
<meta name="dcterms.date" content="2026-06-24">
<meta name="description" content="Two days spent mostly off the R console: hunting down good resources for properly learning the discrete Fourier transform, working through limit cycles and into bifurcations in Strogatz, picking group velocity back up in the wave-motion textbook, and continuing the fishing-only-the-peaks investigation. Also revisits generation time: the steady-state calculation gives 2.38, but replacing the fixed growth rate with the real, time-varying growth field and tracking cohorts through it pulls that back up to about 3.27, closer to the original ballpark guess.">

<title>Day 12 and 13: Learning the Discrete Fourier Transform, Limit Cycles, and a Second Look at Generation Time – Modelling-the-flow-of-biomass</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a9447a135e5b1c05e5522b7712596fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Modelling-the-flow-of-biomass</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tuesday-hunting-for-dft-resources-and-a-second-look-at-generation-time" id="toc-tuesday-hunting-for-dft-resources-and-a-second-look-at-generation-time" class="nav-link active" data-scroll-target="#tuesday-hunting-for-dft-resources-and-a-second-look-at-generation-time">Tuesday: Hunting for DFT Resources, and a Second Look at Generation Time</a>
  <ul class="collapse">
  <li><a href="#where-to-actually-learn-the-dft" id="toc-where-to-actually-learn-the-dft" class="nav-link" data-scroll-target="#where-to-actually-learn-the-dft">Where to Actually Learn the DFT</a></li>
  <li><a href="#limit-cycles" id="toc-limit-cycles" class="nav-link" data-scroll-target="#limit-cycles">Limit Cycles</a></li>
  <li><a href="#generation-time-checked-again" id="toc-generation-time-checked-again" class="nav-link" data-scroll-target="#generation-time-checked-again">Generation Time, Checked Again</a></li>
  <li><a href="#does-the-growth-rate-assumption-hold-up" id="toc-does-the-growth-rate-assumption-hold-up" class="nav-link" data-scroll-target="#does-the-growth-rate-assumption-hold-up">Does the Growth Rate Assumption Hold Up?</a></li>
  </ul></li>
  <li><a href="#wednesday-closing-out-dft-and-limit-cycles-starting-bifurcations-back-to-waves" id="toc-wednesday-closing-out-dft-and-limit-cycles-starting-bifurcations-back-to-waves" class="nav-link" data-scroll-target="#wednesday-closing-out-dft-and-limit-cycles-starting-bifurcations-back-to-waves">Wednesday: Closing Out DFT and Limit Cycles, Starting Bifurcations, Back to Waves</a>
  <ul class="collapse">
  <li><a href="#can-you-beat-constant-fishing-by-fishing-only-the-peaks" id="toc-can-you-beat-constant-fishing-by-fishing-only-the-peaks" class="nav-link" data-scroll-target="#can-you-beat-constant-fishing-by-fishing-only-the-peaks">Can You Beat Constant Fishing by Fishing Only the Peaks?</a></li>
  </ul></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 12 and 13: Learning the Discrete Fourier Transform, Limit Cycles, and a Second Look at Generation Time</h1>
  <div class="quarto-categories">
    <div class="quarto-category">research</div>
    <div class="quarto-category">mizer</div>
    <div class="quarto-category">dft</div>
    <div class="quarto-category">nonlinear-dynamics</div>
    <div class="quarto-category">waves</div>
    <div class="quarto-category">fishing-strategy</div>
    <div class="quarto-category">blog</div>
  </div>
  </div>

<div>
  <div class="description">
    Two days spent mostly off the R console: hunting down good resources for properly learning the discrete Fourier transform, working through limit cycles and into bifurcations in Strogatz, picking group velocity back up in the wave-motion textbook, and continuing the fishing-only-the-peaks investigation. Also revisits generation time: the steady-state calculation gives 2.38, but replacing the fixed growth rate with the real, time-varying growth field and tracking cohorts through it pulls that back up to about 3.27, closer to the original ballpark guess.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="tuesday-hunting-for-dft-resources-and-a-second-look-at-generation-time" class="level2">
<h2 class="anchored" data-anchor-id="tuesday-hunting-for-dft-resources-and-a-second-look-at-generation-time">Tuesday: Hunting for DFT Resources, and a Second Look at Generation Time</h2>
<p>Day 11 used <code>fft()</code> as a black box to get a dominant period and a phase argument out of the simulation, with a note left in “What’s Next” to actually learn what the transform is doing rather than keep treating it as a library call. Tuesday went looking for resources to do that properly, rather than diving straight back into mizer.</p>
<section id="where-to-actually-learn-the-dft" class="level3">
<h3 class="anchored" data-anchor-id="where-to-actually-learn-the-dft">Where to Actually Learn the DFT</h3>
<p>The most useful resources found were:</p>
<ul>
<li><a href="https://ccrma.stanford.edu/~jos/st/Discrete_Fourier_Transform_DFT.html">Julius O. Smith III’s <em>Discrete Fourier Transform (DFT)</em></a>, the Stanford CCRMA page on the DFT, which derives the transform itself rather than just stating the formula and lists the standard properties (linearity, the shift and convolution theorems, Parseval’s relation) in one place.</li>
<li>YouTube explanations from <strong>3Blue1Brown</strong> and <strong>Steve Brunton</strong>, for the geometric “winding the signal around a circle at different frequencies” intuition that’s harder to get from a written derivation alone.</li>
</ul>
<p>The rest of Tuesday’s DFT time went into working through that material and starting a proper set of notes rather than anything that produces code or numbers worth showing here.</p>
</section>
<section id="limit-cycles" class="level3">
<h3 class="anchored" data-anchor-id="limit-cycles">Limit Cycles</h3>
<p>Alongside the DFT, Tuesday’s reading time also went into Strogatz’s <em>Nonlinear Dynamics and Chaos</em>, picking up the limit-cycle chapter that had been queued since Day 11 (the system’s boom-bust oscillation is exactly the kind of self-sustained periodic attractor that chapter is about, and Day 11 had been reasoning about phase and feedback without that theory underneath it).</p>
</section>
<section id="generation-time-checked-again" class="level3">
<h3 class="anchored" data-anchor-id="generation-time-checked-again">Generation Time, Checked Again</h3>
<p>The other piece of Tuesday went back to Day 11’s generation-time calculation, re-running the same steady-state age-at-size integral to make sure the number being carried forward was right rather than half-remembered:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizer)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizerExperimental)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Same single-species Anchovy setup as Day 8/11.</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>run_anchovy <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda) {</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt =</span> <span class="fl">0.001</span>, <span class="at">dx =</span> <span class="fl">0.1</span>, <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_mat =</span> <span class="dv">10</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>, <span class="at">lambda =</span> lambda, <span class="at">a0 =</span> <span class="dv">100</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> p<span class="sc">$</span>a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (p<span class="sc">$</span>lambda <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(p<span class="sc">$</span>w_max <span class="sc">/</span> p<span class="sc">$</span>w_min) <span class="sc">/</span> p<span class="sc">$</span>dx)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_min =</span> p<span class="sc">$</span>w_min, <span class="at">w_max =</span> p<span class="sc">$</span>w_max, <span class="at">w_mat =</span> p<span class="sc">$</span>w_mat,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w  =</span> no_w,    <span class="at">lambda =</span> p<span class="sc">$</span>lambda, <span class="at">kappa =</span> kappa,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> p<span class="sc">$</span>alpha, <span class="at">gamma  =</span> p<span class="sc">$</span>gamma,  <span class="at">ks    =</span> <span class="dv">0</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> <span class="fl">0.001</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  params<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> params<span class="sc">@</span>cc_pp <span class="sc">*</span> <span class="fl">0.1</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>                 <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  idx  <span class="ot">&lt;-</span> params<span class="sc">@</span>w <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> params<span class="sc">@</span>w <span class="sc">&lt;=</span> <span class="dv">100</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  last <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  sim<span class="sc">@</span>n[last, , idx] <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[last, , idx] <span class="sc">/</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">3</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  sim     <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">90</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                     <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  sim_300 <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">200</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                     <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  sim_600 <span class="ot">&lt;-</span> <span class="fu">project</span>(sim_300, <span class="at">t_max =</span> <span class="dv">300</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                     <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">params =</span> params, <span class="at">sim_600 =</span> sim_600)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Reused from Day 8/11: power spectrum of a (mean-subtracted) signal.</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>power_spectrum <span class="ot">&lt;-</span> <span class="cf">function</span>(signal, dt) {</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  signal <span class="ot">&lt;-</span> signal <span class="sc">-</span> <span class="fu">mean</span>(signal)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  n      <span class="ot">&lt;-</span> <span class="fu">length</span>(signal)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  freqs  <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span>(n <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (n <span class="sc">*</span> dt)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>  power  <span class="ot">&lt;-</span> <span class="fu">Mod</span>(<span class="fu">fft</span>(signal))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>  half   <span class="ot">&lt;-</span> <span class="fu">seq_len</span>(<span class="fu">floor</span>((n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span>))</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">freq =</span> freqs[half], <span class="at">period =</span> <span class="dv">1</span> <span class="sc">/</span> freqs[half], <span class="at">power =</span> power[half <span class="sc">+</span> <span class="dv">1</span>])</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>run_2   <span class="ot">&lt;-</span> <span class="fu">run_anchovy</span>(<span class="dv">2</span>)</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>params  <span class="ot">&lt;-</span> run_2<span class="sc">$</span>params</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>sim_600 <span class="ot">&lt;-</span> run_2<span class="sc">$</span>sim_600</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>times   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">dimnames</span>(sim_600<span class="sc">@</span>n)[[<span class="dv">1</span>]])</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>bm      <span class="ot">&lt;-</span> <span class="fu">getBiomass</span>(sim_600)[, <span class="st">"Anchovy"</span>]</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>ps      <span class="ot">&lt;-</span> <span class="fu">power_spectrum</span>(bm[times <span class="sc">&gt;</span> <span class="dv">300</span>], <span class="fl">0.2</span>)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>period_dom <span class="ot">&lt;-</span> ps<span class="sc">$</span>period[<span class="fu">which.max</span>(ps<span class="sc">$</span>power)]</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="co"># age(w) = integral_{w_min}^{w} 1/g(w') dw' under the steady-state growth</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="co"># rate, i.e. how long a fish takes to grow from w_min up to w.</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>g  <span class="ot">&lt;-</span> <span class="fu">getEGrowth</span>(params)[<span class="st">"Anchovy"</span>, ]</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>w  <span class="ot">&lt;-</span> params<span class="sc">@</span>w</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>dw <span class="ot">&lt;-</span> params<span class="sc">@</span>dw</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>integrand  <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> g</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>age        <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">cumsum</span>((integrand[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">+</span> integrand[<span class="sc">-</span><span class="fu">length</span>(integrand)]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">*</span> dw[<span class="sc">-</span><span class="fu">length</span>(dw)]))</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>age_at_mat <span class="ot">&lt;-</span> <span class="fu">approx</span>(<span class="at">x =</span> w, <span class="at">y =</span> age, <span class="at">xout =</span> params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat)<span class="sc">$</span>y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">period_dom =</span> period_dom, <span class="at">age_at_mat =</span> age_at_mat,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">ratio =</span> period_dom <span class="sc">/</span> age_at_mat), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>period_dom age_at_mat      ratio 
     8.333      3.497      2.383 </code></pre>
</div>
</div>
<p>The dominant oscillation period comes out at 8.33 years, age-at-maturity at 3.50 years, giving a period-to-generation-time ratio of 2.38. The earlier working assumption had been “about 3 generations” per period; the actual calculated number sits a bit below that, closer to “two and a bit” generations than three. Worth flagging honestly: this uses the same fixed, steady-state growth rate as Day 11, not a growth rate that varies with the cycle, so the number is a snapshot to build on rather than a final answer.</p>
</section>
<section id="does-the-growth-rate-assumption-hold-up" class="level3">
<h3 class="anchored" data-anchor-id="does-the-growth-rate-assumption-hold-up">Does the Growth Rate Assumption Hold Up?</h3>
<p>Day 11 derived a clean prediction for how phase should depend on growth rate, then checked it against the actual data and found it failed: the measured phase curve didn’t fall steadily the way the proof predicted, and the relative phase drop from <span class="math inline">\(w_{min}\)</span> to <span class="math inline">\(w_{mat}\)</span> had the wrong sign and was far too small in magnitude. An assumption behind that proof were flagged as suspect: that growth rate is fixed at its steady-state value when the food supply driving it actually oscillates along with everything else. The generation-time number just calculated rests on that same fixed-growth-rate assumption (<code>getEGrowth(params)</code>, evaluated at the steady state), so before moving on to the DFT and limit-cycle reading, it was worth checking directly how much that assumption was costing.</p>
<section id="why-you-cant-just-separate-variables-for-gwt" class="level4">
<h4 class="anchored" data-anchor-id="why-you-cant-just-separate-variables-for-gwt">Why You Can’t Just Separate Variables for <span class="math inline">\(g(w,t)\)</span></h4>
<p>The steady-state version of the age calculation rests on separating variables in <span class="math inline">\(dw/dt = g(w)\)</span>:</p>
<p><span class="math display">\[\frac{dw}{g(w)} = dt \quad\Longrightarrow\quad a(w) = \int_{w_{min}}^{w} \frac{dw'}{g(w')}\]</span></p>
<p>This works because <span class="math inline">\(g(w)\)</span> depends only on <span class="math inline">\(w\)</span>, so all the <span class="math inline">\(w\)</span>-stuff can be put on one side and all the <span class="math inline">\(t\)</span>-stuff on the other before integrating each side independently. The moment growth rate also depends on time, <span class="math inline">\(g(w,t)\)</span>, that move stops being valid:</p>
<p><span class="math display">\[\frac{dw}{g(w,t)} = dt\]</span></p>
<p>looks the same, but the left side still has a <span class="math inline">\(t\)</span> buried inside it, and that <span class="math inline">\(t\)</span> isn’t free to integrate away on its own, because <span class="math inline">\(w\)</span> and <span class="math inline">\(t\)</span> are linked along the very trajectory being solved for. Writing <span class="math inline">\(\int dw/g(w,t)\)</span> in isolation doesn’t mean anything yet: you’d need to already know <span class="math inline">\(w(t)\)</span> to know what to plug into <span class="math inline">\(g\)</span> at each step, which is circular.</p>
<p>There’s one case where separation still rescues you: if the time-dependence factors out multiplicatively, <span class="math inline">\(g(w,t) = g_0(w)\,h(t)\)</span> (e.g.&nbsp;food availability scaling every size class’s growth by the same relative amount), then</p>
<p><span class="math display">\[\frac{dw}{g_0(w)} = h(t)\,dt \quad\Longrightarrow\quad A(w) = H(t) - H(t_{\text{birth}})\]</span></p>
<p>where <span class="math inline">\(A(w) = \int_{w_{min}}^w dw'/g_0(w')\)</span> and <span class="math inline">\(H\)</span> is an antiderivative of <span class="math inline">\(h\)</span>. This still gives a closed form, but a cohort-dependent one: <span class="math inline">\(t_{\text{peak}}(w) = H^{-1}(A(w) + H(t_{\text{birth}}))\)</span> now depends on <span class="math inline">\(t_{\text{birth}}\)</span> in a nonlinear way, unlike the steady-state case where every cohort shares the same offset <span class="math inline">\(a(w)\)</span>. There was no good reason to expect mizer’s actual <span class="math inline">\(g(w,t)\)</span> to factor this cleanly, though, so rather than gamble on that assumption, the honest route is the fully general one: solve <span class="math inline">\(dw/dt = g(w,t)\)</span> as the coupled equation it is, numerically, for each cohort separately. That’s what <code>project()</code> is already doing internally; the next step just pulls a labelled cohort’s trajectory back out of it after the fact.</p>
</section>
<section id="building-gwt-from-the-simulations-own-history" class="level4">
<h4 class="anchored" data-anchor-id="building-gwt-from-the-simulations-own-history">Building <span class="math inline">\(g(w,t)\)</span> From the Simulation’s Own History</h4>
<p><code>getEGrowth()</code> doesn’t have to be evaluated at the steady state. It recomputes growth from whatever population state <code>n</code> and resource state <code>n_pp</code> you hand it, so feeding each saved time step’s actual state back in gives the real, time-varying growth field instead of a single fixed snapshot:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recompute growth at every saved time step in the settled window, using</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># that time step's actual (n, n_pp), not the unperturbed steady state.</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>post     <span class="ot">&lt;-</span> times <span class="sc">&gt;</span> <span class="dv">300</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>idx_post <span class="ot">&lt;-</span> <span class="fu">which</span>(post)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA_real_</span>, <span class="at">nrow =</span> <span class="fu">length</span>(idx_post), <span class="at">ncol =</span> <span class="fu">length</span>(w))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_along</span>(idx_post)) {</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  i      <span class="ot">&lt;-</span> idx_post[k]</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  n_t    <span class="ot">&lt;-</span> <span class="fu">array</span>(sim_600<span class="sc">@</span>n[i, , , <span class="at">drop =</span> <span class="cn">FALSE</span>], <span class="at">dim =</span> <span class="fu">dim</span>(sim_600<span class="sc">@</span>n)[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">dimnames =</span> <span class="fu">dimnames</span>(sim_600<span class="sc">@</span>n)[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  n_pp_t <span class="ot">&lt;-</span> sim_600<span class="sc">@</span>n_pp[i, ]</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  G[k, ] <span class="ot">&lt;-</span> <span class="fu">getEGrowth</span>(params, <span class="at">n =</span> n_t, <span class="at">n_pp =</span> n_pp_t)[<span class="st">"Anchovy"</span>, ]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>times_post <span class="ot">&lt;-</span> times[idx_post]</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>t_save     <span class="ot">&lt;-</span> times_post[<span class="dv">2</span>] <span class="sc">-</span> times_post[<span class="dv">1</span>]   <span class="co"># 0.2, matches the project() calls above</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>This shows that <code>getEGrowth(params, n = n_t, n_pp = n_pp_t)</code> for a single time step gives a growth profile very close to, but not identical to, the steady-state <code>getEGrowth(params)</code> used above. At <span class="math inline">\(t=19.8\)</span> (an early, still-settling point), the smallest-size growth rate was 0.00683 vs.&nbsp;0.00673 from the steady state, a small difference at that particular moment. The whole point of building <code>G</code> across every saved time step is that this difference isn’t constant, it swings with the cycle, and the steady-state calculation used only the time-averaged-looking (but actually unperturbed-equilibrium) snapshot.</p>
</section>
<section id="tracking-real-cohorts-through-the-oscillation" class="level4">
<h4 class="anchored" data-anchor-id="tracking-real-cohorts-through-the-oscillation">Tracking Real Cohorts Through the Oscillation</h4>
<p>With <code>G</code> built, a cohort’s trajectory is found by integrating <span class="math inline">\(dw/dt = g(w,t)\)</span> forward from <span class="math inline">\(w_{min}\)</span>, looking up the growth rate at the cohort’s <em>current</em> size and time at every step rather than assuming a fixed function of size alone:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bilinear-style lookup: blend the two bracketing saved time snapshots, then</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># interpolate across size, to get g(w,t) at an arbitrary (t, w).</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>g_lookup <span class="ot">&lt;-</span> <span class="cf">function</span>(t, w_now) {</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  idx   <span class="ot">&lt;-</span> <span class="fu">floor</span>((t <span class="sc">-</span> times_post[<span class="dv">1</span>]) <span class="sc">/</span> t_save) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  idx   <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">max</span>(idx, <span class="dv">1</span>), <span class="fu">nrow</span>(G) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  frac  <span class="ot">&lt;-</span> (t <span class="sc">-</span> times_post[idx]) <span class="sc">/</span> t_save</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  g_vec <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> frac) <span class="sc">*</span> G[idx, ] <span class="sc">+</span> frac <span class="sc">*</span> G[idx <span class="sc">+</span> <span class="dv">1</span>, ]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">approx</span>(<span class="at">x =</span> w, <span class="at">y =</span> g_vec, <span class="at">xout =</span> w_now, <span class="at">rule =</span> <span class="dv">2</span>)<span class="sc">$</span>y</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Forward-integrate a single fish born at t_birth through the real,</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># time-varying growth field (simple Euler stepping; dt_step is fine enough</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># relative to the ~8 year period that finer stepping doesn't change the result).</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>track_cohort <span class="ot">&lt;-</span> <span class="cf">function</span>(t_birth, <span class="at">w_min =</span> <span class="fu">min</span>(params<span class="sc">@</span>w), <span class="at">w_max =</span> <span class="fu">max</span>(params<span class="sc">@</span>w),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dt_step =</span> <span class="fl">0.02</span>) {</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  t_now <span class="ot">&lt;-</span> t_birth; w_now <span class="ot">&lt;-</span> w_min</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  t_vec <span class="ot">&lt;-</span> t_now;   w_vec <span class="ot">&lt;-</span> w_now</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span> (w_now <span class="sc">&lt;</span> w_max <span class="sc">&amp;&amp;</span> t_now <span class="sc">&lt;</span> <span class="fu">max</span>(times_post) <span class="sc">-</span> <span class="dv">1</span>) {</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    g_now <span class="ot">&lt;-</span> <span class="fu">g_lookup</span>(t_now, w_now)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(g_now) <span class="sc">||</span> g_now <span class="sc">&lt;=</span> <span class="dv">0</span>) <span class="cf">break</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    w_now <span class="ot">&lt;-</span> w_now <span class="sc">+</span> g_now <span class="sc">*</span> dt_step</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    t_now <span class="ot">&lt;-</span> t_now <span class="sc">+</span> dt_step</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    t_vec <span class="ot">&lt;-</span> <span class="fu">c</span>(t_vec, t_now); w_vec <span class="ot">&lt;-</span> <span class="fu">c</span>(w_vec, w_now)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">t =</span> t_vec, <span class="at">w =</span> w_vec, <span class="at">age =</span> t_vec <span class="sc">-</span> t_birth)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Track cohorts born at five phases spread across one full cycle, to see how</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># much age-at-size depends on when a cohort happens to be born.</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>period_dom_check <span class="ot">&lt;-</span> period_dom   <span class="co"># 8.333333, the dominant FFT period from above</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>birth_times <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">305</span>, <span class="dv">305</span> <span class="sc">+</span> period_dom_check, <span class="at">length.out =</span> <span class="dv">6</span>)[<span class="sc">-</span><span class="dv">6</span>]</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>cohorts     <span class="ot">&lt;-</span> <span class="fu">lapply</span>(birth_times, track_cohort)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cohorts) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"t_birth="</span>, <span class="fu">round</span>(birth_times, <span class="dv">2</span>))</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>df_cohorts <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(cohorts), <span class="cf">function</span>(nm) {</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> cohorts[[nm]]; d<span class="sc">$</span>cohort <span class="ot">&lt;-</span> nm; d</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_cohorts, <span class="fu">aes</span>(<span class="at">x =</span> w, <span class="at">y =</span> age, <span class="at">colour =</span> cohort)) <span class="sc">+</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"body mass (g)"</span>, <span class="at">y =</span> <span class="st">"age since birth (years)"</span>,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Age-at-size for cohorts born at different phases"</span>, <span class="at">colour =</span> <span class="st">"birth time"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-23-day-twelve_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ages_at_mat <span class="ot">&lt;-</span> <span class="fu">sapply</span>(cohorts, <span class="cf">function</span>(co)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">approx</span>(<span class="at">x =</span> co<span class="sc">$</span>w, <span class="at">y =</span> co<span class="sc">$</span>age, <span class="at">xout =</span> params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat)<span class="sc">$</span>y)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ages_at_mat, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   t_birth=305 t_birth=306.67 t_birth=308.33    t_birth=310 t_birth=311.67 
         2.464          2.512          2.808          2.490          2.467 </code></pre>
</div>
</div>
<p>The five cohort curves sit almost exactly on top of each other across the entire size range, the plot doesn’t visually distinguish them. Age-at-maturity across the five birth phases comes out as 2.464, 2.512, 2.808, 2.490, and 2.467 years. There is a real spread (the 308.33 cohort takes noticeably longer), but it’s modest compared to the gap between <em>any</em> of these and the steady-state estimate of 3.50 years above. The dominant effect of switching to a real, time-varying growth rate isn’t that different cohorts now disagree with each other, it’s that all of them mature faster than the steady-state calculation predicted.</p>
</section>
<section id="what-this-does-to-the-generation-time-result" class="level4">
<h4 class="anchored" data-anchor-id="what-this-does-to-the-generation-time-result">What This Does to the “Generation Time” Result</h4>
<p>The calculation earlier today reproduced Day 11’s period-to-generation-time ratio of 8.33 / 3.50 <span class="math inline">\(\approx\)</span> 2.38, and treated the original ballpark guess of “about 3 generations” as having been a slight overestimate once actually calculated. That conclusion needs to be walked back. Using the cohort-tracked ages instead of the steady-state one:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ratios <span class="ot">&lt;-</span> period_dom <span class="sc">/</span> ages_at_mat</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ratios, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   t_birth=305 t_birth=306.67 t_birth=308.33    t_birth=310 t_birth=311.67 
         3.382          3.317          2.968          3.347          3.378 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(ratios), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.278</code></pre>
</div>
</div>
<p>The ratio per cohort ranges from about 2.97 to 3.38, averaging <strong>3.27</strong>. That’s much closer to the original “about 3 generations” intuition than the 2.38 figure calculated above, not further from it. The steady-state growth rate was underestimating how fast fish actually grow in this system by roughly 30%, which was dragging the calculated ratio down with it. Once the real, time-varying growth field is used, the rough guess holds up better than the more careful-looking calculation that initially seemed to correct it.</p>
</section>
<section id="phase-velocity-vs-group-velocity-why-the-two-calculations-disagree" class="level4">
<h4 class="anchored" data-anchor-id="phase-velocity-vs-group-velocity-why-the-two-calculations-disagree">Phase Velocity vs Group Velocity: Why the Two Calculations Disagree</h4>
<p>There’s a cleaner way to describe what went wrong with the steady-state estimate and what the cohort-tracking above actually fixed, borrowed from how dispersive waves are normally described.</p>
<p>For a wave built from a single frequency, points of constant phase move through space at the phase velocity, <span class="math inline">\(v_{\text{phase}} = k/\kappa\)</span>, where <span class="math inline">\(k\)</span> is the (temporal) frequency and <span class="math inline">\(\kappa\)</span> is the (spatial) wavenumber. A wave <em>packet</em>, a localised pulse built from a narrow spread of frequencies, instead moves at the group velocity, <span class="math inline">\(v_g = dk/d\kappa\)</span>. In a non-dispersive medium these are the same number. In a dispersive one, they aren’t, and the difference is exactly the gap between “where the ripples appear to be” and “where the actual energy is going.”</p>
<p>This system has a direct translation: size <span class="math inline">\(w\)</span> plays the role of space, real time <span class="math inline">\(t\)</span> plays the role of time, and Day 11’s <span class="math inline">\(\kappa(w) = d\varphi/dw = -k/g(w)\)</span> is a wavenumber computed from a single frequency, the dominant FFT peak. That makes the whole Day 11 derivation a phase-velocity calculation: how fast a surface of constant phase, for one Fourier component, moves through size-space. <code>track_cohort()</code> above does something different: it forward-integrates the actual nonlinear <span class="math inline">\(g(w,t)\)</span> that real fish experience, with no decomposition into frequencies at all. That’s a direct measurement of how fast the real pulse of fish moves through size-space, which is exactly what <strong>group velocity</strong> means once “wave packet” is replaced with “cohort.”</p>
<p>These two only have to agree if the underlying signal is a clean single sinusoid riding a linear, non-dispersive medium. Neither is true here. Day 8 already found the oscillation is a relaxation-oscillator shape (sharp crash, long plateau) loaded with harmonics, not a pure sine wave, and the growth field <span class="math inline">\(g(w,t)\)</span> is itself nonlinear, depending on the very population state being transported through it, which is exactly what makes a medium dispersive rather than uniform. The mismatch between Day 11’s phase-velocity calculation and today’s cohort-tracked group velocity isn’t a separate failure from Day 8’s harmonic finding; it’s the same fact, met again in a different calculation.</p>
<p>It also gives a tidier reading of today’s cohort-to-cohort spread. If there were one well-defined phase velocity for this system, every cohort would share exactly the same generation time. Instead the five tracked cohorts came out at 2.46 to 2.81 years, and the period-to-generation-time ratio ranged from 2.97 to 3.38 rather than landing on one fixed number. That spread is the sign of their being dispersion. A single “the” generation time was never quite the right concept for a system like this; there’s a distribution of them, the same way a dispersive pulse doesn’t have one well-defined speed once you look closely enough.</p>
<hr>
</section>
</section>
</section>
<section id="wednesday-closing-out-dft-and-limit-cycles-starting-bifurcations-back-to-waves" class="level2">
<h2 class="anchored" data-anchor-id="wednesday-closing-out-dft-and-limit-cycles-starting-bifurcations-back-to-waves">Wednesday: Closing Out DFT and Limit Cycles, Starting Bifurcations, Back to Waves</h2>
<p>Wednesday finished off the notes that Tuesday started rather than opening new threads: the discrete Fourier transform notes (covering the CCRMA derivation plus the 3Blue1Brown/Brunton intuition) got finished, and so did the limit-cycle section of Strogatz. With both of those closed out, the next chapter in Strogatz, on bifurcations, got started.</p>
<p>Separately, Wednesday’s reading also went back to waves: a refresher on group velocity from <em>Waves: A Mathematical Approach to the Common Types of Wave Motion</em>, and then chapters 15, 16, and 17 of <em>An Introduction to the Mathematical Theory of Waves</em>. The group velocity refresher is a useful one to have fresh, since Tuesday’s write-up above had already reached for the phase velocity/group velocity distinction (treating a single Fourier component’s wavenumber as a phase velocity, and a tracked cohort’s actual trajectory through size-space as the group velocity) without having the underlying wave theory freshly in mind at the time.</p>
<section id="can-you-beat-constant-fishing-by-fishing-only-the-peaks" class="level3">
<h3 class="anchored" data-anchor-id="can-you-beat-constant-fishing-by-fishing-only-the-peaks">Can You Beat Constant Fishing by Fishing Only the Peaks?</h3>
<p>The other Wednesday thread continued an investigation that had been running in parallel this week on the same Anchovy size-spectrum setup: given that biomass oscillates in boom-bust cycles, is it better to fish constantly, or only in pulses timed to the peaks?</p>
<p>An earlier draft of this used a box-selectivity gear catching only “sub-adults” (sizes between half of <span class="math inline">\(w_{mat}\)</span> and <span class="math inline">\(w_{mat}\)</span>), i.e.&nbsp;fish that hadn’t yet had a chance to reproduce. That’s not a realistic fishery, so it was replaced with mizer’s built-in knife-edge selectivity at <span class="math inline">\(w_{mat}\)</span>: nothing below maturity weight is ever caught, only mature individuals, the standard “minimum landing size” idealisation.</p>
<p>Separately, the first version of “fish only at the peaks” found peak times once, in advance, by running the unfished trajectory all the way to <span class="math inline">\(t=600\)</span> and scanning it for local maxima, then baked those fixed times into a constant effort schedule. That’s static, and more importantly it’s circular for any real use of this model: peak timing isn’t knowable in advance without already having run the unfished case to completion first. The fix uses mizer’s <code>setRateFunction()</code> to swap in a custom fishing-mortality function that detects peaks live, from the actual (fished) trajectory as it’s being simulated, with no foreknowledge:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mizer resolves a custom rate function by name via get(), searched from</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># wherever mizer's own internal code calls it -- that lookup never reaches a</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># closure stashed inside another R function's local frame, so this factory</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (and the name it gets assigned to) has to live at top level, not inside</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># modelling_fishing_at_peaks() below.</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>make_dynamic_peak_FMort <span class="ot">&lt;-</span> <span class="cf">function</span>(window) {</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  state <span class="ot">&lt;-</span> <span class="fu">new.env</span>()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  state<span class="sc">$</span>t_prev     <span class="ot">&lt;-</span> <span class="cn">NA_real_</span>   <span class="co"># time of the last distinct recorded point</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  state<span class="sc">$</span>bm_prev1   <span class="ot">&lt;-</span> <span class="cn">NA_real_</span>   <span class="co"># biomass one recorded step back</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  state<span class="sc">$</span>bm_prev2   <span class="ot">&lt;-</span> <span class="cn">NA_real_</span>   <span class="co"># biomass two recorded steps back</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  state<span class="sc">$</span>fish_until <span class="ot">&lt;-</span> <span class="sc">-</span><span class="cn">Inf</span>       <span class="co"># fishing stays on until this time</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(params, n, n_pp, n_other, t, effort, e_growth, pred_mort, ...) {</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    bm <span class="ot">&lt;-</span> <span class="fu">sum</span>(n[<span class="dv">1</span>, ] <span class="sc">*</span> params<span class="sc">@</span>w <span class="sc">*</span> params<span class="sc">@</span>dw)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># predictor-corrector calls FMort twice per dt at the same t; only</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># advance the rolling history once per distinct time point</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(state<span class="sc">$</span>t_prev) <span class="sc">||</span> t <span class="sc">&gt;</span> state<span class="sc">$</span>t_prev) {</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(state<span class="sc">$</span>bm_prev2) <span class="sc">&amp;&amp;</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>          state<span class="sc">$</span>bm_prev1 <span class="sc">&gt;</span> state<span class="sc">$</span>bm_prev2 <span class="sc">&amp;&amp;</span> state<span class="sc">$</span>bm_prev1 <span class="sc">&gt;</span> bm) {</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># bm_prev1, recorded at state$t_prev, was a local peak in the</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>        <span class="co"># actual (fished) trajectory -&gt; open/extend the fishing window</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>        state<span class="sc">$</span>fish_until <span class="ot">&lt;-</span> <span class="fu">max</span>(state<span class="sc">$</span>fish_until, state<span class="sc">$</span>t_prev <span class="sc">+</span> window)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>      state<span class="sc">$</span>bm_prev2 <span class="ot">&lt;-</span> state<span class="sc">$</span>bm_prev1</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>      state<span class="sc">$</span>bm_prev1 <span class="ot">&lt;-</span> bm</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>      state<span class="sc">$</span>t_prev   <span class="ot">&lt;-</span> t</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    dynamic_effort <span class="ot">&lt;-</span> effort</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    dynamic_effort[] <span class="ot">&lt;-</span> <span class="cf">if</span> (t <span class="sc">&lt;=</span> state<span class="sc">$</span>fish_until) effort <span class="cf">else</span> <span class="dv">0</span></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mizerFMort</span>(params, <span class="at">n =</span> n, <span class="at">n_pp =</span> n_pp, <span class="at">n_other =</span> n_other, <span class="at">t =</span> t,</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>               <span class="at">effort =</span> dynamic_effort, <span class="at">e_growth =</span> e_growth, <span class="at">pred_mort =</span> pred_mort, ...)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>modelling_steady_state <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">resource_decrease =</span> <span class="dv">1</span>, <span class="at">f_effort =</span> <span class="fl">0.3</span>) {</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">dt =</span> <span class="fl">0.001</span>, <span class="at">dx =</span> <span class="fl">0.1</span>, <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>, <span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">a0 =</span> <span class="dv">100</span>)</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> p<span class="sc">$</span>a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (p<span class="sc">$</span>lambda <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(p<span class="sc">$</span>w_max <span class="sc">/</span> p<span class="sc">$</span>w_min) <span class="sc">/</span> p<span class="sc">$</span>dx)</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>, <span class="at">w_min =</span> p<span class="sc">$</span>w_min, <span class="at">w_max =</span> p<span class="sc">$</span>w_max, <span class="at">w_mat =</span> p<span class="sc">$</span>w_mat,</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> p<span class="sc">$</span>lambda, <span class="at">kappa =</span> kappa, <span class="at">alpha =</span> p<span class="sc">$</span>alpha,</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">gamma =</span> p<span class="sc">$</span>gamma, <span class="at">ks =</span> <span class="dv">0</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>)</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>  params<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> params<span class="sc">@</span>cc_pp <span class="sc">*</span> <span class="fl">0.1</span></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>                 <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">90</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>                 <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>  sim_300 <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">200</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>                     <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Constant fishing from t = 300 onwards, same realistic knife-edge gear.</span></span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>  params_fished <span class="ot">&lt;-</span> sim_300<span class="sc">@</span>params</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>  gp <span class="ot">&lt;-</span> params_fished<span class="sc">@</span>gear_params</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>sel_func        <span class="ot">&lt;-</span> <span class="st">"knife_edge"</span></span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>knife_edge_size <span class="ot">&lt;-</span> p<span class="sc">$</span>w_mat</span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>catchability    <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>w_low           <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>w_high          <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gear_params</span>(params_fished) <span class="ot">&lt;-</span> gp</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a>  sim_300_fished        <span class="ot">&lt;-</span> sim_300</span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a>  sim_300_fished<span class="sc">@</span>params <span class="ot">&lt;-</span> params_fished</span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">project</span>(sim_300_fished, <span class="at">t_max =</span> <span class="dv">300</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-74"><a href="#cb12-74" aria-hidden="true" tabindex="-1"></a>         <span class="at">effort =</span> f_effort, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-75"><a href="#cb12-75" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-76"><a href="#cb12-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-77"><a href="#cb12-77" aria-hidden="true" tabindex="-1"></a>modelling_fishing_at_peaks <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>, <span class="at">f_effort =</span> <span class="fl">0.3</span>, <span class="at">peak_window =</span> <span class="dv">1</span>) {</span>
<span id="cb12-78"><a href="#cb12-78" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">dt =</span> <span class="fl">0.001</span>, <span class="at">dx =</span> <span class="fl">0.1</span>, <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb12-79"><a href="#cb12-79" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>, <span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">a0 =</span> <span class="dv">100</span>)</span>
<span id="cb12-80"><a href="#cb12-80" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> p<span class="sc">$</span>a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (p<span class="sc">$</span>lambda <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb12-81"><a href="#cb12-81" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(p<span class="sc">$</span>w_max <span class="sc">/</span> p<span class="sc">$</span>w_min) <span class="sc">/</span> p<span class="sc">$</span>dx)</span>
<span id="cb12-82"><a href="#cb12-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-83"><a href="#cb12-83" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb12-84"><a href="#cb12-84" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>, <span class="at">w_min =</span> p<span class="sc">$</span>w_min, <span class="at">w_max =</span> p<span class="sc">$</span>w_max, <span class="at">w_mat =</span> p<span class="sc">$</span>w_mat,</span>
<span id="cb12-85"><a href="#cb12-85" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> p<span class="sc">$</span>lambda, <span class="at">kappa =</span> kappa, <span class="at">alpha =</span> p<span class="sc">$</span>alpha,</span>
<span id="cb12-86"><a href="#cb12-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">gamma =</span> p<span class="sc">$</span>gamma, <span class="at">ks =</span> <span class="dv">0</span></span>
<span id="cb12-87"><a href="#cb12-87" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-88"><a href="#cb12-88" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb12-89"><a href="#cb12-89" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>)</span>
<span id="cb12-90"><a href="#cb12-90" aria-hidden="true" tabindex="-1"></a>  params<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> params<span class="sc">@</span>cc_pp <span class="sc">*</span> <span class="fl">0.1</span></span>
<span id="cb12-91"><a href="#cb12-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-92"><a href="#cb12-92" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-93"><a href="#cb12-93" aria-hidden="true" tabindex="-1"></a>                 <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-94"><a href="#cb12-94" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">90</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-95"><a href="#cb12-95" aria-hidden="true" tabindex="-1"></a>                 <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-96"><a href="#cb12-96" aria-hidden="true" tabindex="-1"></a>  sim_300 <span class="ot">&lt;-</span> <span class="fu">project</span>(sim, <span class="at">t_max =</span> <span class="dv">200</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-97"><a href="#cb12-97" aria-hidden="true" tabindex="-1"></a>                     <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-98"><a href="#cb12-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-99"><a href="#cb12-99" aria-hidden="true" tabindex="-1"></a>  params_fished <span class="ot">&lt;-</span> sim_300<span class="sc">@</span>params</span>
<span id="cb12-100"><a href="#cb12-100" aria-hidden="true" tabindex="-1"></a>  gp <span class="ot">&lt;-</span> params_fished<span class="sc">@</span>gear_params</span>
<span id="cb12-101"><a href="#cb12-101" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>sel_func        <span class="ot">&lt;-</span> <span class="st">"knife_edge"</span></span>
<span id="cb12-102"><a href="#cb12-102" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>knife_edge_size <span class="ot">&lt;-</span> p<span class="sc">$</span>w_mat</span>
<span id="cb12-103"><a href="#cb12-103" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>catchability    <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb12-104"><a href="#cb12-104" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>w_low           <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb12-105"><a href="#cb12-105" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>w_high          <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb12-106"><a href="#cb12-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gear_params</span>(params_fished) <span class="ot">&lt;-</span> gp</span>
<span id="cb12-107"><a href="#cb12-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-108"><a href="#cb12-108" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fish only at peaks, never at troughs, detected live via the FMort hook</span></span>
<span id="cb12-109"><a href="#cb12-109" aria-hidden="true" tabindex="-1"></a>  <span class="co"># above -- selectivity (just set, on params_fished) is never touched again.</span></span>
<span id="cb12-110"><a href="#cb12-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">assign</span>(<span class="st">"dynamic_peak_FMort"</span>, <span class="fu">make_dynamic_peak_FMort</span>(<span class="at">window =</span> peak_window), <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb12-111"><a href="#cb12-111" aria-hidden="true" tabindex="-1"></a>  params_fished_peaks <span class="ot">&lt;-</span> <span class="fu">setRateFunction</span>(params_fished, <span class="st">"FMort"</span>, <span class="st">"dynamic_peak_FMort"</span>)</span>
<span id="cb12-112"><a href="#cb12-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-113"><a href="#cb12-113" aria-hidden="true" tabindex="-1"></a>  sim_300_fished_peaks        <span class="ot">&lt;-</span> sim_300</span>
<span id="cb12-114"><a href="#cb12-114" aria-hidden="true" tabindex="-1"></a>  sim_300_fished_peaks<span class="sc">@</span>params <span class="ot">&lt;-</span> params_fished_peaks</span>
<span id="cb12-115"><a href="#cb12-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-116"><a href="#cb12-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">project</span>(sim_300_fished_peaks, <span class="at">t_max =</span> <span class="dv">300</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb12-117"><a href="#cb12-117" aria-hidden="true" tabindex="-1"></a>         <span class="at">effort =</span> f_effort, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb12-118"><a href="#cb12-118" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><code>make_dynamic_peak_FMort()</code> is a closure factory. The environment it creates (<code>state</code>) is captured by the function it returns, so that function can read and mutate <code>t_prev</code>/<code>bm_prev1</code>/<code>bm_prev2</code>/<code>fish_until</code> across thousands of calls during a single <code>project()</code> run without mizer’s API giving it any explicit mechanism for that. Peak detection itself is the classic “is the middle of three points a local max” test, applied causally: it only confirms <code>bm_prev1</code> was a peak once a <em>later</em> point (<code>bm</code>) shows biomass has already started falling, so this can only react to a peak one step after it happened, not anticipate one in advance, unlike the old offline version. Once confirmed, a <code>window</code>-year fishing pulse opens from that point forward; overlapping pulses extend rather than reset (<code>max(state$fish_until, ...)</code>). The function never reimplements how selectivity, catchability, and effort combine, it just substitutes a gated <code>effort</code> into mizer’s own <code>mizerFMort()</code>, so only effort changes, never selectivity.</p>
<section id="constant-fishing-vs.-fishing-the-peaks" class="level4">
<h4 class="anchored" data-anchor-id="constant-fishing-vs.-fishing-the-peaks">Constant Fishing vs.&nbsp;Fishing the Peaks</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sim_const_fish <span class="ot">&lt;-</span> <span class="fu">modelling_steady_state</span>(<span class="fl">0.001</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sim_peaks      <span class="ot">&lt;-</span> <span class="fu">modelling_fishing_at_peaks</span>()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plotYield</span>(sim_const_fish, sim_peaks, <span class="at">log =</span> <span class="st">"x"</span>, <span class="at">tlim =</span> <span class="fu">c</span>(<span class="dv">550</span>, <span class="dv">600</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-23-day-twelve_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The first version of this comparison used each function’s own default resource scenario (<code>modelling_steady_state()</code>’s default is full resource, <code>modelling_fishing_at_peaks()</code>’s default is heavily depleted resource), which is not a fair comparison of fishing strategies, it’s a comparison of two different ecosystems. Worse, under that mismatch the constant-fishing run produced <em>exactly</em> zero yield from <span class="math inline">\(t=300\)</span> onward, while total biomass stayed healthy and oscillating. Checking <code>range(selectivity)</code> ruled out a gear bug (it was a proper <code>[0, 1]</code>), which narrowed it to either a real population collapse or a structural mismatch between the two resource scenarios. The code above now matches <code>resource_decrease</code> between the two calls, which should remove that confound, but a clean re-check of the zero-yield anomaly specifically, biomass-above-<span class="math inline">\(w_{mat}\)</span> over time, with and without fishing, hasn’t been re-run since making that fix. Treat the comparison plot as illustrative of the mechanism, not yet a verified result.</p>
</section>
<section id="hunting-for-the-best-effort-and-window" class="level4">
<h4 class="anchored" data-anchor-id="hunting-for-the-best-effort-and-window">Hunting for the Best Effort and Window</h4>
<p>With a working dynamic peaks-only model, the next question was what combination of fishing effort and pulse window maximises yield:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>peak_yield_summary <span class="ot">&lt;-</span> <span class="cf">function</span>(f_effort, peak_window) {</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">modelling_fishing_at_peaks</span>(<span class="at">f_effort =</span> f_effort, <span class="at">peak_window =</span> peak_window)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  yt  <span class="ot">&lt;-</span> <span class="fu">getYield</span>(sim)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  t   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">rownames</span>(yt))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(yt[t <span class="sc">&gt;</span> <span class="dv">300</span>, ])</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>effort_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">5</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>window_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">5</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">f_effort =</span> effort_grid, <span class="at">peak_window =</span> window_grid)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>grid<span class="sc">$</span>mean_yield <span class="ot">&lt;-</span> <span class="fu">mapply</span>(peak_yield_summary, grid<span class="sc">$</span>f_effort, grid<span class="sc">$</span>peak_window)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>grid[<span class="fu">order</span>(<span class="sc">-</span>grid<span class="sc">$</span>mean_yield), ][<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   f_effort peak_window   mean_yield
5         1       0.500 4.321194e-05
10        1       1.625 4.008065e-05
20        1       3.875 3.814550e-05
15        1       2.750 3.804524e-05
25        1       5.000 3.745273e-05</code></pre>
</div>
</div>
<p>The best of this first, coarse grid was effort = 1, window = 0.5 years (mean yield <span class="math inline">\(\approx 4.32\times10^{-5}\)</span>), with yield rising monotonically across the whole tested effort range and falling off only mildly as the window lengthened. Both of those are edges of the grid, not an interior optimum, so the search was widened:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>effort_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">2</span>, <span class="fl">2.5</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">10</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>window_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>grid2 <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">f_effort =</span> effort_grid, <span class="at">peak_window =</span> window_grid)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>grid2<span class="sc">$</span>mean_yield <span class="ot">&lt;-</span> <span class="fu">mapply</span>(peak_yield_summary, grid2<span class="sc">$</span>f_effort, grid2<span class="sc">$</span>peak_window)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>grid2[<span class="fu">order</span>(<span class="sc">-</span>grid2<span class="sc">$</span>mean_yield), ][<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   f_effort peak_window   mean_yield
9        10        0.10 0.0004022949
18       10        0.25 0.0003083597
8         7        0.10 0.0002840509
27       10        0.50 0.0002735408
36       10        0.75 0.0002624430</code></pre>
</div>
</div>
<p>Same story, an order of magnitude further out: best was effort = 10, window = 0.1 years (mean yield <span class="math inline">\(\approx 4.02\times10^{-4}\)</span>), still sitting on both edges of the grid. Constraining the search to a more operationally plausible range didn’t fix this either:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>effort_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">8</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>window_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">3</span>, <span class="at">length.out =</span> <span class="dv">6</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>grid3 <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">f_effort =</span> effort_grid, <span class="at">peak_window =</span> window_grid)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>grid3<span class="sc">$</span>mean_yield <span class="ot">&lt;-</span> <span class="fu">mapply</span>(peak_yield_summary, grid3<span class="sc">$</span>f_effort, grid3<span class="sc">$</span>peak_window)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>grid3[<span class="fu">order</span>(<span class="sc">-</span>grid3<span class="sc">$</span>mean_yield), ][<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   f_effort peak_window   mean_yield
8  2.000000         0.5 8.144766e-05
16 2.000000         1.0 7.321432e-05
7  1.728571         0.5 7.146888e-05
48 2.000000         3.0 6.880975e-05
24 2.000000         1.5 6.693908e-05</code></pre>
</div>
</div>
<p>Best again landed on the boundary: effort = 2, window = 0.5. Widening or narrowing the box just relocates the wall; it never produces an interior maximum.</p>
<p>This shows how raw yield, as an optimisation target, is structurally degenerate here. A pulse removes roughly <span class="math inline">\(1-e^{-F\cdot\text{window}}\)</span> of the standing mature biomass, a fraction that climbs toward (but can never exceed) 100% as effort rises and the window shrinks. Because the pulse is brief, it never touches the juveniles driving recruitment, so the stock fully rebuilds before the next peak regardless of how hard a given pulse hit it. Nothing in raw yield penalises “more effort, less time”, so the optimum is always at whatever the most extreme effort/shortest window in the search range happens to be: take as much of each peak as possible, as fast as possible, and leave the rest of the cycle alone. That’s a real result about the biology, no biological mechanism here makes brief, intense harvesting unsustainable, but it also means the search needs a different objective before “optimal effort and window” means anything a real fishery could act on.</p>
<hr>
</section>
</section>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<ul>
<li><strong>Chapters 18, 19, and 20 of <em>An Introduction to the Mathematical Theory of Waves</em>.</strong> Continuing on from 15–17.</li>
<li><strong>Work through exercises from the textbooks</strong> (Strogatz and the wave-motion books) rather than just reading, to actually solidify the DFT, limit-cycle, bifurcation, and group-velocity material rather than letting it stay passive.</li>
<li><strong>Read over the Mizer Course material on tuning results.</strong> Useful to revisit now, with a live model that needs its own tuning decisions justified rather than just copied from the course examples.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>