<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samia">
<meta name="dcterms.date" content="2026-07-14">
<meta name="description" content="Day 26’s ‘genuine threshold D < 0.144’ for the P-only-delay variant was wrong – it checked only that the quadratic’s roots sum to something positive, not that they’re real; the discriminant never overlaps the sum condition, so this placement can’t produce a Hopf bifurcation for any parameters. A fourth delay placement – N(t-tau) in the predator’s intake term – completes the delay-placement space: nondimensionalising collapses it to two ratios (delta = D/m, kappa = aP*/m), giving a Hopf crossing that always exists with a closed-form critical delay, confirmed by simulation and eigenvalue tracking.">

<title>Day 27: Day 26’s P-Delay Threshold Was Wrong, and a Fourth Delay Placement That’s Always Possible – Modelling-the-flow-of-biomass</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a9447a135e5b1c05e5522b7712596fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Modelling-the-flow-of-biomass</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#where-day-26-left-us" id="toc-where-day-26-left-us" class="nav-link active" data-scroll-target="#where-day-26-left-us">Where Day 26 Left Us</a></li>
  <li><a href="#closing-day-26s-last-loose-end-is-the-operating-point-actually-oscillating" id="toc-closing-day-26s-last-loose-end-is-the-operating-point-actually-oscillating" class="nav-link" data-scroll-target="#closing-day-26s-last-loose-end-is-the-operating-point-actually-oscillating">Closing Day 26’s Last Loose End: Is the Operating Point Actually Oscillating?</a>
  <ul class="collapse">
  <li><a href="#the-windowed-average-rerun-of-gamma-and-kappa" id="toc-the-windowed-average-rerun-of-gamma-and-kappa" class="nav-link" data-scroll-target="#the-windowed-average-rerun-of-gamma-and-kappa">The Windowed-Average Rerun of Gamma and Kappa</a></li>
  </ul></li>
  <li><a href="#the-tell-extending-tau-never-found-an-onset" id="toc-the-tell-extending-tau-never-found-an-onset" class="nav-link" data-scroll-target="#the-tell-extending-tau-never-found-an-onset">The Tell: Extending tau Never Found an Onset</a></li>
  <li><a href="#re-deriving-the-full-condition" id="toc-re-deriving-the-full-condition" class="nav-link" data-scroll-target="#re-deriving-the-full-condition">Re-Deriving the Full Condition</a>
  <ul class="collapse">
  <li><a href="#deriving-the-quadratic-in-u" id="toc-deriving-the-quadratic-in-u" class="nav-link" data-scroll-target="#deriving-the-quadratic-in-u">Deriving the Quadratic in u</a></li>
  <li><a href="#from-the-quadratic-to-the-hopf-condition" id="toc-from-the-quadratic-to-the-hopf-condition" class="nav-link" data-scroll-target="#from-the-quadratic-to-the-hopf-condition">From the Quadratic to the Hopf Condition</a></li>
  <li><a href="#substituting-the-equilibrium-relation" id="toc-substituting-the-equilibrium-relation" class="nav-link" data-scroll-target="#substituting-the-equilibrium-relation">Substituting the Equilibrium Relation</a></li>
  </ul></li>
  <li><a href="#checking-both-conditions-at-d-0.1" id="toc-checking-both-conditions-at-d-0.1" class="nav-link" data-scroll-target="#checking-both-conditions-at-d-0.1">Checking Both Conditions at D = 0.1</a></li>
  <li><a href="#is-d-0.1-just-an-unlucky-pick" id="toc-is-d-0.1-just-an-unlucky-pick" class="nav-link" data-scroll-target="#is-d-0.1-just-an-unlucky-pick">Is D = 0.1 Just an Unlucky Pick?</a></li>
  <li><a href="#proving-its-structural-not-just-these-numbers" id="toc-proving-its-structural-not-just-these-numbers" class="nav-link" data-scroll-target="#proving-its-structural-not-just-these-numbers">Proving It’s Structural, Not Just These Numbers</a></li>
  <li><a href="#a-fourth-delay-placement-nt-tau-inside-the-intake-term" id="toc-a-fourth-delay-placement-nt-tau-inside-the-intake-term" class="nav-link" data-scroll-target="#a-fourth-delay-placement-nt-tau-inside-the-intake-term">A Fourth Delay Placement: N(t-tau) Inside the Intake Term</a>
  <ul class="collapse">
  <li><a href="#setting-up-and-linearising" id="toc-setting-up-and-linearising" class="nav-link" data-scroll-target="#setting-up-and-linearising">Setting Up and Linearising</a></li>
  <li><a href="#nondimensionalising" id="toc-nondimensionalising" class="nav-link" data-scroll-target="#nondimensionalising">Nondimensionalising</a></li>
  <li><a href="#the-hopf-condition-in-dimensionless-form" id="toc-the-hopf-condition-in-dimensionless-form" class="nav-link" data-scroll-target="#the-hopf-condition-in-dimensionless-form">The Hopf Condition, in Dimensionless Form</a></li>
  </ul></li>
  <li><a href="#confirming-the-onset-and-why-decaying-below-it-doesnt-contradict-a-hopf-bifurcation" id="toc-confirming-the-onset-and-why-decaying-below-it-doesnt-contradict-a-hopf-bifurcation" class="nav-link" data-scroll-target="#confirming-the-onset-and-why-decaying-below-it-doesnt-contradict-a-hopf-bifurcation">Confirming the Onset, and Why “Decaying” Below It Doesn’t Contradict a Hopf Bifurcation</a></li>
  <li><a href="#how-far-can-tau-go-min_n-doesnt-fail-gently" id="toc-how-far-can-tau-go-min_n-doesnt-fail-gently" class="nav-link" data-scroll-target="#how-far-can-tau-go-min_n-doesnt-fail-gently">How Far Can tau Go? min_N Doesn’t Fail Gently</a></li>
  <li><a href="#a-sweep-design-mistake-in-testing-period-vs-alpha-and-m" id="toc-a-sweep-design-mistake-in-testing-period-vs-alpha-and-m" class="nav-link" data-scroll-target="#a-sweep-design-mistake-in-testing-period-vs-alpha-and-m">A Sweep-Design Mistake in Testing Period vs alpha and m</a></li>
  <li><a href="#the-corrected-picture" id="toc-the-corrected-picture" class="nav-link" data-scroll-target="#the-corrected-picture">The Corrected Picture</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 27: Day 26’s P-Delay Threshold Was Wrong, and a Fourth Delay Placement That’s Always Possible</h1>
  <div class="quarto-categories">
    <div class="quarto-category">research</div>
    <div class="quarto-category">mizer</div>
    <div class="quarto-category">time-delay</div>
    <div class="quarto-category">hopf-bifurcation</div>
    <div class="quarto-category">predator-prey</div>
    <div class="quarto-category">correction</div>
    <div class="quarto-category">blog</div>
  </div>
  </div>

<div>
  <div class="description">
    Day 26’s ‘genuine threshold D &lt; 0.144’ for the P-only-delay variant was wrong – it checked only that the quadratic’s roots sum to something positive, not that they’re real; the discriminant never overlaps the sum condition, so this placement can’t produce a Hopf bifurcation for any parameters. A fourth delay placement – N(t-tau) in the predator’s intake term – completes the delay-placement space: nondimensionalising collapses it to two ratios (delta = D/m, kappa = aP*/m), giving a Hopf crossing that always exists with a closed-form critical delay, confirmed by simulation and eigenvalue tracking.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 14, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="where-day-26-left-us" class="level2">
<h2 class="anchored" data-anchor-id="where-day-26-left-us">Where Day 26 Left Us</h2>
<p>Day 26 worked out three delay placements in the toy predator-prey system: delaying the predator’s conversion of intake into growth is structurally impossible; delaying the prey’s own self-limitation genuinely produces a Hopf bifurcation (onset near <span class="math inline">\(\tau \approx 2.4\)</span>); and a third variant – delaying only <span class="math inline">\(P(t-\tau)\)</span> inside the predator’s intake term, leaving <span class="math inline">\(N(t)\)</span> instantaneous – was reported as <em>conditional</em>: “a genuine threshold on D”, <span class="math inline">\(D &lt; 2amC/(1+aC)^2 \approx 0.144\)</span>.</p>
<p>That third verdict was wrong. This post works out why, and fixes it. First, though, two loose ends queued at the end of Day 26 finished running yesterday and are worth closing out before that.</p>
<hr>
</section>
<section id="closing-day-26s-last-loose-end-is-the-operating-point-actually-oscillating" class="level2">
<h2 class="anchored" data-anchor-id="closing-day-26s-last-loose-end-is-the-operating-point-actually-oscillating">Closing Day 26’s Last Loose End: Is the Operating Point Actually Oscillating?</h2>
<p>Day 26’s <code>gamma = 305.8</code> recheck found <code>catchable_fraction</code> flipping non-monotonically as <code>t_run</code> grew, which is not a shrinking dip (critical slowing down) and not a stable one (a real feature), but a reordering of all three rechecked points at <code>t_run = 2400</code>. The suspected cause: <code>capacity_mult = 10, resource_decrease = 0.001</code> (the baseline every juvenile-pileup sweep has used since Day 24) might be gently oscillating rather than settled, with each single-snapshot read just sampling a different phase.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizer)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizerExperimental)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>make_second_order_params_kr <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">resource_decrease =</span> <span class="fl">0.001</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">capacity_mult =</span> <span class="dv">1</span>, <span class="at">second_order =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">ext_diff =</span> <span class="fl">0.00</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">ks =</span> <span class="dv">0</span>, <span class="at">kappa_override =</span> <span class="cn">NULL</span>) {</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  a0    <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">is.null</span>(kappa_override)) a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (lambda <span class="sc">-</span> <span class="dv">1</span>)) <span class="cf">else</span> kappa_override</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="fl">66.5</span> <span class="sc">/</span> <span class="fl">0.0003</span>) <span class="sc">/</span> <span class="fl">0.1</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> lambda, <span class="at">kappa =</span> kappa,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> alpha, <span class="at">gamma =</span> gamma, <span class="at">ks =</span> ks</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">given_species_params</span>(params)<span class="sc">$</span>D_ext <span class="ot">&lt;-</span> ext_diff</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setBevertonHolt</span>(params)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  default_capacity <span class="ot">&lt;-</span> <span class="fu">getResourceCapacity</span>(params)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  r  <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  cc <span class="ot">&lt;-</span> default_capacity <span class="sc">*</span> capacity_mult</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_capacity =</span> cc,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>                        <span class="at">balance =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (second_order) {</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">second_order_w</span>(params) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">flux =</span> <span class="st">"centred"</span>, <span class="at">bin_average =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  params</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>A real time series settles it directly, rather than reading single snapshots at different <code>t_max</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>catchable_fraction_timeseries <span class="ot">&lt;-</span> <span class="cf">function</span>(params, <span class="at">t_max =</span> <span class="dv">4800</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="dv">1</span>) {</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  sim   <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> t_max, <span class="at">dt =</span> dt, <span class="at">t_save =</span> t_save,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">method =</span> <span class="st">"tr_bdf2"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  times <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">dimnames</span>(sim<span class="sc">@</span>n)[[<span class="dv">1</span>]])</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  w     <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>w</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  dw    <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>dw</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  w_mat <span class="ot">&lt;-</span> params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat[<span class="dv">1</span>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  fractions <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">seq_along</span>(times), <span class="cf">function</span>(i) {</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    bm_density   <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[i, <span class="dv">1</span>, ] <span class="sc">*</span> w <span class="sc">*</span> dw</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    total_bm     <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    catchable_bm <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density[w <span class="sc">&gt;=</span> w_mat])</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    catchable_bm <span class="sc">/</span> total_bm</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">time =</span> times, <span class="at">catchable_fraction =</span> fractions)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>operating_point_params <span class="ot">&lt;-</span> <span class="fu">make_second_order_params_kr</span>(<span class="at">capacity_mult =</span> <span class="dv">10</span>, <span class="at">resource_decrease =</span> <span class="fl">0.001</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>operating_point_ts <span class="ot">&lt;-</span> <span class="fu">catchable_fraction_timeseries</span>(operating_point_params, <span class="at">t_max =</span> <span class="dv">4800</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>late_window <span class="ot">&lt;-</span> operating_point_ts <span class="sc">%&gt;%</span> <span class="fu">filter</span>(time <span class="sc">&gt;</span> <span class="fl">0.6</span> <span class="sc">*</span> <span class="fu">max</span>(time))</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>rel_amplitude_operating_point <span class="ot">&lt;-</span> (<span class="fu">max</span>(late_window<span class="sc">$</span>catchable_fraction) <span class="sc">-</span> <span class="fu">min</span>(late_window<span class="sc">$</span>catchable_fraction)) <span class="sc">/</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(late_window<span class="sc">$</span>catchable_fraction)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>rel_amplitude_operating_point</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.845728e-13</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(late_window, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> catchable_fraction)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#55A868"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Catchable fraction"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Late window of a t_max=4800 run, at the sweeps' own operating point"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"rel_amplitude ~ 1e-12 -- flat to numerical precision, not a sustained oscillation"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-14-day-twenty-seven_files/figure-html/operating-point-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>rel_amplitude</code> comes back at flat to numerical precision. This operating point is <strong>not</strong> genuinely oscillating. Whatever drove the <code>gamma=305.8</code> flip in Day 26, it isn’t a real limit cycle at the sweep’s own reference parameters.</p>
<section id="the-windowed-average-rerun-of-gamma-and-kappa" class="level3">
<h3 class="anchored" data-anchor-id="the-windowed-average-rerun-of-gamma-and-kappa">The Windowed-Average Rerun of Gamma and Kappa</h3>
<p>If it’s not a limit cycle, is it slow settling at specific sweep points instead? Rerunning gamma and kappa’s 15-point sweeps with a mean over the same late window, rather than a single final-timestep read:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>catchable_fraction_windowed <span class="ot">&lt;-</span> <span class="cf">function</span>(params, <span class="at">t_max =</span> <span class="dv">600</span>, <span class="at">window_frac =</span> <span class="fl">0.4</span>) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  sim   <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> t_max, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.5</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">method =</span> <span class="st">"tr_bdf2"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  times <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">dimnames</span>(sim<span class="sc">@</span>n)[[<span class="dv">1</span>]])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  w     <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>w</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  dw    <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>dw</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  w_mat <span class="ot">&lt;-</span> params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat[<span class="dv">1</span>]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  window_start <span class="ot">&lt;-</span> t_max <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> window_frac)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">which</span>(times <span class="sc">&gt;=</span> window_start)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  fractions <span class="ot">&lt;-</span> <span class="fu">sapply</span>(idx, <span class="cf">function</span>(i) {</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    bm_density   <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[i, <span class="dv">1</span>, ] <span class="sc">*</span> w <span class="sc">*</span> dw</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    total_bm     <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    catchable_bm <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density[w <span class="sc">&gt;=</span> w_mat])</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    catchable_bm <span class="sc">/</span> total_bm</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">catchable_fraction_mean =</span> <span class="fu">mean</span>(fractions),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">catchable_fraction_sd   =</span> <span class="fu">sd</span>(fractions),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">catchable_fraction_min  =</span> <span class="fu">min</span>(fractions),</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>             <span class="at">catchable_fraction_max  =</span> <span class="fu">max</span>(fractions))</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>run_param_sweep_windowed <span class="ot">&lt;-</span> <span class="cf">function</span>(param_name, param_seq, <span class="at">capacity_mult =</span> <span class="dv">10</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">resource_decrease =</span> <span class="fl">0.001</span>, <span class="at">t_max =</span> <span class="dv">600</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">window_frac =</span> <span class="fl">0.4</span>) {</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(param_seq, <span class="cf">function</span>(v) {</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    args <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">capacity_mult =</span> capacity_mult, <span class="at">resource_decrease =</span> resource_decrease)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    args[[param_name]] <span class="ot">&lt;-</span> v</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> <span class="fu">do.call</span>(make_second_order_params_kr, args)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">param =</span> param_name, <span class="at">value =</span> v,</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>               <span class="fu">catchable_fraction_windowed</span>(p, <span class="at">t_max =</span> t_max, <span class="at">window_frac =</span> window_frac))</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>  }))</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>gamma_seq_original <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="dv">100</span>), <span class="fu">log</span>(<span class="dv">5000</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>kappa_seq_original <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.001</span>), <span class="fu">log</span>(<span class="dv">1</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>gamma_windowed_df <span class="ot">&lt;-</span> <span class="fu">run_param_sweep_windowed</span>(<span class="st">"gamma"</span>, gamma_seq_original)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>kappa_windowed_df <span class="ot">&lt;-</span> <span class="fu">run_param_sweep_windowed</span>(<span class="st">"kappa_override"</span>, kappa_seq_original) <span class="sc">%&gt;%</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">param =</span> <span class="st">"kappa"</span>)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(gamma_windowed_df, kappa_windowed_df) <span class="sc">%&gt;%</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(param) <span class="sc">%&gt;%</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">log10_range =</span> <span class="fu">log10</span>(<span class="fu">max</span>(catchable_fraction_mean)) <span class="sc">-</span> <span class="fu">log10</span>(<span class="fu">min</span>(catchable_fraction_mean)),</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_rel_sd  =</span> <span class="fu">max</span>(catchable_fraction_sd <span class="sc">/</span> catchable_fraction_mean), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  param log10_range max_rel_sd
  &lt;chr&gt;       &lt;dbl&gt;      &lt;dbl&gt;
1 gamma       0.875      0.400
2 kappa       2.50       0.394</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(gamma_windowed_df, kappa_windowed_df) <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> catchable_fraction_mean)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> catchable_fraction_min, <span class="at">ymax =</span> catchable_fraction_max), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>param, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span> <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_scientific</span>()) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Catchable fraction (late-window mean)"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Gamma and kappa windowed-average sweeps"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Ribbon = min-max within the late window"</span>) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-14-day-twenty-seven_files/figure-html/windowed-sweep-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Gamma’s windowed range (<code>log10 ~ 0.87</code>) comes in even smaller than Day 25’s single-snapshot value (<code>1.3</code>); kappa’s (<code>log10 ~ 2.50</code>) lands almost exactly on Day 25’s (<code>2.6</code>). Either way, windowing doesn’t inflate the ranges, if anything gamma’s shrinks, so this isn’t sampling noise papering over a bigger real effect. The within-window spread (<code>max_rel_sd</code>, ~40% for both) peaks at exactly <code>gamma ~ 306</code> and <code>kappa ~ 0.03</code> - the same low-parameter region Day 26’s gamma-dip check flagged, then collapses to numerical noise once <code>gamma &gt; 700</code> or <code>kappa &gt; 0.08</code>. Combined with the flat operating-point time series above, that reads as a slow transient concentrated at the low end of each parameter’s range, not a genuine limit cycle: Day 25’s gamma and kappa conclusions survive.</p>
<p><code>alpha</code>’s own windowed rerun is still outstanding. Its 27.5-order-of-magnitude range was never at risk from a noise floor this small, so it’s lower priority, but it should still be run for consistency with gamma and kappa’s footing.</p>
<hr>
</section>
</section>
<section id="the-tell-extending-tau-never-found-an-onset" class="level2">
<h2 class="anchored" data-anchor-id="the-tell-extending-tau-never-found-an-onset">The Tell: Extending tau Never Found an Onset</h2>
<p>Locating the critical <span class="math inline">\(\tau\)</span> for the P-only-delay variant at <span class="math inline">\(D=0.1\)</span> (comfortably under Day 26’s 0.144 threshold) turned up nothing. Day 26 itself already found <span class="math inline">\(\tau=10\)</span> still decaying; pushing <span class="math inline">\(\tau\)</span> to 20, 40, 60, 100, and eventually 1000 (at <span class="math inline">\(t_{\max}=6000\)</span>) never produced a sustained oscillation - the amplitude just kept decaying.</p>
<p>That’s the signature of a condition that was never satisfiable, not a critical delay simply further out than tested.</p>
<hr>
</section>
<section id="re-deriving-the-full-condition" class="level2">
<h2 class="anchored" data-anchor-id="re-deriving-the-full-condition">Re-Deriving the Full Condition</h2>
<p>The characteristic equation for this variant (delay only inside the predator’s intake term):</p>
<p><span class="math display">\[(\lambda+\alpha)\left(\lambda+m-me^{-\lambda\tau}\right) + \beta\gamma = 0\]</span></p>
<section id="deriving-the-quadratic-in-u" class="level3">
<h3 class="anchored" data-anchor-id="deriving-the-quadratic-in-u">Deriving the Quadratic in u</h3>
<p><strong>Step 1: Substitute</strong> <span class="math inline">\(\lambda=i\omega\)</span>. A root can only cross from stable to unstable by passing through the imaginary axis, so any Hopf crossing must satisfy the characteristic equation at <span class="math inline">\(\lambda=i\omega\)</span> for some real <span class="math inline">\(\omega&gt;0\)</span>:</p>
<p><span class="math display">\[(i\omega+\alpha)\left(i\omega+m-me^{-i\omega\tau}\right) + \beta\gamma = 0\]</span></p>
<p><strong>Step 2: Expand the product and isolate the delay term.</strong> Multiplying out and moving everything except the <span class="math inline">\(e^{-i\omega\tau}\)</span> term to the right:</p>
<p><span class="math display">\[(i\omega+\alpha)(i\omega+m) - m(i\omega+\alpha)e^{-i\omega\tau} + \beta\gamma = 0\]</span></p>
<p><span class="math display">\[m(i\omega+\alpha)e^{-i\omega\tau} = (i\omega+\alpha)(i\omega+m) + \beta\gamma\]</span></p>
<p><strong>Step 3: Take the modulus of both sides.</strong> Since <span class="math inline">\(|e^{-i\omega\tau}|=1\)</span> for any real <span class="math inline">\(\omega,\tau\)</span>, this eliminates <span class="math inline">\(\tau\)</span> entirely:</p>
<p><span class="math display">\[m\left|i\omega+\alpha\right| = \left|(i\omega+\alpha)(i\omega+m) + \beta\gamma\right|\]</span></p>
<p><strong>Step 4: Expand both sides into real and imaginary parts.</strong> The left side is immediate: <span class="math inline">\(|i\omega+\alpha| = \sqrt{\alpha^2+\omega^2}\)</span>. For the right side, multiply out the product first:</p>
<p><span class="math display">\[(i\omega+\alpha)(i\omega+m) = -\omega^2 + \alpha m + i\omega(\alpha+m)\]</span></p>
<p>so the right-hand quantity is <span class="math inline">\((\alpha m - \omega^2+\beta\gamma) + i\omega(\alpha+m)\)</span>, a complex number with modulus <span class="math inline">\(\sqrt{(\alpha m-\omega^2+\beta\gamma)^2 + \omega^2(\alpha+m)^2}\)</span>.</p>
<p><strong>Step 5: Square both sides.</strong> Both sides of Step 3 are non-negative, so this is a legal move and it clears every square root:</p>
<p><span class="math display">\[m^2(\alpha^2+\omega^2) = (\alpha m-\omega^2+\beta\gamma)^2 + \omega^2(\alpha+m)^2\]</span></p>
<p><strong>Step 6: Write</strong> <span class="math inline">\(u=\omega^2\)</span> and expand. Expanding <span class="math inline">\((\alpha m-\omega^2+\beta\gamma)^2 = u^2 - 2(\alpha m+\beta\gamma)u + (\alpha m+\beta\gamma)^2\)</span> and gathering every term onto the right:</p>
<p><span class="math display">\[u^2 + \Big[(\alpha+m)^2 - 2(\alpha m+\beta\gamma) - m^2\Big]u + (\alpha m+\beta\gamma)^2 - m^2\alpha^2 = 0\]</span></p>
<p><strong>Step 7: Simplify the two coefficients.</strong> Since <span class="math inline">\((\alpha+m)^2-m^2=\alpha^2+2\alpha m\)</span>, the <span class="math inline">\(u\)</span>-coefficient collapses to <span class="math inline">\(\alpha^2+2\alpha m-2\alpha m-2\beta\gamma=\alpha^2-2\beta\gamma\)</span>. The constant term expands to <span class="math inline">\((\alpha m)^2+2\alpha m\beta\gamma+(\beta\gamma)^2-m^2\alpha^2=\beta\gamma(2\alpha m+\beta\gamma)\)</span>. That leaves a real, single-variable equation in <span class="math inline">\(u=\omega^2\)</span> - re-derived here from scratch by expanding the complex arithmetic directly, rather than by hand-matching real/imaginary parts the way Day 26 did - and it reproduces Day 26’s own quadratic exactly, which is a useful check that nothing was lost along the way:</p>
<p><span class="math display">\[u^2 + (\alpha^2-2\beta\gamma)u + \beta\gamma(2\alpha m+\beta\gamma) = 0\]</span></p>
</section>
<section id="from-the-quadratic-to-the-hopf-condition" class="level3">
<h3 class="anchored" data-anchor-id="from-the-quadratic-to-the-hopf-condition">From the Quadratic to the Hopf Condition</h3>
<p><strong>Step 8: What a crossing needs.</strong> By Vieta’s formulas, the product of this quadratic’s two roots is <span class="math inline">\(\beta\gamma(2\alpha m+\beta\gamma)\)</span>, always positive since <span class="math inline">\(\alpha,\beta,\gamma,m&gt;0\)</span> by construction. A quadratic with real coefficients and a <em>negative</em> product of roots is guaranteed real roots automatically. Complex-conjugate roots always multiply to <span class="math inline">\(p^2+q^2\geq0\)</span>, so a negative product rules complex roots out on its own. That’s the shortcut Day 25 got to use for the <em>conversion-delay</em> variant, whose quadratic (<span class="math inline">\(u^2+\alpha^2u+\beta\gamma(2m\alpha-\beta\gamma)=0\)</span>) has a product term that CAN go negative, so checking <span class="math inline">\(\beta\gamma&gt;2m\alpha\)</span> there was enough.</p>
<p>The P-only-delay variant’s product term is <em>always</em> positive, so its roots are either both real or a complex-conjugate pair, checking only the sum can’t tell those cases apart. That distinction needs the discriminant, which Day 26 never checked. Two conditions are needed together, not one:</p>
<ul>
<li><strong>Sum condition</strong> (Day 26’s condition): <span class="math inline">\(2\beta\gamma &gt; \alpha^2\)</span></li>
<li><strong>Discriminant condition</strong> (the missing piece): dividing <span class="math inline">\(\text{disc}=\alpha(\alpha^3-4\alpha\beta\gamma-8m\beta\gamma)\)</span> through by <span class="math inline">\(\alpha&gt;0\)</span>: <span class="math display">\[\alpha^3 \geq 4\beta\gamma(\alpha+2m)\]</span></li>
</ul>
</section>
<section id="substituting-the-equilibrium-relation" class="level3">
<h3 class="anchored" data-anchor-id="substituting-the-equilibrium-relation">Substituting the Equilibrium Relation</h3>
<p><strong>Step 9: Substitute</strong> <span class="math inline">\(\beta\gamma=amP^*\)</span>. This falls straight out of the equilibrium relation <span class="math inline">\(eaN^*=m\)</span>: <span class="math inline">\(\beta\gamma=(aN^*)(eaP^*)=a(eaN^*)P^*=amP^*\)</span>. Both conditions become:</p>
<p><span class="math display">\[\alpha^2 &lt; 2amP^* \qquad\text{and}\qquad \alpha^3 \geq 4amP^*(\alpha+2m)\]</span></p>
<p>Both have to hold at once for a real, positive crossing frequency to exist and therefore for any <span class="math inline">\(\tau\)</span> to produce a Hopf bifurcation.</p>
<hr>
</section>
</section>
<section id="checking-both-conditions-at-d-0.1" class="level2">
<h2 class="anchored" data-anchor-id="checking-both-conditions-at-d-0.1">Checking Both Conditions at D = 0.1</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>check_hopf_feasibility_pdelay_full <span class="ot">&lt;-</span> <span class="cf">function</span>(D, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">e =</span> <span class="fl">0.5</span>, <span class="at">m =</span> <span class="fl">0.3</span>, <span class="at">K =</span> <span class="dv">1</span>) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  N_star <span class="ot">&lt;-</span> m <span class="sc">/</span> (e <span class="sc">*</span> a)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  C      <span class="ot">&lt;-</span> (K <span class="sc">-</span> N_star) <span class="sc">/</span> (a <span class="sc">*</span> N_star)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  P_star <span class="ot">&lt;-</span> D <span class="sc">*</span> C</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  alpha  <span class="ot">&lt;-</span> D <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> a <span class="sc">*</span> C)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  beta   <span class="ot">&lt;-</span> a <span class="sc">*</span> N_star</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  gamma  <span class="ot">&lt;-</span> e <span class="sc">*</span> a <span class="sc">*</span> P_star</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  bg     <span class="ot">&lt;-</span> beta <span class="sc">*</span> gamma</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  B  <span class="ot">&lt;-</span> alpha<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> bg</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  Cc <span class="ot">&lt;-</span> bg <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> alpha <span class="sc">*</span> m <span class="sc">+</span> bg)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  disc <span class="ot">&lt;-</span> B<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">4</span> <span class="sc">*</span> Cc</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">D =</span> D, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta, <span class="at">gamma =</span> gamma, <span class="at">beta_gamma =</span> bg,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">B =</span> B, <span class="at">Cc =</span> Cc, <span class="at">disc =</span> disc,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">sum_positive =</span> (<span class="sc">-</span>B) <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">disc_nonneg =</span> disc <span class="sc">&gt;=</span> <span class="dv">0</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">hopf_possible =</span> (<span class="sc">-</span>B) <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> disc <span class="sc">&gt;=</span> <span class="dv">0</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="fu">check_hopf_feasibility_pdelay_full</span>(<span class="at">D =</span> <span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    D     alpha beta      gamma beta_gamma           B     Cc         disc
1 0.1 0.1666667  0.6 0.03333333       0.02 -0.01222222 0.0024 -0.009450617
  sum_positive disc_nonneg hopf_possible
1         TRUE       FALSE         FALSE</code></pre>
</div>
</div>
<p>The discriminant comes back negative (<code>disc ~ -0.00945</code>, <code>disc_nonneg = FALSE</code>) even though the sum condition holds (<code>sum_positive = TRUE</code>). No real <span class="math inline">\(\omega\)</span> satisfies the crossing condition at <span class="math inline">\(D=0.1\)</span>, so no <span class="math inline">\(\tau\)</span> can put a root on the imaginary axis, exactly what the tau-extension search showed empirically.</p>
<hr>
</section>
<section id="is-d-0.1-just-an-unlucky-pick" class="level2">
<h2 class="anchored" data-anchor-id="is-d-0.1-just-an-unlucky-pick">Is D = 0.1 Just an Unlucky Pick?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>D_scan_seq <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">1e-4</span>), <span class="fu">log</span>(<span class="fl">1e2</span>), <span class="at">length.out =</span> <span class="dv">300</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>pdelay_D_scan_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(D_scan_seq, check_hopf_feasibility_pdelay_full))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(pdelay_D_scan_df<span class="sc">$</span>hopf_possible)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Scanning <code>D</code> across six orders of magnitude (<code>1e-4</code> to <code>100</code>), <code>hopf_possible</code> is <code>FALSE</code> at every point. The sum condition only holds for small <code>D</code> (below the <code>0.144</code> threshold), and the discriminant only turns non-negative for much larger <code>D</code> - the two windows never overlap.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pdelay_D_scan_df, <span class="fu">aes</span>(<span class="at">x =</span> D)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="sc">-</span>B, <span class="at">color =</span> <span class="st">"sum of roots (-B), need &gt; 0"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> disc, <span class="at">color =</span> <span class="st">"discriminant, need &gt;= 0"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"D"</span>, <span class="at">y =</span> <span class="st">"Value"</span>, <span class="at">color =</span> <span class="cn">NULL</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Neither condition needed for a Hopf crossing is ever satisfied together"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Sum &gt; 0 holds only for small D; discriminant &gt;= 0 only for much larger D"</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-14-day-twenty-seven_files/figure-html/d-scan-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="proving-its-structural-not-just-these-numbers" class="level2">
<h2 class="anchored" data-anchor-id="proving-its-structural-not-just-these-numbers">Proving It’s Structural, Not Just These Numbers</h2>
<p>Rescaling by <code>m</code> collapses the whole system to one dimensionless ratio, <span class="math inline">\(r = Kae/m\)</span> (physically, <span class="math inline">\(r &gt; 1\)</span> is required for the equilibrium to exist at all, since <code>N* &lt; K</code> needs <code>K*a*e &gt; m</code>). In these units, the sum-condition cutoff and the point where the discriminant turns non-negative both become functions of <code>r</code> alone:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>D_max_of_r <span class="ot">&lt;-</span> <span class="cf">function</span>(r) <span class="dv">2</span> <span class="sc">*</span> (r <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> r<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>D_r_of_r <span class="ot">&lt;-</span> <span class="cf">function</span>(r) {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  Aq <span class="ot">&lt;-</span> r<span class="sc">^</span><span class="dv">3</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  Bq <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span> <span class="sc">*</span> r <span class="sc">*</span> (r <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  Cq <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">8</span> <span class="sc">*</span> (r <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  (<span class="sc">-</span>Bq <span class="sc">+</span> <span class="fu">sqrt</span>(Bq<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">4</span> <span class="sc">*</span> Aq <span class="sc">*</span> Cq)) <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> Aq)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>r_seq <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">1.001</span>), <span class="fu">log</span>(<span class="dv">1000</span>), <span class="at">length.out =</span> <span class="dv">300</span>))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>structural_check_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">r =</span> r_seq, <span class="at">D_max =</span> <span class="fu">D_max_of_r</span>(r_seq), <span class="at">D_r =</span> <span class="fu">D_r_of_r</span>(r_seq)) <span class="sc">%&gt;%</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">window_open =</span> D_r <span class="sc">&lt;</span> D_max)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(structural_check_df<span class="sc">$</span>window_open)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(structural_check_df, <span class="fu">aes</span>(<span class="at">x =</span> r)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> D_max, <span class="at">color =</span> <span class="st">"D_max(r): sum-condition cutoff"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> D_r, <span class="at">color =</span> <span class="st">"D_r(r): discriminant turns non-negative"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"r = Kae/m"</span>, <span class="at">y =</span> <span class="st">"D"</span>, <span class="at">color =</span> <span class="cn">NULL</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"The discriminant threshold sits above the sum-condition cutoff at every r"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"D_r &gt; D_max across three orders of magnitude in r -- the Hopf-feasible window never opens"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-14-day-twenty-seven_files/figure-html/structural-check-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>D_r</code> sits above <code>D_max</code> at every value of <code>r</code> tested, from just above 1 out to 1000,which is not a coincidence of the scan: substituting <code>D = D_max(r)</code> into the discriminant and simplifying by hand (cross-checked symbolically) collapses to a single closed form:</p>
<p><span class="math display">\[ \operatorname{disc}(D_{\max}) = -\frac{16m^4(s-m)^3(3s-m)}{s^4} \qquad (s=Kae)\]</span></p>
<p>Given the physical requirement <span class="math inline">\(s&gt;m&gt;0\)</span>, every factor here is strictly positive, so this is always strictly negative. At this project’s reference parameters (<span class="math inline">\(s=Kae=0.5\)</span>, <span class="math inline">\(m=0.3\)</span>), it evaluates to <span class="math inline">\(-0.0199\)</span>, matching a direct plug-in at <span class="math inline">\(D=D_{\max}=0.144\)</span> exactly.</p>
<p>Since <span class="math inline">\(\operatorname{disc}(D)\)</span> is <span class="math inline">\(D^2\)</span> times an upward-opening parabola in <span class="math inline">\(D\)</span>, negative at both <span class="math inline">\(D=0\)</span> and <span class="math inline">\(D=D_{\max}\)</span>, it must stay negative for the entire interval between - exactly the range where the sum condition holds. So for every <span class="math inline">\(D&gt;0\)</span>, at least one of the two necessary conditions always fails.</p>
<p><strong>A Hopf bifurcation is structurally impossible for this delay placement, for any positive</strong> <span class="math inline">\(D,a,e,m,K\)</span>. Not “below a threshold”. Never.</p>
<hr>
</section>
<section id="a-fourth-delay-placement-nt-tau-inside-the-intake-term" class="level2">
<h2 class="anchored" data-anchor-id="a-fourth-delay-placement-nt-tau-inside-the-intake-term">A Fourth Delay Placement: N(t-tau) Inside the Intake Term</h2>
<p>Three ways to place a single delay inside the intake product <span class="math inline">\(aNP\)</span> have been tried so far: both <span class="math inline">\(N\)</span> and <span class="math inline">\(P\)</span> delayed together in the conversion term (Day 25, impossible), <span class="math inline">\(N\)</span> delayed inside the prey’s self-limitation term (Day 26, possible), and <span class="math inline">\(P\)</span> alone delayed inside the intake term (Day 26, corrected above to impossible). The remaining combination is the mirror image of that last one: delay <span class="math inline">\(N\)</span> alone, leaving <span class="math inline">\(P(t)\)</span> instantaneous:</p>
<p><span class="math display">\[\begin{aligned}
\frac{dN}{dt} &amp;= D(K-N(t)) - aN(t)P(t) \\
\frac{dP}{dt} &amp;= eaN(t-\tau)P(t) - mP(t)
\end{aligned}\]</span></p>
<section id="setting-up-and-linearising" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-and-linearising">Setting Up and Linearising</h3>
<p>Equilibrium is unchanged (<span class="math inline">\(N^*=m/(ea)\)</span>, <span class="math inline">\(P^*=D(K-N^*)/(aN^*)\)</span>), and <span class="math inline">\(dN/dt\)</span> is identical to every other variant, so <span class="math inline">\(dn/dt=-\alpha n(t)-\beta p(t)\)</span> exactly as before, with <span class="math inline">\(\alpha=D+aP^*\)</span>, <span class="math inline">\(\beta=aN^*\)</span>.</p>
<p>The new structure is in <span class="math inline">\(dp/dt=eaN(t-\tau)P(t)-mP(t)\)</span>. Differentiating: the coefficient of <span class="math inline">\(n(t-\tau)\)</span> is <span class="math inline">\(eaP^*=\gamma\)</span> as always, but the coefficient of <span class="math inline">\(p(t)\)</span> is <span class="math inline">\(eaN^*-m\)</span>, which is <strong>exactly zero</strong> - it cancels identically, since <span class="math inline">\(eaN^*=m\)</span> is the equilibrium relation itself.</p>
<p>That cancellation is the interesting feature: the instantaneous growth-from-prey and death terms in <span class="math inline">\(dP/dt\)</span> cancel exactly at equilibrium for <em>any</em> parameters, leaving no instantaneous <span class="math inline">\(p(t)\)</span> term at all:</p>
<p><span class="math display">\[\begin{aligned}
\frac{dn}{dt} &amp;= -\alpha n(t) - \beta p(t) \\
\frac{dp}{dt} &amp;= \gamma n(t-\tau)
\end{aligned}\]</span></p>
<p>Characteristic equation:</p>
<p><span id="eq-lorenz"><span class="math display">\[\lambda^2 + \alpha\lambda + \beta\gamma e^{-\lambda\tau} = 0 \tag{1}\]</span></span></p>
<p>which correctly collapses to <span class="math inline">\(\lambda^2+\alpha\lambda+\beta\gamma=0\)</span> at <span class="math inline">\(\tau=0\)</span>, matching the non-delayed result.</p>
</section>
<section id="nondimensionalising" class="level3">
<h3 class="anchored" data-anchor-id="nondimensionalising">Nondimensionalising</h3>
<p>Five physical parameters (<span class="math inline">\(D,a,e,m,K\)</span>) plus a delay is a lot to carry through a Hopf analysis. Rescaling time by the predator’s own mortality rate <span class="math inline">\(m\)</span> collapses this down: define dimensionless time <span class="math inline">\(s=mt\)</span>, delay <span class="math inline">\(T=m\tau\)</span>, frequency <span class="math inline">\(\Omega=\omega/m\)</span>, and two dimensionless groups:</p>
<p><span class="math display">\[\delta = \frac{D}{m} \ \text{(prey renewal, relative to predator mortality)}, \qquad \kappa = \frac{aP^*}{m} \ \text{(attack pressure, relative to mortality)}\]</span></p>
<p>Two identities fall out directly: <span class="math inline">\(\alpha/m=(D+aP^*)/m=\delta+\kappa\)</span>, and,using <span class="math inline">\(\beta\gamma=amP^*\)</span> from the P-delay correction above <span class="math inline">\(\beta\gamma/m^2=aP^*/m=\kappa\)</span>. Substituting <span class="math inline">\(\lambda=m\Lambda\)</span>, <span class="math inline">\(\tau=T/m\)</span> and dividing through by <span class="math inline">\(m^2\)</span> gives:</p>
<p><span class="math display">\[\Lambda^2 + (\delta+\kappa)\Lambda + \kappa e^{-\Lambda T} = 0\]</span></p>
<p>Five dimensional parameters and a delay have become <strong>two dimensionless numbers</strong> (<span class="math inline">\(\delta,\kappa\)</span>) and a dimensionless delay <span class="math inline">\(T\)</span>. Every physical parameter set with the same <span class="math inline">\((\delta,\kappa)\)</span> behaves identically in dimensionless time.This was checked directly by picking a second, unrelated set of <span class="math inline">\(D,a,e,m,K\)</span> engineered to share the same <span class="math inline">\(\delta\)</span> and <span class="math inline">\(\kappa\)</span> as the reference parameters, and confirming the dimensionless critical delay <span class="math inline">\(T_c\)</span> comes out identical to five decimal places, while <span class="math inline">\(\tau_c=T_c/m\)</span> differs only by the ratio of the two <span class="math inline">\(m\)</span> values, as it should.</p>
</section>
<section id="the-hopf-condition-in-dimensionless-form" class="level3">
<h3 class="anchored" data-anchor-id="the-hopf-condition-in-dimensionless-form">The Hopf Condition, in Dimensionless Form</h3>
<p>Setting <span class="math inline">\(\Lambda=i\Omega\)</span> and eliminating <span class="math inline">\(T\)</span> the same way as every other variant gives a quadratic in <span class="math inline">\(U=\Omega^2\)</span>:</p>
<p><span class="math display">\[U^2 + (\delta+\kappa)^2 U - \kappa^2 = 0\]</span></p>
<p>The constant term, <span class="math inline">\(-\kappa^2\)</span>, is <strong>always negative</strong> whenever the equilibrium exists at all (<span class="math inline">\(\kappa=aP^*/m&gt;0\)</span> as soon as <span class="math inline">\(P^*&gt;0\)</span>) and a quadratic with a negative product of roots always has one real positive root automatically, the same shortcut that made the conversion-delay model’s condition a clean one-liner on Day 25. Nondimensionalising makes this visible directly: the “always possible” property doesn’t depend on <span class="math inline">\(\delta\)</span> at all, only on <span class="math inline">\(\kappa\neq0\)</span>, which is guaranteed the instant a coexistence equilibrium exists.</p>
<p>Solving for the positive root and the phase condition for the smallest consistent delay gives closed forms entirely in <span class="math inline">\(\delta,\kappa\)</span>:</p>
<p><span class="math display">\[\Omega = \sqrt{\frac{-(\delta+\kappa)^2 + \sqrt{(\delta+\kappa)^4+4\kappa^2}}{2}}, \qquad T_c = \frac{\operatorname{atan2}\!\left((\delta+\kappa)\Omega,\ \Omega^2\right)}{\Omega}\]</span></p>
<p>with dimensional quantities recovered as <span class="math inline">\(\omega=\Omega m\)</span>, <span class="math inline">\(\tau_c=T_c/m\)</span>. The transversality condition (<span class="math inline">\(\operatorname{Re}(d\lambda/d\tau)\)</span> at the crossing) carries over unchanged in sign under this rescaling, since <span class="math inline">\(d\lambda/d\tau=m^2\,d\Lambda/dT\)</span> and <span class="math inline">\(m^2&gt;0\)</span> was confirmed strictly positive at the reference parameters before trusting any of this.</p>
<p>At this project’s reference parameters (<span class="math inline">\(D=1,a=1,e=0.5,m=0.3,K=1\)</span>): <span class="math inline">\(\delta=3.333\)</span>, <span class="math inline">\(\kappa=2.222\)</span>, giving <span class="math inline">\(\Omega\approx0.399\)</span>, <span class="math inline">\(T_c\approx3.757\)</span>, and converting back, <span class="math inline">\(\omega\approx0.1197\)</span>, <span class="math inline">\(\tau_c\approx12.525\)</span> matching the dimensional derivation exactly.</p>
<p>Unlike the P-only variant, this one needs no threshold check: <strong>a genuine Hopf bifurcation exists for any positive</strong> <span class="math inline">\(D,a,e,m,K\)</span>, the same absolute character as the self-limitation-delay model, with its own onset delay rather than that model’s <span class="math inline">\(\tau\approx2.4\)</span>. <code>27_experiments.R</code> has the simulation set up to confirm this onset empirically, bracketing <span class="math inline">\(\tau_c\approx12.5\)</span> and checking for a genuine sustained limit cycle past it.</p>
<hr>
</section>
</section>
<section id="confirming-the-onset-and-why-decaying-below-it-doesnt-contradict-a-hopf-bifurcation" class="level2">
<h2 class="anchored" data-anchor-id="confirming-the-onset-and-why-decaying-below-it-doesnt-contradict-a-hopf-bifurcation">Confirming the Onset, and Why “Decaying” Below It Doesn’t Contradict a Hopf Bifurcation</h2>
<p>A first sweep past <code>tau_c</code> showed no visible knee at <code>12.5</code>, unlike the self-limitation model’s sharp onset. Rerunning <code>tau=9, 10, 11</code> at increasing <code>t_max</code> resolves it: by <code>t_max=6000</code>, <code>rel_amplitude_P</code> for all three has collapsed to machine-precision zero (<code>1.95e-14</code>, <code>2.26e-14</code>, <code>1.60e-12</code>), confirming genuine transients rather than an earlier onset, while <code>tau=15</code> holds steady at <code>rel_amplitude_P ~ 2.9-2.97</code>.</p>
<p>That leaves a real question: how can something decay to zero near a bifurcation that’s supposed to be about oscillation? Because it <em>is</em> oscillating the whole time - a decaying transient below a Hopf bifurcation is a damped spiral, not plain exponential decay. Tracking the dominant root of <span class="math inline">\(\lambda^2+\alpha\lambda+\beta\gamma e^{-\lambda\tau}=0\)</span> confirms it: the root stays complex the whole way from <span class="math inline">\(\tau=\tau_c\)</span> (where <span class="math inline">\(\lambda=i\omega\)</span> exactly) down to <span class="math inline">\(\tau=9\)</span>, and its real part shrinks monotonically toward zero as <span class="math inline">\(\tau\to\tau_c\)</span> (<span class="math inline">\(\operatorname{Re}(\lambda)=-0.0231\)</span> at <span class="math inline">\(\tau=9\)</span>, <span class="math inline">\(-0.0076\)</span> at <span class="math inline">\(\tau=11\)</span>, <span class="math inline">\(0\)</span> at <span class="math inline">\(\tau_c\)</span>), a stable spiral whose decay rate, <span class="math inline">\(|\operatorname{Re}(\lambda)|\)</span>, is exactly what “approaching a Hopf bifurcation” means. Past <span class="math inline">\(\tau_c\)</span> that real part goes positive and nonlinearity caps the growth into the limit cycle seen at <span class="math inline">\(\tau=15\)</span>. (Between <span class="math inline">\(\tau=2\)</span> and <span class="math inline">\(4\)</span> the root also stops being complex altogether, turning the equilibrium into a plain overdamped node at small <span class="math inline">\(\tau\)</span> - a separate, unrelated transition.)</p>
<hr>
</section>
<section id="how-far-can-tau-go-min_n-doesnt-fail-gently" class="level2">
<h2 class="anchored" data-anchor-id="how-far-can-tau-go-min_n-doesnt-fail-gently">How Far Can tau Go? min_N Doesn’t Fail Gently</h2>
<p>Extending to <code>tau</code> up to 200, to check whether <code>min_N</code> eventually goes negative the way the self-limitation model’s did, and as gracefully: it never cleanly crosses into “modestly negative” (<code>min_N = 0.00082</code> at <code>tau=60</code>, still <code>1.6e-17</code> ,vanishingly small but positive, at <code>tau=200</code>). Instead the simulation turns pathological before any tidy boundary: <code>max_P</code> swings between near-total predator collapse (<code>7.1e-5</code> at <code>tau=80</code>) and explosive blowup (<code>6.4e16</code> by <code>tau=200</code>) - amplitude growing without limit and dynamics turning erratic, not a bounded, readable limit cycle. That walks back last time’s read that this variant “self-limits more gracefully”: it just takes longer to break, and arguably breaks worse.</p>
<hr>
</section>
<section id="a-sweep-design-mistake-in-testing-period-vs-alpha-and-m" class="level2">
<h2 class="anchored" data-anchor-id="a-sweep-design-mistake-in-testing-period-vs-alpha-and-m">A Sweep-Design Mistake in Testing Period vs alpha and m</h2>
<p>A first attempt at testing how oscillation <em>period</em> depends on <code>alpha</code> (via <code>D</code>) and <code>m</code> tested each value at <code>1.5 * tau_critical(parameter)</code> – but <code>tau_critical</code> itself shifts with the swept parameter (<code>11.48</code> to <code>12.97</code> across the <code>D</code> range, <code>12.09</code> to <code>34.81</code> across <code>m</code>), confounding each parameter’s own effect with how far past its own onset it was tested. Bad enough for the <code>alpha</code> sweep to flip the apparent trend: the closed-form period drifted <em>down</em> with <code>alpha</code> while the measured period drifted <em>up</em>, purely because larger <code>D</code> meant a larger <code>tau_tested</code>.</p>
<p>Fixed by testing every value at one <strong>shared, fixed</strong> <code>tau</code> per sweep, above that sweep’s largest <code>tau_critical</code> (<code>tau=20</code> for <code>alpha</code>/<code>D</code>, <code>tau=45</code> for <code>m</code>). The corrected sweep is in <code>27_experiments.R</code>; results pending a fresh run.</p>
<hr>
</section>
<section id="the-corrected-picture" class="level2">
<h2 class="anchored" data-anchor-id="the-corrected-picture">The Corrected Picture</h2>
<p>Four ways to place a single discrete delay in this predator-prey system have now been tried across Days 25-27:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Delay placement</th>
<th>Day 26 verdict</th>
<th>Corrected verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predator’s conversion of intake into growth (<code>N</code>, <code>P</code> both delayed)</td>
<td>Impossible, any parameters</td>
<td>Unchanged</td>
</tr>
<tr class="even">
<td>Prey’s own self-limitation (<code>N(t-tau)</code> in <code>dN/dt</code>)</td>
<td>Possible, confirmed by simulation</td>
<td>Unchanged, onset <code>tau ~ 2.4</code></td>
</tr>
<tr class="odd">
<td>Predator’s intake term, <code>P</code> only (<code>N(t)</code> instantaneous)</td>
<td>“Genuine threshold <code>D &lt; 0.144</code>”</td>
<td><strong>Impossible, any parameters</strong></td>
</tr>
<tr class="even">
<td>Predator’s intake term, <code>N</code> only (<code>P(t)</code> instantaneous)</td>
<td><em>(not yet tried)</em></td>
<td><strong>Possible, any parameters</strong>, onset <code>tau_c ~ 12.5</code></td>
</tr>
</tbody>
</table>
<p>The clean takeaway isn’t “two absolute, one conditional” as Day 26 had it. It’s <strong>two absolute-impossible, two absolute-possible</strong>, an even split. Where the delay sits changes the <em>type</em> of algebraic condition governing feasibility: the always-possible variants share a constant term in the <span class="math inline">\(u\)</span>-quadratic that’s a bare negative square; the impossible ones have a constant term that’s a sum of positive pieces, easy to mistake for a threshold unless the discriminant is checked too.</p>
<hr>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<ul>
<li><strong>With this knowledge, see whether the cod params actually cause there to be oscillations</strong>: now that all four delay placements have closed-form Hopf conditions, plug in the cod parameter set and check whether any of the feasible placements land past their own onset delay.</li>
<li><strong>Rerun alpha’s isolation sweep:</strong> With the same windowed-average read, for consistency with gamma and kappa’s footing (not expected to change the qualitative threshold, just puts all three sweeps on the same footing).</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>