<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samia">
<meta name="dcterms.date" content="2026-07-10">
<meta name="description" content="Two threads from Day 24 closed. First: a real alpha/gamma/kappa sweep (not just single-value swaps) confirms alpha as the dominant lever by a wide margin - a genuine viability threshold the anchovy’s own value sits right at the foot of - with kappa modest and gamma flat. Second: a time delay in the predator’s growth term is proven analytically to never trigger a Hopf bifurcation here, for any delay or parameters, and simulation confirms it.">

<title>Day 25: A Real alpha/gamma/kappa Sweep, and Ruling Out Time Delay – Modelling-the-flow-of-biomass</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a9447a135e5b1c05e5522b7712596fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Modelling-the-flow-of-biomass</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#where-day-24-left-us" id="toc-where-day-24-left-us" class="nav-link active" data-scroll-target="#where-day-24-left-us">Where Day 24 Left Us</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-sweeps" id="toc-the-sweeps" class="nav-link" data-scroll-target="#the-sweeps">The Sweeps</a>
  <ul class="collapse">
  <li><a href="#alpha" id="toc-alpha" class="nav-link" data-scroll-target="#alpha">alpha</a></li>
  <li><a href="#gamma" id="toc-gamma" class="nav-link" data-scroll-target="#gamma">gamma</a></li>
  <li><a href="#kappa" id="toc-kappa" class="nav-link" data-scroll-target="#kappa">kappa</a></li>
  </ul></li>
  <li><a href="#what-the-sweeps-show" id="toc-what-the-sweeps-show" class="nav-link" data-scroll-target="#what-the-sweeps-show">What the Sweeps Show</a></li>
  <li><a href="#the-time-delay-predator-prey-model" id="toc-the-time-delay-predator-prey-model" class="nav-link" data-scroll-target="#the-time-delay-predator-prey-model">The Time-Delay Predator-Prey Model</a>
  <ul class="collapse">
  <li><a href="#setting-up-the-delay" id="toc-setting-up-the-delay" class="nav-link" data-scroll-target="#setting-up-the-delay">Setting Up the Delay</a></li>
  <li><a href="#working-out-the-maths-first" id="toc-working-out-the-maths-first" class="nav-link" data-scroll-target="#working-out-the-maths-first">Working Out the Maths First</a></li>
  <li><a href="#checking-the-algebra-numerically" id="toc-checking-the-algebra-numerically" class="nav-link" data-scroll-target="#checking-the-algebra-numerically">Checking the Algebra Numerically</a></li>
  <li><a href="#simulating-it-anyway" id="toc-simulating-it-anyway" class="nav-link" data-scroll-target="#simulating-it-anyway">Simulating It Anyway</a></li>
  </ul></li>
  <li><a href="#what-this-shows" id="toc-what-this-shows" class="nav-link" data-scroll-target="#what-this-shows">What This Shows</a></li>
  <li><a href="#what-this-all-adds-up-to" id="toc-what-this-all-adds-up-to" class="nav-link" data-scroll-target="#what-this-all-adds-up-to">What This All Adds Up To</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 25: A Real alpha/gamma/kappa Sweep, and Ruling Out Time Delay</h1>
  <div class="quarto-categories">
    <div class="quarto-category">research</div>
    <div class="quarto-category">mizer</div>
    <div class="quarto-category">juvenile-pileup</div>
    <div class="quarto-category">alpha</div>
    <div class="quarto-category">parameter-sweep</div>
    <div class="quarto-category">predator-prey</div>
    <div class="quarto-category">time-delay</div>
    <div class="quarto-category">blog</div>
  </div>
  </div>

<div>
  <div class="description">
    Two threads from Day 24 closed. First: a real alpha/gamma/kappa sweep (not just single-value swaps) confirms alpha as the dominant lever by a wide margin - a genuine viability threshold the anchovy’s own value sits right at the foot of - with kappa modest and gamma flat. Second: a time delay in the predator’s growth term is proven analytically to never trigger a Hopf bifurcation here, for any delay or parameters, and simulation confirms it.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="where-day-24-left-us" class="level2">
<h2 class="anchored" data-anchor-id="where-day-24-left-us">Where Day 24 Left Us</h2>
<p>Day 24 closed out the <code>capacity_mult</code> hysteresis window and Gustav’s resource-rate prediction, but left three threads open for what’s next: giving the toy predator-prey model a time delay, trying a feedback-loop variant of it, and rerunning the <code>alpha</code>/<code>gamma</code>/<code>kappa</code> juvenile-pileup isolation properly. That last one is a direct fix to a real gap: Day 24’s version only ever swapped each parameter to <em>one</em> alternate value , the other species’ own default , not a real range, and it surfaced a genuine confound along the way (mizer’s own default-parameter calibration turned out to be interdependent, so leaving a parameter unspecified silently let other parameters re-derive too). Today closes that thread.</p>
<hr>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizer)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizerExperimental)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(colorRamps)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(future)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Same builder as every day since Day 20, self-contained rather than sourced from <code>24_experiments.R</code> but extended with <code>alpha</code>/<code>gamma</code>/<code>kappa</code> arguments (all defaulting to the anchovy’s own values), so the same single builder can sweep any one of the three while pinning the rest at the anchovy’s own fully-specified values throughout. That’s what sidesteps Day 24’s confound directly: nothing here is ever left for mizer to fill in, so there’s no re-derivation to worry about, and every sweep point is directly comparable to every other.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>make_second_order_params_kr <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">resource_decrease =</span> <span class="fl">0.001</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">capacity_mult =</span> <span class="dv">1</span>, <span class="at">second_order =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">ext_diff =</span> <span class="fl">0.00</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">ks =</span> <span class="dv">0</span>, <span class="at">kappa_override =</span> <span class="cn">NULL</span>) {</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  a0    <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">is.null</span>(kappa_override)) a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (lambda <span class="sc">-</span> <span class="dv">1</span>)) <span class="cf">else</span> kappa_override</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="fl">66.5</span> <span class="sc">/</span> <span class="fl">0.0003</span>) <span class="sc">/</span> <span class="fl">0.1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> lambda, <span class="at">kappa =</span> kappa,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> alpha, <span class="at">gamma =</span> gamma, <span class="at">ks =</span> ks</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">given_species_params</span>(params)<span class="sc">$</span>D_ext <span class="ot">&lt;-</span> ext_diff</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setBevertonHolt</span>(params)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  default_capacity <span class="ot">&lt;-</span> <span class="fu">getResourceCapacity</span>(params)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  r  <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  cc <span class="ot">&lt;-</span> default_capacity <span class="sc">*</span> capacity_mult</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_capacity =</span> cc,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>                        <span class="at">balance =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (second_order) {</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">second_order_w</span>(params) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">flux =</span> <span class="st">"centred"</span>, <span class="at">bin_average =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  params</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The default species’ own <code>alpha</code>/<code>gamma</code>/<code>kappa</code>, purely as reference lines on the sweep plots below.It’s not used to build anything, so there’s no risk of reintroducing the confound this rerun is designed to avoid:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>default_species_raw <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(<span class="at">species_name =</span> <span class="st">"Anchovy"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>default_alpha <span class="ot">&lt;-</span> default_species_raw<span class="sc">@</span>species_params<span class="sc">$</span>alpha[<span class="dv">1</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>default_gamma <span class="ot">&lt;-</span> default_species_raw<span class="sc">@</span>species_params<span class="sc">$</span>gamma[<span class="dv">1</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>default_kappa <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">resource_params</span>(default_species_raw)<span class="sc">$</span>kappa,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NA_real_</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>anchovy_kappa <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (<span class="fl">2.05</span> <span class="sc">-</span> <span class="dv">1</span>))  <span class="co"># same formula make_second_order_params_kr() uses</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Reference values (anchovy | default species):</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"  alpha: %.4f | %.4f</span><span class="sc">\n</span><span class="st">  gamma: %.1f | %.1f</span><span class="sc">\n</span><span class="st">  kappa: %.4f | %.4f</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.1</span>, default_alpha, <span class="dv">750</span>, default_gamma, anchovy_kappa, default_kappa</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reference values (anchovy | default species):
  alpha: 0.1000 | 0.4000
  gamma: 750.0 | 2066.0
  kappa: 0.0714 | 0.0050</code></pre>
</div>
</div>
<p>Three more helper functions round out the setup. <code>catchable_fraction_at()</code> runs a simulation out to <code>t_max</code> and returns the settled fraction of biomass sitting at or above <code>w_mat</code>. <code>run_param_sweep()</code> calls it across a sequence of values for one parameter, holding everything else fixed:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>catchable_fraction_at <span class="ot">&lt;-</span> <span class="cf">function</span>(params, <span class="at">t_max =</span> <span class="dv">600</span>) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> t_max, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.5</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">method =</span> <span class="st">"tr_bdf2"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  last  <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  w_mat <span class="ot">&lt;-</span> params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat[<span class="dv">1</span>]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  w     <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>w</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  dw    <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>dw</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  bm_density   <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[last, <span class="dv">1</span>, ] <span class="sc">*</span> w <span class="sc">*</span> dw</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  total_bm     <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  catchable_bm <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density[w <span class="sc">&gt;=</span> w_mat])</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">catchable_fraction =</span> catchable_bm <span class="sc">/</span> total_bm, <span class="at">error =</span> <span class="cn">NA_character_</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>run_param_sweep <span class="ot">&lt;-</span> <span class="cf">function</span>(param_name, param_seq, <span class="at">capacity_mult =</span> <span class="dv">10</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>                            <span class="at">resource_decrease =</span> <span class="fl">0.001</span>) {</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(param_seq, <span class="cf">function</span>(v) {</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    args <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">capacity_mult =</span> capacity_mult, <span class="at">resource_decrease =</span> resource_decrease)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    args[[param_name]] <span class="ot">&lt;-</span> v</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>({</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>      p <span class="ot">&lt;-</span> <span class="fu">do.call</span>(make_second_order_params_kr, args)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">catchable_fraction_at</span>(p)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    }, <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>      <span class="fu">data.frame</span>(<span class="at">catchable_fraction =</span> <span class="cn">NA_real_</span>, <span class="at">error =</span> <span class="fu">conditionMessage</span>(e))</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(result<span class="sc">$</span>error)) {</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">warning</span>(<span class="fu">sprintf</span>(<span class="st">"%s = %.4g: %s"</span>, param_name, v, result<span class="sc">$</span>error))</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">param =</span> param_name, <span class="at">value =</span> v,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>               <span class="at">catchable_fraction =</span> result<span class="sc">$</span>catchable_fraction,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>               <span class="at">error =</span> result<span class="sc">$</span>error)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  }))</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The <code>tryCatch</code> wraps both the params construction and the simulation, not just the simulation - a value near the edge of the tested range can make <code>newSingleSpeciesParams()</code> itself throw (“the feeding level is not sufficient to maintain the fish”) before <code>project()</code> is ever reached, so an infeasible point needs to be caught there too. It comes back as an <code>NA</code> row with the error message kept, rather than halting the sweep.</p>
<p><code>plot_param_sweep()</code> draws the result on a log-scaled y-axis, labelled in scientific notation rather than as a percentage. <code>catchable_fraction</code> ranges from numerically-extinct up to double-digit percentages within a single sweep, and a fixed-accuracy percent label rounds everything below its threshold to the same “0.0000%” string, which erases exactly the low end of the range this plot needs to show:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>plot_param_sweep <span class="ot">&lt;-</span> <span class="cf">function</span>(df, param_label, ref_values, <span class="at">log_x =</span> <span class="cn">TRUE</span>) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> catchable_fraction)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#4C72B0"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#4C72B0"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_scientific</span>()) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> param_label, <span class="at">y =</span> <span class="st">"Catchable fraction (biomass at or above w_mat)"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="fu">sprintf</span>(<span class="st">"Juvenile-pileup sweep: %s"</span>, param_label),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"capacity_mult = 10, resource_decrease = 0.001 — every other parameter pinned at the anchovy's own value"</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (log_x) p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">scale_x_log10</span>()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (rv <span class="cf">in</span> ref_values) {</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> rv<span class="sc">$</span>value, <span class="at">linetype =</span> rv<span class="sc">$</span>linetype, <span class="at">color =</span> <span class="st">"grey40"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  p</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="the-sweeps" class="level2">
<h2 class="anchored" data-anchor-id="the-sweeps">The Sweeps</h2>
<p><code>capacity_mult = 10</code>, <code>resource_decrease = 0.001</code> throughout which is the same operating point every isolation check in <code>24_experiments.R</code> used, comfortably inside the coexistence region so a marginal population never confounds the pileup reading.</p>
<section id="alpha" class="level3">
<h3 class="anchored" data-anchor-id="alpha">alpha</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>alpha_seq <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.02</span>), <span class="fu">log</span>(<span class="fl">0.8</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>alpha_sweep_df <span class="ot">&lt;-</span> <span class="fu">run_param_sweep</span>(<span class="st">"alpha"</span>, alpha_seq)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_param_sweep</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  alpha_sweep_df, <span class="st">"alpha (assimilation efficiency)"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref_values =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">value =</span> <span class="fl">0.1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">list</span>(<span class="at">value =</span> default_alpha, <span class="at">linetype =</span> <span class="st">"dotted"</span>))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-10-day-twenty-five_files/figure-html/alpha-sweep-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>alpha</th>
<th>catchable fraction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.020</td>
<td>3.2×10⁻²⁸</td>
</tr>
<tr class="even">
<td>0.057</td>
<td>1.1×10⁻⁹</td>
</tr>
<tr class="odd">
<td>0.075</td>
<td>8.9×10⁻⁷</td>
</tr>
<tr class="even">
<td>0.097</td>
<td>2.1×10⁻⁴</td>
</tr>
<tr class="odd">
<td>0.126</td>
<td>1.10%</td>
</tr>
<tr class="even">
<td>0.164</td>
<td>8.76%</td>
</tr>
<tr class="odd">
<td>0.214</td>
<td>25.5%</td>
</tr>
<tr class="even">
<td>0.279</td>
<td>46.1%</td>
</tr>
<tr class="odd">
<td>0.363</td>
<td>64.7%</td>
</tr>
<tr class="even">
<td>0.472</td>
<td>78.3%</td>
</tr>
<tr class="odd">
<td>0.615</td>
<td>87.1%</td>
</tr>
<tr class="even">
<td>0.800</td>
<td>92.3%</td>
</tr>
</tbody>
</table>
</section>
<section id="gamma" class="level3">
<h3 class="anchored" data-anchor-id="gamma">gamma</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>gamma_seq <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="dv">100</span>), <span class="fu">log</span>(<span class="dv">5000</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>gamma_sweep_df <span class="ot">&lt;-</span> <span class="fu">run_param_sweep</span>(<span class="st">"gamma"</span>, gamma_seq)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_param_sweep</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  gamma_sweep_df, <span class="st">"gamma (search volume)"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref_values =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">value =</span> <span class="dv">750</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">list</span>(<span class="at">value =</span> default_gamma, <span class="at">linetype =</span> <span class="st">"dotted"</span>))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-10-day-twenty-five_files/figure-html/gamma-sweep-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>gamma</th>
<th>catchable fraction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100</td>
<td>2.20×10⁻⁵</td>
</tr>
<tr class="even">
<td>231</td>
<td>2.45×10⁻⁴</td>
</tr>
<tr class="odd">
<td>306</td>
<td>9.48×10⁻⁵</td>
</tr>
<tr class="even">
<td>404</td>
<td>4.03×10⁻⁴</td>
</tr>
<tr class="odd">
<td>707</td>
<td>3.62×10⁻⁴</td>
</tr>
<tr class="even">
<td>1237</td>
<td>3.85×10⁻⁴</td>
</tr>
<tr class="odd">
<td>2162</td>
<td>4.18×10⁻⁴</td>
</tr>
<tr class="even">
<td>3781</td>
<td>4.50×10⁻⁴</td>
</tr>
<tr class="odd">
<td>5000</td>
<td>4.67×10⁻⁴</td>
</tr>
</tbody>
</table>
</section>
<section id="kappa" class="level3">
<h3 class="anchored" data-anchor-id="kappa">kappa</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>kappa_seq <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.001</span>), <span class="fu">log</span>(<span class="dv">1</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>kappa_sweep_df <span class="ot">&lt;-</span> <span class="fu">run_param_sweep</span>(<span class="st">"kappa_override"</span>, kappa_seq) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">param =</span> <span class="st">"kappa"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_param_sweep</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  kappa_sweep_df, <span class="st">"kappa (background resource spectrum)"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref_values =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">value =</span> anchovy_kappa, <span class="at">linetype =</span> <span class="st">"dashed"</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">list</span>(<span class="at">value =</span> default_kappa, <span class="at">linetype =</span> <span class="st">"dotted"</span>))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-10-day-twenty-five_files/figure-html/kappa-sweep-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>kappa</th>
<th>catchable fraction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.0010</td>
<td>1.35×10⁻⁶</td>
</tr>
<tr class="even">
<td>0.0044</td>
<td>1.76×10⁻⁵</td>
</tr>
<tr class="odd">
<td>0.0118</td>
<td>1.21×10⁻⁴</td>
</tr>
<tr class="even">
<td>0.0193</td>
<td>9.96×10⁻⁵</td>
</tr>
<tr class="odd">
<td>0.0316</td>
<td>1.58×10⁻⁴</td>
</tr>
<tr class="even">
<td>0.0848</td>
<td>3.60×10⁻⁴</td>
</tr>
<tr class="odd">
<td>0.2276</td>
<td>4.22×10⁻⁴</td>
</tr>
<tr class="even">
<td>0.6105</td>
<td>4.79×10⁻⁴</td>
</tr>
<tr class="odd">
<td>1.0000</td>
<td>4.96×10⁻⁴</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="what-the-sweeps-show" class="level2">
<h2 class="anchored" data-anchor-id="what-the-sweeps-show">What the Sweeps Show</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>all_sweeps_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(alpha_sweep_df, gamma_sweep_df, kappa_sweep_df)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sweep_magnitude <span class="ot">&lt;-</span> all_sweeps_df <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(error), catchable_fraction <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(param) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_fraction =</span> <span class="fu">min</span>(catchable_fraction),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_fraction =</span> <span class="fu">max</span>(catchable_fraction),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">log10_range  =</span> <span class="fu">log10</span>(max_fraction) <span class="sc">-</span> <span class="fu">log10</span>(min_fraction),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(log10_range))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>sweep_magnitude</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  param min_fraction max_fraction log10_range
  &lt;chr&gt;        &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;
1 alpha     3.25e-28     0.923          27.5 
2 kappa     1.35e- 6     0.000496        2.56
3 gamma     2.20e- 5     0.000467        1.33</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>param</th>
<th>min</th>
<th>max</th>
<th>log10 range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>alpha</td>
<td>3.2×10⁻²⁸</td>
<td>92.3%</td>
<td><strong>27.5</strong></td>
</tr>
<tr class="even">
<td>kappa</td>
<td>1.4×10⁻⁶</td>
<td>4.96×10⁻⁴</td>
<td>2.6</td>
</tr>
<tr class="odd">
<td>gamma</td>
<td>2.2×10⁻⁵</td>
<td>4.67×10⁻⁴</td>
<td>1.3</td>
</tr>
</tbody>
</table>
<p>alpha is confirmed as the dominant lever, and it’s a threshold, not a gradual slope. Between <code>alpha = 0.057</code> and <code>alpha = 0.28</code> the catchable fraction jumps roughly 8 orders of magnitude (1.1×10⁻⁹ → 25.5%).This seems to be a viability threshold for juvenile survivorship, the same qualitative signature as the <code>capacity_mult</code> collapse bifurcations from Days 22-24. The anchovy’s own <code>alpha = 0.1</code> sits right at the foot of that climb (catchable fraction ≈0.02% there), not in some ordinary low-effect regime , so the real anchovy model is parked right at the edge of the transition, which is a sharper explanation for the extreme pileup than Day 24’s two-point swap could give.</p>
<p>Gamma is close to flat. the smallest range of the three, confirming Day 24’s anchovy-side finding directly rather than just from two points. One thing worth flagging: the point at <code>gamma = 305.8</code> (9.48×10⁻⁵) breaks monotonicity, dipping below both neighbours. That matches a pattern this project has seen before (Day 23’s scan-rate check, Day 24’s Type II wobble), which is critical slowing down near a transition, where <code>t_run = 600</code> might not be quite enough to fully settle. It is worth a longer run at that one point before trusting it as a real feature.</p>
<p>kappa shows a real but modest, mostly-monotonic effect.It is bigger than gamma’s, nowhere close to alpha’s.</p>
<hr>
</section>
<section id="the-time-delay-predator-prey-model" class="level2">
<h2 class="anchored" data-anchor-id="the-time-delay-predator-prey-model">The Time-Delay Predator-Prey Model</h2>
<p>Day 24’s toy predator-prey model (chemostat prey growth, mass-action Type I predation) has no hysteresis at all. This was both proven analytically (chemostat growth keeps the Jacobian trace negative regardless of the predation term’s shape) and confirmed by simulation. The next candidate mechanism, flagged in Day 24’s own “What’s Next”: a time delay between a predator eating and that intake showing up as predator growth , a maturation or gestation lag , which is a well-known route to oscillation in delay differential equation (DDE) models that an instantaneous ODE can’t produce on its own.</p>
<section id="setting-up-the-delay" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-the-delay">Setting Up the Delay</h3>
<p>The classical form for this (Wangersky-Cunningham, 1957) keeps predation and prey loss instantaneous, but delays the <em>conversion</em> of that predation into new predator biomass by <code>tau</code>:</p>
<pre><code>dN/dt = D*(K - N(t)) - a*N(t)*P(t)
dP/dt = e*a*N(t-tau)*P(t-tau) - m*P(t)</code></pre>
<p>Predator death stays instantaneous, since dying isn’t subject to the same conversion lag as being born.</p>
</section>
<section id="working-out-the-maths-first" class="level3">
<h3 class="anchored" data-anchor-id="working-out-the-maths-first">Working Out the Maths First</h3>
<p>The question is whether adding the delay <code>tau</code> can turn the stable fixed point Day 24 found into an unstable one that oscillates instead. That’s checked in three steps: find where the fixed point sits, linearise the system around it to see how a small perturbation behaves, then ask what value of <code>tau</code> (if any) could flip that perturbation from decaying to growing.</p>
<p><strong>Step 1 - the equilibrium doesn’t move.</strong></p>
<p>At a constant solution, <code>N</code> and <code>P</code> aren’t changing, so every delayed term is just equal to its own current value (<code>N(t-tau) = N(t)</code>, and likewise for <code>P</code>). That means the delay drops out of the equilibrium condition entirely, and setting both derivatives to zero reproduces exactly Day 24’s non-delayed result:</p>
<pre><code>N* = m / (e*a)
P* = D*(K - N*) / (a*N*)</code></pre>
<p>So <code>tau</code> can only change whether this point is <em>stable</em>, not where the point itself sits.</p>
<p><strong>Step 2 - linearise around the equilibrium.</strong></p>
<p>Write <code>N = N* + n</code> and <code>P = P* + p</code>, where <code>n</code> and <code>p</code> are small perturbations, and drop every term of second order or higher in them (the standard move for checking local stability). Using the equilibrium relation <code>e*a*N* = m</code> to simplify the result gives:</p>
<pre><code>dn/dt = -alpha*n(t) - beta*p(t)
dp/dt = gamma*n(t-tau) + m*p(t-tau) - m*p(t)</code></pre>
<p>where <code>alpha = D + a*P*</code>, <code>beta = a*N*</code>, and <code>gamma = e*a*P*</code> are just shorthand for the constants that fall out of the substitution.</p>
<p>Trying a solution of the form <code>n, p ~ exp(lambda*t)</code> , the standard ansatz for a linear system like this , turns the two differential equations into one algebraic condition on <code>lambda</code>, the characteristic equation:</p>
<pre><code>(lambda + alpha) * (lambda + m - m*exp(-lambda*tau)) + beta*gamma*exp(-lambda*tau) = 0</code></pre>
<p>As a sanity check before trusting this for <code>tau &gt; 0</code>: setting <code>tau = 0</code> should recover Day 24’s own non-delayed result. It does. The equation collapses to <code>lambda^2 + alpha*lambda + beta*gamma = 0</code>, matching Day 24’s <code>trace = -alpha</code>, <code>det = beta*gamma</code> exactly.</p>
<p><strong>Step 3 - ask what a Hopf bifurcation would require.</strong></p>
<p>A Hopf bifurcation is the specific way a delay can destabilise a fixed point: as <code>tau</code> grows from 0, a pair of roots of the characteristic equation crosses from the stable side of the complex plane to the unstable side, passing through the imaginary axis at <code>lambda = i*omega</code>. Substituting that in and solving for when a real, positive <code>omega^2</code> exists reduces to one inequality:</p>
<pre><code>beta*gamma &gt; 2*m*alpha                                            (*)</code></pre>
<p>If (*) can never hold, no crossing is possible at any <code>tau</code>, and the fixed point stays stable forever. So the whole question comes down to checking the sign of <code>beta*gamma - 2*m*alpha</code>.</p>
<p>Substituting <code>beta = a*N*</code> and <code>gamma = e*a*P*</code>, then using <code>e*a*N* = m</code> once more to simplify, step by step:</p>
<pre><code>beta*gamma - 2*m*alpha
    = a^2*e*N**P* - 2*m*(D + a*P*)          [substitute beta, gamma, alpha]
    = a*P*(a*e*N*) - 2*m*D - 2*m*a*P*       [expand the bracket]
    = a*P*(a*e*N* - 2*m) - 2*m*D            [group the a*P* terms]
    = a*P*(m - 2*m) - 2*m*D                 [a*e*N* = m, from the equilibrium relation]
    = -a*m*P* - 2*m*D</code></pre>
<p>Every term in that final line , <code>a</code>, <code>m</code>, <code>P*</code>, <code>D</code> , is strictly positive by construction, so the whole expression is strictly negative, for any choice of these parameters. Condition (<em>) can never hold, which means a Hopf bifurcation is analytically impossible here, for</em> any* delay and <em>any</em> parameter choice.</p>
<p>That’s the same underlying reason Day 24 already ruled out the Type I/II functional-response route: chemostat-style prey growth contributes a fixed restoring force (the <code>-D</code>/<code>-2mD</code> term above) that neither a saturating predation term nor a delayed one can get around.</p>
</section>
<section id="checking-the-algebra-numerically" class="level3">
<h3 class="anchored" data-anchor-id="checking-the-algebra-numerically">Checking the Algebra Numerically</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(deSolve)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>predator_prey_params_delay <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">D =</span> <span class="dv">1</span>, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">e =</span> <span class="fl">0.5</span>, <span class="at">m =</span> <span class="fl">0.3</span>, <span class="at">K =</span> <span class="dv">1</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>check_hopf_feasibility <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">parms =</span> predator_prey_params_delay) {</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  D <span class="ot">&lt;-</span> parms<span class="sc">$</span>D; a <span class="ot">&lt;-</span> parms<span class="sc">$</span>a; e <span class="ot">&lt;-</span> parms<span class="sc">$</span>e; m <span class="ot">&lt;-</span> parms<span class="sc">$</span>m; K <span class="ot">&lt;-</span> parms<span class="sc">$</span>K</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  N_star <span class="ot">&lt;-</span> m <span class="sc">/</span> (e <span class="sc">*</span> a)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  P_star <span class="ot">&lt;-</span> D <span class="sc">*</span> (K <span class="sc">-</span> N_star) <span class="sc">/</span> (a <span class="sc">*</span> N_star)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  alpha  <span class="ot">&lt;-</span> D <span class="sc">+</span> a <span class="sc">*</span> P_star</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  beta   <span class="ot">&lt;-</span> a <span class="sc">*</span> N_star</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  gamma  <span class="ot">&lt;-</span> e <span class="sc">*</span> a <span class="sc">*</span> P_star</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">N_star =</span> N_star, <span class="at">P_star =</span> P_star, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">gamma =</span> gamma, <span class="at">beta_gamma =</span> beta <span class="sc">*</span> gamma, <span class="at">two_m_alpha =</span> <span class="dv">2</span> <span class="sc">*</span> m <span class="sc">*</span> alpha,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">hopf_possible =</span> (beta <span class="sc">*</span> gamma) <span class="sc">&gt;</span> (<span class="dv">2</span> <span class="sc">*</span> m <span class="sc">*</span> alpha))</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>hopf_check <span class="ot">&lt;-</span> <span class="fu">check_hopf_feasibility</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hopf_check</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  N_star    P_star    alpha beta     gamma beta_gamma two_m_alpha hopf_possible
1    0.6 0.6666667 1.666667  0.6 0.3333333        0.2           1         FALSE</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>N*</th>
<th>P*</th>
<th>alpha</th>
<th>beta</th>
<th>gamma</th>
<th>beta·gamma</th>
<th>2·m·alpha</th>
<th>Hopf possible?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.600</td>
<td>0.667</td>
<td>1.667</td>
<td>0.600</td>
<td>0.333</td>
<td>0.200</td>
<td>1.000</td>
<td><strong>FALSE</strong></td>
</tr>
</tbody>
</table>
<p><code>beta*gamma = 0.2</code> against <code>2*m*alpha = 1.0</code>.It’s not close, and by the derivation above it never can be, for any of these parameters.</p>
</section>
<section id="simulating-it-anyway" class="level3">
<h3 class="anchored" data-anchor-id="simulating-it-anyway">Simulating It Anyway</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>predator_prey_rhs_delay <span class="ot">&lt;-</span> <span class="cf">function</span>(t, state, parms) {</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  N <span class="ot">&lt;-</span> <span class="fu">max</span>(state[<span class="dv">1</span>], <span class="dv">0</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  P <span class="ot">&lt;-</span> <span class="fu">max</span>(state[<span class="dv">2</span>], <span class="dv">0</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  D   <span class="ot">&lt;-</span> parms[[<span class="st">"D"</span>]];   a <span class="ot">&lt;-</span> parms[[<span class="st">"a"</span>]]; e <span class="ot">&lt;-</span> parms[[<span class="st">"e"</span>]]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  m   <span class="ot">&lt;-</span> parms[[<span class="st">"m"</span>]];   K <span class="ot">&lt;-</span> parms[[<span class="st">"K"</span>]]; tau <span class="ot">&lt;-</span> parms[[<span class="st">"tau"</span>]]</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  N0  <span class="ot">&lt;-</span> parms[[<span class="st">"N0"</span>]]; P0 <span class="ot">&lt;-</span> parms[[<span class="st">"P0"</span>]]</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (t <span class="sc">&lt;=</span> tau) {</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    lag_N <span class="ot">&lt;-</span> N0</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    lag_P <span class="ot">&lt;-</span> P0</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    lag   <span class="ot">&lt;-</span> <span class="fu">lagvalue</span>(t <span class="sc">-</span> tau)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    lag_N <span class="ot">&lt;-</span> <span class="fu">max</span>(lag[<span class="dv">1</span>], <span class="dv">0</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    lag_P <span class="ot">&lt;-</span> <span class="fu">max</span>(lag[<span class="dv">2</span>], <span class="dv">0</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  dN <span class="ot">&lt;-</span> D <span class="sc">*</span> (K <span class="sc">-</span> N) <span class="sc">-</span> a <span class="sc">*</span> N <span class="sc">*</span> P</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  dP <span class="ot">&lt;-</span> e <span class="sc">*</span> a <span class="sc">*</span> lag_N <span class="sc">*</span> lag_P <span class="sc">-</span> m <span class="sc">*</span> P</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="fu">c</span>(dN, dP))</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>run_predator_prey_delay <span class="ot">&lt;-</span> <span class="cf">function</span>(tau, <span class="at">state0 =</span> <span class="fu">c</span>(<span class="at">N =</span> <span class="dv">1</span>, <span class="at">P =</span> <span class="fl">0.1</span>), <span class="at">t_max =</span> <span class="dv">300</span>,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">parms =</span> predator_prey_params_delay) {</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>  parms<span class="sc">$</span>tau <span class="ot">&lt;-</span> tau</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  parms<span class="sc">$</span>N0  <span class="ot">&lt;-</span> state0[[<span class="st">"N"</span>]]</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  parms<span class="sc">$</span>P0  <span class="ot">&lt;-</span> state0[[<span class="st">"P"</span>]]</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  out  <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">dede</span>(<span class="at">y =</span> state0, <span class="at">times =</span> <span class="fu">seq</span>(<span class="dv">0</span>, t_max, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>                             <span class="at">func =</span> predator_prey_rhs_delay, <span class="at">parms =</span> parms))</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>  late <span class="ot">&lt;-</span> out[out<span class="sc">$</span>time <span class="sc">&gt;</span> t_max <span class="sc">*</span> <span class="fl">0.6</span>, ]</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">tau =</span> tau, <span class="at">max_N =</span> <span class="fu">max</span>(late<span class="sc">$</span>N), <span class="at">min_N =</span> <span class="fu">min</span>(late<span class="sc">$</span>N),</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>             <span class="at">max_P =</span> <span class="fu">max</span>(late<span class="sc">$</span>P), <span class="at">min_P =</span> <span class="fu">min</span>(late<span class="sc">$</span>P),</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>             <span class="at">rel_amplitude_P =</span> (<span class="fu">max</span>(late<span class="sc">$</span>P) <span class="sc">-</span> <span class="fu">min</span>(late<span class="sc">$</span>P)) <span class="sc">/</span> <span class="fu">mean</span>(late<span class="sc">$</span>P))</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Perturbed well away from equilibrium (<code>N=1</code> vs <code>N*=0.6</code>, <code>P=0.1</code> vs <code>P*=0.667</code>), since a system started exactly at a stable fixed point never oscillates regardless of <code>tau</code>. This is a test of whether delay lets a real perturbation grow into a sustained oscillation instead of damping back out. <code>tau</code> swept up to 40, two orders of magnitude past the model’s own natural timescales (<code>1/D</code>, <code>1/m</code>):</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tau_seq <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>delay_sweep_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(tau_seq, run_predator_prey_delay))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>delay_sweep_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   tau     max_N     min_N     max_P     min_P rel_amplitude_P
1  0.0 0.6000000 0.6000000 0.6666667 0.6666667    1.826377e-10
2  0.5 0.6000000 0.6000000 0.6666667 0.6666667    1.625068e-09
3  1.0 0.6000000 0.6000000 0.6666667 0.6666667    1.091836e-08
4  2.0 0.6000001 0.6000000 0.6666667 0.6666665    2.438337e-07
5  5.0 0.6000167 0.6000000 0.6666666 0.6666219    6.704088e-05
6 10.0 0.6009766 0.6000093 0.6666414 0.6640213    3.933543e-03
7 20.0 0.6181879 0.6013198 0.6630575 0.6182940    6.894508e-02
8 40.0 0.6848407 0.6270410 0.5956804 0.4621942    2.495004e-01</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>tau</th>
<th>rel. amplitude of P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1.8×10⁻¹⁰</td>
</tr>
<tr class="even">
<td>0.5</td>
<td>1.6×10⁻⁹</td>
</tr>
<tr class="odd">
<td>1</td>
<td>1.1×10⁻⁸</td>
</tr>
<tr class="even">
<td>2</td>
<td>2.4×10⁻⁷</td>
</tr>
<tr class="odd">
<td>5</td>
<td>6.7×10⁻⁵</td>
</tr>
<tr class="even">
<td>10</td>
<td>3.9×10⁻³</td>
</tr>
<tr class="odd">
<td>20</td>
<td>6.9×10⁻²</td>
</tr>
<tr class="even">
<td>40</td>
<td>0.250</td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(delay_sweep_df, <span class="fu">aes</span>(<span class="at">x =</span> tau, <span class="at">y =</span> rel_amplitude_P)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#55A868"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#55A868"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"tau (delay in predator conversion)"</span>, <span class="at">y =</span> <span class="st">"Relative amplitude of P (settled)"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Does delay reintroduce the oscillation the instantaneous model doesn't have?"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Perturbed start (N=1, P=0.1) — analytic prediction: no, for any tau"</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-10-day-twenty-five_files/figure-html/delay-amplitude-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Read on its own, that plot looks worrying for the analytic result - amplitude climbing smoothly from near-zero up to 0.25 by <code>tau=40</code> looks exactly like a trend heading toward real oscillation. The time series at <code>tau=40</code> tells a different story:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>longest_delay_ts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">dede</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="at">N =</span> <span class="dv">1</span>, <span class="at">P =</span> <span class="fl">0.1</span>),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">times =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">300</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">func =</span> predator_prey_rhs_delay,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">parms =</span> <span class="fu">modifyList</span>(predator_prey_params_delay, <span class="fu">list</span>(<span class="at">tau =</span> <span class="dv">40</span>, <span class="at">N0 =</span> <span class="dv">1</span>, <span class="at">P0 =</span> <span class="fl">0.1</span>))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(longest_delay_ts, <span class="fu">aes</span>(<span class="at">x =</span> time)) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> N, <span class="at">color =</span> <span class="st">"N (prey)"</span>)) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> P, <span class="at">color =</span> <span class="st">"P (predator)"</span>)) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> hopf_check<span class="sc">$</span>N_star, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> hopf_check<span class="sc">$</span>P_star, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Biomass"</span>, <span class="at">color =</span> <span class="cn">NULL</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Time series at tau = 40 (the longest delay tested)"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Dotted lines = analytic equilibrium N*, P* — both unchanged by tau, as derived above"</span>) <span class="sc">+</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-10-day-twenty-five_files/figure-html/delay-timeseries-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="what-this-shows" class="level2">
<h2 class="anchored" data-anchor-id="what-this-shows">What This Shows</h2>
<p>Both <code>N</code> and <code>P</code> move monotonically toward the dotted equilibrium lines for the entire 300 time units.There is no overshoot, no crossing back and forth, none of the up-down-up-down signature a real oscillation would show. What the delay does produce is a visible staircase: distinct steps roughly every 40 time units, matching <code>tau</code> itself, since the growth rate is periodically “informed” by a signal from exactly <code>tau</code> ago. That staircase is a genuine delay effect, but it’s a shape imposed on a monotonic approach to equilibrium, not evidence of a limit cycle.</p>
<p>That reframes the amplitude sweep: <code>rel_amplitude_P</code> is climbing with <code>tau</code> not because oscillation is building, but because larger delays relax more slowly (the same critical-slowing-down pattern flagged repeatedly elsewhere in this project - Day 18, Day 23’s scan-rate check, Day 24’s Type II wobble), so the fixed <code>t_max = 300</code> / late-window-starts-at-<code>t &gt; 180</code> sampling catches the system still mid-approach rather than settled. The “amplitude” being measured there is really “how far an unfinished monotonic relaxation has drifted within the sampling window,” not a real oscillation’s size.</p>
<p>The maths and the simulation agree: a Hopf bifurcation is impossible for this delayed-conversion model, for any tested delay. Chemostat-style prey growth blocks this route to hysteresis the same way it blocked Type I and Type II functional-response changes on Day 24. The one loose end is methodological rather than substantive: confirming that <code>rel_amplitude_P</code> actually decays to ~0 at <code>tau=40</code> given enough time, rather than plateauing (which the algebra says is impossible, but is worth catching directly rather than assuming), needs a rerun with a much longer <code>t_max</code>.</p>
<hr>
</section>
<section id="what-this-all-adds-up-to" class="level2">
<h2 class="anchored" data-anchor-id="what-this-all-adds-up-to">What This All Adds Up To</h2>
<p>A real range, not two guessed points, and the ranking Day 24 could only sketch out now has actual curves behind it: alpha dominant by a wide margin, and not just “moves a lot” but sitting on a genuine threshold that the anchovy’s own calibration happens to sit right at the foot of. gamma and kappa are both real but minor by comparison, confirming rather than overturning Day 24’s rough read.</p>
<p>The time-delay predator-prey model closes out a second thread from Day 24’s “What’s Next” on the same day: a full analytic derivation (equilibrium unchanged by <code>tau</code>, characteristic equation reduces correctly to Day 24’s own result at <code>tau=0</code>, and the Hopf condition <code>beta*gamma &gt; 2*m*alpha</code> reduces via the equilibrium relation to <code>-a*m*P* - 2*m*D</code>, always negative) proves a Hopf bifurcation is impossible here for any delay, and the simulation backs it up once the amplitude sweep’s misleading climb is read correctly against the actual time series.</p>
<hr>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<ul>
<li><strong>Pin down alpha’s transition window more precisely</strong>, the same way the <code>capacity_mult</code> window got refined on Day 24, i.e a denser sweep over roughly <code>[0.05, 0.3]</code> at the same <code>t_run</code> to bracket where the steep climb actually starts and ends.</li>
<li><strong>Check whether the <code>gamma = 305.8</code> dip is real or an under-settled transient</strong>: Rerun just that point (and its neighbours) at a longer <code>t_run</code> than 600 to see whether it’s critical slowing down near a smaller feature, the same check Day 24 flagged for its own default-species Forward spike.</li>
<li><strong>Confirm <code>rel_amplitude_P</code> actually decays to ~0 at large <code>tau</code> given enough time</strong>, rather than plateauing. Rerun <code>tau=40</code> (and perhaps larger) with a much longer <code>t_max</code> than 300. The algebra says a plateau is impossible, which is exactly why it’s worth checking directly rather than assuming.</li>
<li><strong>Try a feedback-loop variant of the predator-prey model</strong>, such as switching prey growth from chemostat to logistic (<code>r*N*(1-N/K)</code>), to test whether that is what unlocks mizer’s hysteresis. Still open from Day 24, and now the more promising direction given delay and Type II saturation have both been ruled out for the same structural reason.</li>
<li><strong>Fix <code>save_plot()</code>’s silently-truncated filenames</strong> as the delay-experiment PNGs saved to disk missing their <code>.png</code> extension and (for the longer filename) part of the name itself (<code>... tau40.png</code> became <code>... tau4</code>), almost certainly a Windows <code>MAX_PATH</code> (260-character) limit hit by this project’s deeply nested folder path. Worth shortening <code>save_plot()</code>’s output filenames or moving <code>interesting_plots/</code> closer to the drive root before it silently clips something less recoverable than a plot.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>