<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samia">
<meta name="dcterms.date" content="2026-07-09">
<meta name="description" content="Day 23’s rough (1.27, 2.07) hysteresis bracket gets refined down to a precisely-pinned (1.30, 1.41), and holds up under two robustness checks - a faster-replenishing resource shifts and narrows it as predicted, and a species swap reproduces the same shape and a comparably narrow window, so it isn’t an anchovy-specific artefact. A non-size-structured predator-prey model, built to test whether size resolution is even necessary, reproduces the collapse threshold exactly but shows no hysteresis at all, even with Type II saturation added - pointing at chemostat-style prey growth, not size structure, as the reason it can’t destabilise the way mizer does.">

<title>Day 24: Pinning Down the capacity_mult Hysteresis Window – Modelling-the-flow-of-biomass</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a9447a135e5b1c05e5522b7712596fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Modelling-the-flow-of-biomass</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#where-day-23-left-us" id="toc-where-day-23-left-us" class="nav-link active" data-scroll-target="#where-day-23-left-us">Where Day 23 Left Us</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-refined-sweep" id="toc-the-refined-sweep" class="nav-link" data-scroll-target="#the-refined-sweep">The Refined Sweep</a></li>
  <li><a href="#what-the-refined-sweep-shows" id="toc-what-the-refined-sweep-shows" class="nav-link" data-scroll-target="#what-the-refined-sweep-shows">What the Refined Sweep Shows</a></li>
  <li><a href="#pinning-down-the-edges-numerically" id="toc-pinning-down-the-edges-numerically" class="nav-link" data-scroll-target="#pinning-down-the-edges-numerically">Pinning Down the Edges Numerically</a></li>
  <li><a href="#what-this-pins-down" id="toc-what-this-pins-down" class="nav-link" data-scroll-target="#what-this-pins-down">What This Pins Down</a></li>
  <li><a href="#testing-gustavs-prediction-does-the-boundary-move-with-resource-rate" id="toc-testing-gustavs-prediction-does-the-boundary-move-with-resource-rate" class="nav-link" data-scroll-target="#testing-gustavs-prediction-does-the-boundary-move-with-resource-rate">Testing Gustav’s Prediction: Does the Boundary Move With Resource Rate?</a>
  <ul class="collapse">
  <li><a href="#first-pass-five-resource-rates-wide-capacity-range" id="toc-first-pass-five-resource-rates-wide-capacity-range" class="nav-link" data-scroll-target="#first-pass-five-resource-rates-wide-capacity-range">First Pass: Five Resource Rates, Wide Capacity Range</a></li>
  <li><a href="#second-pass-zoomed-to-1-15" id="toc-second-pass-zoomed-to-1-15" class="nav-link" data-scroll-target="#second-pass-zoomed-to-1-15">Second Pass: Zoomed to [1, 15]</a></li>
  </ul></li>
  <li><a href="#what-this-shows" id="toc-what-this-shows" class="nav-link" data-scroll-target="#what-this-shows">What This Shows</a></li>
  <li><a href="#testing-whether-size-structure-is-necessary-a-non-size-structured-predator-prey-model" id="toc-testing-whether-size-structure-is-necessary-a-non-size-structured-predator-prey-model" class="nav-link" data-scroll-target="#testing-whether-size-structure-is-necessary-a-non-size-structured-predator-prey-model">Testing Whether Size Structure Is Necessary: A Non-Size-Structured Predator-Prey Model</a>
  <ul class="collapse">
  <li><a href="#a-sweep-design-lesson-why-not-state-carry-this-one" id="toc-a-sweep-design-lesson-why-not-state-carry-this-one" class="nav-link" data-scroll-target="#a-sweep-design-lesson-why-not-state-carry-this-one">A Sweep-Design Lesson: Why Not State-Carry This One</a></li>
  </ul></li>
  <li><a href="#what-this-shows-1" id="toc-what-this-shows-1" class="nav-link" data-scroll-target="#what-this-shows-1">What This Shows</a></li>
  <li><a href="#is-the-capacity_mult-bifurcation-shape-just-an-artefact-of-our-species-parameters" id="toc-is-the-capacity_mult-bifurcation-shape-just-an-artefact-of-our-species-parameters" class="nav-link" data-scroll-target="#is-the-capacity_mult-bifurcation-shape-just-an-artefact-of-our-species-parameters">Is the capacity_mult Bifurcation Shape Just an Artefact of Our Species Parameters?</a>
  <ul class="collapse">
  <li><a href="#zooming-into-the-hysteresis-region" id="toc-zooming-into-the-hysteresis-region" class="nav-link" data-scroll-target="#zooming-into-the-hysteresis-region">Zooming Into the Hysteresis Region</a></li>
  </ul></li>
  <li><a href="#what-this-shows-2" id="toc-what-this-shows-2" class="nav-link" data-scroll-target="#what-this-shows-2">What This Shows</a></li>
  <li><a href="#is-the-juvenile-biomass-pileup-general-or-specific-to-our-anchovy-calibration" id="toc-is-the-juvenile-biomass-pileup-general-or-specific-to-our-anchovy-calibration" class="nav-link" data-scroll-target="#is-the-juvenile-biomass-pileup-general-or-specific-to-our-anchovy-calibration">Is the Juvenile-Biomass Pileup General, or Specific to Our Anchovy Calibration?</a></li>
  <li><a href="#what-this-shows-3" id="toc-what-this-shows-3" class="nav-link" data-scroll-target="#what-this-shows-3">What This Shows</a></li>
  <li><a href="#what-this-all-adds-up-to" id="toc-what-this-all-adds-up-to" class="nav-link" data-scroll-target="#what-this-all-adds-up-to">What This All Adds Up To</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 24: Pinning Down the capacity_mult Hysteresis Window</h1>
  <div class="quarto-categories">
    <div class="quarto-category">research</div>
    <div class="quarto-category">mizer</div>
    <div class="quarto-category">hysteresis</div>
    <div class="quarto-category">bifurcation</div>
    <div class="quarto-category">capacity_mult</div>
    <div class="quarto-category">predator-prey</div>
    <div class="quarto-category">blog</div>
  </div>
  </div>

<div>
  <div class="description">
    Day 23’s rough (1.27, 2.07) hysteresis bracket gets refined down to a precisely-pinned (1.30, 1.41), and holds up under two robustness checks - a faster-replenishing resource shifts and narrows it as predicted, and a species swap reproduces the same shape and a comparably narrow window, so it isn’t an anchovy-specific artefact. A non-size-structured predator-prey model, built to test whether size resolution is even necessary, reproduces the collapse threshold exactly but shows no hysteresis at all, even with Type II saturation added - pointing at chemostat-style prey growth, not size structure, as the reason it can’t destabilise the way mizer does.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="where-day-23-left-us" class="level2">
<h2 class="anchored" data-anchor-id="where-day-23-left-us">Where Day 23 Left Us</h2>
<p>Day 23’s <code>capacity_mult</code> bifurcation sweep (<code>cc_seq_bif</code>, 20 log-spaced points from <code>1</code> to <code>100</code>, <code>resource_decrease</code> held at <code>0.001</code>) turned up something the coarse phase-diagram grid never tested for: a genuine hysteresis loop, not an artefact. At <code>capacity_mult = 1.62</code>, Forward (arriving from nothing) was still numerically dead (<code>7.71e-24</code>) while Backward (arriving from an established population at <code>capacity_mult = 100</code>) was already alive (<code>6.66e-4</code>) , about 20 orders of magnitude apart at the identical parameter value.</p>
<p>But that grid only had four points anywhere near the transition , <code>1.00</code>, <code>1.27</code>, <code>1.62</code>, <code>2.07</code> , so all it could say was that Backward’s collapse point sat somewhere in <code>(1.27, 1.62]</code> and Forward’s escape point sat somewhere in <code>(1.62, 2.07)</code>. That’s the first item on Day 23’s “What’s Next” list, and today closes it.</p>
<hr>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizer)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizerExperimental)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(colorRamps)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(future)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><code>make_second_order_params_kr()</code> and <code>run_bifurcation_sweep()</code> carry over unchanged from Day 23, so today’s refinement is directly comparable to the sweep that found the loop in the first place, not a new setup that might disagree for unrelated reasons:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>make_second_order_params_kr <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">resource_decrease =</span> <span class="fl">0.001</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">capacity_mult =</span> <span class="dv">1</span>, <span class="at">second_order =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">ext_diff =</span> <span class="fl">0.00</span>) {</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  a0    <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (lambda <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="fl">66.5</span> <span class="sc">/</span> <span class="fl">0.0003</span>) <span class="sc">/</span> <span class="fl">0.1</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> lambda, <span class="at">kappa =</span> kappa,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>, <span class="at">ks =</span> <span class="dv">0</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">given_species_params</span>(params)<span class="sc">$</span>D_ext <span class="ot">&lt;-</span> ext_diff</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setBevertonHolt</span>(params)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  default_capacity <span class="ot">&lt;-</span> <span class="fu">getResourceCapacity</span>(params)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  r  <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  cc <span class="ot">&lt;-</span> default_capacity <span class="sc">*</span> capacity_mult</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_capacity =</span> cc,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>                        <span class="at">balance =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (second_order) {</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">second_order_w</span>(params) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">flux =</span> <span class="st">"centred"</span>, <span class="at">bin_average =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  params</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>run_bifurcation_sweep <span class="ot">&lt;-</span> <span class="cf">function</span>(param_seq, param_name, <span class="at">fixed_params =</span> <span class="fu">list</span>(),</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">params_fn =</span> make_second_order_params_kr,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">t_run =</span> <span class="dv">600</span>, <span class="at">lambda =</span> <span class="fl">2.05</span>) {</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>  run_one_direction <span class="ot">&lt;-</span> <span class="cf">function</span>(seq_vals, <span class="at">init_n =</span> <span class="cn">NULL</span>, <span class="at">init_n_pp =</span> <span class="cn">NULL</span>) {</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    out       <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> seq_vals, <span class="at">max_bm =</span> <span class="cn">NA_real_</span>, <span class="at">min_bm =</span> <span class="cn">NA_real_</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    state_n   <span class="ot">&lt;-</span> init_n</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    state_npp <span class="ot">&lt;-</span> init_n_pp</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(seq_vals)) {</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>      args <span class="ot">&lt;-</span> fixed_params</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>      args[[param_name]] <span class="ot">&lt;-</span> seq_vals[i]</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>      args<span class="sc">$</span>lambda <span class="ot">&lt;-</span> lambda</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>      p <span class="ot">&lt;-</span> <span class="fu">do.call</span>(params_fn, args)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(state_n)) {</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        p<span class="sc">@</span>initial_n[]    <span class="ot">&lt;-</span> state_n</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>        p<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> state_npp</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>      sim <span class="ot">&lt;-</span> <span class="fu">project</span>(p, <span class="at">t_max =</span> t_run, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.5</span>,</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>                     <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">method =</span> <span class="st">"tr_bdf2"</span>)</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>      bm   <span class="ot">&lt;-</span> <span class="fu">getBiomass</span>(sim)[, <span class="st">"Anchovy"</span>]</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>      tv   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(bm))</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>      late <span class="ot">&lt;-</span> bm[tv <span class="sc">&gt;</span> t_run <span class="sc">*</span> <span class="fl">0.6</span>]</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>      last <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>      state_n   <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[last, , ]</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>      state_npp <span class="ot">&lt;-</span> sim<span class="sc">@</span>n_pp[last, ]</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>      out<span class="sc">$</span>max_bm[i] <span class="ot">&lt;-</span> <span class="fu">max</span>(late)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>      out<span class="sc">$</span>min_bm[i] <span class="ot">&lt;-</span> <span class="fu">min</span>(late)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">df =</span> out, <span class="at">n_final =</span> state_n, <span class="at">npp_final =</span> state_npp)</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>  fwd    <span class="ot">&lt;-</span> <span class="fu">run_one_direction</span>(param_seq)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>  bwd    <span class="ot">&lt;-</span> <span class="fu">run_one_direction</span>(<span class="fu">rev</span>(param_seq), <span class="at">init_n =</span> fwd<span class="sc">$</span>n_final, <span class="at">init_n_pp =</span> fwd<span class="sc">$</span>npp_final)</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>  bwd_df <span class="ot">&lt;-</span> bwd<span class="sc">$</span>df[<span class="fu">order</span>(bwd<span class="sc">$</span>df<span class="sc">$</span>value), ]</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">value =</span> fwd<span class="sc">$</span>df<span class="sc">$</span>value, <span class="at">biomass =</span> fwd<span class="sc">$</span>df<span class="sc">$</span>max_bm, <span class="at">direction =</span> <span class="st">"Forward"</span>,  <span class="at">branch =</span> <span class="st">"max"</span>),</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">value =</span> fwd<span class="sc">$</span>df<span class="sc">$</span>value, <span class="at">biomass =</span> fwd<span class="sc">$</span>df<span class="sc">$</span>min_bm, <span class="at">direction =</span> <span class="st">"Forward"</span>,  <span class="at">branch =</span> <span class="st">"min"</span>),</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">value =</span> bwd_df<span class="sc">$</span>value, <span class="at">biomass =</span> bwd_df<span class="sc">$</span>max_bm, <span class="at">direction =</span> <span class="st">"Backward"</span>, <span class="at">branch =</span> <span class="st">"max"</span>),</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">value =</span> bwd_df<span class="sc">$</span>value, <span class="at">biomass =</span> bwd_df<span class="sc">$</span>min_bm, <span class="at">direction =</span> <span class="st">"Backward"</span>, <span class="at">branch =</span> <span class="st">"min"</span>)</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>plot_bifurcation <span class="ot">&lt;-</span> <span class="cf">function</span>(df, x_label, title, <span class="at">subtitle =</span> <span class="cn">NULL</span>) {</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> biomass, <span class="at">color =</span> direction, <span class="at">linetype =</span> branch)) <span class="sc">+</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> x_label, <span class="at">y =</span> <span class="st">"Biomass"</span>, <span class="at">title =</span> title, <span class="at">subtitle =</span> subtitle) <span class="sc">+</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="the-refined-sweep" class="level2">
<h2 class="anchored" data-anchor-id="the-refined-sweep">The Refined Sweep</h2>
<p>Same move as Day 23’s own <code>[3, 10]</code> plateau refinement: rerun the same kind of sweep at much higher density, zoomed into just the bracketed window, rather than guessing where the two edges sit. The window is <code>[1.2, 2.3]</code> , both suspected edges (<code>1.27</code> and <code>2.07</code>) with margin either side , at 25 log-spaced points, roughly 4x the points-per-decade of the original 20-point sweep over <code>[1, 100]</code>.</p>
<p><code>t_run</code> is kept at the sweep’s own default, <code>600</code>, matching the run that found the loop, rather than cut down the way the phase-diagram grid refinements were. This is specifically a hysteresis-<em>width</em> measurement, so trading settle time for point density here would confound a genuine scan-rate effect (Day 23’s own scan-rate follow-up) with the resolution increase this is meant to isolate:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cc_seq_refine <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">1.2</span>), <span class="fu">log</span>(<span class="fl">2.3</span>), <span class="at">length.out =</span> <span class="dv">25</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>bif_cc_refine_df <span class="ot">&lt;-</span> <span class="fu">run_bifurcation_sweep</span>(cc_seq_refine, <span class="st">"capacity_mult"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">fixed_params =</span> <span class="fu">list</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">params_fn =</span> make_second_order_params_kr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bif_cc_refine_plot <span class="ot">&lt;-</span> <span class="fu">plot_bifurcation</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  bif_cc_refine_df, <span class="st">"capacity_mult"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Refined bifurcation: capacity_mult in [1.2, 2.3]"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resource_decrease held at 0.001 (balance = FALSE) -- 25 points vs. the original 20 over [1, 100]"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>bif_cc_refine_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/refine-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-the-refined-sweep-shows" class="level2">
<h2 class="anchored" data-anchor-id="what-the-refined-sweep-shows">What the Refined Sweep Shows</h2>
<p>Both branches sit flat at essentially zero biomass below <code>capacity_mult ≈ 1.3</code>. Backward (arriving from a real population at the top of the sweep) breaks away from zero first, climbing smoothly from around <code>1.3</code>. Forward (arriving from nothing) stays flat near zero until roughly <code>1.4</code>, then jumps up sharply to rejoin Backward by about <code>1.45</code>-<code>1.5</code>. Above that, the two branches are indistinguishable on the plot which is consistent with Day 23’s own observation that Forward and Backward agree closely away from the boundary, e.g.&nbsp;around <code>capacity_mult ≈ 10</code>.</p>
<p>So the loop itself is real but narrow: the wide <code>(1.27, 2.07)</code> bracket Day 23 reported was an artefact of only having grid points at <code>1.27</code>, <code>1.62</code>, and <code>2.07</code> to sample from, not the loop’s actual extent.</p>
<hr>
</section>
<section id="pinning-down-the-edges-numerically" class="level2">
<h2 class="anchored" data-anchor-id="pinning-down-the-edges-numerically">Pinning Down the Edges Numerically</h2>
<p>Reading edges off a chart is imprecise, so each point gets classified alive or dead directly. “Dead” here means numerically collapsed to floating-point-underflow levels , Day 23’s dead values ranged <code>1e-24</code> to <code>1e-57</code> , not just “small”: a real, viable population right at the edge of this loop can itself be small (Backward’s <code>6.66e-4</code> and <code>1.46e-3</code> near-boundary points were both called “alive” on Day 23). <code>MIN_VIABLE_BIOMASS</code> (<code>1e-2</code>) is tuned for a different job, filtering numerical noise out of the relative-amplitude oscillation score in the phase-diagram sweeps, and is too strict to reuse here as it would wrongly call some genuinely-alive near-boundary points dead. A threshold of <code>1e-6</code> sits in the wide, empty gap between every dead value and every alive value seen so far, so it separates the two cleanly without needing to be finely tuned:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ALIVE_THRESHOLD <span class="ot">&lt;-</span> <span class="fl">1e-6</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>edge_calls <span class="ot">&lt;-</span> bif_cc_refine_df <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(branch <span class="sc">==</span> <span class="st">"max"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">capacity_mult =</span> value, direction, biomass, <span class="at">alive =</span> biomass <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(direction, capacity_mult)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># For each direction, walking capacity_mult ascending: the last point still</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># called dead, and the first point called alive. The true transition sits</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># somewhere in (dead_below, alive_above].</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>find_transition <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(capacity_mult)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">dead_below  =</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>alive) <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(capacity_mult, <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(capacity_mult),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">alive_above =</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(alive)  <span class="sc">%&gt;%</span> <span class="fu">slice_min</span>(capacity_mult, <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(capacity_mult)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>transitions <span class="ot">&lt;-</span> edge_calls <span class="sc">%&gt;%</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(direction) <span class="sc">%&gt;%</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> <span class="fu">find_transition</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>transitions</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  direction dead_below alive_above
  &lt;chr&gt;          &lt;dbl&gt;       &lt;dbl&gt;
1 Backward        1.27        1.30
2 Forward         1.37        1.41</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>direction</th>
<th>dead below</th>
<th>alive above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Backward</td>
<td>1.2669</td>
<td>1.3017</td>
</tr>
<tr class="even">
<td>Forward</td>
<td>1.3742</td>
<td>1.4119</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="what-this-pins-down" class="level2">
<h2 class="anchored" data-anchor-id="what-this-pins-down">What This Pins Down</h2>
<p>The genuine bistable window , where the two approach directions disagree about whether the population is alive at the identical <code>capacity_mult</code> , is <strong><code>(1.30, 1.41)</code></strong>, width <code>≈ 0.11</code>, about 8% relative width. Backward stays alive down to <code>1.3017</code>, collapsing somewhere before <code>1.2669</code>; Forward stays dead through <code>1.3742</code>, escaping somewhere before <code>1.4119</code>. Each edge is now bracketed to within a single grid step, roughly 3% in <code>capacity_mult</code>. This is a real result, not a sparse-sampling artefact, and an order of magnitude tighter than the <code>(1.27, 2.07)</code> bracket Day 23 could report from three interior points.</p>
<hr>
</section>
<section id="testing-gustavs-prediction-does-the-boundary-move-with-resource-rate" class="level2">
<h2 class="anchored" data-anchor-id="testing-gustavs-prediction-does-the-boundary-move-with-resource-rate">Testing Gustav’s Prediction: Does the Boundary Move With Resource Rate?</h2>
<p>Gustav’s prediction, from the 2026-07-08 meeting: since a higher <code>resource_decrease</code> means more of the default resource rate survives , a faster-replenishing resource , the population should need a <em>smaller</em> carrying capacity to sustain itself, so the <code>capacity_mult</code> boundary just pinned down above should shift left as <code>resource_decrease</code> increases. Everything so far only tested this at a single <code>resource_decrease = 0.001</code>, so there’s no way yet to tell whether that’s a general relationship or one cherrypicked rate.</p>
<section id="first-pass-five-resource-rates-wide-capacity-range" class="level3">
<h3 class="anchored" data-anchor-id="first-pass-five-resource-rates-wide-capacity-range">First Pass: Five Resource Rates, Wide Capacity Range</h3>
<p>Reruns the same <code>capacity_mult</code> bifurcation sweep at the same five <code>resource_decrease</code> values as Day 23’s original snake grid, rather than picking new ones which are the points behind the plot Gustav was reading when he made the prediction. The capacity range is widened well past <code>[1, 100]</code> on both sides in case the boundary shifts further than expected:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rd_grid_multi <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.0001</span>), <span class="fu">log</span>(<span class="fl">0.5</span>), <span class="at">length.out =</span> <span class="dv">5</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cc_seq_multi  <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.05</span>), <span class="fu">log</span>(<span class="dv">200</span>), <span class="at">length.out =</span> <span class="dv">20</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>bif_multi_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(rd_grid_multi, <span class="cf">function</span>(rd) {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">run_bifurcation_sweep</span>(cc_seq_multi, <span class="st">"capacity_mult"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">fixed_params =</span> <span class="fu">list</span>(<span class="at">resource_decrease =</span> rd),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">params_fn =</span> make_second_order_params_kr) <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">resource_decrease =</span> rd)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>})) <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rd_label =</span> <span class="fu">factor</span>(<span class="fu">sprintf</span>(<span class="st">"resource_decrease = %.4g"</span>, resource_decrease),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">sprintf</span>(<span class="st">"resource_decrease = %.4g"</span>, <span class="fu">sort</span>(<span class="fu">unique</span>(resource_decrease)))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bif_multi_df, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> biomass, <span class="at">color =</span> direction, <span class="at">linetype =</span> branch)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>rd_label, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"capacity_mult"</span>, <span class="at">y =</span> <span class="st">"Biomass"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"capacity_mult bifurcation at five different resource rates"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"If Gustav's prediction holds, the collapse boundary should shift left as resource_decrease increases"</span>) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/multi-rate-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Reading the transition off each panel with the same <code>ALIVE_THRESHOLD</code>/bracket logic as above:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>edge_calls_multi <span class="ot">&lt;-</span> bif_multi_df <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(branch <span class="sc">==</span> <span class="st">"max"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(resource_decrease, <span class="at">capacity_mult =</span> value, direction,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>           biomass, <span class="at">alive =</span> biomass <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(resource_decrease, direction, capacity_mult)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>transitions_multi <span class="ot">&lt;-</span> edge_calls_multi <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(resource_decrease, direction) <span class="sc">%&gt;%</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> <span class="fu">find_transition</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>bifurcation_trend <span class="ot">&lt;-</span> transitions_multi <span class="sc">%&gt;%</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bifurcation_estimate =</span> <span class="fu">sqrt</span>(dead_below <span class="sc">*</span> alive_above)) <span class="sc">%&gt;%</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(resource_decrease, direction, bifurcation_estimate) <span class="sc">%&gt;%</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> direction, <span class="at">values_from =</span> bifurcation_estimate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bifurcation_trend</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  resource_decrease Backward Forward
              &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1          0.000100     1.32    4.89
2          0.000841     1.32    4.89
3          0.00707      1.32    4.89
4          0.0595       1.32    4.89
5          0.5          1.32    4.89</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>resource_decrease</th>
<th>Backward</th>
<th>Forward</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.0001</td>
<td>1.32</td>
<td>4.89</td>
</tr>
<tr class="even">
<td>0.000841</td>
<td>1.32</td>
<td>4.89</td>
</tr>
<tr class="odd">
<td>0.00707</td>
<td>1.32</td>
<td>4.89</td>
</tr>
<tr class="even">
<td>0.0595</td>
<td>1.32</td>
<td>4.89</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td>1.32</td>
<td>4.89</td>
</tr>
</tbody>
</table>
<p>It’s completely flat - every resource rate gives the exact same bracket. That’s not evidence against Gustav’s prediction, though: the grid here steps by roughly 55% (the ratio between adjacent log-spaced points over 3.6 decades in 20 steps), while the actual hysteresis window at a single rate, pinned down above, is only about 8% wide. A shift smaller than the grid’s own resolution looks exactly like no shift at all. This result only says the grid is too coarse to tell, not that the boundary is fixed.</p>
</section>
<section id="second-pass-zoomed-to-1-15" class="level3">
<h3 class="anchored" data-anchor-id="second-pass-zoomed-to-1-15">Second Pass: Zoomed to [1, 15]</h3>
<p>Same five resource rates, <code>capacity_mult</code> narrowed to <code>[1, 15]</code> , comfortably bracketing anything the coarse pass could plausibly have missed , at higher density. Settle time is cut from <code>600</code> to <code>150</code> to keep the run practical, reusing the exact scan-rate check Day 23 already ran on a similar grid (which found <code>t_run = 150</code> agreed with <code>t_run = 600</code> everywhere), rather than an unvalidated shortcut:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cc_seq_multi_refine <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="dv">1</span>), <span class="fu">log</span>(<span class="dv">15</span>), <span class="at">length.out =</span> <span class="dv">20</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>bif_multi_refine_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(rd_grid_multi, <span class="cf">function</span>(rd) {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">run_bifurcation_sweep</span>(cc_seq_multi_refine, <span class="st">"capacity_mult"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">fixed_params =</span> <span class="fu">list</span>(<span class="at">resource_decrease =</span> rd),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">params_fn =</span> make_second_order_params_kr,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">t_run =</span> <span class="dv">150</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">resource_decrease =</span> rd)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>})) <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rd_label =</span> <span class="fu">factor</span>(<span class="fu">sprintf</span>(<span class="st">"resource_decrease = %.4g"</span>, resource_decrease),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">sprintf</span>(<span class="st">"resource_decrease = %.4g"</span>, <span class="fu">sort</span>(<span class="fu">unique</span>(resource_decrease)))))</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>edge_calls_multi_refine <span class="ot">&lt;-</span> bif_multi_refine_df <span class="sc">%&gt;%</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(branch <span class="sc">==</span> <span class="st">"max"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(resource_decrease, <span class="at">capacity_mult =</span> value, direction,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>           biomass, <span class="at">alive =</span> biomass <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(resource_decrease, direction, capacity_mult)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>transitions_multi_refine <span class="ot">&lt;-</span> edge_calls_multi_refine <span class="sc">%&gt;%</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(resource_decrease, direction) <span class="sc">%&gt;%</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> <span class="fu">find_transition</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>transitions_multi_refine</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   resource_decrease direction dead_below alive_above
               &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;       &lt;dbl&gt;
 1          0.000100 Backward        1           1.15
 2          0.000100 Forward         2.71        3.13
 3          0.000841 Backward        1.15        1.33
 4          0.000841 Forward         1.77        2.04
 5          0.00707  Backward        1.15        1.33
 6          0.00707  Forward         1.53        1.77
 7          0.0595   Backward        1           1.15
 8          0.0595   Forward         1.53        1.77
 9          0.5      Backward        1           1.15
10          0.5      Forward         1.53        1.77</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>resource_decrease</th>
<th>direction</th>
<th>dead below</th>
<th>alive above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.0001</td>
<td>Backward</td>
<td>1.00</td>
<td>1.15</td>
</tr>
<tr class="even">
<td>0.0001</td>
<td>Forward</td>
<td>2.71</td>
<td>3.13</td>
</tr>
<tr class="odd">
<td>0.000841</td>
<td>Backward</td>
<td>1.15</td>
<td>1.33</td>
</tr>
<tr class="even">
<td>0.000841</td>
<td>Forward</td>
<td>1.77</td>
<td>2.04</td>
</tr>
<tr class="odd">
<td>0.00707</td>
<td>Backward</td>
<td>1.15</td>
<td>1.33</td>
</tr>
<tr class="even">
<td>0.00707</td>
<td>Forward</td>
<td>1.53</td>
<td>1.77</td>
</tr>
<tr class="odd">
<td>0.0595</td>
<td>Backward</td>
<td>1.00</td>
<td>1.15</td>
</tr>
<tr class="even">
<td>0.0595</td>
<td>Forward</td>
<td>1.53</td>
<td>1.77</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td>Backward</td>
<td>1.00</td>
<td>1.15</td>
</tr>
<tr class="even">
<td>0.5</td>
<td>Forward</td>
<td>1.53</td>
<td>1.77</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="what-this-shows" class="level2">
<h2 class="anchored" data-anchor-id="what-this-shows">What This Shows</h2>
<p><strong>Forward confirms Gustav’s prediction, clearly.</strong> The escape-from-nothing boundary shifts left monotonically as <code>resource_decrease</code> increases: the geometric-mean estimate drops from <code>≈2.91</code> at the lowest rate down to <code>≈1.65</code> by <code>resource_decrease = 0.00707</code>, then holds there through the two highest rates. Higher resource rate really does need a smaller <code>capacity_mult</code> for the population to establish – exactly the direction predicted, and not an artefact of the single rate the <code>(1.30, 1.41)</code> window above was found at.</p>
<p><strong>Backward doesn’t confirm or contradict it - it’s inconclusive at this resolution.</strong> The Backward bracket only ever takes two values across all five rates, and doesn’t move monotonically with <code>resource_decrease</code> (tight at the two middle rates, looser at the three outer ones). Backward tends to be the more robust direction throughout this project - it starts from an established population rather than nothing - so if its true shift across this range is smaller than the grid’s ~15% step, this grid simply can’t resolve it. That’s a gap in the evidence, not evidence against the prediction.</p>
<p><strong>A bonus finding: the loop itself narrows, not just shifts.</strong> The gap between Forward and Backward shrinks from roughly <code>2.7</code>x at the lowest resource rate down to about <code>1.3</code>-<code>1.5</code>x at the highest. Higher resource rate doesn’t just move the whole bistable region left,but also compresses it.</p>
<p><strong>One loose end:</strong> <code>resource_decrease = 0.0595</code> and <code>0.5</code> , nearly a decade apart , land on the <em>exact same</em> Forward bracket, <code>(1.53, 1.77)</code>. That could be a genuine floor the boundary can’t be pushed below, or the same resolution ceiling that’s hiding Backward’s trend. Telling those apart needs a finer grid at full settle time, not yet done. Worth flagging too: today’s refined numbers were generated at the <code>t_run = 150</code> shortcut rather than the validated <code>600</code>, so there’s some risk these exact brackets shift slightly at longer settle times, though Day 23’s own check suggests that risk is small.</p>
<hr>
</section>
<section id="testing-whether-size-structure-is-necessary-a-non-size-structured-predator-prey-model" class="level2">
<h2 class="anchored" data-anchor-id="testing-whether-size-structure-is-necessary-a-non-size-structured-predator-prey-model">Testing Whether Size Structure Is Necessary: A Non-Size-Structured Predator-Prey Model</h2>
<p>From the 2026-07-08 meeting: is the <code>capacity_mult</code> collapse bifurcation actually a consequence of mizer’s size structure, or would the same qualitative behaviour already show up in the simplest possible unstructured version - a two-species system with no age, size, or stage distinction at all? Gustav’s suggested model: prey with chemostat-style replenishment and a carrying capacity (the same functional form as mizer’s <code>resource_semichemostat</code>), predator with intake proportional to prey times predator (mass-action, no saturation) and mortality proportional to its own abundance:</p>
<pre><code>dN/dt = D * (K - N) - a * N * P
dP/dt = e * a * N * P - m * P</code></pre>
<p>Setting <code>dP/dt = 0</code> (excluding the trivial <code>P = 0</code> branch) gives the predator’s break-even prey level, <code>N* = m / (e * a)</code> – independent of <code>K</code>. Coexistence needs the prey-alone equilibrium (<code>N = K</code>) to exceed that level, i.e.&nbsp;<code>K &gt; m / (e * a)</code>. Crossing that threshold from below is a transcritical bifurcation: the prey-only state and the coexistence state exchange stability.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(deSolve)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>predator_prey_rhs <span class="ot">&lt;-</span> <span class="cf">function</span>(t, state, parms) {</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Positional indexing: lsoda strips state's names during its internal</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Jacobian estimation. Clamped to &gt;= 0: an under-damped transient can</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># hand a later step a transiently negative N or P, which flips the sign</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># of a*N*P and produced a NaN-tolerance solver failure during testing.</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  N <span class="ot">&lt;-</span> <span class="fu">max</span>(state[<span class="dv">1</span>], <span class="dv">0</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  P <span class="ot">&lt;-</span> <span class="fu">max</span>(state[<span class="dv">2</span>], <span class="dv">0</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  D <span class="ot">&lt;-</span> parms[[<span class="st">"D"</span>]]</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> parms[[<span class="st">"a"</span>]]</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> parms[[<span class="st">"e"</span>]]</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> parms[[<span class="st">"m"</span>]]</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  K <span class="ot">&lt;-</span> parms[[<span class="st">"K"</span>]]</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  dN <span class="ot">&lt;-</span> D <span class="sc">*</span> (K <span class="sc">-</span> N) <span class="sc">-</span> a <span class="sc">*</span> N <span class="sc">*</span> P</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  dP <span class="ot">&lt;-</span> e <span class="sc">*</span> a <span class="sc">*</span> N <span class="sc">*</span> P <span class="sc">-</span> m <span class="sc">*</span> P</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="fu">c</span>(dN, dP))</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>predator_prey_params <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">D =</span> <span class="dv">1</span>, <span class="at">a =</span> <span class="dv">1</span>, <span class="at">e =</span> <span class="fl">0.5</span>, <span class="at">m =</span> <span class="fl">0.3</span>, <span class="at">K =</span> <span class="dv">1</span>)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>N_star <span class="ot">&lt;-</span> <span class="fu">with</span>(predator_prey_params, m <span class="sc">/</span> (e <span class="sc">*</span> a))</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>K_crit <span class="ot">&lt;-</span> N_star</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>run_predator_prey <span class="ot">&lt;-</span> <span class="cf">function</span>(K, <span class="at">state0 =</span> <span class="fu">c</span>(<span class="at">N =</span> <span class="dv">1</span>, <span class="at">P =</span> <span class="fl">0.1</span>), <span class="at">t_max =</span> <span class="dv">500</span>, <span class="at">parms =</span> predator_prey_params) {</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  parms<span class="sc">$</span>K <span class="ot">&lt;-</span> K</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  out  <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">ode</span>(<span class="at">y =</span> state0, <span class="at">times =</span> <span class="fu">seq</span>(<span class="dv">0</span>, t_max, <span class="at">by =</span> <span class="fl">0.5</span>),</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>                            <span class="at">func =</span> predator_prey_rhs, <span class="at">parms =</span> parms))</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>  late <span class="ot">&lt;-</span> out[out<span class="sc">$</span>time <span class="sc">&gt;</span> t_max <span class="sc">*</span> <span class="fl">0.6</span>, ]</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(late) <span class="sc">==</span> <span class="dv">0</span>) late <span class="ot">&lt;-</span> <span class="fu">tail</span>(out, <span class="dv">1</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">K =</span> K, <span class="at">max_P =</span> <span class="fu">max</span>(late<span class="sc">$</span>P), <span class="at">min_P =</span> <span class="fu">min</span>(late<span class="sc">$</span>P), <span class="at">mean_P =</span> <span class="fu">mean</span>(late<span class="sc">$</span>P),</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>             <span class="at">n_final =</span> <span class="fu">tail</span>(late<span class="sc">$</span>N, <span class="dv">1</span>), <span class="at">p_final =</span> <span class="fu">tail</span>(late<span class="sc">$</span>P, <span class="dv">1</span>))</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>P_star_at <span class="ot">&lt;-</span> <span class="cf">function</span>(K, <span class="at">parms =</span> predator_prey_params) {</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>  D <span class="ot">&lt;-</span> parms[[<span class="st">"D"</span>]]</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> parms[[<span class="st">"a"</span>]]</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  D <span class="sc">*</span> (K <span class="sc">-</span> N_star) <span class="sc">/</span> (a <span class="sc">*</span> N_star)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>A quick sanity check before sweeping the whole range: does a single run below and above <code>K_crit</code> behave the way the analytic threshold predicts?</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sanity_below <span class="ot">&lt;-</span> <span class="fu">run_predator_prey</span>(<span class="at">K =</span> K_crit <span class="sc">*</span> <span class="fl">0.5</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sanity_above <span class="ot">&lt;-</span> <span class="fu">run_predator_prey</span>(<span class="at">K =</span> K_crit <span class="sc">*</span> <span class="dv">2</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"K = %.3f (below K_crit): simulated P settles to %.6f (expect ~0)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"K = %.3f (above K_crit): simulated P settles to %.6f, analytic P* = %.6f</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  K_crit <span class="sc">*</span> <span class="fl">0.5</span>, sanity_below<span class="sc">$</span>p_final,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  K_crit <span class="sc">*</span> <span class="dv">2</span>, sanity_above<span class="sc">$</span>p_final, <span class="fu">P_star_at</span>(K_crit <span class="sc">*</span> <span class="dv">2</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>K = 0.300 (below K_crit): simulated P settles to 0.000000 (expect ~0)
K = 1.200 (above K_crit): simulated P settles to 1.000000, analytic P* = 1.000000</code></pre>
</div>
</div>
<section id="a-sweep-design-lesson-why-not-state-carry-this-one" class="level3">
<h3 class="anchored" data-anchor-id="a-sweep-design-lesson-why-not-state-carry-this-one">A Sweep-Design Lesson: Why Not State-Carry This One</h3>
<p>Every <code>capacity_mult</code> sweep in this project so far carries the settled state from one point to the next, to test for hysteresis. That doesn’t transfer here: a transcritical bifurcation has no bistable region at all, so Forward and Backward are only ever expected to disagree exactly at <code>K_crit</code>. Worse, state-carrying actively breaks this model and with no immigration term, <code>dP/dt = 0</code> identically once <code>P</code> underflows to exact floating-point zero, so once an early, harsh <code>K</code> kills the population, it stays dead for every later, more favourable <code>K</code> too. A first attempt hit exactly that: predator biomass read as numerically extinct all the way out to <code>K = 3</code>, deep in territory the analytic threshold says should sustain a real population.</p>
<p>The fix is to test each <code>K</code> independently, fresh from the same default initial condition every time, rather than threading one easily-extinguished population through the whole sweep:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>K_seq_pp <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(K_crit <span class="sc">*</span> <span class="fl">0.2</span>), <span class="fu">log</span>(K_crit <span class="sc">*</span> <span class="dv">5</span>), <span class="at">length.out =</span> <span class="dv">25</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>pp_fresh_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(K_seq_pp, run_predator_prey))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>pp_analytic_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">K =</span> K_seq_pp) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">P_star =</span> <span class="fu">ifelse</span>(K <span class="sc">&gt;</span> K_crit, <span class="fu">vapply</span>(K, P_star_at, <span class="fu">numeric</span>(<span class="dv">1</span>)), <span class="cn">NA_real_</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pp_fresh_df, <span class="fu">aes</span>(<span class="at">x =</span> K, <span class="at">y =</span> p_final)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#4C72B0"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#4C72B0"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pp_analytic_df, <span class="fu">aes</span>(<span class="at">x =</span> K, <span class="at">y =</span> P_star),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"grey40"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> K_crit, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"K (prey carrying capacity)"</span>, <span class="at">y =</span> <span class="st">"Predator biomass (P), settled"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Non-size-structured predator-prey model: fresh run at each K"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Solid = simulated; dashed = analytic P*(K); dotted = analytic K_crit"</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/pp-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>find_transition_pp <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  df         <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(K)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  dead_vals  <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>alive) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(K)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  alive_vals <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(alive)  <span class="sc">%&gt;%</span> <span class="fu">pull</span>(K)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">dead_below  =</span> <span class="cf">if</span> (<span class="fu">length</span>(dead_vals)  <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">max</span>(dead_vals)  <span class="cf">else</span> <span class="cn">NA_real_</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">alive_above =</span> <span class="cf">if</span> (<span class="fu">length</span>(alive_vals) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">min</span>(alive_vals) <span class="cf">else</span> <span class="cn">NA_real_</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>pp_transition <span class="ot">&lt;-</span> pp_fresh_df <span class="sc">%&gt;%</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(K, <span class="at">alive =</span> p_final <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">find_transition_pp</span>()</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>pp_transition</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  dead_below alive_above
1  0.5246912         0.6</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Analytic K_crit</th>
<th>Simulated dead below</th>
<th>Simulated alive above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.6000</td>
<td>0.5247</td>
<td>0.6000</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="what-this-shows-1" class="level2">
<h2 class="anchored" data-anchor-id="what-this-shows-1">What This Shows</h2>
<p>Predator biomass sits at zero for every <code>K</code> below <code>≈0.6</code>, then rises along a curve that lands exactly on the analytic <code>P*(K)</code> line above it - simulated and analytic values overlap completely, and the simulated transition, <code>(0.5247, 0.60]</code>, brackets the analytic <code>K_crit = 0.6</code> in the very last grid step below it. No hysteresis, as expected for a transcritical bifurcation.</p>
<p>This settles the original question, at least for one specific feature: <strong>the collapse-at-low-carrying-capacity behaviour does not require size resolution.</strong> A bare 2-ODE consumer-resource system with no age, size, or stage structure at all shows the same “population collapses below a critical capacity” transition, for the same textbook reason - Tilman’s R* threshold, not anything about growth or maturation.</p>
<p>But there’s a pointed asymmetry worth carrying forward: the mizer model’s <code>capacity_mult</code> boundary has <em>genuine</em> hysteresis (the real <code>(1.30, 1.41)</code> bistable window pinned down earlier today), and this toy model has none, by mathematical necessity of its linear functional response - textbook theory (Rosenzweig’s paradox of enrichment) says a model like this one can never destabilise into bistability or oscillation, regardless of parameters. So while the <em>existence</em> of a collapse threshold clearly doesn’t need size structure, the <em>hysteresis</em> around it apparently needs something this toy model doesn’t have: plausibly mizer’s saturating feeding kernel, the size/stage structure itself, or the Beverton-Holt recruitment nonlinearity. That’s a sharper follow-up question than the one this model actually answered.</p>
<hr>
</section>
<section id="is-the-capacity_mult-bifurcation-shape-just-an-artefact-of-our-species-parameters" class="level2">
<h2 class="anchored" data-anchor-id="is-the-capacity_mult-bifurcation-shape-just-an-artefact-of-our-species-parameters">Is the capacity_mult Bifurcation Shape Just an Artefact of Our Species Parameters?</h2>
<p>Every <code>capacity_mult</code> sweep in this project, from Day 22 onward, has used the same anchovy-like calibration (<code>w_min = 0.0003</code>, <code>w_max = 66.5</code>, <code>w_mat = 10</code>, <code>lambda = 2.05</code>, <code>alpha = 0.1</code>, <code>gamma = 750</code>, <code>ks = 0</code>), carried over unchanged since Day 17. That’s one specific point in a large parameter space - nothing so far has checked whether the collapse-then-rise shape survives swapping in a completely different species. <code>newSingleSpeciesParams()</code> called with none of those arguments gives mizer’s own built-in defaults instead, so rerunning the same kind of sweep against it is the direct test.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>make_default_species_params_kr <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>, <span class="at">capacity_mult =</span> <span class="dv">1</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">second_order =</span> <span class="cn">TRUE</span>, <span class="at">ext_diff =</span> <span class="fl">0.00</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">lambda =</span> <span class="cn">NULL</span>) {</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># species_name is a label, not a biological parameter -- kept as "Anchovy"</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># purely so run_bifurcation_sweep()'s shared harness (which hardcodes</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># getBiomass(sim)[, "Anchovy"] for extracting the biomass series) doesn't</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need touching. Every actual biological argument (w_min, w_max, w_mat,</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># lambda, kappa, alpha, gamma, ks, ...) is left unspecified, so mizer</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fills in its own defaults instead of this project's anchovy calibration.</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(<span class="at">species_name =</span> <span class="st">"Anchovy"</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">given_species_params</span>(params)<span class="sc">$</span>D_ext <span class="ot">&lt;-</span> ext_diff</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setBevertonHolt</span>(params)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  default_capacity <span class="ot">&lt;-</span> <span class="fu">getResourceCapacity</span>(params)</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  r  <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  cc <span class="ot">&lt;-</span> default_capacity <span class="sc">*</span> capacity_mult</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r, <span class="at">resource_capacity =</span> cc,</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>,</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>                        <span class="at">balance =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (second_order) {</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">second_order_w</span>(params) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">flux =</span> <span class="st">"centred"</span>, <span class="at">bin_average =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  params</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The scan will be wide and sparse rather than a multi-stage refinement - the point here is just to see whether a collapse-then-rise shape shows up at all for a different species, not to pin its edges down precisely the way the anchovy version was. <code>t_run = 150</code> reuses the same validated shortcut as the multi-rate sweeps above; <code>capacity_mult</code> spans 5 orders of magnitude since there’s no prior information about where a default species’ threshold would fall:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>cc_seq_default <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.01</span>), <span class="fu">log</span>(<span class="dv">1000</span>), <span class="at">length.out =</span> <span class="dv">15</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>bif_default_df <span class="ot">&lt;-</span> <span class="fu">run_bifurcation_sweep</span>(cc_seq_default, <span class="st">"capacity_mult"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">fixed_params =</span> <span class="fu">list</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">params_fn =</span> make_default_species_params_kr,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">t_run =</span> <span class="dv">150</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_bifurcation</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  bif_default_df, <span class="st">"capacity_mult"</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"capacity_mult bifurcation with mizer's own default species parameters"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resource_decrease held at 0.001, t_run = 150 -- same sweep style as the anchovy version, different species"</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/default-species-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>edge_calls_default <span class="ot">&lt;-</span> bif_default_df <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(branch <span class="sc">==</span> <span class="st">"max"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">capacity_mult =</span> value, direction, biomass, <span class="at">alive =</span> biomass <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(direction, capacity_mult)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>transitions_default <span class="ot">&lt;-</span> edge_calls_default <span class="sc">%&gt;%</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(direction) <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> <span class="fu">find_transition</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>transitions_default</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  direction dead_below alive_above
  &lt;chr&gt;          &lt;dbl&gt;       &lt;dbl&gt;
1 Backward       0.611        1.39
2 Forward        3.16         7.20</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>direction</th>
<th>dead below</th>
<th>alive above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Backward</td>
<td>0.611</td>
<td>1.389</td>
</tr>
<tr class="even">
<td>Forward</td>
<td>3.162</td>
<td>7.197</td>
</tr>
</tbody>
</table>
<p>The coarse pass alone is already informative: the collapse-then-rise shape reproduces cleanly with a completely different species, and Backward’s and Forward’s brackets don’t overlap at all, a ~2.3x gap between them - apparent real hysteresis, not just an artefact of this grid’s own ~62% step size. But this project has learned that lesson before (the resource-rate sweep earlier today): a coarse grid can only ever <em>overestimate</em> how wide a bistable region is. Worth checking directly rather than taking the gap at face value.</p>
<section id="zooming-into-the-hysteresis-region" class="level3">
<h3 class="anchored" data-anchor-id="zooming-into-the-hysteresis-region">Zooming Into the Hysteresis Region</h3>
<p>Narrowing <code>capacity_mult</code> to <code>[0.5, 8]</code> - comfortably bracketing both coarse-pass edges with margin - at 25 points. <code>t_run</code> goes back to the sweep’s own default, <code>600</code>, rather than reusing the <code>150</code> shortcut from the coarse pass: that shortcut was validated specifically against the anchovy-calibrated model (Day 23’s scan-rate check), not this different default species, so reusing it here would be stacking one unvalidated assumption on another. The window is narrow enough now that full accuracy doesn’t cost much:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>cc_seq_default_refine <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">seq</span>(<span class="fu">log</span>(<span class="fl">0.5</span>), <span class="fu">log</span>(<span class="dv">8</span>), <span class="at">length.out =</span> <span class="dv">25</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>bif_default_refine_df <span class="ot">&lt;-</span> <span class="fu">run_bifurcation_sweep</span>(cc_seq_default_refine, <span class="st">"capacity_mult"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">fixed_params =</span> <span class="fu">list</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">params_fn =</span> make_default_species_params_kr,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">t_run =</span> <span class="dv">600</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_bifurcation</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  bif_default_refine_df, <span class="st">"capacity_mult"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Refined capacity_mult bifurcation, default species: [0.5, 8]"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resource_decrease held at 0.001, t_run = 600 -- 25 points vs. the coarse pass's 15 over [0.01, 1000]"</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/default-species-refine-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>edge_calls_default_refine <span class="ot">&lt;-</span> bif_default_refine_df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(branch <span class="sc">==</span> <span class="st">"max"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">capacity_mult =</span> value, direction, biomass, <span class="at">alive =</span> biomass <span class="sc">&gt;</span> ALIVE_THRESHOLD) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(direction, capacity_mult)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>transitions_default_refine <span class="ot">&lt;-</span> edge_calls_default_refine <span class="sc">%&gt;%</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(direction) <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> <span class="fu">find_transition</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>transitions_default_refine</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  direction dead_below alive_above
  &lt;chr&gt;          &lt;dbl&gt;       &lt;dbl&gt;
1 Backward       0.891        1   
2 Forward        1.12         1.26</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>direction</th>
<th>dead below</th>
<th>alive above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Backward</td>
<td>0.8909</td>
<td>1.0000</td>
</tr>
<tr class="even">
<td>Forward</td>
<td>1.1225</td>
<td>1.2599</td>
</tr>
</tbody>
</table>
<p>One artefact worth flagging in the plot itself: Forward shows a sharp, narrow spike (up to roughly <code>8e-4</code>, well above the smooth curve on either side) right around <code>capacity_mult ≈ 1.2-1.3</code>, before dropping back and resuming the smooth rise from <code>~1.5</code> onward. This is very likely <strong>critical slowing down</strong> -we’ve already found (Day 18, Day 23’s own scan-rate check) that relaxation time diverges right at a bifurcation point, so <code>t_run = 600</code> may not be long enough to fully settle exactly at the escape threshold, even though it’s plenty everywhere else. That one point’s “max” reading is probably an unsettled transient overshoot, not a real equilibrium value. It doesn’t change the transition bracket itself (based on crossing <code>ALIVE_THRESHOLD</code>, comfortably satisfied either way), but that specific point shouldn’t be read as genuine steady-state biomass.</p>
</section>
</section>
<section id="what-this-shows-2" class="level2">
<h2 class="anchored" data-anchor-id="what-this-shows-2">What This Shows</h2>
<p>The collapse-then-rise shape reproduces cleanly with a completely different species: flat near-zero biomass at low <code>capacity_mult</code>, rising smoothly at higher <code>capacity_mult</code> – the same qualitative shape as every anchovy-calibrated sweep this project has run, despite none of the anchovy-specific biological parameters being used.</p>
<p>Real hysteresis shows up too, and refining it down reveals its actual size: Backward stays alive down to <code>1.00</code>, collapsing somewhere before <code>0.89</code>; Forward stays dead through <code>1.1225</code>, escaping somewhere before <code>1.2599</code>. The two directions actually disagree only in the narrow band <code>(1.00, 1.12)</code>, about 12% relative width. The coarse pass’s apparent <code>(1.39, 3.16)</code> gap was mostly a resolution artefact, not the bistable region’s real extent. That 12% figure lands in the same order of magnitude as the anchovy model’s own <code>(1.30, 1.41)</code> window (~8%), rather than the dramatically wider gap the coarse pass suggested as a tidier, more convincing match between two very differently-parameterised species than “wider in relative terms” would have been.</p>
<p>One more thing worth a closer look later: away from the transition itself, the branches fan apart slightly at the top of the tested range (min biomass noticeably below max at the highest <code>capacity_mult</code> in the coarse pass), reminiscent of the paradox-of-enrichment-style oscillation onset the anchovy model showed around <code>capacity_mult = 10</code> on Day 22. Not confirmed as real oscillation yet , <code>t_run = 150</code> may just not be long enough to fully settle there , but consistent with the same pattern showing up again.</p>
<p>Taken together, this is fairly strong evidence that the collapse bifurcation <em>and</em> its hysteresis are general features of this consumer-resource structure, not artefacts of the specific anchovy calibration used throughout this project - the species parameters seem to control <em>where</em> and <em>how wide</em> the bistable region sits (and even then, only by a factor of ~1.3-1.5x in relative width), not <em>whether</em> it exists at all.</p>
<hr>
</section>
<section id="is-the-juvenile-biomass-pileup-general-or-specific-to-our-anchovy-calibration" class="level2">
<h2 class="anchored" data-anchor-id="is-the-juvenile-biomass-pileup-general-or-specific-to-our-anchovy-calibration">Is the Juvenile-Biomass Pileup General, or Specific to Our Anchovy Calibration?</h2>
<p>Day 19 found that the anchovy size spectrum drops several orders of magnitude right at <code>w_mat = 10</code>: only <code>~0.031%</code> (default feeding kernel) to <code>~0.0033%</code> (highest-amplitude kernel) of total biomass was ever “catchable” (mature). That was flagged as an open demographic question, survivorship through growth, not yet explained, and carried forward unresolved through Days 20-24. The default-species <code>capacity_mult</code> check above only looked at <em>aggregate</em> biomass and found the same collapse-then-rise shape; it never looked at how that biomass is distributed across sizes. This is the actual pileup check: mizer’s own default species instead of the anchovy calibration, but looking at the size spectrum itself rather than the aggregate bifurcation curve.</p>
<p><code>capacity_mult = 10</code> is used rather than <code>1</code>: the refined sweep above found <code>capacity_mult = 1</code> sits right at this species’ own collapse boundary (Backward barely alive there, Forward dead until <code>~1.26</code>) – a marginal, not-fully-established population would be a poor basis for a clean size-spectrum comparison. <code>capacity_mult = 10</code> is comfortably inside the coexistence region, matching the kind of healthy, established regime Day 19’s original anchovy spectrum was taken from.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>default_spectrum_params <span class="ot">&lt;-</span> <span class="fu">make_default_species_params_kr</span>(<span class="at">resource_decrease =</span> <span class="fl">0.001</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                                                           <span class="at">capacity_mult =</span> <span class="dv">10</span>, <span class="at">lambda =</span> <span class="fl">2.05</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>default_spectrum_sim <span class="ot">&lt;-</span> <span class="fu">project</span>(default_spectrum_params, <span class="at">t_max =</span> <span class="dv">600</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.5</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>, <span class="at">method =</span> <span class="st">"tr_bdf2"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>last_default_spectrum <span class="ot">&lt;-</span> <span class="fu">dim</span>(default_spectrum_sim<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>default_w_mat         <span class="ot">&lt;-</span> default_spectrum_params<span class="sc">@</span>species_params<span class="sc">$</span>w_mat[<span class="dv">1</span>]</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>default_spectrum_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">w               =</span> default_spectrum_sim<span class="sc">@</span>params<span class="sc">@</span>w,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">biomass_density =</span> default_spectrum_sim<span class="sc">@</span>n[last_default_spectrum, <span class="dv">1</span>, ] <span class="sc">*</span> default_spectrum_sim<span class="sc">@</span>params<span class="sc">@</span>w</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(default_spectrum_df, <span class="fu">aes</span>(<span class="at">x =</span> w, <span class="at">y =</span> biomass_density)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"#4C72B0"</span>) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> default_w_mat, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span> <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Body weight (g)"</span>, <span class="at">y =</span> <span class="st">"Biomass density (N x w)"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Size spectrum, mizer's own default species parameters"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">sprintf</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">"capacity_mult = 10, resource_decrease = 0.001 -- dashed line = this species' own w_mat = %.3g"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>         default_w_mat</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>       )) <span class="sc">+</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-07-09-day-twenty-four_files/figure-html/default-spectrum-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Same <code>catchable_fraction()</code> quantification Day 19 used for the anchovy, so the two are directly comparable numbers, not just similar-looking plots:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>catchable_fraction_default <span class="ot">&lt;-</span> <span class="cf">function</span>(sim, cutoff) {</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  last         <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  w            <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>w</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  dw           <span class="ot">&lt;-</span> sim<span class="sc">@</span>params<span class="sc">@</span>dw</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  bm_density   <span class="ot">&lt;-</span> sim<span class="sc">@</span>n[last, <span class="dv">1</span>, ] <span class="sc">*</span> w <span class="sc">*</span> dw</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  total_bm     <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  catchable_bm <span class="ot">&lt;-</span> <span class="fu">sum</span>(bm_density[w <span class="sc">&gt;=</span> cutoff])</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">total_bm =</span> total_bm, <span class="at">catchable_bm =</span> catchable_bm,</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">catchable_fraction =</span> catchable_bm <span class="sc">/</span> total_bm)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="fu">catchable_fraction_default</span>(default_spectrum_sim, <span class="at">cutoff =</span> default_w_mat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     total_bm catchable_bm catchable_fraction
1 0.001334518  9.51763e-05         0.07131888</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>w_mat</th>
<th>Fraction of biomass at or above w_mat (“catchable”)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>25.12</td>
<td>7.13%</td>
</tr>
</tbody>
</table>
</section>
<section id="what-this-shows-3" class="level2">
<h2 class="anchored" data-anchor-id="what-this-shows-3">What This Shows</h2>
<p><code>~7.1%</code> of this default species’ biomass sits at or above its own <code>w_mat</code> - roughly 200-2000x larger than the anchovy’s <code>0.031%</code>/<code>0.0033%</code>. The spectrum plot shows why: the normal, gently-declining shape for most of the size range, a small shoulder right around <code>w_mat = 25.12</code>, then a steep drop-off toward the top of the tested weights which is a much more moderate version of the same qualitative “something changes at maturity” feature, not the near-total juvenile domination (<code>&gt;99.9%</code>) Day 19 found.</p>
<p>This points the opposite direction from the capacity_mult check above: <strong>the juvenile-biomass pileup does not look like a general mizer/growth-mortality feature.</strong> It’s not simply that maturity sits in a different place on the size axis either - the anchovy’s <code>w_mat</code>/<code>w_max</code> ratio (<code>10/66.5 ≈ 0.15</code>) and the default species’ (roughly <code>25/100 ≈ 0.25</code>, going by where the spectrum’s steep drop happens) aren’t wildly different. Both species show <em>some</em> juvenile skew, which is ordinary size-spectrum theory (smaller, younger individuals are always more abundant), but the anchovy’s skew is several orders of magnitude more extreme. That points at the specific <code>alpha</code>, <code>gamma</code>, <code>ks</code>, or <code>w_min</code>/<code>w_max</code> choices carried since Day 17 , not mizer’s growth-mortality structure in general , as what’s actually producing the near-complete absence of mature biomass in this project’s anchovy model.</p>
<p>So the two checks run today land on opposite answers: the <code>capacity_mult</code> collapse-and-hysteresis behaviour looks like a general feature of this model class, while the juvenile-biomass pileup looks like a specific consequence of this project’s own species calibration.</p>
<hr>
</section>
<section id="what-this-all-adds-up-to" class="level2">
<h2 class="anchored" data-anchor-id="what-this-all-adds-up-to">What This All Adds Up To</h2>
<p>A properly satisfying day - four open questions went in, four real answers came out. Day 23’s rough <code>(1.27, 2.07)</code> bracket is now a precisely-pinned <code>(1.30, 1.41)</code> window, Gustav’s prediction held up for the Forward branch, and both robustness checks (a different species, a different functional response) landed the same way: none of this is an anchovy-specific artefact.</p>
<p>Best result of the day: the toy predator-prey model. A bare two-ODE system reproduces mizer’s collapse threshold exactly, but not the hysteresis around it. That’s not a dead end, it’s progress: the Jacobian argument explains <em>why</em> (chemostat-style prey growth keeps the trace negative no matter the predation term’s shape), which narrows the missing ingredient down to real size structure, or recruitment.</p>
<p>One loose thread: the juvenile-biomass pileup looks anchovy-specific rather than general, but what in the calibration actually drives it is only partly worked out - picked up in What’s Next.</p>
<hr>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<ul>
<li><strong>Give the toy predator-prey model a time delay.</strong> Route the predator’s growth through a lagged version of the prey signal (<code>dP/dt</code> depending on <code>P(t - τ)</code> rather than <code>P(t)</code>) instead of an instantaneous response, representing something like a maturation or handling lag before eaten prey turns into predator growth. Delayed feedback is a well-known route to sustained oscillation and multistability that an instantaneous ODE can’t produce on its own, so it’s a different candidate mechanism from size structure or saturation.</li>
<li><strong>Rerun the <code>alpha</code>/<code>gamma</code>/<code>ks</code>/<code>kappa</code> juvenile-pileup isolation properly.</strong> Today’s pass only swapped each parameter to one alternate value, and mizer’s own parameter interdependency (an unspecified parameter silently re-deriving from whatever <em>was</em> specified) muddied several of the four comparisons. Needs a real range per parameter, with every other parameter explicitly pinned.</li>
<li><strong>Try a feedback-loop variant of the predator-prey model</strong>, such as switching prey growth from chemostat to logistic (<code>r*N*(1-N/K)</code>) or another form of density-dependent self-limitation, to test whether that , rather than time delay or size structure , is what actually unlocks mizer’s hysteresis.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>