<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samia">
<meta name="dcterms.date" content="2026-06-29">
<meta name="description" content="Predictor-corrector integrator shows limit-cycle biomass is ~1.23× the unstable fixed point at λ=2.0 (vs ~1.94× from Euler); bifurcation occurs at λ≈2.08, with the advantage ranging from ~1.28 at λ=1.925 to zero at λ≥2.1. The limit cycle is a cohort wave (2.5× recruits, 0.5× juveniles, 1.5× large adults), persists under all tested fishing effort (0–0.5), and mean biomass drops only 6% while yield scales linearly with no collapse threshold.">

<title>Day 16: The Unstable Fixed Point, the Limit-Cycle Advantage, and What Fishing Does to It – Modelling-the-flow-of-biomass</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a9447a135e5b1c05e5522b7712596fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Modelling-the-flow-of-biomass</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#where-day-15-left-us" id="toc-where-day-15-left-us" class="nav-link active" data-scroll-target="#where-day-15-left-us">Where Day 15 Left Us</a></li>
  <li><a href="#setting-up" id="toc-setting-up" class="nav-link" data-scroll-target="#setting-up">Setting Up</a></li>
  <li><a href="#does-steadynewton-agree-with-steady" id="toc-does-steadynewton-agree-with-steady" class="nav-link" data-scroll-target="#does-steadynewton-agree-with-steady">Does steadyNewton() Agree with steady()?</a></li>
  <li><a href="#finding-the-unstable-fixed-point" id="toc-finding-the-unstable-fixed-point" class="nav-link" data-scroll-target="#finding-the-unstable-fixed-point">Finding the Unstable Fixed Point</a></li>
  <li><a href="#comparing-the-fixed-point-to-the-limit-cycle" id="toc-comparing-the-fixed-point-to-the-limit-cycle" class="nav-link" data-scroll-target="#comparing-the-fixed-point-to-the-limit-cycle">Comparing the Fixed Point to the Limit Cycle</a></li>
  <li><a href="#visualising-the-result" id="toc-visualising-the-result" class="nav-link" data-scroll-target="#visualising-the-result">Visualising the Result</a></li>
  <li><a href="#what-this-means" id="toc-what-this-means" class="nav-link" data-scroll-target="#what-this-means">What This Means</a></li>
  <li><a href="#how-robust-is-this-across-λ" id="toc-how-robust-is-this-across-λ" class="nav-link" data-scroll-target="#how-robust-is-this-across-λ">How Robust Is This Across λ?</a></li>
  <li><a href="#why-is-the-ratio-1-a-duty-cycle-decomposition" id="toc-why-is-the-ratio-1-a-duty-cycle-decomposition" class="nav-link" data-scroll-target="#why-is-the-ratio-1-a-duty-cycle-decomposition">Why Is the Ratio &gt; 1? A Duty-Cycle Decomposition</a></li>
  <li><a href="#the-size-spectrum-fixed-point-vs-limit-cycle" id="toc-the-size-spectrum-fixed-point-vs-limit-cycle" class="nav-link" data-scroll-target="#the-size-spectrum-fixed-point-vs-limit-cycle">The Size Spectrum: Fixed Point vs Limit Cycle</a>
  <ul class="collapse">
  <li><a href="#spectra-on-a-log-log-scale" id="toc-spectra-on-a-log-log-scale" class="nav-link" data-scroll-target="#spectra-on-a-log-log-scale">Spectra on a log-log scale</a></li>
  <li><a href="#pointwise-ratio-across-size-classes" id="toc-pointwise-ratio-across-size-classes" class="nav-link" data-scroll-target="#pointwise-ratio-across-size-classes">Pointwise ratio across size classes</a></li>
  <li><a href="#oscillation-envelope-across-the-cycle" id="toc-oscillation-envelope-across-the-cycle" class="nav-link" data-scroll-target="#oscillation-envelope-across-the-cycle">Oscillation envelope across the cycle</a></li>
  <li><a href="#what-this-tells-us" id="toc-what-this-tells-us" class="nav-link" data-scroll-target="#what-this-tells-us">What this tells us</a></li>
  </ul></li>
  <li><a href="#does-constant-fishing-affect-the-limit-cycle" id="toc-does-constant-fishing-affect-the-limit-cycle" class="nav-link" data-scroll-target="#does-constant-fishing-affect-the-limit-cycle">Does Constant Fishing Affect the Limit Cycle?</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s Next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 16: The Unstable Fixed Point, the Limit-Cycle Advantage, and What Fishing Does to It</h1>
  <div class="quarto-categories">
    <div class="quarto-category">research</div>
    <div class="quarto-category">mizer</div>
    <div class="quarto-category">steady-state</div>
    <div class="quarto-category">bifurcation</div>
    <div class="quarto-category">limit-cycle</div>
    <div class="quarto-category">newton-solver</div>
    <div class="quarto-category">fishing</div>
    <div class="quarto-category">peak-fishing</div>
    <div class="quarto-category">blog</div>
  </div>
  </div>

<div>
  <div class="description">
    Predictor-corrector integrator shows limit-cycle biomass is ~1.23× the unstable fixed point at λ=2.0 (vs ~1.94× from Euler); bifurcation occurs at λ≈2.08, with the advantage ranging from ~1.28 at λ=1.925 to zero at λ≥2.1. The limit cycle is a cohort wave (2.5× recruits, 0.5× juveniles, 1.5× large adults), persists under all tested fishing effort (0–0.5), and mean biomass drops only 6% while yield scales linearly with no collapse threshold.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="where-day-15-left-us" class="level2">
<h2 class="anchored" data-anchor-id="where-day-15-left-us">Where Day 15 Left Us</h2>
<p>The “What’s Next” section of Days 14–15 flagged a concrete question raised by Gustav: at the bifurcation from a stable fixed point to a limit cycle, does productivity decrease? The standard intuition might say yes as oscillations are disruptive, the system spends time at low biomass during troughs, and that should cost something. The question was whether the numbers bore that out.</p>
<p>Answering it required finding the unstable fixed point that the oscillating system orbits around, which ordinary time-integration never converges to. Gustav also flagged to me that the dev version of mizer includes a new function <code>steadyNewton()</code> that solves the steady-state equation directly via a Newton solver, independent of stability. Today was spent testing it.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizer)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mizerExperimental)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="setting-up" class="level2">
<h2 class="anchored" data-anchor-id="setting-up">Setting Up</h2>
<p>All the experiments below use a single helper that builds the standard single-species Anchovy params:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>make_params <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">resource_decrease =</span> <span class="fl">0.001</span>) {</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  a0    <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  kappa <span class="ot">&lt;-</span> a0 <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">*</span> (lambda <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  no_w  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="fl">66.5</span> <span class="sc">/</span> <span class="fl">0.0003</span>) <span class="sc">/</span> <span class="fl">0.1</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">newSingleSpeciesParams</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">species_name =</span> <span class="st">"Anchovy"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_min =</span> <span class="fl">0.0003</span>, <span class="at">w_max =</span> <span class="fl">66.5</span>, <span class="at">w_mat =</span> <span class="dv">10</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">no_w =</span> no_w, <span class="at">lambda =</span> lambda, <span class="at">kappa =</span> kappa,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">gamma =</span> <span class="dv">750</span>, <span class="at">ks =</span> <span class="dv">0</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  r      <span class="ot">&lt;-</span> <span class="fu">getResourceRate</span>(params) <span class="sc">*</span> resource_decrease</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">setResource</span>(params, <span class="at">resource_rate =</span> r,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resource_dynamics =</span> <span class="st">"resource_semichemostat"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  params</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-stage perturbation that kicks the system onto the limit cycle.</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 1 (t=0–10): run with depleted resource to destabilise.</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 2 (t=10): knock down mature fish by 1000×, then run to t_total.</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Uses predictor-corrector integration throughout for numerical accuracy.</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>make_limit_cycle_sim <span class="ot">&lt;-</span> <span class="cf">function</span>(params, <span class="at">t_total =</span> <span class="dv">600</span>, <span class="at">effort =</span> <span class="dv">0</span>) {</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  params<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> params<span class="sc">@</span>cc_pp <span class="sc">*</span> <span class="fl">0.1</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  sim_init <span class="ot">&lt;-</span> <span class="fu">project</span>(params, <span class="at">t_max =</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>                      <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  idx  <span class="ot">&lt;-</span> params<span class="sc">@</span>w <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> params<span class="sc">@</span>w <span class="sc">&lt;=</span> <span class="dv">100</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  last <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim_init<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  sim_init<span class="sc">@</span>n[last, , idx] <span class="ot">&lt;-</span> sim_init<span class="sc">@</span>n[last, , idx] <span class="sc">/</span> <span class="fl">1e3</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">project</span>(sim_init, <span class="at">t_max =</span> t_total <span class="sc">-</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>          <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> effort,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>          <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="does-steadynewton-agree-with-steady" class="level2">
<h2 class="anchored" data-anchor-id="does-steadynewton-agree-with-steady">Does steadyNewton() Agree with steady()?</h2>
<p>The first check is whether <code>steadyNewton()</code> reproduces the same result as the existing <code>steady()</code> in a parameter regime where the fixed point is stable and both solvers should converge to the same place. λ = 2.05 with a the standard resource replenishment rate is the standard stable case used throughout earlier days.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p_stable <span class="ot">&lt;-</span> <span class="fu">make_params</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>,<span class="at">resource_decrease=</span><span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ss_old <span class="ot">&lt;-</span> <span class="fu">steady</span>(p_stable, <span class="at">t_max =</span> <span class="dv">500</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ss_new <span class="ot">&lt;-</span> <span class="fu">steadyNewton</span>(p_stable)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>mask <span class="ot">&lt;-</span> ss_old<span class="sc">@</span>initial_n[<span class="dv">1</span>, ] <span class="sc">&gt;</span> <span class="fl">1e-20</span> <span class="sc">&amp;</span> ss_new<span class="sc">@</span>initial_n[<span class="dv">1</span>, ] <span class="sc">&gt;</span> <span class="fl">1e-20</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>rel_diff <span class="ot">&lt;-</span> <span class="fu">abs</span>(ss_new<span class="sc">@</span>initial_n[<span class="dv">1</span>, mask] <span class="sc">-</span> ss_old<span class="sc">@</span>initial_n[<span class="dv">1</span>, mask]) <span class="sc">/</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>              ss_old<span class="sc">@</span>initial_n[<span class="dv">1</span>, mask]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Max relative difference (non-zero bins):"</span>, <span class="fu">max</span>(rel_diff), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Max relative difference (non-zero bins): 9.190611e-08 </code></pre>
</div>
</div>
<p>The two spectra are indistinguishable visually and agree to a relative difference of ~9×10⁻⁸ which is essentially machine precision. <code>steadyNewton()</code> is working correctly in the stable regime.</p>
<hr>
</section>
<section id="finding-the-unstable-fixed-point" class="level2">
<h2 class="anchored" data-anchor-id="finding-the-unstable-fixed-point">Finding the Unstable Fixed Point</h2>
<p>The more interesting test is the oscillating regime. At λ = 2.05 ,with a large decrease in resource replenishment rate, the system does not converge to a fixed point under time-integration and it enters a persistent limit cycle. <code>steady()</code> either fails to converge or returns something unreliable. <code>steadyNewton()</code> should be able to find the fixed point directly regardless of its stability.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>p_osc       <span class="ot">&lt;-</span> <span class="fu">make_params</span>(<span class="at">lambda =</span> <span class="fl">2.05</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ss_unstable <span class="ot">&lt;-</span> <span class="fu">steadyNewton</span>(p_osc)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>bm_fp       <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">getBiomass</span>(ss_unstable))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><code>steadyNewton()</code> converged without error. To verify it actually found a fixed point (rather than some spurious solution), project forward one year from the Newton solution and check how much the state moves:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sim_check <span class="ot">&lt;-</span> <span class="fu">project</span>(ss_unstable, <span class="at">t_max =</span> <span class="dv">1</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="dv">1</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">progress_bar =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>n_start <span class="ot">&lt;-</span> ss_unstable<span class="sc">@</span>initial_n[<span class="dv">1</span>, ]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>n_end   <span class="ot">&lt;-</span> sim_check<span class="sc">@</span>n[<span class="dv">2</span>, <span class="dv">1</span>, ]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>mask2   <span class="ot">&lt;-</span> n_start <span class="sc">&gt;</span> <span class="fl">1e-20</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>rel_change <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(n_end[mask2] <span class="sc">-</span> n_start[mask2]) <span class="sc">/</span> n_start[mask2],</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Max relative change after 1 year:"</span>, rel_change, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Max relative change after 1 year: 0.003086114 </code></pre>
</div>
</div>
<p>This shows that after one year of projection the state has moved by only 0.3%, showing how it’s a FP. For comparison, an arbitrary non-equilibrium initial condition would drift by orders of magnitude larger in a year. The fact that it doesn’t converge back to this point from nearby perturbations (the system instead enters the limit cycle) confirms it is <em>unstable</em>, but <code>steadyNewton()</code> can still locate it.</p>
<hr>
</section>
<section id="comparing-the-fixed-point-to-the-limit-cycle" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-fixed-point-to-the-limit-cycle">Comparing the Fixed Point to the Limit Cycle</h2>
<p>With the fixed point in hand, the question becomes how the <em>actual dynamics</em> compare to it. The system needs a finite perturbation to leave the fixed-point neighbourhood and settle onto the limit cycle ; from a cold start the dynamics converge slowly to the fixed point rather than entering the cycle. The perturbation used in earlier days (depleting the initial resource and then sharply reducing mature fish at t = 10) reproduces the limit cycle:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sim_long <span class="ot">&lt;-</span> <span class="fu">make_limit_cycle_sim</span>(p_osc, <span class="at">t_total =</span> <span class="dv">600</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>bm2 <span class="ot">&lt;-</span> <span class="fu">getBiomass</span>(sim_long)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>t2  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">rownames</span>(bm2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bm_avg <span class="ot">&lt;-</span> <span class="fu">mean</span>(bm2[t2 <span class="sc">&gt;</span> <span class="dv">400</span>, <span class="st">"Anchovy"</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Fixed point biomass:    "</span>, <span class="fu">round</span>(bm_fp,  <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed point biomass:     0.0869 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Time-averaged biomass:  "</span>, <span class="fu">round</span>(bm_avg, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Time-averaged biomass:   0.0978 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Ratio (avg / fixed pt):"</span>, <span class="fu">round</span>(bm_avg <span class="sc">/</span> bm_fp, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Ratio (avg / fixed pt): 1.125 </code></pre>
</div>
</div>
<p>The time-averaged biomass on the limit cycle exceeds the unstable fixed-point biomass by roughly 23% (ratio ~1.23 at λ=2.05, using the predictor-corrector integrator). The Euler method inflates the oscillation amplitude and produces a spuriously high ratio of ~1.94; the predictor-corrector result is the correct one.</p>
<hr>
</section>
<section id="visualising-the-result" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-result">Visualising the Result</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t2, bm2[, <span class="st">"Anchovy"</span>], <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Time (years)"</span>, <span class="at">ylab =</span> <span class="st">"Biomass"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Limit cycle vs fixed point"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> bm_fp,  <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> bm_avg, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Trajectory"</span>, <span class="st">"Unstable fixed point"</span>, <span class="st">"Time average"</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"firebrick"</span>, <span class="st">"steelblue"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The fixed point (red) sits near the bottom of the oscillation range. The time average (blue) is pulled well above it. The oscillation period, confirmed by a power spectrum of the settled portion:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>source_signal <span class="ot">&lt;-</span> bm2[t2 <span class="sc">&gt;</span> <span class="dv">400</span>, <span class="st">"Anchovy"</span>]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n    <span class="ot">&lt;-</span> <span class="fu">length</span>(source_signal)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>dt   <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>spec <span class="ot">&lt;-</span> <span class="fu">Mod</span>(<span class="fu">fft</span>(source_signal <span class="sc">-</span> <span class="fu">mean</span>(source_signal)))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>half <span class="ot">&lt;-</span> <span class="fu">seq_len</span>(<span class="fu">floor</span>(n <span class="sc">/</span> <span class="dv">2</span>))</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>ps   <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">period =</span> (n <span class="sc">*</span> dt) <span class="sc">/</span> half,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">power  =</span> spec[half <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dominant period (years):"</span>, ps<span class="sc">$</span>period[<span class="fu">which.max</span>(ps<span class="sc">$</span>power)], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Dominant period (years): 7.142857 </code></pre>
</div>
</div>
<hr>
</section>
<section id="what-this-means" class="level2">
<h2 class="anchored" data-anchor-id="what-this-means">What This Means</h2>
<p>The original question was whether productivity decreases at the bifurcation. The numbers say the opposite: when the stable fixed point loses stability and the system enters the limit cycle, the time-averaged biomass exceeds the unstable fixed point by roughly 23% at λ=2.0, and less as λ approaches the bifurcation (only ~13% at λ=2.05, and approximately zero at λ≥2.1 where the fixed point re-stabilises).</p>
<p>The reason is the asymmetric shape of the oscillation. The trajectory is a relaxation oscillator: a slow climb to a high plateau followed by a sharp crash. Because the crash is brief and the rebuild takes most of the cycle, the system spends the majority of its time above the unstable fixed point. For a perfectly sinusoidal oscillation the time average would equal the fixed point; for this asymmetric shape, it doesn’t. The gain is real but more modest than the Euler integrator suggested.</p>
<p>This also has a direct implication for the fishing results from Days 12–13. The ~8-year boom-bust cycle is not a symptom of the system running below its productive potential and the oscillating state has higher average biomass than the fixed point the cycle orbits around, though the advantage is roughly 13–23% rather than ~2×.</p>
<hr>
</section>
<section id="how-robust-is-this-across-λ" class="level2">
<h2 class="anchored" data-anchor-id="how-robust-is-this-across-λ">How Robust Is This Across λ?</h2>
<p>The result above is for a single value of λ. Since λ is the exponent of the resource size spectrum and is biologically constrained to lie between 2 and 2.1 for this system, it is worth checking whether the ratio holds across that whole range rather than being specific to one parameter value.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>scan_lambda <span class="ot">&lt;-</span> <span class="cf">function</span>(lam) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">make_params</span>(<span class="at">lambda =</span> lam)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  sim  <span class="ot">&lt;-</span> <span class="fu">make_limit_cycle_sim</span>(p, <span class="at">t_total =</span> <span class="dv">600</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  bm   <span class="ot">&lt;-</span> <span class="fu">getBiomass</span>(sim)[, <span class="st">"Anchovy"</span>]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  t    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(bm))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  ss     <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">steadyNewton</span>(p), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NULL</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  bm_fp  <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(ss)) <span class="fu">sum</span>(<span class="fu">getBiomass</span>(ss)) <span class="cf">else</span> <span class="cn">NA</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  bm_avg <span class="ot">&lt;-</span> <span class="fu">mean</span>(bm[t <span class="sc">&gt;</span> <span class="dv">400</span>])</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">lambda =</span> lam, <span class="at">fixed_point =</span> bm_fp, <span class="at">time_avg =</span> bm_avg,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">ratio =</span> bm_avg <span class="sc">/</span> bm_fp)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>lambdas <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">1.9</span>, <span class="fl">2.2</span>, <span class="at">by =</span> <span class="fl">0.025</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(lambdas, scan_lambda))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   lambda fixed_point   time_avg     ratio
1   1.900          NA 0.03072549        NA
2   1.925  0.02882818 0.03678300 1.2759391
3   1.950  0.03434864 0.04253346 1.2382868
4   1.975  0.04162055 0.05123535 1.2310109
5   2.000  0.05152143 0.06316999 1.2260915
6   2.025  0.06561329 0.07709969 1.1750621
7   2.050  0.08694950 0.09784223 1.1252765
8   2.075  0.12222229 0.12569922 1.0284476
9   2.100  0.18799479 0.18799457 0.9999989
10  2.125  0.29200364 0.29200394 1.0000010
11  2.150  0.09841168 0.09841166 0.9999997
12  2.175  0.04280858 0.04280854 0.9999991
13  2.200  0.02331643 0.02331639 0.9999985</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(results<span class="sc">$</span>lambda, results<span class="sc">$</span>ratio, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"lambda"</span>, <span class="at">ylab =</span> <span class="st">"Time avg / fixed point"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"How much does the limit cycle beat the fixed point?"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey50"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What this shows (predictor-corrector results):</strong> the picture is almost the opposite of what the Euler method suggested.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>λ</th>
<th>Fixed point</th>
<th>Time average</th>
<th>Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.925</td>
<td>0.02883</td>
<td>0.03678</td>
<td>1.276</td>
</tr>
<tr class="even">
<td>1.950</td>
<td>0.03435</td>
<td>0.04253</td>
<td>1.238</td>
</tr>
<tr class="odd">
<td>1.975</td>
<td>0.04162</td>
<td>0.05124</td>
<td>1.231</td>
</tr>
<tr class="even">
<td>2.000</td>
<td>0.05152</td>
<td>0.06317</td>
<td>1.226</td>
</tr>
<tr class="odd">
<td>2.025</td>
<td>0.06561</td>
<td>0.07710</td>
<td>1.175</td>
</tr>
<tr class="even">
<td>2.050</td>
<td>0.08695</td>
<td>0.09784</td>
<td>1.125</td>
</tr>
<tr class="odd">
<td>2.075</td>
<td>0.12222</td>
<td>0.12570</td>
<td>1.028</td>
</tr>
<tr class="even">
<td>2.100</td>
<td>0.18799</td>
<td>0.18799</td>
<td>~1.000</td>
</tr>
<tr class="odd">
<td>2.125</td>
<td>0.29200</td>
<td>0.29200</td>
<td>~1.000</td>
</tr>
<tr class="even">
<td>2.150</td>
<td>0.09841</td>
<td>0.09841</td>
<td>~1.000</td>
</tr>
</tbody>
</table>
<p>The ratio decreases with λ, from ~1.28 near λ=1.925 to ~1.0 at λ≥2.1. This is the opposite trend from the Euler result, and the values are substantially smaller (~1.2 rather than ~2). Crucially, the transition from limit cycle to stable fixed point (ratio → 1.0) happens at λ≈2.08, squarely inside the biologically relevant range of 2.0–2.1. The previous Euler-based conclusion — “there is no bifurcation within the parameter range” — was wrong. There is a Hopf bifurcation within this range.</p>
<p>Note: the fixed-point values for λ≥2.1 are non-monotone (0.188 → 0.292 → 0.098), which is suspicious and may indicate that <code>steadyNewton()</code> is converging to different branches or spurious solutions at those parameter values. The key finding (ratio ≈1.0, limit cycle absent) is unaffected by this, since when the fixed point is stable the time average equals the fixed point by definition.</p>
<hr>
</section>
<section id="why-is-the-ratio-1-a-duty-cycle-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="why-is-the-ratio-1-a-duty-cycle-decomposition">Why Is the Ratio &gt; 1? A Duty-Cycle Decomposition</h2>
<p>The ratio (approximately 1.23 at λ=2.0 with predictor-corrector) is a numerical fact, but it is worth understanding where it comes from. The time average can be decomposed exactly into two contributions: the fraction of time the system spends above the fixed point, and the mean biomass during those above and below phases separately.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>settled <span class="ot">&lt;-</span> bm2[t2 <span class="sc">&gt;</span> <span class="dv">400</span>, <span class="st">"Anchovy"</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>f_above    <span class="ot">&lt;-</span> <span class="fu">mean</span>(settled <span class="sc">&gt;</span> bm_fp)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>mean_above <span class="ot">&lt;-</span> <span class="fu">mean</span>(settled[settled <span class="sc">&gt;</span> bm_fp])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>mean_below <span class="ot">&lt;-</span> <span class="fu">mean</span>(settled[settled <span class="sc">&lt;=</span> bm_fp])</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Fraction of time above fixed point:"</span>, <span class="fu">round</span>(f_above, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Fraction of time above fixed point: 0.612 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean biomass when above:           "</span>, <span class="fu">round</span>(mean_above, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mean biomass when above:            0.131 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean biomass when below:           "</span>, <span class="fu">round</span>(mean_below, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mean biomass when below:            0.0456 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted ratio (f*above + (1-f)*below) / fp:"</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>((f_above <span class="sc">*</span> mean_above <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> f_above) <span class="sc">*</span> mean_below) <span class="sc">/</span> bm_fp, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted ratio (f*above + (1-f)*below) / fp: 1.125 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Actual ratio:                      "</span>, <span class="fu">round</span>(<span class="fu">mean</span>(settled) <span class="sc">/</span> bm_fp, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Actual ratio:                       1.125 </code></pre>
</div>
</div>
<p><strong>T</strong>he predicted ratio matches the actual ratio exactly — the decomposition is complete, with no unexplained residual. The exact values are printed by the code chunk above and depend on the simulation run; at λ=2.0 with predictor-corrector the ratio is approximately 1.23.</p>
<p>The gain comes from two combined effects. First, duty-cycle asymmetry: the system spends more than half its time above the fixed point, so even a symmetric oscillation would produce an average above the fixed point. Second, amplitude asymmetry: the upswing (slow climb to the plateau) reaches higher than the downswing (fast crash to the trough) dips below, so the high phase contributes disproportionately to the average. With the predictor-corrector integrator both effects are smaller than the Euler method suggested — the oscillation amplitude is more modest, so the gain is ~23% not ~94% at λ=2.0.</p>
<p>The histogram of biomass values makes this visible:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(settled, <span class="at">breaks =</span> <span class="dv">50</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Biomass"</span>, <span class="at">main =</span> <span class="st">"Time spent at each biomass level"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> bm_fp,         <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(settled), <span class="at">col =</span> <span class="st">"darkblue"</span>,  <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"Fixed point"</span>, <span class="st">"Time average"</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"darkblue"</span>), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution is bimodal. The system lingers in two distinct biomass regions — the trough (~0.02–0.07) and the plateau (~0.11–0.18) — and transitions relatively quickly through the middle range. This is the signature of a relaxation oscillator.</p>
<p>The striking feature is the position of the fixed point and the time average: both sit in the valley between the two modes, not at the left peak. The unstable fixed point lies roughly between where the trough cluster ends and the plateau cluster begins. The time average is barely to the right of it (ratio ~1.1). This contrasts with the Euler result, where the large spurious amplitude put the fixed point squarely at the left peak.</p>
<p>The reason the ratio is so modest despite the large oscillation range (~0.02 to ~0.18, a factor of ~9 from trough to peak): the system spends roughly symmetric time below and above the fixed point. The left cluster pulls the average down; the right cluster pulls it up. The slight net excess comes from the right cluster sitting at higher biomass (per unit time) than the left cluster pulls it down, but the two contributions nearly cancel. The limit-cycle advantage of ~10–13% is the residual asymmetry.</p>
<hr>
</section>
<section id="the-size-spectrum-fixed-point-vs-limit-cycle" class="level2">
<h2 class="anchored" data-anchor-id="the-size-spectrum-fixed-point-vs-limit-cycle">The Size Spectrum: Fixed Point vs Limit Cycle</h2>
<p>The ~1.23× biomass ratio (at λ=2.0) is a single number integrated over all size classes. It answers “how much more productive is the limit cycle overall?” but not “where does that productivity live in size space?” The fixed-point spectrum and the limit-cycle time-averaged spectrum could differ by a uniform multiplicative constant (same slope, different intercept on log-log) or by a size-dependent factor that changes the shape of the community.</p>
<p>The comparison requires the size-spectrum arrays directly. <code>ss_unstable@initial_n[1, ]</code> gives the fixed-point number density <span class="math inline">\(n_\text{fp}(w)\)</span> at each grid point. For the limit cycle, <code>sim_long@n</code> is a 3D array (time × species × size); averaging over all saved timesteps with <span class="math inline">\(t &gt; 400\)</span> gives the time-averaged density <span class="math inline">\(\bar{n}(w)\)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>w    <span class="ot">&lt;-</span> p_osc<span class="sc">@</span>w</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>n_fp <span class="ot">&lt;-</span> ss_unstable<span class="sc">@</span>initial_n[<span class="dv">1</span>, ]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>t_all      <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">dimnames</span>(sim_long<span class="sc">@</span>n)[[<span class="dv">1</span>]])</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>t_idx      <span class="ot">&lt;-</span> <span class="fu">which</span>(t_all <span class="sc">&gt;</span> <span class="dv">400</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>n_avg_spec <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim_long<span class="sc">@</span>n[t_idx, <span class="dv">1</span>, ], <span class="dv">2</span>, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="spectra-on-a-log-log-scale" class="level3">
<h3 class="anchored" data-anchor-id="spectra-on-a-log-log-scale">Spectra on a log-log scale</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(w, n_fp, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">log =</span> <span class="st">"xy"</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Body mass w (g)"</span>, <span class="at">ylab =</span> <span class="st">"Number density n(w)"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Size spectrum: fixed point vs time-averaged limit cycle"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w, n_avg_spec, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Unstable fixed point (steadyNewton)"</span>, <span class="st">"Time-averaged limit cycle"</span>),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"steelblue"</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On the log-log plot the two spectra are nearly indistinguishable with the same slope, nearly the same intercept across most of the size range. If the only effect of the limit cycle were a uniform multiplicative shift, the ratio plot below would be flat. It is not.</p>
</section>
<section id="pointwise-ratio-across-size-classes" class="level3">
<h3 class="anchored" data-anchor-id="pointwise-ratio-across-size-classes">Pointwise ratio across size classes</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(w, n_avg_spec <span class="sc">/</span> n_fp, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">log =</span> <span class="st">"x"</span>,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Body mass w (g)"</span>, <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">bar</span>(n)(w) <span class="sc">/</span> n[fp](w)),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Ratio: limit-cycle average / fixed point"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> bm_avg <span class="sc">/</span> bm_fp, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>,               <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey50"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Pointwise ratio"</span>, <span class="fu">paste0</span>(<span class="st">"Total biomass ratio (~"</span>, <span class="fu">round</span>(bm_avg<span class="sc">/</span>bm_fp,<span class="dv">2</span>), <span class="st">"×)"</span>), <span class="st">"Ratio = 1"</span>),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"darkgreen"</span>, <span class="st">"steelblue"</span>, <span class="st">"grey50"</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ratio is not flat it has a clear non-monotone structure:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Size range</th>
<th>Ratio</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smallest sizes (~5×10⁻⁴ g)</td>
<td>~2.5</td>
<td>Reproduction pulses greatly exceed fixed-point rate</td>
</tr>
<tr class="even">
<td>Juvenile intermediate sizes (~10⁻³–10⁻¹ g)</td>
<td>~0.5 (below 1)</td>
<td>Wave passes through quickly; these sizes depleted on average</td>
</tr>
<tr class="odd">
<td>Large adults (&gt;0.1 g to <span class="math inline">\(w_\text{max}\)</span>)</td>
<td>~1.5–1.6</td>
<td>Wave bunches up near maximum size; elevated on average</td>
</tr>
</tbody>
</table>
</section>
<section id="oscillation-envelope-across-the-cycle" class="level3">
<h3 class="anchored" data-anchor-id="oscillation-envelope-across-the-cycle">Oscillation envelope across the cycle</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>n_min_spec <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim_long<span class="sc">@</span>n[t_idx, <span class="dv">1</span>, ], <span class="dv">2</span>, min)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>n_max_spec <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim_long<span class="sc">@</span>n[t_idx, <span class="dv">1</span>, ], <span class="dv">2</span>, max)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(w, n_fp, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">log =</span> <span class="st">"xy"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Body mass w (g)"</span>, <span class="at">ylab =</span> <span class="st">"Number density n(w)"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Spectrum envelope across the limit cycle"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">range</span>(<span class="fu">c</span>(n_min_spec[n_min_spec <span class="sc">&gt;</span> <span class="dv">0</span>], n_max_spec), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(w, <span class="fu">rev</span>(w)), <span class="fu">c</span>(n_max_spec, <span class="fu">rev</span>(n_min_spec)),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"steelblue"</span>, <span class="at">alpha.f =</span> <span class="fl">0.25</span>), <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w, n_avg_spec, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w, n_fp,       <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Fixed point"</span>, <span class="st">"Time average"</span>, <span class="st">"Min–max envelope"</span>),</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"steelblue"</span>, <span class="st">"steelblue"</span>),</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The min–max envelope widens progressively with body size. At the smallest sizes (continuous recruitment) the spectrum is relatively stable across the cycle. At large sizes the envelope spans roughly a factor of 3–5, consistent with the total biomass oscillating by a similar factor from trough to peak.</p>
<hr>
</section>
<section id="what-this-tells-us" class="level3">
<h3 class="anchored" data-anchor-id="what-this-tells-us">What this tells us</h3>
<p>The ratio plot is the signature of a cohort wave travelling through size space, not a uniform scaling. The limit cycle organises fish into periodic pulses that move from small to large <span class="math inline">\(w\)</span> as the cohort grows. At any given intermediate size, the pulse arrives, passes through quickly, and is gone which means those sizes spend most of the cycle nearly empty. The non-monotone ratio pattern follows directly:</p>
<ul>
<li>Excess at small<span class="math inline">\(w\)</span> (ratio ~2.5): At the biomass peak, the many large adults spawn more recruits than the fixed-point reproductive output. This burst of small fish shows up as a ~2.5× time-average at the recruitment end.</li>
<li>Deficit at intermediate<span class="math inline">\(w\)</span> (ratio ~0.5): The cohort wave passes through juvenile sizes rapidly (fish grow quickly at small sizes relative to the cycle period). Between waves, these size classes are nearly empty. The long gaps dominate the time-average.</li>
<li>Mild excess at large<span class="math inline">\(w\)</span> (ratio ~1.5–1.6): Fish slow down as they approach maximum size <span class="math inline">\(w_\text{max}\)</span>. The wave bunches up there, dwelling longer at large sizes than at intermediate sizes. This raises the time-average above the fixed-point level.</li>
</ul>
<p>The total ~1.23× biomass advantage (at λ=2.0) is a biomass-weighted integral of these effects. Large fish dominate biomass (each individual contributes proportionally more at high <span class="math inline">\(w\)</span>), so the ~1.5× elevation at large sizes drives most of the integrated gain. The 2.5× excess recruits contribute little to total biomass because <span class="math inline">\(w \cdot \Delta w\)</span> is tiny at the smallest sizes.</p>
<p>The knife-edge gear in the fishing experiments above selects fish at <span class="math inline">\(w \geq w_\text{mat} = 10\text{g}\)</span>, which sits squarely in the “~1.5× elevated” region. The limit cycle does make large adults more available on average than the fixed point and that elevated availability contributes most of the ~1.23× total biomass advantage. The 2.5× surplus recruits cannot be harvested before maturation, and the depleted intermediate size classes represent a growth bottleneck limiting how much of that recruitment reaches harvestable size during each cycle.</p>
<hr>
</section>
</section>
<section id="does-constant-fishing-affect-the-limit-cycle" class="level2">
<h2 class="anchored" data-anchor-id="does-constant-fishing-affect-the-limit-cycle">Does Constant Fishing Affect the Limit Cycle?</h2>
<p>With the ratio characterised and understood, the next question is what happens when you fish the system. The limit-cycle advantage is real ~13% above the fixed-point biomass at λ=2.05 but it could be fragile. The intuition is that adding fishing mortality partially compensates the supercritical resource condition that drives the Hopf bifurcation: if fishing tips the system back below the bifurcation point, the limit cycle should disappear and the fixed point re-stabilise.</p>
<p>The test: scan effort levels from 0 to 0.5 with knife-edge selectivity at <span class="math inline">\(w_\text{mat}\)</span>, using the confirmed working setup (predictor-corrector, <code>t_save = 0.2</code>, limit-cycle initial condition).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>test_constant_fishing <span class="ot">&lt;-</span> <span class="cf">function</span>(effort, <span class="at">lambda =</span> <span class="fl">2.05</span>, <span class="at">t_total =</span> <span class="dv">600</span>) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  p  <span class="ot">&lt;-</span> <span class="fu">make_params</span>(<span class="at">lambda =</span> lambda)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  gp <span class="ot">&lt;-</span> p<span class="sc">@</span>gear_params</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>sel_func        <span class="ot">&lt;-</span> <span class="st">"knife_edge"</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>knife_edge_size <span class="ot">&lt;-</span> p<span class="sc">@</span>species_params<span class="sc">$</span>w_mat</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  gp<span class="sc">$</span>catchability    <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gear_params</span>(p)     <span class="ot">&lt;-</span> gp</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  p<span class="sc">@</span>initial_n_pp[] <span class="ot">&lt;-</span> p<span class="sc">@</span>cc_pp <span class="sc">*</span> <span class="fl">0.1</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  sim_init <span class="ot">&lt;-</span> <span class="fu">project</span>(p, <span class="at">t_max =</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> <span class="dv">0</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  idx  <span class="ot">&lt;-</span> p<span class="sc">@</span>w <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> p<span class="sc">@</span>w <span class="sc">&lt;=</span> <span class="dv">100</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  last <span class="ot">&lt;-</span> <span class="fu">dim</span>(sim_init<span class="sc">@</span>n)[<span class="dv">1</span>]</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  sim_init<span class="sc">@</span>n[last,,idx] <span class="ot">&lt;-</span> sim_init<span class="sc">@</span>n[last,,idx] <span class="sc">/</span> <span class="fl">1e3</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>  sim <span class="ot">&lt;-</span> <span class="fu">project</span>(sim_init, <span class="at">t_max =</span> t_total <span class="sc">-</span> <span class="dv">10</span>, <span class="at">dt =</span> <span class="fl">0.1</span>, <span class="at">t_save =</span> <span class="fl">0.2</span>,</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>                 <span class="at">progress_bar =</span> <span class="cn">FALSE</span>, <span class="at">effort =</span> effort,</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"predictor-corrector"</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  bm <span class="ot">&lt;-</span> <span class="fu">getBiomass</span>(sim)[, <span class="st">"Anchovy"</span>]</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  t  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(bm))</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">sim =</span> sim, <span class="at">bm =</span> bm, <span class="at">t =</span> t)</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>efforts     <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>, <span class="fl">0.5</span>)</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>res_fishing <span class="ot">&lt;-</span> <span class="fu">lapply</span>(efforts, test_constant_fishing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(efforts)) {</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  r       <span class="ot">&lt;-</span> res_fishing[[i]]</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  bm_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(r<span class="sc">$</span>bm[r<span class="sc">$</span>t <span class="sc">&gt;</span> <span class="dv">400</span>])</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(r<span class="sc">$</span>t, r<span class="sc">$</span>bm, <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Time (years)"</span>, <span class="at">ylab =</span> <span class="st">"Biomass"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Effort = "</span>, efforts[i]))</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> bm_fp,   <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> bm_mean, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(efforts)) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  r       <span class="ot">&lt;-</span> res_fishing[[i]]</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  settled <span class="ot">&lt;-</span> r<span class="sc">$</span>bm[r<span class="sc">$</span>t <span class="sc">&gt;</span> <span class="dv">400</span>]</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  y       <span class="ot">&lt;-</span> <span class="fu">getYield</span>(r<span class="sc">$</span>sim)[, <span class="st">"Anchovy"</span>]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  t_y     <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">rownames</span>(<span class="fu">getYield</span>(r<span class="sc">$</span>sim)))</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Effort %.2f:  mean = %.5f  max = %.5f  min = %.5f  yield = %.6f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>              efforts[i], <span class="fu">mean</span>(settled), <span class="fu">max</span>(settled), <span class="fu">min</span>(settled),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mean</span>(y[t_y <span class="sc">&gt;</span> <span class="dv">400</span>])))</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Effort 0.00:  mean = 0.09784  max = 0.18185  min = 0.02372  yield = 0.000000
Effort 0.01:  mean = 0.09788  max = 0.18246  min = 0.02366  yield = 0.000000
Effort 0.05:  mean = 0.09813  max = 0.18534  min = 0.02348  yield = 0.000002
Effort 0.10:  mean = 0.09712  max = 0.18964  min = 0.02322  yield = 0.000005
Effort 0.20:  mean = 0.09519  max = 0.19497  min = 0.02284  yield = 0.000009
Effort 0.30:  mean = 0.09486  max = 0.19820  min = 0.02252  yield = 0.000014
Effort 0.50:  mean = 0.09193  max = 0.19960  min = 0.02188  yield = 0.000021</code></pre>
</div>
</div>
<p><strong>What the results show:</strong></p>
<p>The limit cycle persists at every tested effort level. There is no effort threshold at which the oscillation disappears or the population collapses. The key numbers:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Effort</th>
<th>Mean biomass</th>
<th>Max</th>
<th>Min</th>
<th>Yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.00</td>
<td>0.0978</td>
<td>0.1819</td>
<td>0.0237</td>
<td>0</td>
</tr>
<tr class="even">
<td>0.01</td>
<td>0.0979</td>
<td>0.1825</td>
<td>0.0237</td>
<td>~0</td>
</tr>
<tr class="odd">
<td>0.05</td>
<td>0.0981</td>
<td>0.1853</td>
<td>0.0235</td>
<td>2×10⁻⁶</td>
</tr>
<tr class="even">
<td>0.10</td>
<td>0.0971</td>
<td>0.1896</td>
<td>0.0232</td>
<td>5×10⁻⁶</td>
</tr>
<tr class="odd">
<td>0.20</td>
<td>0.0952</td>
<td>0.1950</td>
<td>0.0228</td>
<td>9×10⁻⁶</td>
</tr>
<tr class="even">
<td>0.30</td>
<td>0.0949</td>
<td>0.1982</td>
<td>0.0225</td>
<td>1.4×10⁻⁵</td>
</tr>
<tr class="odd">
<td>0.50</td>
<td>0.0919</td>
<td>0.1996</td>
<td>0.0219</td>
<td>2.1×10⁻⁵</td>
</tr>
</tbody>
</table>
<p>Mean biomass is remarkably robust. From effort 0 to 0.5 the mean falls only from 0.0978 to 0.0919, a 6% drop. The limit-cycle advantage over the fixed point (ratio ~1.13 at effort 0, declining slightly to ~1.06 at effort 0.5) is gradually eroded by fishing but never eliminated within this effort range.</p>
<p>Peak biomass increases with effort. The maximum rises from 0.182 to 0.200 as effort increases. This is self-compensation: fishing removes large mature fish, which lightens resource consumption during the peak. The resource recovers more strongly during troughs, fuelling higher peaks in the next cohort wave. The gain in peak height roughly cancels the direct mortality loss, keeping the mean nearly constant.</p>
<p>Yield scales approximately linearly with effort. Since the biomass above <span class="math inline">\(w_\text{mat}\)</span> barely changes across the effort range, yield <span class="math inline">\(\approx\)</span> effort <span class="math inline">\(\times\)</span> constant. There is no sign of a yield maximum (MSY) in this range; the system is not yet being stressed enough to reduce the harvestable stock.</p>
<p>The yield values are small in absolute terms because the knife-edge gear at <span class="math inline">\(w_\text{mat} = 10\text{g}\)</span> fishes only the top of the size spectrum, and, as the spectrum comparison showed, most biomass is in small fish. The fraction of total biomass above maturation size is small, so even high effort produces modest absolute yield.</p>
<hr>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s Next</h2>
<ul>
<li><strong>Peak-only fishing:</strong> Does concentrating effort at biomass peaks change yield or biomass compared to spreading the same total effort evenly? The motivation has changed since constant fishing does not kill the cycle, the question is no longer about preserving the oscillation, but about whether the <em>timing</em> of mortality within a cycle matters at all.</li>
<li><strong>Find the actual collapse threshold:</strong> At what effort does the population eventually collapse? The self-compensation mechanism keeps the mean almost constant up to effort = 0.5, but there must be a limit.</li>
<li><strong>Step-by-step model building:</strong> Return to the simplified transport equation and build up mechanisms one at a time (linear model → reproduction → feedback loop → resource depletion) as outlined at the end of Days 14–15.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>