{
  "hash": "6206ca5d533042c8a4a641b9d7f1ce58",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 19: balance = FALSE Doesn't Kill the Oscillation, It Starves the Population\"\nauthor: \"Samia\"\ndate: \"2026-07-02\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, limit-cycle, resource-balance, bifurcation, yield, blog]\ndescription: \"Re-running Day 18's resource_decrease sweep with balance = FALSE first looks like it kills the oscillation, but a controlled A/B shows it's actually chronic starvation, not stabilisation. Fixing the resource baseline at its best-oscillating values and varying the feeding kernel instead shows kernel shape sets oscillation amplitude directly, and explains an 8x yield gap between two kernels: most of the higher-amplitude kernel's extra biomass is juveniles below the gear's catchable-size cutoff.\"\n---\n\n## Where Day 18 Left Us\n\nDay 18 confirmed one thing outright: the limit cycle is a stable global attractor (trajectories from perturbations spanning three orders of magnitude all converge to the same orbit). The bifurcation's character was left open rather than settled: amplitude grows continuously from zero on the forward sweep (a supercritical signature), but the backward sweep sustains oscillation to a noticeably higher `resource_decrease` than the forward onset — a gap too large to write off as a sweep-start artefact alone, so a purely supercritical Hopf bifurcation couldn't yet be confirmed. Its \"What's Next\" list left several threads open: try a different perturbation type, run with `balance = FALSE` in the resource-setting step, plot maximum and minimum separately instead of max − min, and resolve whether that forward/backward gap is real hysteresis or a run-length artefact.\n\nToday tackles the `balance = FALSE` thread, and it took a couple of false starts to understand what's actually going on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\nlibrary(colorRamps)\nlibrary(future.apply)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Setup\n\n`balance` is now an explicit argument on `make_params`, defaulting to `FALSE`. `r_d` is the same log-spaced grid from 0.001 to 0.3 used in Day 18's hysteresis sweep — it brackets the bifurcation point found there (`rd ≈ 0.008`), so every value tested produced clear oscillation under the default `balance = TRUE` setting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_params <- function(lambda = 2.05, resource_decrease = 0.001,\n                        beta = NULL, sigma = NULL, balance = FALSE) {\n  a0    <- 100\n  kappa <- a0 * exp(-6.9 * (lambda - 1))\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  args <- list(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n  if (!is.null(beta))  args$beta  <- beta\n  if (!is.null(sigma)) args$sigma <- sigma\n\n  params <- do.call(newSingleSpeciesParams, args)\n  r      <- getResourceRate(params) * resource_decrease\n  setResource(params, resource_rate = r,\n             resource_dynamics = \"resource_semichemostat\", balance = balance)\n}\n\nmake_limit_cycle_sim <- function(params, t_total = 600, effort = 0, perturbation = 1e3) {\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim_init <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0,\n                      method = \"predictor-corrector\")\n  idx  <- params@w >= 10 & params@w <= 100\n  last <- dim(sim_init@n)[1]\n  sim_init@n[last, , idx] <- sim_init@n[last, , idx] / perturbation\n\n  project(sim_init, t_max = t_total - 10, dt = 0.1, t_save = 0.2,\n          progress_bar = FALSE, effort = effort,\n          method = \"tr_bdf2\")\n}\n\ntest_effort <- function(r_d, lambda = 2.05, t_total = 600, balance = FALSE) {\n  p   <- make_params(lambda = lambda, resource_decrease = r_d, balance = balance)\n  sim <- make_limit_cycle_sim(p, t_total = t_total)\n  bm  <- getBiomass(sim)[, \"Anchovy\"]\n  t   <- as.numeric(names(bm))\n  list(sim = sim, bm = bm, t = t)\n}\n\nr_d <- exp(seq(log(0.001), log(0.3), length.out = 10))\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Experiment: Does `balance = FALSE` Kill the Oscillation?\n\nThe first pass just re-runs Day 18's sweep with the new default (`balance = FALSE`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplan(multisession)\nresults_fishing <- future_lapply(r_d, test_effort, future.seed = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(NULL, xlim = c(550, 600),\n     ylim = range(sapply(results_fishing, function(r) range(r$bm[r$t > 550]))),\n     xlab = \"Time (years)\", ylab = \"Biomass\", main = \"Biomass trajectories (t > 550), balance = FALSE\")\ncols <- colorRampPalette(c(\"blue\", \"red\"))(length(r_d))\nfor (i in seq_along(results_fishing)) {\n  r    <- results_fishing[[i]]\n  mask <- r$t > 550\n  lines(r$t[mask], r$bm[mask], col = cols[i])\n}\nlegend(\"topright\", legend = paste0(\"r_d = \", r_d), col = cols, lty = 1, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nEvery trajectory is flat by $t = 550$, across the entire range that produced clear oscillation under `balance = TRUE` on Day 18. Read at face value, this says `balance = FALSE` removes the oscillatory mechanism. That reading turns out to be wrong.\n\nA controlled A/B settles it: the same grid, run with `balance = TRUE` and `balance = FALSE`, holding every other setting (solvers, perturbation, `t_total`) identical.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplan(multisession)\nresults_balance_true  <- future_lapply(r_d, test_effort, balance = TRUE,  future.seed = TRUE)\nresults_balance_false <- future_lapply(r_d, test_effort, balance = FALSE, future.seed = TRUE)\n\namp_by_balance <- data.frame(\n  r_d = r_d,\n  amp_balance_true  = sapply(results_balance_true,  function(r) {\n    late <- r$bm[r$t > 550]; max(late) - min(late)\n  }),\n  amp_balance_false = sapply(results_balance_false, function(r) {\n    late <- r$bm[r$t > 550]; max(late) - min(late)\n  })\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(amp_by_balance, digits = 20)\n```\n\n::: {.cell-output-display}\n\n\n|         r_d| amp_balance_true| amp_balance_false|\n|-----------:|----------------:|-----------------:|\n| 0.001000000|     1.593367e-01|      5.000000e-20|\n| 0.001884672|     1.138260e-01|      5.229620e-15|\n| 0.003551987|     8.187341e-02|      3.044118e-09|\n| 0.006694330|     4.769457e-02|      1.153583e-06|\n| 0.012616613|     1.664753e-08|      3.895321e-06|\n| 0.023778173|     2.636800e-16|      7.906750e-06|\n| 0.044814047|     1.665300e-16|      1.514768e-05|\n| 0.084459764|     2.498000e-16|      2.864715e-05|\n| 0.159178922|     1.387800e-16|      5.380267e-05|\n| 0.300000000|     1.942900e-16|      1.001213e-04|\n\n\n:::\n:::\n\n\n`amp_balance_true` reproduces Day 18's bifurcation exactly: large amplitude (0.05–0.16) below `r_d ≈ 0.008–0.02`, then a hard drop to `1e-16`-scale floating-point noise above it, which shows that it is stable fixed point. `amp_balance_false` never gets near that amplitude, but it doesn't look like flat noise either: it climbs smoothly across roughly sixteen orders of magnitude, from `4.5e-20` at `r_d = 0.001` up to `1e-4` at `r_d = 0.3`. Floating-point noise around a fixed point doesn't behave like that but a quantity that scales smoothly with its own magnitude does, which is what it looks like if the biomass itself is climbing steadily across the grid rather than sitting at a fixed, non-oscillating level.\n\nChecking final biomass directly, not just amplitude, confirms it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_final_balance <- data.frame(\n  r_d            = r_d,\n  bm_final_true  = sapply(results_balance_true,  function(r) tail(r$bm, 1)),\n  bm_final_false = sapply(results_balance_false, function(r) tail(r$bm, 1))\n)\nknitr::kable(bm_final_balance, digits = 20)\n```\n\n::: {.cell-output-display}\n\n\n|         r_d| bm_final_true| bm_final_false|\n|-----------:|-------------:|--------------:|\n| 0.001000000|    0.02526607|   1.608000e-17|\n| 0.001884672|    0.13871143|   1.536803e-10|\n| 0.003551987|    0.11998995|   7.175693e-07|\n| 0.006694330|    0.10128766|   1.861367e-05|\n| 0.012616613|    0.08694962|   4.647158e-05|\n| 0.023778173|    0.08694962|   9.077286e-05|\n| 0.044814047|    0.08694962|   1.724468e-04|\n| 0.084459764|    0.08694962|   3.255665e-04|\n| 0.159178922|    0.08694962|   6.125855e-04|\n| 0.300000000|    0.08694962|   1.147551e-03|\n\n\n:::\n:::\n\n\nAt `r_d = 0.001`, `bm_final_false` is `1.6e-17` , the population is extinct , against `bm_final_true`'s real biomass of `0.025`. It isn't just the smallest `r_d` either: even at `r_d = 0.3`, the top of the entire tested range, `bm_final_false` (`1.1e-3`) is still roughly 76 times smaller than `bm_final_true`'s stable-fixed-point plateau (`0.087`). The population under `balance = FALSE` never reaches a biomass comparable to the `balance = TRUE` case anywhere in this grid, let alone the level needed to destabilise into a limit cycle.\n\n### What This Shows\n\n`balance = FALSE` doesn't remove the oscillatory mechanism. It chronically underfeeds the population across the whole `resource_decrease` range, and drives it toward extinction at the low end. The two settings were never testing comparable resource availability at the \"same\" `resource_decrease` value, `resource_decrease = 0.3` under `balance = FALSE` leaves the population worse off than `resource_decrease = 0.001` does under `balance = TRUE`.\n\nA tempting shortcut here would have been to check `resource_capacity` (`cc_pp`) directly on a freshly built `params` object: it comes back identical between `balance = TRUE` and `balance = FALSE`, which looks like it rules capacity out entirely. It doesn't so that check runs before any consumption dynamics exist for `balance` to compensate for, so its real effect only shows up once the model actually runs, as the biomass comparison above confirms.\n\n------------------------------------------------------------------------\n\n## Experiment: Feeding-Kernel Shape, Fishing Effort, and the Yield Gap\n\nA first attempt to find *some* destabilising effect under `balance = FALSE` scanned the feeding kernel (`beta`, `sigma`) at `resource_decrease` fixed at `0.001` and found nothing, every cell essentially zero amplitude. That's explained by the previous section: at `r_d = 0.001` under `balance = FALSE` the population is already deep in the near-extinct regime, and no feeding-kernel shape can matter when there's essentially no population left to feed.\n\nRepeating it properly means fixing `resource_rate`/`resource_capacity` at values that are actually known to sustain oscillation, pulled directly from the strongest `balance = TRUE` run above (`r_d = r_d[1]`, amplitude `0.159`), and varying `beta`/`sigma` on top of that known-good baseline instead of a starved one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_params   <- make_params(resource_decrease = r_d[1], balance = TRUE)\nbest_rate     <- best_params@rr_pp\nbest_capacity <- best_params@cc_pp\n\n# Supplying both resource_rate and resource_capacity leaves nothing for\n# balance to back-solve, so balance = FALSE here just sets them directly.\nmake_params_fixed_resource <- function(lambda = 2.05, resource_rate, resource_capacity,\n                                       beta = NULL, sigma = NULL) {\n  a0    <- 100\n  kappa <- a0 * exp(-6.9 * (lambda - 1))\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  args <- list(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n  if (!is.null(beta))  args$beta  <- beta\n  if (!is.null(sigma)) args$sigma <- sigma\n\n  params <- do.call(newSingleSpeciesParams, args)\n  setResource(params, resource_rate = resource_rate, resource_capacity = resource_capacity,\n             resource_dynamics = \"resource_semichemostat\", balance = FALSE)\n}\n\ntest_beta_sigma_fixed <- function(beta, sigma, resource_rate, resource_capacity,\n                                  lambda = 2.05, t_total = 600) {\n  p   <- make_params_fixed_resource(lambda = lambda, resource_rate = resource_rate,\n                                    resource_capacity = resource_capacity,\n                                    beta = beta, sigma = sigma)\n  sim <- make_limit_cycle_sim(p, t_total = t_total)\n  bm  <- getBiomass(sim)[, \"Anchovy\"]\n  t   <- as.numeric(names(bm))\n  list(sim = sim, bm = bm, t = t, beta = beta, sigma = sigma)\n}\n\n# newSingleSpeciesParams() defaults to beta = 100, sigma = 1.3, so the grid\n# is centred on those defaults with room to move in both directions.\nbeta_seq_fixed  <- c(50, 75, 100, 150, 200, 300)\nsigma_seq_fixed <- c(0.8, 1.0, 1.3, 1.6, 2.0)\ngrid_fixed      <- expand.grid(beta = beta_seq_fixed, sigma = sigma_seq_fixed)\n\nplan(multisession)\nresults_beta_sigma_fixed <- future_lapply(seq_len(nrow(grid_fixed)), function(i) {\n  test_beta_sigma_fixed(beta = grid_fixed$beta[i], sigma = grid_fixed$sigma[i],\n                        resource_rate = best_rate, resource_capacity = best_capacity)\n}, future.seed = TRUE)\n\namp_df_fixed <- data.frame(\n  beta  = grid_fixed$beta,\n  sigma = grid_fixed$sigma,\n  amp   = sapply(results_beta_sigma_fixed, function(r) {\n    late <- r$bm[r$t > 550]\n    max(late) - min(late)\n  })\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(amp_df_fixed, aes(x = factor(beta), y = factor(sigma), fill = amp)) +\n  geom_tile() +\n  geom_point(data = subset(amp_df_fixed, beta == 100 & sigma == 1.3),\n             aes(x = factor(beta), y = factor(sigma)),\n             shape = 4, size = 4, color = \"red\") +\n  scale_fill_viridis_c() +\n  labs(x = \"beta\", y = \"sigma\",\n       fill = \"Amplitude\\n(max - min, t > 550)\",\n       title = \"Oscillation amplitude across beta/sigma grid\",\n       subtitle = \"resource_rate/capacity fixed at the best-oscillating balance = TRUE values; red x = defaults (beta=100, sigma=1.3)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe red-marked cell is the default kernel (`beta = 100, sigma = 1.3`) behind every oscillation characterised in Days 10–18. This heatmap has real structure: amplitude ranges smoothly from around `0.05` (dark, top-right) up to over `0.5` (bright yellow, `beta = 50, sigma = 0.8`), with the default sitting mid-range around `0.25`–`0.3`. Narrower, more concentrated feeding kernels (lower `beta`, lower `sigma`) sustain a noticeably larger-amplitude oscillation than the default; wider ones damp it down.\n\nChecking the actual biomass trajectories behind the darkest cells (not shown in full here) rules out one obvious confound: most low-amplitude cells are near-fixed-points, not starvation. But a couple are still slowly relaxing toward their eventual level rather than truly flat by `t = 600`, and one (`beta = 150, sigma = 0.8`) develops irregular, non-periodic fluctuation on a much longer run, a possible chaos signature, parked here for a proper Poincaré-map test (see Theoretical Grounding below).\n\n### Fishing Effort in the Oscillating Regime\n\nThe more immediately useful question is what fishing does to yield in the parts of this grid that are unambiguously oscillating: the default kernel (`beta = 100, sigma = 1.3`) and the highest-amplitude one (`beta = 50, sigma = 0.8`), both run across a range of `effort` values on the same fixed best-oscillating resource baseline. `effort = 0` (no fishing) is the baseline every fished run is compared against.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_effort_fixed <- function(effort, beta, sigma, resource_rate, resource_capacity,\n                              lambda = 2.05, t_total = 600) {\n  p     <- make_params_fixed_resource(lambda = lambda, resource_rate = resource_rate,\n                                      resource_capacity = resource_capacity,\n                                      beta = beta, sigma = sigma)\n  sim   <- make_limit_cycle_sim(p, t_total = t_total, effort = effort)\n  bm    <- getBiomass(sim)[, \"Anchovy\"]\n  yield <- getYield(sim)[, \"Anchovy\"]\n  t     <- as.numeric(names(bm))\n  list(sim = sim, bm = bm, yield = yield, t = t,\n       effort = effort, beta = beta, sigma = sigma)\n}\n\neffort_seq <- seq(0, 6, length.out = 13)  # extended from 0-2: both curves were still climbing at effort = 2\n\nfishing_kernels <- list(\n  list(beta = 100, sigma = 1.3, label = \"default (beta=100, sigma=1.3)\"),\n  list(beta = 50,  sigma = 0.8, label = \"highest-amplitude (beta=50, sigma=0.8)\")\n)\n\nplan(multisession)\nfishing_results <- lapply(fishing_kernels, function(k) {\n  runs <- future_lapply(effort_seq, function(e) {\n    test_effort_fixed(effort = e, beta = k$beta, sigma = k$sigma,\n                      resource_rate = best_rate, resource_capacity = best_capacity)\n  }, future.seed = TRUE)\n  list(kernel = k, runs = runs)\n})\n\nfishing_summary <- bind_rows(lapply(fishing_results, function(fr) {\n  data.frame(\n    kernel     = fr$kernel$label,\n    effort     = effort_seq,\n    mean_bm    = sapply(fr$runs, function(r) mean(r$bm[r$t > 550])),\n    mean_yield = sapply(fr$runs, function(r) mean(r$yield[r$t > 550])),\n    amp        = sapply(fr$runs, function(r) {\n      late <- r$bm[r$t > 550]; max(late) - min(late)\n    })\n  )\n}))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(fishing_summary, aes(x = effort, y = mean_yield, color = kernel)) +\n  geom_line(linewidth = 1) + geom_point() +\n  labs(x = \"Fishing effort\", y = \"Mean yield (t > 550)\",\n       title = \"Yield vs fishing effort in the oscillating regime\",\n       subtitle = \"effort = 0 (leftmost point) is the unfished baseline\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseline_bm <- fishing_summary[fishing_summary$effort == 0, c(\"kernel\", \"mean_bm\")]\nnames(baseline_bm)[2] <- \"baseline_bm\"\n\nggplot(fishing_summary, aes(x = effort, y = mean_bm, color = kernel)) +\n  geom_line(linewidth = 1) + geom_point() +\n  geom_hline(data = baseline_bm, aes(yintercept = baseline_bm, color = kernel),\n             linetype = \"dashed\") +\n  labs(x = \"Fishing effort\", y = \"Mean biomass (t > 550)\",\n       title = \"Biomass vs fishing effort in the oscillating regime\",\n       subtitle = \"Dashed lines = each kernel's unfished (effort = 0) baseline biomass\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(fishing_summary, aes(x = effort, y = amp, color = kernel)) +\n  geom_line(linewidth = 1) + geom_point() +\n  labs(x = \"Fishing effort\", y = \"Oscillation amplitude (max - min, t > 550)\",\n       title = \"Does fishing effort dampen the oscillation?\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n`effort_seq` was extended from `0–2` to `0–6` after a first pass, since both yield curves were still climbing at `effort = 2`. Biomass declines smoothly for both kernels, the highest-amplitude kernel drops about 44% from its unfished baseline (`0.225 → 0.125`), the default about 28% (`0.097 → 0.07`), but neither collapses to zero even by `effort = 6`, and yield still hasn't peaked for either: the default flattens near the top (\\~`1.05e-4`) but hasn't turned down, and the highest-amplitude kernel has essentially plateaued around `1.5e-5`. Since neither stock is collapsing, there's no maximum-sustainable-yield hump showing up in this range; as fishing reduces the fish population, predation pressure on the resource likely eases and lets it partially recover, buffering yield and pushing any real hump further out than `effort = 6`. The wider range also resolves an earlier ambiguity about damping: the default kernel's amplitude does decline with effort (`0.16 → ~0.08`, roughly halved), it just needed the wider window to separate the trend from noise; the highest-amplitude kernel's decline is smooth and monotonic throughout (`0.6 → 0.27`).\n\nMost striking: **the highest-amplitude kernel has more than double the default kernel's unfished biomass (\\~0.22 vs \\~0.097) but produces roughly 8× less yield at every effort level tested.** More standing stock is not turning into more catch. Gear selectivity here is knife-edge at `w_mat` by default, meaning only fish above that size are catchable.So if the highest-amplitude kernel's biomass is concentrated below that cutoff, that alone explains the mismatch. This is checkable for free, reusing the `sim` objects already stored from the `effort = 0` runs above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunfished_default     <- fishing_results[[1]]$runs[[which(effort_seq == 0)]]$sim\nunfished_highest_amp <- fishing_results[[2]]$runs[[which(effort_seq == 0)]]$sim\n\nlast_default <- dim(unfished_default@n)[1]\nlast_highamp <- dim(unfished_highest_amp@n)[1]\n\nspectrum_df <- bind_rows(\n  data.frame(\n    w               = unfished_default@params@w,\n    biomass_density = unfished_default@n[last_default, 1, ] * unfished_default@params@w,\n    kernel          = \"default (beta=100, sigma=1.3)\"\n  ),\n  data.frame(\n    w               = unfished_highest_amp@params@w,\n    biomass_density = unfished_highest_amp@n[last_highamp, 1, ] * unfished_highest_amp@params@w,\n    kernel          = \"highest-amplitude (beta=50, sigma=0.8)\"\n  )\n)\n\nggplot(spectrum_df, aes(x = w, y = biomass_density, color = kernel)) +\n  geom_line(linewidth = 1) +\n  geom_vline(xintercept = 10, linetype = \"dashed\") +\n  scale_x_log10() + scale_y_log10() +\n  labs(x = \"Body weight (g)\", y = \"Biomass density (N x w)\",\n       title = \"Size spectra at effort = 0\",\n       subtitle = \"Dashed line = w_mat = 10, the default gear knife-edge selectivity cutoff\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nBoth curves drop steeply right at `w_mat = 10`, but they also cross a couple of times near the cutoff, so it's hard to tell by eye which kernel actually has more catchable biomass. Quantifying it directly (correctly, weighting by the log-spaced bin width `dw`, the same integral `getBiomass()` uses internally):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncatchable_fraction <- function(sim, cutoff = 10) {\n  last         <- dim(sim@n)[1]\n  w            <- sim@params@w\n  dw           <- sim@params@dw\n  bm_density   <- sim@n[last, 1, ] * w * dw\n  total_bm     <- sum(bm_density)\n  catchable_bm <- sum(bm_density[w >= cutoff])\n  data.frame(total_bm = total_bm, catchable_bm = catchable_bm,\n             catchable_fraction = catchable_bm / total_bm)\n}\n\ncatchable_summary <- rbind(\n  data.frame(kernel = \"default (beta=100, sigma=1.3)\",\n             catchable_fraction(unfished_default)),\n  data.frame(kernel = \"highest-amplitude (beta=50, sigma=0.8)\",\n             catchable_fraction(unfished_highest_amp))\n)\nknitr::kable(catchable_summary)\n```\n\n::: {.cell-output-display}\n\n\n|kernel                                 |  total_bm| catchable_bm| catchable_fraction|\n|:--------------------------------------|---------:|------------:|------------------:|\n|default (beta=100, sigma=1.3)          | 0.0252661|      7.9e-06|           3.13e-04|\n|highest-amplitude (beta=50, sigma=0.8) | 0.1837927|      6.0e-06|           3.26e-05|\n\n\n:::\n:::\n\n\nConfirmed. Despite having roughly 7× more total biomass, the highest-amplitude kernel has slightly less absolute catchable biomass than the default (`5.98e-6` vs `7.91e-6`), and its `catchable_fraction` is about 10× lower (`0.0033%` vs `0.031%`). Nearly all of that kernel's extra standing stock is juveniles that never cross the `w_mat = 10` selectivity cutoff.So the \"more biomass\" seen in the size-spectrum plot is largely fictitious from the fishery's perspective, and is the primary explanation for the yield gap.\n\n### What This Shows\n\nFeeding-kernel shape sets oscillation amplitude directly: narrower, more concentrated kernels sustain larger-amplitude cycles than the default. Fishing effort reduces biomass smoothly in both kernels without finding a maximum-sustainable-yield peak in the tested range, most likely because eased predation pressure lets the resource partially recover as the fish population is fished down. And a striking yield/biomass mismatch between kernels — more standing stock but far less catch — turns out to be a size-selectivity effect: most of the higher-amplitude kernel's extra biomass is juveniles below the catchable-size cutoff, not extra mature stock.\n\n------------------------------------------------------------------------\n\n## Why Are There So Many More Juveniles Than Adults?\n\nBoth size spectra above show a steep drop in biomass right at `w_mat = 10` ; several orders of magnitude fewer individuals ever reach a catchable, mature size than exist as juveniles. Going back to the original Day 18-style regime (`balance = TRUE`, `resource_decrease = r_d[1] = 0.001`, default perturbation, reusing the sim already computed in `results_balance_true[[1]]`), the natural first check is whether adults or juveniles oscillate more:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrack_life_stages <- function(sim, w_mat = 10) {\n  bm_juv   <- getBiomass(sim, max_w = w_mat)[, \"Anchovy\"]\n  bm_adult <- getBiomass(sim, min_w = w_mat)[, \"Anchovy\"]\n  t        <- as.numeric(names(bm_juv))\n  data.frame(t = t, bm_juv = bm_juv, bm_adult = bm_adult)\n}\n\nday18_sim     <- results_balance_true[[1]]$sim\nlife_stage_bm <- track_life_stages(day18_sim)\nmask          <- life_stage_bm$t > 550\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(NULL, xlim = c(550, 600),\n     ylim = range(c(life_stage_bm$bm_juv[mask], life_stage_bm$bm_adult[mask])),\n     xlab = \"Time (years)\", ylab = \"Biomass\",\n     main = \"Juvenile vs adult biomass (balance = TRUE, r_d = 0.001)\")\nlines(life_stage_bm$t[mask], life_stage_bm$bm_juv[mask],   col = \"darkgreen\", lwd = 2)\nlines(life_stage_bm$t[mask], life_stage_bm$bm_adult[mask], col = \"purple\",    lwd = 2)\nlegend(\"topright\", legend = c(\"Juveniles (w < 10)\", \"Adults (w >= 10)\"),\n       col = c(\"darkgreen\", \"purple\"), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](2026-07-02-day-nineteen_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nJuveniles and adults sit at very different biomass scales, so relative amplitude (`amp / mean`) is the fair comparison, not absolute amplitude:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrel_amp <- function(x) (max(x) - min(x)) / mean(x)\n\nlife_stage_summary <- data.frame(\n  stage   = c(\"Juvenile (w < 10)\", \"Adult (w >= 10)\"),\n  mean_bm = c(mean(life_stage_bm$bm_juv[mask]),  mean(life_stage_bm$bm_adult[mask])),\n  amp     = c(max(life_stage_bm$bm_juv[mask]) - min(life_stage_bm$bm_juv[mask]),\n             max(life_stage_bm$bm_adult[mask]) - min(life_stage_bm$bm_adult[mask])),\n  rel_amp = c(rel_amp(life_stage_bm$bm_juv[mask]), rel_amp(life_stage_bm$bm_adult[mask]))\n)\nknitr::kable(life_stage_summary)\n```\n\n::: {.cell-output-display}\n\n\n|stage             |   mean_bm|       amp|  rel_amp|\n|:-----------------|---------:|---------:|--------:|\n|Juvenile (w < 10) | 0.0977290| 0.1592718| 1.629730|\n|Adult (w >= 10)   | 0.0000497| 0.0001048| 2.107687|\n\n\n:::\n:::\n\n\nThe result is the opposite of expected. Adults show higher relative amplitude than juveniles (\\~2.11 vs \\~1.63) and proportionally, the rare mature fish swing more than the abundant juveniles do, not less. But that answers a different question from the one that actually matters here: how much either life stage oscillates around its own mean says nothing about why the standing-stock ratio between juveniles and adults is so lopsided in the first place. That's a demographic question, more about survivorship through growth, cumulative mortality, and how long an individual takes to grow from `w_min` to `w_mat` and not a dynamical one about oscillation amplitude.\n\n------------------------------------------------------------------------\n\n## Theoretical Grounding: Strogatz, Chapter 8\n\nAlongside the coding, the next stretch of work is going through *Nonlinear Dynamics and Chaos* (Strogatz), sections 8.3–8.7, plus the accompanying exercises. These chapters line up almost exactly with the open questions this project has been circling since Day 18: what kind of bifurcation this is, whether the parked `beta = 150, sigma = 0.8` cell is chaos, quasiperiodicity, or a slow transient, and how to test for hysteresis properly rather than by eye.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Plot maximum and minimum separately:** Instead of plotting max − min, to get a bifurcation-diagram look at the amplitude data rather than a single collapsed amplitude curve.\n\n- **Try a different perturbation type:** To see whether the same convergence-to-attractor result holds no matter what form the perturbation takes, rather than relying solely on the mature-stock knock-down used so far.\n\n- **Working through the Nonlinear Dynamics book:** Continuing Strogatz sections 8.3–8.7 on global bifurcations, hysteresis, quasiperiodicity, and Poincaré maps, to properly ground the bifurcation classification and diagnose the parked chaos-looking cell.\n\n- **Think on why there is so much biomass accumulated at juvenile stages:** The survivorship-through-growth question raised above but not resolved.\n",
    "supporting": [
      "2026-07-02-day-nineteen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}