{
  "hash": "d04099e1211b2c31730a7bb284892655",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 23: Fixing the Overnight Run, Closing Its Open Questions, and a Hysteresis Loop It Missed\"\nauthor: \"Samia\"\ndate: \"2026-07-08\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, hysteresis, phase-diagram, path-dependence, bifurcation, diffusion, reproducibility, blog]\ndescription: \"A single day's work, all appended onto 23_experiments.R: fixing the MIN_VIABLE_BIOMASS bug that kept the overnight phase-diagram run from surviving a fresh session, reading back a clean 'no path dependence' result across 20 grid points, then closing out that result's three open caveats (scan rate, perturbation, grid resolution) -- all of which hold up. Then a return to classic forward/backward bifurcation diagrams turns up something the phase-diagram grid never tested: a real hysteresis loop sitting right at the capacity_mult collapse boundary (~1.6-2.1), below where every grid so far started sampling. Chasing why capacity_mult = 1 collapses entirely rules out two plausible mechanisms (an over-extreme starting perturbation, a resource-rate/capacity mismatch) without yet landing on a third. Separately, a diffusion-strength sweep under the old balance = TRUE setup confirms hysteresis is genuinely diffusion-dependent -- strong at ext_diff = 0.001, gone by 0.167 -- answering, at least for that setup, whether Day 22's 'no hysteresis' result was a diffusion artefact.\"\n---\n\n## Where We Started: A Missing Constant\n\nRunning `23_experiments.R` fresh came back with:\n\n```         \nError in `mutate()`:\nℹ In argument: `collapsed = mean_bm < MIN_VIABLE_BIOMASS`.\nCaused by error:\n! object 'MIN_VIABLE_BIOMASS' not found\n```\n\n`MIN_VIABLE_BIOMASS` - the biomass floor introduced on Day 22 to stop numerically-collapsed populations from winning the \"most oscillatory\" ranking on floating-point noise - was never actually defined in `23_experiments.R`. It only ever worked because `22_experiments.R`'s session was still open in the same RStudio instance. Source `23_experiments.R` alone, in a fresh session, and it has nothing to check the floor against.\n\nThe fix is one line, added where the constant is actually needed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Same threshold as Day 22's baseline sweep -- filters out numerical noise\n# masquerading as a viable population. Defined here, not inherited from\n# 22_experiments.R's session state, so this file runs standalone.\nMIN_VIABLE_BIOMASS <- 1e-2\n```\n:::\n\n\nEvery script since Day 20 redefines `make_second_order_params()` from scratch specifically so each day's file is self-contained, but that discipline slipped for this one constant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\nlibrary(colorRamps)\nlibrary(future)\nlibrary(scales)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The Params Builder\n\n`make_second_order_params_kr()` , carrying capacity and resource rate set independently, both as multipliers on mizer's own `kappa`/`lambda`-derived defaults, `balance = FALSE` so neither gets silently recomputed from the other , carries over unchanged from Day 22's \"take two\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_second_order_params_kr <- function(lambda = 2.05, resource_decrease = 0.001,\n                                        capacity_mult = 1, second_order = TRUE,\n                                        ext_diff = 0.00) {\n  a0    <- 100\n  kappa <- a0 * exp(-6.9 * (lambda - 1))\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n\n  given_species_params(params)$D_ext <- ext_diff\n  params <- setBevertonHolt(params)\n\n  default_capacity <- getResourceCapacity(params)\n  r  <- getResourceRate(params) * resource_decrease\n  cc <- default_capacity * capacity_mult\n\n  params <- setResource(params, resource_rate = r, resource_capacity = cc,\n                        resource_dynamics = \"resource_semichemostat\",\n                        balance = FALSE)\n\n  if (second_order) {\n    second_order_w(params) <- c(flux = \"centred\", bin_average = TRUE)\n  }\n\n  params\n}\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The Phase Diagram: A Snake Sweep and Three Routes\n\nRather than sweeping `resource_decrease` independently at each `capacity_mult` row , restarting from mizer's default state every time , the whole grid gets traced as one continuous boustrophedon path, carrying the settled state from each point into its immediate neighbour, including across the row-to-row step:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_snake_grid <- function(rd_grid, cc_grid, lambda = 2.05, t_run = 600) {\n  out       <- vector(\"list\", length(rd_grid) * length(cc_grid))\n  state_n   <- NULL\n  state_npp <- NULL\n  k <- 1\n\n  for (j in seq_along(cc_grid)) {\n    rd_order <- if (j %% 2 == 1) rd_grid else rev(rd_grid)\n\n    for (rd in rd_order) {\n      p <- make_second_order_params_kr(lambda = lambda, resource_decrease = rd,\n                                       capacity_mult = cc_grid[j])\n      if (!is.null(state_n)) {\n        p@initial_n[]    <- state_n\n        p@initial_n_pp[] <- state_npp\n      }\n      sim <- project(p, t_max = t_run, dt = 0.1, t_save = 0.5,\n                     progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n      bm   <- getBiomass(sim)[, \"Anchovy\"]\n      tv   <- as.numeric(names(bm))\n      late <- bm[tv > t_run * 0.6]\n      last <- dim(sim@n)[1]\n\n      state_n   <- sim@n[last, , ]\n      state_npp <- sim@n_pp[last, ]\n\n      out[[k]] <- data.frame(resource_decrease = rd, capacity_mult = cc_grid[j],\n                             max_bm        = max(late), min_bm = min(late),\n                             mean_bm       = mean(late),\n                             rel_amplitude = (max(late) - min(late)) / mean(late),\n                             step          = k)\n      k <- k + 1\n    }\n  }\n  bind_rows(out)\n}\n\nrd_grid_snake <- exp(seq(log(0.0001), log(0.5), length.out = 5))\ncc_grid_snake <- exp(seq(log(3), log(100), length.out = 4))\n\nsnake_df <- run_snake_grid(rd_grid_snake, cc_grid_snake) %>%\n  arrange(step) %>%\n  mutate(collapsed = mean_bm < MIN_VIABLE_BIOMASS,\n         phase     = case_when(\n           collapsed            ~ \"Collapsed\",\n           rel_amplitude > 1e-2 ~ \"Oscillating\",\n           TRUE                 ~ \"Fixed point\"\n         ))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnake_plot_fwd <- ggplot(snake_df, aes(x = resource_decrease, y = capacity_mult)) +\n  geom_tile(aes(fill = phase), color = \"white\", linewidth = 0.3) +\n  geom_path(color = \"black\", linewidth = 0.3, alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_fill_manual(values = c(\"Fixed point\" = \"#4C72B0\",\n                               \"Oscillating\" = \"#DD8452\",\n                               \"Collapsed\"   = \"grey70\")) +\n  labs(x = \"resource_decrease (resource rate)\",\n       y = \"capacity_mult (carrying capacity)\",\n       title = \"Phase diagram: fixed point vs. oscillating regime\",\n       subtitle = \"Traced as a snake path -- state carried continuously between neighbouring points\",\n       fill = \"Regime\") +\n  theme_minimal()\nsnake_plot_fwd\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThree regions fall out of the 5x4 grid: `Collapsed` at low `resource_decrease` combined with low-to-mid `capacity_mult`, a `Fixed point` band along the diagonal, and `Oscillating` covering most of the rest. One easy-to-miss detail: the lowest `resource_decrease` column isn't uniformly collapsed ; at `capacity_mult = 100` it's a `Fixed point`, not `Collapsed`, showing carrying capacity alone can rescue that corner even at the most depleted resource rate.\n\nThe point of tracing the grid at all is Day 22's supercooling/superheating framing: if the phase boundary genuinely depends on history, different routes through the same grid should trace different boundaries. Three get compared: **Forward** (the snake above), **Reversed** (the exact retrace, walked backwards), and **Transposed** (`capacity_mult` swept within each `resource_decrease` row instead). The **Reversed** route is also what closes out Day 22's parked item about rechecking Day 21's backward-first bifurcation ordering against the capacity-aware setup: it's the same \"walk it backwards\" idea, just now run against both parameters at once instead of `resource_decrease` alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuild_path_capacity_rows <- function(rd_grid, cc_grid) {\n  path <- vector(\"list\", length(rd_grid) * length(cc_grid))\n  k <- 1\n  for (j in seq_along(cc_grid)) {\n    rd_order <- if (j %% 2 == 1) rd_grid else rev(rd_grid)\n    for (rd in rd_order) {\n      path[[k]] <- data.frame(resource_decrease = rd, capacity_mult = cc_grid[j])\n      k <- k + 1\n    }\n  }\n  bind_rows(path)\n}\n\nbuild_path_rd_rows <- function(rd_grid, cc_grid) {\n  path <- vector(\"list\", length(rd_grid) * length(cc_grid))\n  k <- 1\n  for (i in seq_along(rd_grid)) {\n    cc_order <- if (i %% 2 == 1) cc_grid else rev(cc_grid)\n    for (cc in cc_order) {\n      path[[k]] <- data.frame(resource_decrease = rd_grid[i], capacity_mult = cc)\n      k <- k + 1\n    }\n  }\n  bind_rows(path)\n}\n\nrun_along_path <- function(path_df, lambda = 2.05, t_run = 600, label = \"\") {\n  state_n   <- NULL\n  state_npp <- NULL\n  out <- vector(\"list\", nrow(path_df))\n\n  for (i in seq_len(nrow(path_df))) {\n    rd <- path_df$resource_decrease[i]\n    cc <- path_df$capacity_mult[i]\n\n    p <- make_second_order_params_kr(lambda = lambda, resource_decrease = rd,\n                                     capacity_mult = cc)\n    if (!is.null(state_n)) {\n      p@initial_n[]    <- state_n\n      p@initial_n_pp[] <- state_npp\n    }\n    sim <- project(p, t_max = t_run, dt = 0.1, t_save = 0.5,\n                   progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n    bm   <- getBiomass(sim)[, \"Anchovy\"]\n    tv   <- as.numeric(names(bm))\n    late <- bm[tv > t_run * 0.6]\n    last <- dim(sim@n)[1]\n\n    state_n   <- sim@n[last, , ]\n    state_npp <- sim@n_pp[last, ]\n\n    out[[i]] <- data.frame(resource_decrease = rd, capacity_mult = cc,\n                           max_bm        = max(late), min_bm = min(late),\n                           mean_bm       = mean(late),\n                           rel_amplitude = (max(late) - min(late)) / mean(late),\n                           step = i, route = label)\n  }\n  bind_rows(out)\n}\n\nclassify_phase <- function(mean_bm, rel_amplitude) {\n  case_when(\n    mean_bm < MIN_VIABLE_BIOMASS ~ \"Collapsed\",\n    rel_amplitude > 1e-2         ~ \"Oscillating\",\n    TRUE                         ~ \"Fixed point\"\n  )\n}\n\npath_fwd         <- build_path_capacity_rows(rd_grid_snake, cc_grid_snake)\npath_bwd         <- path_fwd[rev(seq_len(nrow(path_fwd))), ]\npath_transposed  <- build_path_rd_rows(rd_grid_snake, cc_grid_snake)\n\nroutes_df <- bind_rows(\n  run_along_path(path_fwd,        label = \"Forward (capacity rows)\"),\n  run_along_path(path_bwd,        label = \"Reversed (exact retrace)\"),\n  run_along_path(path_transposed, label = \"Transposed (resource-rate rows)\")\n) %>%\n  mutate(phase = classify_phase(mean_bm, rel_amplitude))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroutes_plot <- ggplot(routes_df, aes(x = resource_decrease, y = capacity_mult)) +\n  geom_tile(aes(fill = phase), color = \"white\", linewidth = 0.3) +\n  geom_path(color = \"black\", linewidth = 0.3, alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_fill_manual(values = c(\"Fixed point\" = \"#4C72B0\",\n                               \"Oscillating\" = \"#DD8452\",\n                               \"Collapsed\"   = \"grey70\")) +\n  facet_wrap(~route) +\n  labs(x = \"resource_decrease (resource rate)\",\n       y = \"capacity_mult (carrying capacity)\",\n       title = \"Phase diagram by route: same grid, three different paths\",\n       subtitle = \"If these three panels disagree, the boundary is path-dependent\",\n       fill = \"Regime\") +\n  theme_minimal()\nroutes_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nChecked numerically rather than by eye: zero of the 20 grid points disagree across all three routes, and where they agree the underlying `mean_bm` values agree to within a few percent almost everywhere (three cells agree to machine precision). A clean negative result for path-dependence, within this grid, which starts sampling at `capacity_mult = 3`. That qualifier turns out to matter later.\n\n------------------------------------------------------------------------\n\n## Closing Three Open Questions\n\nThat \"no path dependence\" result came with three caveats: untested scan-rate dependence (`t_run = 600` might just be long enough to relax away any real memory effect), no genuine perturbation test (every `Fixed point` cell was only ever approached from a settled neighbour, never actively kicked), and grid resolution (5x4 is coarse enough to hide a narrow band). All three get closed out.\n\n### 1. Scan-Rate Dependence\n\nThe three-route comparison reruns at `t_run = 50` and `150`, reusing `routes_df` above as the `t_run = 600` baseline rather than recomputing it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_three_routes <- function(t_run, rd_grid = rd_grid_snake, cc_grid = cc_grid_snake) {\n  fwd        <- build_path_capacity_rows(rd_grid, cc_grid)\n  bwd        <- fwd[rev(seq_len(nrow(fwd))), ]\n  transposed <- build_path_rd_rows(rd_grid, cc_grid)\n\n  bind_rows(\n    run_along_path(fwd,        t_run = t_run, label = \"Forward (capacity rows)\"),\n    run_along_path(bwd,        t_run = t_run, label = \"Reversed (exact retrace)\"),\n    run_along_path(transposed, t_run = t_run, label = \"Transposed (resource-rate rows)\")\n  ) %>%\n    mutate(t_run = t_run, phase = classify_phase(mean_bm, rel_amplitude))\n}\n\nscan_rate_df <- bind_rows(\n  run_three_routes(t_run = 50),\n  run_three_routes(t_run = 150),\n  routes_df %>% mutate(t_run = 600)\n)\n\nscan_rate_agreement <- scan_rate_df %>%\n  select(resource_decrease, capacity_mult, t_run, route, phase) %>%\n  tidyr::pivot_wider(names_from = route, values_from = phase) %>%\n  mutate(agree = `Forward (capacity rows)` == `Reversed (exact retrace)` &\n                 `Reversed (exact retrace)` == `Transposed (resource-rate rows)`) %>%\n  group_by(t_run) %>%\n  summarise(n_disagree = sum(!agree), n_total = n(), .groups = \"drop\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscan_rate_agreement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  t_run n_disagree n_total\n  <dbl>      <int>   <int>\n1    50          1      20\n2   150          0      20\n3   600          0      20\n```\n\n\n:::\n:::\n\n\n| t_run | disagreements | out of |\n|-------|---------------|--------|\n| 50    | 1             | 20     |\n| 150   | 0             | 20     |\n| 600   | 0             | 20     |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscan_rate_plot <- ggplot(scan_rate_df, aes(x = resource_decrease, y = capacity_mult)) +\n  geom_tile(aes(fill = phase), color = \"white\", linewidth = 0.3) +\n  geom_path(color = \"black\", linewidth = 0.3, alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_fill_manual(values = c(\"Fixed point\" = \"#4C72B0\",\n                               \"Oscillating\" = \"#DD8452\",\n                               \"Collapsed\"   = \"grey70\")) +\n  facet_grid(t_run ~ route) +\n  labs(x = \"resource_decrease (resource rate)\",\n       y = \"capacity_mult (carrying capacity)\",\n       title = \"Scan-rate dependence: same three routes at t_run = 50, 150, 600\",\n       subtitle = \"Rows = per-step settle time\",\n       fill = \"Regime\") +\n  theme_minimal()\nscan_rate_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nOne disagreement at the fastest rate, gone by `150`. The disagreeing cell (`resource_decrease = 0.00707, capacity_mult = 3`) is one of the five cells the perturbation retest below confirms stable - pointing at a relaxation-time artefact (50 years isn't long enough for a transient to decay before sampling) rather than a second real attractor.\n\n### 2. A Genuine Perturbation Retest\n\nDay 17/18's original limit-cycle search actively kicked the system done by reducing the resource to 10% of carrying capacity, a short burn-in, then the mature stock divided by 1000x which is a step every sweep since Day 20 dropped. This reruns it, adapted to `tr_bdf2`, on every cell the `t_run = 600` sweep called `Fixed point`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_limit_cycle_sim_kr <- function(params, t_total = 600, effort = 0, perturbation = 1e3) {\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim_init <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0,\n                      method = \"predictor-corrector\")\n  idx  <- params@w >= 10 & params@w <= 100\n  last <- dim(sim_init@n)[1]\n  sim_init@n[last, , idx] <- sim_init@n[last, , idx] / perturbation\n\n  project(sim_init, t_max = t_total - 10, dt = 0.1, t_save = 0.2,\n          progress_bar = FALSE, effort = effort,\n          method = \"tr_bdf2\")\n}\n\nfixed_point_cells <- routes_df %>%\n  filter(phase == \"Fixed point\") %>%\n  distinct(resource_decrease, capacity_mult)\n\nretest_with_kick <- function(rd, cc, lambda = 2.05, t_total = 600, perturbation = 1e3) {\n  p   <- make_second_order_params_kr(lambda = lambda, resource_decrease = rd,\n                                     capacity_mult = cc)\n  sim <- make_limit_cycle_sim_kr(p, t_total = t_total, perturbation = perturbation)\n  bm   <- getBiomass(sim)[, \"Anchovy\"]\n  tv   <- as.numeric(names(bm))\n  late <- bm[tv > (t_total - 10) * 0.6]\n\n  data.frame(resource_decrease = rd, capacity_mult = cc,\n             mean_bm       = mean(late),\n             rel_amplitude = (max(late) - min(late)) / mean(late))\n}\n\nkick_retest_df <- purrr::map2_dfr(\n  fixed_point_cells$resource_decrease, fixed_point_cells$capacity_mult,\n  retest_with_kick\n) %>%\n  mutate(phase_after_kick = classify_phase(mean_bm, rel_amplitude))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkick_retest_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  resource_decrease capacity_mult    mean_bm rel_amplitude phase_after_kick\n1      0.0070710678      3.000000 0.02197924  2.073532e-11      Fixed point\n2      0.0594603558      3.000000 0.18482266  8.860271e-15      Fixed point\n3      0.5000000000      3.000000 1.55416716  8.715099e-15      Fixed point\n4      0.0008408964      9.654894 0.01374181  5.308598e-04      Fixed point\n5      0.0001000000    100.000000 0.02526812  3.190598e-03      Fixed point\n```\n\n\n:::\n:::\n\n\n| resource_decrease | capacity_mult | rel_amplitude after kick | phase after kick |\n|------------------|------------------|------------------|------------------|\n| 0.00707           | 3             | 2.9e-11                  | Fixed point      |\n| 0.0595            | 3             | 8.9e-15                  | Fixed point      |\n| 0.5               | 3             | 8.7e-15                  | Fixed point      |\n| 0.000841          | 9.65          | 5.3e-4                   | Fixed point      |\n| 0.0001            | 100           | 3.2e-3                   | Fixed point      |\n\nAll five survive. Three come back at essentially machine-precision zero amplitude. These aren't unexplored limit cycles the default initial state never found but rather, the same kick that originally revealed the Day 18 limit cycle puts all five straight back where they started.\n\n### 3. Grid Resolution\n\nA densified 9x7 grid - double the resolution of the 5x4 grid above, Forward route only, `t_run = 300`, checks whether a narrow band could be sitting entirely inside one of the coarse grid's tiles:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrd_grid_fine <- exp(seq(log(0.0001), log(0.5), length.out = 9))\ncc_grid_fine <- exp(seq(log(3), log(100), length.out = 7))\n\npath_fwd_fine <- build_path_capacity_rows(rd_grid_fine, cc_grid_fine)\n\nfine_grid_df <- run_along_path(path_fwd_fine, t_run = 300,\n                               label = \"Forward (capacity rows), fine grid\") %>%\n  mutate(phase = classify_phase(mean_bm, rel_amplitude))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfine_grid_plot <- ggplot(fine_grid_df, aes(x = resource_decrease, y = capacity_mult)) +\n  geom_tile(aes(fill = phase), color = \"white\", linewidth = 0.2) +\n  geom_path(color = \"black\", linewidth = 0.3, alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_fill_manual(values = c(\"Fixed point\" = \"#4C72B0\",\n                               \"Oscillating\" = \"#DD8452\",\n                               \"Collapsed\"   = \"grey70\")) +\n  labs(x = \"resource_decrease (resource rate)\",\n       y = \"capacity_mult (carrying capacity)\",\n       title = \"Densified phase diagram: 9x7 grid, Forward route only\",\n       subtitle = \"t_run = 300 per step -- double the resolution of the 5x4 grid above\",\n       fill = \"Regime\") +\n  theme_minimal()\nfine_grid_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nIt found something the coarse grid's row spacing hid: a wide `Fixed point` band at `capacity_mult = 5.38`, interpolated between the coarse grid's `cap = 3` row (almost entirely `Fixed point`) and `cap = 9.65` row (almost entirely `Oscillating`) but with zero `Oscillating` cells in it. The coarse grid made that transition look fast; it isn't.\n\nA targeted refinement of `capacity_mult` in `[3, 10]` (same 9-point density, still Forward-only, `t_run = 300`) pins the shape down:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncc_grid_refine <- exp(seq(log(3), log(10), length.out = 9))\n\npath_fwd_refine <- build_path_capacity_rows(rd_grid_fine, cc_grid_refine)\n\nrefine_grid_df <- run_along_path(path_fwd_refine, t_run = 300,\n                                 label = \"Forward (capacity rows), cap in [3,10]\") %>%\n  mutate(phase = classify_phase(mean_bm, rel_amplitude))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrefine_grid_plot <- ggplot(refine_grid_df, aes(x = resource_decrease, y = capacity_mult)) +\n  geom_tile(aes(fill = phase), color = \"white\", linewidth = 0.2) +\n  geom_path(color = \"black\", linewidth = 0.3, alpha = 0.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  scale_fill_manual(values = c(\"Fixed point\" = \"#4C72B0\",\n                               \"Oscillating\" = \"#DD8452\",\n                               \"Collapsed\"   = \"grey70\")) +\n  labs(x = \"resource_decrease (resource rate)\",\n       y = \"capacity_mult (carrying capacity)\",\n       title = \"Refined phase diagram: capacity_mult in [3, 10], 9x9 grid\",\n       subtitle = \"Zooming in on the plateau found in the 9x7 grid\",\n       fill = \"Regime\") +\n  theme_minimal()\nrefine_grid_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nFlat (zero `Oscillating`) from `3.00` through `5.48`, then a narrow flip: one stray cell at `6.37` (`rel_amplitude` landing almost exactly on the `1e-2` classification threshold ,which is likely a borderline call, not a clean oscillation), then a complete reversal by `7.40`.\n\n------------------------------------------------------------------------\n\n## Bifurcation Sweeps Revisited: A Hysteresis Loop the Grid Missed\n\nEverything above uses discrete phase classification on a grid. Returning to the classic style of bifurcation diagram used throughout Days 18-22 , forward and backward branches of biomass against one swept parameter , adds something the tile-grid approach doesn't show as directly, and it surfaced a real result the phase diagram never tested for, simply because its grid always started at `capacity_mult = 3`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_bifurcation_sweep <- function(param_seq, param_name, fixed_params = list(),\n                                  params_fn = make_second_order_params_kr,\n                                  t_run = 600, lambda = 2.05) {\n  run_one_direction <- function(seq_vals, init_n = NULL, init_n_pp = NULL) {\n    out       <- data.frame(value = seq_vals, max_bm = NA_real_, min_bm = NA_real_)\n    state_n   <- init_n\n    state_npp <- init_n_pp\n\n    for (i in seq_along(seq_vals)) {\n      args <- fixed_params\n      args[[param_name]] <- seq_vals[i]\n      args$lambda <- lambda\n      p <- do.call(params_fn, args)\n      if (!is.null(state_n)) {\n        p@initial_n[]    <- state_n\n        p@initial_n_pp[] <- state_npp\n      }\n      sim <- project(p, t_max = t_run, dt = 0.1, t_save = 0.5,\n                     progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n      bm   <- getBiomass(sim)[, \"Anchovy\"]\n      tv   <- as.numeric(names(bm))\n      late <- bm[tv > t_run * 0.6]\n      last <- dim(sim@n)[1]\n\n      state_n   <- sim@n[last, , ]\n      state_npp <- sim@n_pp[last, ]\n\n      out$max_bm[i] <- max(late)\n      out$min_bm[i] <- min(late)\n    }\n    list(df = out, n_final = state_n, npp_final = state_npp)\n  }\n\n  fwd    <- run_one_direction(param_seq)\n  bwd    <- run_one_direction(rev(param_seq), init_n = fwd$n_final, init_n_pp = fwd$npp_final)\n  bwd_df <- bwd$df[order(bwd$df$value), ]\n\n  bind_rows(\n    data.frame(value = fwd$df$value, biomass = fwd$df$max_bm, direction = \"Forward\",  branch = \"max\"),\n    data.frame(value = fwd$df$value, biomass = fwd$df$min_bm, direction = \"Forward\",  branch = \"min\"),\n    data.frame(value = bwd_df$value, biomass = bwd_df$max_bm, direction = \"Backward\", branch = \"max\"),\n    data.frame(value = bwd_df$value, biomass = bwd_df$min_bm, direction = \"Backward\", branch = \"min\")\n  )\n}\n\nrd_seq_bif <- exp(seq(log(0.0001), log(0.5), length.out = 20))\ncc_seq_bif <- exp(seq(log(1), log(100), length.out = 20))\n\nbif_rd_df <- run_bifurcation_sweep(rd_seq_bif, \"resource_decrease\",\n                                   fixed_params = list(capacity_mult = 1),\n                                   params_fn = make_second_order_params_kr)\n\nbif_cc_df <- run_bifurcation_sweep(cc_seq_bif, \"capacity_mult\",\n                                   fixed_params = list(resource_decrease = 0.001),\n                                   params_fn = make_second_order_params_kr)\n```\n:::\n\n\nBoth `rd_seq_bif` and `cc_seq_bif` use the same `exp(seq(log(lo), log(hi), length.out = n))` log-spacing pattern used throughout this project's grids: linear steps in log-space become constant-*ratio* steps in real space, so the same resolution is spent on the `1`-`10` decade as on `10`-`100`, rather than a linear grid burying almost every point above 50.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbif_rd_plot <- ggplot(bif_rd_df, aes(x = value, y = biomass, color = direction, linetype = branch)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.2) + scale_x_log10() +\n  labs(x = \"resource_decrease\", y = \"Biomass\",\n       title = \"resource_decrease swept\", subtitle = \"capacity_mult held at 1\") +\n  theme_minimal()\nbif_cc_plot <- ggplot(bif_cc_df, aes(x = value, y = biomass, color = direction, linetype = branch)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.2) + scale_x_log10() +\n  labs(x = \"capacity_mult\", y = \"Biomass\",\n       title = \"capacity_mult swept\", subtitle = \"resource_decrease held at 0.001\") +\n  theme_minimal()\nbif_rd_plot | bif_cc_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n### The resource_decrease panel is an artefact, not a finding\n\nEvery value in the `capacity_mult = 1` panel , Forward, Backward, min, max, across all 20 points, bottoms out at `5.50e-316`, the same repeated constant: floating-point underflow, an absorbing numerically-extinct state. The Forward branch's early points show it happening in real time: `1.22e-63 → 6.75e-113 → 8.93e-161 → ...`, decaying by \\~30 orders of magnitude per step until it hits the underflow floor around `resource_decrease ≈ 0.0009`, then stays there the rest of the way to `0.5`. Because state carries forward point to point, once the population dies at the very first (lowest, harshest) value, nothing in the model lets a truly-zero population regrow - so the rest of the panel is one dead trajectory being dragged along, not independent evidence about every `resource_decrease` value.\n\nThe obvious next question: is that death *itself* an artefact - a starting perturbation too extreme to survive - or is `capacity_mult = 1` genuinely unviable? Two follow-up checks, both fresh starts from mizer's own default initial condition, no sweep history at all:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_fresh <- function(rd, cc, t_run = 600) {\n  p   <- make_second_order_params_kr(resource_decrease = rd, capacity_mult = cc)\n  sim <- project(p, t_max = t_run, dt = 0.1, t_save = 0.5,\n                 progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n  bm   <- getBiomass(sim)[, \"Anchovy\"]\n  tv   <- as.numeric(names(bm))\n  late <- bm[tv > t_run * 0.6]\n  data.frame(resource_decrease = rd, capacity_mult = cc, mean_bm = mean(late))\n}\n\nfresh_check <- bind_rows(lapply(c(1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.1, 0.01, 0.001, 0.0001),\n                                run_fresh, cc = 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfresh_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   resource_decrease capacity_mult      mean_bm\n1              1e+00             1 3.829992e-32\n2              9e-01             1 3.754233e-32\n3              8e-01             1 3.662810e-32\n4              7e-01             1 3.550328e-32\n5              6e-01             1 3.408611e-32\n6              5e-01             1 3.224661e-32\n7              1e-01             1 1.197569e-32\n8              1e-02             1 6.268999e-34\n9              1e-03             1 2.131057e-37\n10             1e-04             1 2.651641e-65\n```\n\n\n:::\n:::\n\n\n| resource_decrease (fresh start) | mean biomass |\n|---------------------------------|--------------|\n| 1.0 (no cut at all)             | 3.83e-32     |\n| 0.5                             | 3.22e-32     |\n| 0.1                             | 1.20e-32     |\n| 0.01                            | 6.27e-34     |\n| 0.001                           | 2.13e-37     |\n| 0.0001                          | 2.65e-65     |\n\nTwo things fall out of this table. First: **`capacity_mult = 1` is genuinely unviable at every `resource_decrease` tested**, even the friendliest (`0.5`) and even starting completely fresh - refuting the \"the perturbation was too extreme\" hypothesis. Second, and more surprising: **it's *still* dead at `resource_decrease = 1`**, with no cut applied at all, both `resource_rate` and `resource_capacity` handed back as mizer's own unscaled defaults, with no mismatch between them whatsoever. That refutes a second, more specific hypothesis , that the collapse was a rate/capacity mismatch (a capacity sized for the *default*, faster-refilling rate, paired with a rate slowed down by `resource_decrease`). If that were the mechanism, `resource_decrease = 1` should have fixed it. It didn't; the biomass barely moves across the whole `0.5`-`1.0` range.\n\nThe best lead so far, not yet fully confirmed: `make_second_order_params_balanced()` (below, used for the diffusion sweep) is structurally almost identical , same species setup, same `D_ext`/`setBevertonHolt()` order , and *does* produce real, viable populations at the same species parameters. The only structural difference is `balance = TRUE` with only `resource_rate` passed, versus `balance = FALSE` with an explicit `resource_capacity`. That isolates the cause to `balance = FALSE` itself doing something more than \"pick consistent numbers\" - Day 22's own note describes `balance = TRUE` as keeping \"the derived capacity, the rate, and the actual dynamics consistent with each other,\" which sounds like a broader reconciliation against the whole calibrated community (feeding rates, `setBevertonHolt()`'s reproduction calibration) that `balance = FALSE` skips by design. Exactly what breaks isn't nailed down yet - comparing `erepro`/reproduction-level calibration between the two constructions is the natural next step.\n\n### The capacity_mult panel is real and it's a hysteresis loop the phase diagram never tested for\n\nUnlike the `resource_decrease` panel, this one isn't an artefact:\n\n| capacity_mult | Forward             | Backward                   |\n|---------------|---------------------|----------------------------|\n| 1.00          | 8.97e-36 (dead)     | 8.85e-34 (dead)            |\n| 1.27          | 1.30e-57 (dead)     | 3.38e-6 (still collapsing) |\n| **1.62**      | **7.71e-24 (dead)** | **6.66e-4 (alive)**        |\n| 2.07          | 1.46e-3 (alive)     | 1.46e-3 (alive)            |\n| 8.86          | 0.0147              | 0.0147                     |\n| 11.3          | 0.0208 / 0.0189     | 0.0213 / 0.0185            |\n\nAway from the boundary -- e.g. around `capacity_mult ≈ 10` -- Forward and Backward agree closely, consistent with everything found in the phase-diagram work above. But right at `capacity_mult = 1.62`, they disagree by roughly 20 orders of magnitude at the *identical* parameter value: Forward, arriving from nothing, is still dead; Backward, arriving from an established population at `capacity_mult = 100`, is already on the real branch. That's a hysteresis loop, bracketed (at this grid's resolution) to Backward's collapse point sitting in `(1.27, 1.62]` and Forward's escape point sitting in `(1.62, 2.07)` so narrower resolution would need a targeted refinement the same way the `[3, 10]` plateau got refined earlier.\n\nThis doesn't overturn the \"no path dependence\" result from the phase-diagram section above - it extends it. That grid never sampled below `capacity_mult = 3`, so it never had the chance to see this boundary at all. The two findings are consistent, not contradictory: no path dependence *within the range tested*, and a real one just outside it.\n\n------------------------------------------------------------------------\n\n## Was It Diffusion?\n\nDay 22's own framing raised the question directly: the forward/backward hysteresis gap Days 18-21 built the whole limit-cycle story around disappeared once Day 22 changed *two* things at once , the resource mechanism (`balance = TRUE` → `FALSE`) and the diffusion strength (`ext_diff` default `0.01` → `0`), and which one actually killed the hysteresis was left explicitly unresolved. This tests diffusion strength directly, on the *old* `balance = TRUE` mechanism (Day 21's original, the one that first produced the hysteresis):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_second_order_params_balanced <- function(lambda = 2.05, resource_decrease = 0.001,\n                                              resource_level = 1, second_order = TRUE,\n                                              ext_diff = 0.00) {\n  a0    <- 100\n  kappa <- a0 * exp(-6.9 * (lambda - 1))\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n\n  given_species_params(params)$D_ext <- ext_diff\n  params <- setBevertonHolt(params)\n\n  # setResource() rejects resource_rate and resource_level together under\n  # balance = TRUE -- confirmed directly against the installed mizer build:\n  # \"you should only provide either... because the other is determined.\"\n  # resource_level is kept as an argument (default 1, i.e. the resource left\n  # at its full, unsuppressed level) to document intent; only resource_rate\n  # is actually passed, exactly reproducing Day 21's original balance = TRUE\n  # call before Day 22 moved to balance = FALSE + explicit resource_level.\n  r <- getResourceRate(params) * resource_decrease\n  params <- setResource(params, resource_rate = r,\n                        resource_dynamics = \"resource_semichemostat\",\n                        balance = TRUE)\n\n  if (second_order) {\n    second_order_w(params) <- c(flux = \"centred\", bin_average = TRUE)\n  }\n\n  params\n}\n\n# Cut down from the full 20-point / t_run=600 spec to fit a ~20-minute\n# budget: 12 points and t_run=300 -- the latter already validated as\n# sufficient to settle in the phase-diagram refinements above.\nrd_seq_quick <- exp(seq(log(0.0001), log(0.5), length.out = 12))\next_diff_values_bif <- seq(0.001, 0.5, length.out = 4)\n\nbif_balanced_df <- bind_rows(lapply(ext_diff_values_bif, function(ed) {\n  run_bifurcation_sweep(rd_seq_quick, \"resource_decrease\",\n                        fixed_params = list(resource_level = 1, ext_diff = ed),\n                        params_fn = make_second_order_params_balanced,\n                        t_run = 300) %>%\n    mutate(ext_diff = ed)\n})) %>%\n  mutate(ext_diff_label = factor(sprintf(\"ext_diff = %.3f\", ext_diff),\n                                 levels = sprintf(\"ext_diff = %.3f\", sort(unique(ext_diff)))))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bif_balanced_df, aes(x = value, y = biomass, color = direction, linetype = branch)) +\n  geom_line(linewidth = 1) + geom_point(size = 1.2) + scale_x_log10() +\n  facet_wrap(~ext_diff_label, nrow = 1) +\n  labs(x = \"resource_decrease\", y = \"Biomass\",\n       title = \"resource_decrease swept at 4 diffusion strengths\",\n       subtitle = \"balance = TRUE -- the pre-Day-22-fix resource setup\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-08-day-twenty-three_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n| ext_diff | Forward/Backward gap |\n|------------------------------------|------------------------------------|\n| 0.001 | Large -- e.g. `resource_decrease = 0.049`: Forward `0.0537` vs Backward `3.55e-35` |\n| 0.167 | Agree within 1-3% everywhere |\n| 0.334 | Agree within 1-3% everywhere |\n| 0.5 | Agree within 1-3% everywhere |\n\nAt the lowest diffusion tested, there's a large hysteresis gap which is not just at one point: `resource_decrease = 0.049`, `0.106`, and `0.231` all show Forward sustaining real biomass while Backward is collapsed to near-zero at the identical value, a textbook two-states-at-one-parameter-value signature. By `ext_diff = 0.167` that gap has essentially vanished, and stays gone through `0.5`.\n\nSo: yes, diffusion strength controls whether hysteresis appears, at least under the `balance = TRUE` mechanism. That's a verified answer, not a guess. The caveat: this only tests the *old* mechanism. Whether the *current* `balance = FALSE` setup (what Day 22/23's \"no hysteresis\" conclusion was actually based on, at `ext_diff = 0`) would also show hysteresis at `ext_diff = 0.001` is a distinct, still-open test - the full 20-point / `t_run = 600` version of this sweep is saved in `23_experiments.R` if a longer, higher-resolution run is wanted later.\n\n------------------------------------------------------------------------\n\n## What This All Adds Up To\n\nThe phase-diagram work (snake sweep, three routes, scan-rate test, perturbation retest, densified grid) is a genuinely clean, thoroughly-checked \"no path dependence\" result but only within the range it tested, `capacity_mult ≥ 3`. Push below that, and there's a real hysteresis loop right at the collapse boundary (`~1.6-2.1`) that no version of the grid ever had the chance to see. Separately, diffusion strength is confirmed to control hysteresis under the old resource mechanism, closing (for that mechanism) the question Day 22 left open while opening a narrower one about why `balance = FALSE` breaks viability at `capacity_mult = 1` even with perfectly matched default values.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Pin down the capacity_mult ≈ 1.6-2.1 hysteresis window more precisely** with a targeted refinement, the same way `[3, 10]` got refined earlier.\n- **Find the actual mechanism behind `balance = FALSE`'s viability collapse at `capacity_mult = 1`** -- the rate/capacity mismatch hypothesis is refuted; comparing `erepro`/reproduction-level calibration against the working `balance = TRUE` construction is the natural next step.\n- **Rerun the diffusion sweep under `balance = FALSE`** at low `ext_diff` to check whether the current mechanism shows the same diffusion-dependence as the old one, or whether `balance = FALSE` itself suppresses hysteresis regardless of diffusion.\n- **Rerun the diffusion sweep at full resolution** (20 points, `t_run = 600`, code already in `23_experiments.R`) once the `balance = FALSE` question above is settled, rather than spending the longer run on the old mechanism twice.\n- **Rerun the `capacity_mult` bifurcation diagram at a few different fixed resource rates** to check it isn't a cherrypicked example and to confirm Gustav's prediction (from the shape of the earlier snake-sweep plot) that a higher resource rate should move the bifurcation point left, toward a smaller carrying capacity.\n- **Check whether the juvenile-biomass pileup is specific to this parameter range or general**, by rerunning the same single-species bifurcation diagram with mizer's own unspecified/default species parameters and seeing if the same shape shows up.\n- **Build a simple, non-size-structured two-species predator-prey model**: Prey with a chemostat-style replenishment rate and carrying capacity, predator with an intake term proportional to prey × resource and a mortality term proportional to predator abundance and check whether it reproduces the same transcritical-like bifurcation. The point is to test whether size resolution is actually necessary for this bifurcation behaviour or just changes the details on top of it.\n- **Come back to what fish growth (and the growth-slowdown bottleneck) actually has to do with the instability**, once the non-size-structured comparison above has an answer as if the simple predator-prey model shows the same bifurcation, growth probably isn't the mechanism after all; if it doesn't, that's where to dig next.\n",
    "supporting": [
      "2026-07-08-day-twenty-three_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}