{
  "hash": "b17ada9d4f86530076fbd26f91768823",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 25: A Real alpha/gamma/kappa Sweep, and Ruling Out Time Delay\"\nauthor: \"Samia\"\ndate: \"2026-07-10\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, juvenile-pileup, alpha, parameter-sweep, predator-prey, time-delay, blog]\ndescription: \"Two threads from Day 24 closed. First: a real alpha/gamma/kappa sweep (not just single-value swaps) confirms alpha as the dominant lever by a wide margin - a genuine viability threshold the anchovy's own value sits right at the foot of - with kappa modest and gamma flat. Second: a time delay in the predator's growth term is proven analytically to never trigger a Hopf bifurcation here, for any delay or parameters, and simulation confirms it.\"\n---\n\n## Where Day 24 Left Us\n\nDay 24 closed out the `capacity_mult` hysteresis window and Gustav's resource-rate prediction, but left three threads open for what's next: giving the toy predator-prey model a time delay, trying a feedback-loop variant of it, and rerunning the $\\alpha$/$\\gamma$/$\\kappa$ juvenile-pileup isolation properly. That last one is a direct fix to a real gap: Day 24's version only ever swapped each parameter to *one* alternate value , the other species' own default , not a real range, and it surfaced a genuine confound along the way (mizer's own default-parameter calibration turned out to be interdependent, so leaving a parameter unspecified silently let other parameters re-derive too). Today closes that thread.\n\n------------------------------------------------------------------------\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\nlibrary(colorRamps)\nlibrary(future)\nlibrary(scales)\n```\n:::\n\n\nSame builder as every day since Day 20, self-contained rather than sourced from `24_experiments.R` but extended with $\\alpha$/$\\gamma$/$\\kappa$ arguments (all defaulting to the anchovy's own values), so the same single builder can sweep any one of the three while pinning the rest at the anchovy's own fully-specified values throughout. That's what sidesteps Day 24's confound directly: nothing here is ever left for mizer to fill in, so there's no re-derivation to worry about, and every sweep point is directly comparable to every other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_second_order_params_kr <- function(lambda = 2.05, resource_decrease = 0.001,\n                                        capacity_mult = 1, second_order = TRUE,\n                                        ext_diff = 0.00, alpha = 0.1, gamma = 750,\n                                        ks = 0, kappa_override = NULL) {\n  a0    <- 100\n  kappa <- if (is.null(kappa_override)) a0 * exp(-6.9 * (lambda - 1)) else kappa_override\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = alpha, gamma = gamma, ks = ks\n  )\n\n  given_species_params(params)$D_ext <- ext_diff\n  params <- setBevertonHolt(params)\n\n  default_capacity <- getResourceCapacity(params)\n  r  <- getResourceRate(params) * resource_decrease\n  cc <- default_capacity * capacity_mult\n\n  params <- setResource(params, resource_rate = r, resource_capacity = cc,\n                        resource_dynamics = \"resource_semichemostat\",\n                        balance = FALSE)\n\n  if (second_order) {\n    second_order_w(params) <- c(flux = \"centred\", bin_average = TRUE)\n  }\n\n  params\n}\n```\n:::\n\n\nThe default species' own $\\alpha$/$\\gamma$/$\\kappa$, purely as reference lines on the sweep plots below. It's not used to build anything, so there's no risk of reintroducing the confound this rerun is designed to avoid:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndefault_species_raw <- newSingleSpeciesParams(species_name = \"Anchovy\")\ndefault_alpha <- default_species_raw@species_params$alpha[1]\ndefault_gamma <- default_species_raw@species_params$gamma[1]\ndefault_kappa <- tryCatch(resource_params(default_species_raw)$kappa,\n                          error = function(e) NA_real_)\nanchovy_kappa <- 100 * exp(-6.9 * (2.05 - 1))  # same formula make_second_order_params_kr() uses\n\ncat(sprintf(\n  paste0(\n    \"Reference values (anchovy | default species):\\n\",\n    \"  alpha: %.4f | %.4f\\n  gamma: %.1f | %.1f\\n  kappa: %.4f | %.4f\\n\"\n  ),\n  0.1, default_alpha, 750, default_gamma, anchovy_kappa, default_kappa\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReference values (anchovy | default species):\n  alpha: 0.1000 | 0.4000\n  gamma: 750.0 | 2066.0\n  kappa: 0.0714 | 0.0050\n```\n\n\n:::\n:::\n\n\nThree more helper functions round out the setup. `catchable_fraction_at()` runs a simulation out to `t_max` and returns the settled fraction of biomass sitting at or above `w_mat`. `run_param_sweep()` calls it across a sequence of values for one parameter, holding everything else fixed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncatchable_fraction_at <- function(params, t_max = 600) {\n  sim <- project(params, t_max = t_max, dt = 0.1, t_save = 0.5,\n                 progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n  last  <- dim(sim@n)[1]\n  w_mat <- params@species_params$w_mat[1]\n  w     <- sim@params@w\n  dw    <- sim@params@dw\n\n  bm_density   <- sim@n[last, 1, ] * w * dw\n  total_bm     <- sum(bm_density)\n  catchable_bm <- sum(bm_density[w >= w_mat])\n\n  data.frame(catchable_fraction = catchable_bm / total_bm, error = NA_character_)\n}\n\nrun_param_sweep <- function(param_name, param_seq, capacity_mult = 10,\n                            resource_decrease = 0.001) {\n  bind_rows(lapply(param_seq, function(v) {\n    args <- list(capacity_mult = capacity_mult, resource_decrease = resource_decrease)\n    args[[param_name]] <- v\n    result <- tryCatch({\n      p <- do.call(make_second_order_params_kr, args)\n      catchable_fraction_at(p)\n    }, error = function(e) {\n      data.frame(catchable_fraction = NA_real_, error = conditionMessage(e))\n    })\n    if (!is.na(result$error)) {\n      warning(sprintf(\"%s = %.4g: %s\", param_name, v, result$error))\n    }\n    data.frame(param = param_name, value = v,\n               catchable_fraction = result$catchable_fraction,\n               error = result$error)\n  }))\n}\n```\n:::\n\n\nThe `tryCatch` wraps both the params construction and the simulation, not just the simulation - a value near the edge of the tested range can make `newSingleSpeciesParams()` itself throw (\"the feeding level is not sufficient to maintain the fish\") before `project()` is ever reached, so an infeasible point needs to be caught there too. It comes back as an `NA` row with the error message kept, rather than halting the sweep.\n\n`plot_param_sweep()` draws the result on a log-scaled y-axis, labelled in scientific notation rather than as a percentage. `catchable_fraction` ranges from numerically-extinct up to double-digit percentages within a single sweep, and a fixed-accuracy percent label rounds everything below its threshold to the same \"0.0000%\" string, which erases exactly the low end of the range this plot needs to show:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_param_sweep <- function(df, param_label, ref_values, log_x = TRUE) {\n  p <- ggplot(df, aes(x = value, y = catchable_fraction)) +\n    geom_line(color = \"#4C72B0\", linewidth = 1) +\n    geom_point(color = \"#4C72B0\", size = 1.5) +\n    scale_y_log10(labels = scales::label_scientific()) +\n    labs(x = param_label, y = \"Catchable fraction (biomass at or above w_mat)\",\n         title = sprintf(\"Juvenile-pileup sweep: %s\", param_label),\n         subtitle = \"capacity_mult = 10, resource_decrease = 0.001 — every other parameter pinned at the anchovy's own value\") +\n    theme_minimal()\n  if (log_x) p <- p + scale_x_log10()\n  for (rv in ref_values) {\n    p <- p + geom_vline(xintercept = rv$value, linetype = rv$linetype, color = \"grey40\")\n  }\n  p\n}\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The Sweeps\n\n`capacity_mult = 10`, `resource_decrease = 0.001` throughout which is the same operating point every isolation check in `24_experiments.R` used, comfortably inside the coexistence region so a marginal population never confounds the pileup reading.\n\n### alpha\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_seq <- exp(seq(log(0.02), log(0.8), length.out = 15))\nalpha_sweep_df <- run_param_sweep(\"alpha\", alpha_seq)\n\nplot_param_sweep(\n  alpha_sweep_df, \"alpha (assimilation efficiency)\",\n  ref_values = list(list(value = 0.1, linetype = \"dashed\"),\n                    list(value = default_alpha, linetype = \"dotted\"))\n)\n```\n\n::: {.cell-output-display}\n![](2026-07-10-day-twenty-five_files/figure-html/alpha-sweep-1.png){width=672}\n:::\n:::\n\n\n| $\\alpha$ | catchable fraction |\n|-------|--------------------|\n| 0.020 | 3.2×10⁻²⁸          |\n| 0.057 | 1.1×10⁻⁹           |\n| 0.075 | 8.9×10⁻⁷           |\n| 0.097 | 2.1×10⁻⁴           |\n| 0.126 | 1.10%              |\n| 0.164 | 8.76%              |\n| 0.214 | 25.5%              |\n| 0.279 | 46.1%              |\n| 0.363 | 64.7%              |\n| 0.472 | 78.3%              |\n| 0.615 | 87.1%              |\n| 0.800 | 92.3%              |\n\n### gamma\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngamma_seq <- exp(seq(log(100), log(5000), length.out = 15))\ngamma_sweep_df <- run_param_sweep(\"gamma\", gamma_seq)\n\nplot_param_sweep(\n  gamma_sweep_df, \"gamma (search volume)\",\n  ref_values = list(list(value = 750, linetype = \"dashed\"),\n                    list(value = default_gamma, linetype = \"dotted\"))\n)\n```\n\n::: {.cell-output-display}\n![](2026-07-10-day-twenty-five_files/figure-html/gamma-sweep-1.png){width=672}\n:::\n:::\n\n\n| $\\gamma$ | catchable fraction |\n|-------|--------------------|\n| 100   | 2.20×10⁻⁵          |\n| 231   | 2.45×10⁻⁴          |\n| 306   | 9.48×10⁻⁵          |\n| 404   | 4.03×10⁻⁴          |\n| 707   | 3.62×10⁻⁴          |\n| 1237  | 3.85×10⁻⁴          |\n| 2162  | 4.18×10⁻⁴          |\n| 3781  | 4.50×10⁻⁴          |\n| 5000  | 4.67×10⁻⁴          |\n\n### kappa\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkappa_seq <- exp(seq(log(0.001), log(1), length.out = 15))\nkappa_sweep_df <- run_param_sweep(\"kappa_override\", kappa_seq) %>%\n  mutate(param = \"kappa\")\n\nplot_param_sweep(\n  kappa_sweep_df, \"kappa (background resource spectrum)\",\n  ref_values = list(list(value = anchovy_kappa, linetype = \"dashed\"),\n                    list(value = default_kappa, linetype = \"dotted\"))\n)\n```\n\n::: {.cell-output-display}\n![](2026-07-10-day-twenty-five_files/figure-html/kappa-sweep-1.png){width=672}\n:::\n:::\n\n\n| $\\kappa$  | catchable fraction |\n|--------|--------------------|\n| 0.0010 | 1.35×10⁻⁶          |\n| 0.0044 | 1.76×10⁻⁵          |\n| 0.0118 | 1.21×10⁻⁴          |\n| 0.0193 | 9.96×10⁻⁵          |\n| 0.0316 | 1.58×10⁻⁴          |\n| 0.0848 | 3.60×10⁻⁴          |\n| 0.2276 | 4.22×10⁻⁴          |\n| 0.6105 | 4.79×10⁻⁴          |\n| 1.0000 | 4.96×10⁻⁴          |\n\n------------------------------------------------------------------------\n\n## What the Sweeps Show\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_sweeps_df <- bind_rows(alpha_sweep_df, gamma_sweep_df, kappa_sweep_df)\n\nsweep_magnitude <- all_sweeps_df %>%\n  filter(is.na(error), catchable_fraction > 0) %>%\n  group_by(param) %>%\n  summarise(\n    min_fraction = min(catchable_fraction),\n    max_fraction = max(catchable_fraction),\n    log10_range  = log10(max_fraction) - log10(min_fraction),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(log10_range))\n\nsweep_magnitude\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  param min_fraction max_fraction log10_range\n  <chr>        <dbl>        <dbl>       <dbl>\n1 alpha     3.25e-28     0.923          27.5 \n2 kappa     1.35e- 6     0.000496        2.56\n3 gamma     2.20e- 5     0.000467        1.33\n```\n\n\n:::\n:::\n\n\n| param | min       | max       | $\\log_{10}$ range |\n|-------|-----------|-----------|-------------|\n| $\\alpha$ | 3.2×10⁻²⁸ | 92.3%     | **27.5**    |\n| $\\kappa$ | 1.4×10⁻⁶  | 4.96×10⁻⁴ | 2.6         |\n| $\\gamma$ | 2.2×10⁻⁵  | 4.67×10⁻⁴ | 1.3         |\n\n$\\alpha$ is confirmed as the dominant lever, and it's a threshold, not a gradual slope. Between $\\alpha = 0.057$ and $\\alpha = 0.28$ the catchable fraction jumps roughly 8 orders of magnitude ($1.1\\times10^{-9} \\to 25.5\\%$). This seems to be a viability threshold for juvenile survivorship, the same qualitative signature as the `capacity_mult` collapse bifurcations from Days 22-24. The anchovy's own $\\alpha = 0.1$ sits right at the foot of that climb (catchable fraction $\\approx 0.02\\%$ there), not in some ordinary low-effect regime , so the real anchovy model is parked right at the edge of the transition, which is a sharper explanation for the extreme pileup than Day 24's two-point swap could give.\n\nGamma is close to flat. the smallest range of the three, confirming Day 24's anchovy-side finding directly rather than just from two points. One thing worth flagging: the point at $\\gamma = 305.8$ ($9.48\\times10^{-5}$) breaks monotonicity, dipping below both neighbours. That matches a pattern this project has seen before (Day 23's scan-rate check, Day 24's Type II wobble), which is critical slowing down near a transition, where `t_run = 600` might not be quite enough to fully settle. It is worth a longer run at that one point before trusting it as a real feature.\n\n$\\kappa$ shows a real but modest, mostly-monotonic effect. It is bigger than gamma's, nowhere close to alpha's.\n\n------------------------------------------------------------------------\n\n## The Time-Delay Predator-Prey Model\n\nDay 24's toy predator-prey model (chemostat prey growth, mass-action Type I predation) has no hysteresis at all. This was both proven analytically (chemostat growth keeps the Jacobian trace negative regardless of the predation term's shape) and confirmed by simulation. The next candidate mechanism, flagged in Day 24's own \"What's Next\": a time delay between a predator eating and that intake showing up as predator growth , a maturation or gestation lag , which is a well-known route to oscillation in delay differential equation (DDE) models that an instantaneous ODE can't produce on its own.\n\n### Setting Up the Delay\n\nThe classical form for this (Wangersky-Cunningham, 1957) keeps predation and prey loss instantaneous, but delays the *conversion* of that predation into new predator biomass by $\\tau$:\n\n$$\n\\begin{aligned}\n\\frac{dN}{dt} &= D(K - N(t)) - aN(t)P(t) \\\\\n\\frac{dP}{dt} &= eaN(t-\\tau)P(t-\\tau) - mP(t)\n\\end{aligned}\n$$\n\nPredator death stays instantaneous, since dying isn't subject to the same conversion lag as being born.\n\n### Working Out the Maths First\n\nThe question is whether adding the delay $\\tau$ can turn the stable fixed point Day 24 found into an unstable one that oscillates instead. That's checked in three steps: find where the fixed point sits, linearise the system around it to see how a small perturbation behaves, then ask what value of $\\tau$ (if any) could flip that perturbation from decaying to growing.\n\n**Step 1 - the equilibrium doesn't move.**\n\nAt a constant solution, $N$ and $P$ aren't changing, so every delayed term is just equal to its own current value ($N(t-\\tau) = N(t)$, and likewise for $P$). That means the delay drops out of the equilibrium condition entirely, and setting both derivatives to zero reproduces exactly Day 24's non-delayed result:\n\n$$\nN^* = \\frac{m}{ea}, \\qquad P^* = \\frac{D(K - N^*)}{aN^*}\n$$\n\nSo $\\tau$ can only change whether this point is *stable*, not where the point itself sits.\n\n**Step 2 - linearise around the equilibrium.**\n\nWrite $N = N^* + n$ and $P = P^* + p$, where $n$ and $p$ are small perturbations, and drop every term of second order or higher in them (the standard move for checking local stability). Using the equilibrium relation $eaN^* = m$ to simplify the result gives:\n\n$$\n\\begin{aligned}\n\\frac{dn}{dt} &= -\\alpha n(t) - \\beta p(t) \\\\\n\\frac{dp}{dt} &= \\gamma n(t-\\tau) + m p(t-\\tau) - m p(t)\n\\end{aligned}\n$$\n\nwhere $\\alpha = D + aP^*$, $\\beta = aN^*$, and $\\gamma = eaP^*$ are just shorthand for the constants that fall out of the substitution.\n\nTrying a solution of the form $n, p \\sim e^{\\lambda t}$ , the standard ansatz for a linear system like this , turns the two differential equations into one algebraic condition on $\\lambda$, the characteristic equation:\n\n$$\n(\\lambda + \\alpha)\\left(\\lambda + m - m e^{-\\lambda\\tau}\\right) + \\beta\\gamma e^{-\\lambda\\tau} = 0\n$$\n\nAs a sanity check before trusting this for $\\tau > 0$: setting $\\tau = 0$ should recover Day 24's own non-delayed result. It does. The equation collapses to $\\lambda^2 + \\alpha\\lambda + \\beta\\gamma = 0$, matching Day 24's $\\text{trace} = -\\alpha$, $\\det = \\beta\\gamma$ exactly.\n\n**Step 3 - ask what a Hopf bifurcation would require.**\n\nA Hopf bifurcation is the specific way a delay can destabilise a fixed point: as $\\tau$ grows from 0, a pair of roots of the characteristic equation crosses from the stable side of the complex plane to the unstable side, passing through the imaginary axis at $\\lambda = i\\omega$. Substituting that in and solving for when a real, positive $\\omega^2$ exists reduces to one inequality:\n\n$$\n\\beta\\gamma > 2m\\alpha \\tag{$*$}\n$$\n\nIf ($*$) can never hold, no crossing is possible at any $\\tau$, and the fixed point stays stable forever. So the whole question comes down to checking the sign of $\\beta\\gamma - 2m\\alpha$.\n\nSubstituting $\\beta = aN^*$ and $\\gamma = eaP^*$, then using $eaN^* = m$ once more to simplify, step by step:\n\n$$\n\\begin{aligned}\n\\beta\\gamma - 2m\\alpha\n    &= a^2eN^*P^* - 2m(D + aP^*)          &&\\text{[substitute $\\beta$, $\\gamma$, $\\alpha$]}\\\\\n    &= aP^*(aeN^*) - 2mD - 2maP^*         &&\\text{[expand the bracket]}\\\\\n    &= aP^*(aeN^* - 2m) - 2mD             &&\\text{[group the $aP^*$ terms]}\\\\\n    &= aP^*(m - 2m) - 2mD                 &&\\text{[$aeN^* = m$, from the equilibrium relation]}\\\\\n    &= -amP^* - 2mD\n\\end{aligned}\n$$\n\nEvery term in that final line , $a$, $m$, $P^*$, $D$ , is strictly positive by construction, so the whole expression is strictly negative, for any choice of these parameters. Condition ($*$) can never hold, which means a Hopf bifurcation is analytically impossible here, for *any* delay and *any* parameter choice.\n\nThat's the same underlying reason Day 24 already ruled out the Type I/II functional-response route: chemostat-style prey growth contributes a fixed restoring force (the $-D$/$-2mD$ term above) that neither a saturating predation term nor a delayed one can get around.\n\n### Checking the Algebra Numerically\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(deSolve)\n\npredator_prey_params_delay <- list(D = 1, a = 1, e = 0.5, m = 0.3, K = 1)\n\ncheck_hopf_feasibility <- function(parms = predator_prey_params_delay) {\n  D <- parms$D; a <- parms$a; e <- parms$e; m <- parms$m; K <- parms$K\n  N_star <- m / (e * a)\n  P_star <- D * (K - N_star) / (a * N_star)\n  alpha  <- D + a * P_star\n  beta   <- a * N_star\n  gamma  <- e * a * P_star\n  data.frame(N_star = N_star, P_star = P_star, alpha = alpha, beta = beta,\n             gamma = gamma, beta_gamma = beta * gamma, two_m_alpha = 2 * m * alpha,\n             hopf_possible = (beta * gamma) > (2 * m * alpha))\n}\n\nhopf_check <- check_hopf_feasibility()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhopf_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  N_star    P_star    alpha beta     gamma beta_gamma two_m_alpha hopf_possible\n1    0.6 0.6666667 1.666667  0.6 0.3333333        0.2           1         FALSE\n```\n\n\n:::\n:::\n\n\n| $N^*$   | $P^*$   | $\\alpha$ | $\\beta$  | $\\gamma$ | $\\beta\\gamma$ | $2m\\alpha$ | Hopf possible? |\n|-------|-------|-------|-------|-------|------------|-----------|----------------|\n| 0.600 | 0.667 | 1.667 | 0.600 | 0.333 | 0.200      | 1.000     | **FALSE**      |\n\n$\\beta\\gamma = 0.2$ against $2m\\alpha = 1.0$. It's not close, and by the derivation above it never can be, for any of these parameters.\n\n### Simulating It Anyway\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredator_prey_rhs_delay <- function(t, state, parms) {\n  N <- max(state[1], 0)\n  P <- max(state[2], 0)\n  D   <- parms[[\"D\"]];   a <- parms[[\"a\"]]; e <- parms[[\"e\"]]\n  m   <- parms[[\"m\"]];   K <- parms[[\"K\"]]; tau <- parms[[\"tau\"]]\n  N0  <- parms[[\"N0\"]]; P0 <- parms[[\"P0\"]]\n\n  if (t <= tau) {\n    lag_N <- N0\n    lag_P <- P0\n  } else {\n    lag   <- lagvalue(t - tau)\n    lag_N <- max(lag[1], 0)\n    lag_P <- max(lag[2], 0)\n  }\n\n  dN <- D * (K - N) - a * N * P\n  dP <- e * a * lag_N * lag_P - m * P\n  list(c(dN, dP))\n}\n\nrun_predator_prey_delay <- function(tau, state0 = c(N = 1, P = 0.1), t_max = 300,\n                                    parms = predator_prey_params_delay) {\n  parms$tau <- tau\n  parms$N0  <- state0[[\"N\"]]\n  parms$P0  <- state0[[\"P\"]]\n  out  <- as.data.frame(dede(y = state0, times = seq(0, t_max, by = 0.1),\n                             func = predator_prey_rhs_delay, parms = parms))\n  late <- out[out$time > t_max * 0.6, ]\n  data.frame(tau = tau, max_N = max(late$N), min_N = min(late$N),\n             max_P = max(late$P), min_P = min(late$P),\n             rel_amplitude_P = (max(late$P) - min(late$P)) / mean(late$P))\n}\n\n# Perturbed well away from equilibrium (N=1 vs N*=0.6, P=0.1 vs P*=0.667) --\n# a system started exactly at a stable fixed point never oscillates\n# regardless of tau, so this is a genuine test of whether delay lets a real\n# perturbation grow into sustained oscillation rather than damping out.\n# tau up to 40, two orders of magnitude past the model's own natural\n# timescales (1/D, 1/m).\ntau_seq <- c(0, 0.5, 1, 2, 5, 10, 20, 40)\n\ndelay_sweep_df <- bind_rows(lapply(tau_seq, run_predator_prey_delay))\n\nprint(delay_sweep_df)\n```\n:::\n\n\n| $\\tau$ | rel. amplitude of P |\n|-----|---------------------|\n| 0   | 1.8×10⁻¹⁰           |\n| 0.5 | 1.6×10⁻⁹            |\n| 1   | 1.1×10⁻⁸            |\n| 2   | 2.4×10⁻⁷            |\n| 5   | 6.7×10⁻⁵            |\n| 10  | 3.9×10⁻³            |\n| 20  | 6.9×10⁻²            |\n| 40  | 0.250               |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(delay_sweep_df, aes(x = tau, y = rel_amplitude_P)) +\n  geom_line(color = \"#55A868\", linewidth = 1) +\n  geom_point(color = \"#55A868\", size = 1.5) +\n  labs(x = \"tau (delay in predator conversion)\", y = \"Relative amplitude of P (settled)\",\n       title = \"Does delay reintroduce the oscillation the instantaneous model doesn't have?\",\n       subtitle = \"Perturbed start (N=1, P=0.1) — analytic prediction: no, for any tau\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-10-day-twenty-five_files/figure-html/delay-amplitude-plot-1.png){width=672}\n:::\n:::\n\n\nRead on its own, that plot looks worrying for the analytic result - amplitude climbing smoothly from near-zero up to 0.25 by $\\tau=40$ looks exactly like a trend heading toward real oscillation. The time series at $\\tau=40$ tells a different story:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlongest_delay_ts <- as.data.frame(dede(\n  y = c(N = 1, P = 0.1),\n  times = seq(0, 300, by = 0.1),\n  func = predator_prey_rhs_delay,\n  parms = modifyList(predator_prey_params_delay, list(tau = 40, N0 = 1, P0 = 0.1))\n))\n\nggplot(longest_delay_ts, aes(x = time)) +\n  geom_line(aes(y = N, color = \"N (prey)\")) +\n  geom_line(aes(y = P, color = \"P (predator)\")) +\n  geom_hline(yintercept = hopf_check$N_star, linetype = \"dotted\", color = \"grey40\") +\n  geom_hline(yintercept = hopf_check$P_star, linetype = \"dotted\", color = \"grey40\") +\n  labs(x = \"Time\", y = \"Biomass\", color = NULL,\n       title = \"Time series at tau = 40 (the longest delay tested)\",\n       subtitle = \"Dotted lines = analytic equilibrium N*, P* — both unchanged by tau, as derived above\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2026-07-10-day-twenty-five_files/figure-html/delay-timeseries-1.png){width=672}\n:::\n:::\n\n\n## What This Shows\n\nBoth $N$ and $P$ move monotonically toward the dotted equilibrium lines for the entire 300 time units. There is no overshoot, no crossing back and forth, none of the up-down-up-down signature a real oscillation would show. What the delay does produce is a visible staircase: distinct steps roughly every 40 time units, matching $\\tau$ itself, since the growth rate is periodically \"informed\" by a signal from exactly $\\tau$ ago. That staircase is a genuine delay effect, but it's a shape imposed on a monotonic approach to equilibrium, not evidence of a limit cycle.\n\nThat reframes the amplitude sweep: `rel_amplitude_P` is climbing with $\\tau$ not because oscillation is building, but because larger delays relax more slowly (the same critical-slowing-down pattern flagged repeatedly elsewhere in this project - Day 18, Day 23's scan-rate check, Day 24's Type II wobble), so the fixed `t_max = 300` / late-window-starts-at-`t > 180` sampling catches the system still mid-approach rather than settled. The \"amplitude\" being measured there is really \"how far an unfinished monotonic relaxation has drifted within the sampling window,\" not a real oscillation's size.\n\nThe maths and the simulation agree: a Hopf bifurcation is impossible for this delayed-conversion model, for any tested delay. Chemostat-style prey growth blocks this route to hysteresis the same way it blocked Type I and Type II functional-response changes on Day 24. The one loose end is methodological rather than substantive: confirming that `rel_amplitude_P` actually decays to $\\sim 0$ at $\\tau=40$ given enough time, rather than plateauing (which the algebra says is impossible, but is worth catching directly rather than assuming), needs a rerun with a much longer `t_max`.\n\n------------------------------------------------------------------------\n\n## What This All Adds Up To\n\nA real range, not two guessed points, and the ranking Day 24 could only sketch out now has actual curves behind it: $\\alpha$ dominant by a wide margin, and not just \"moves a lot\" but sitting on a genuine threshold that the anchovy's own calibration happens to sit right at the foot of. $\\gamma$ and $\\kappa$ are both real but minor by comparison, confirming rather than overturning Day 24's rough read.\n\nThe time-delay predator-prey model closes out a second thread from Day 24's \"What's Next\" on the same day: a full analytic derivation (equilibrium unchanged by $\\tau$, characteristic equation reduces correctly to Day 24's own result at $\\tau=0$, and the Hopf condition $\\beta\\gamma > 2m\\alpha$ reduces via the equilibrium relation to $-am P^* - 2mD$, always negative) proves a Hopf bifurcation is impossible here for any delay, and the simulation backs it up once the amplitude sweep's misleading climb is read correctly against the actual time series.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Pin down alpha's transition window more precisely**, the same way the `capacity_mult` window got refined on Day 24, i.e a denser sweep over roughly $[0.05, 0.3]$ at the same `t_run` to bracket where the steep climb actually starts and ends.\n- **Check whether the gamma = 305.8 dip is real or an under-settled transient**: Rerun just that point (and its neighbours) at a longer `t_run` than 600 to see whether it's critical slowing down near a smaller feature, the same check Day 24 flagged for its own default-species Forward spike.\n- **Confirm `rel_amplitude_P` actually decays to $\\sim 0$ at large tau given enough time**, rather than plateauing. Rerun `tau=40` (and perhaps larger) with a much longer `t_max` than 300. The algebra says a plateau is impossible, which is exactly why it's worth checking directly rather than assuming.\n- **Try a feedback-loop variant of the predator-prey model**, such as switching prey growth from chemostat to logistic ($rN(1-N/K)$), to test whether that is what unlocks mizer's hysteresis. Still open from Day 24, and now the more promising direction given delay and Type II saturation have both been ruled out for the same structural reason.\n- **Fix `save_plot()`'s silently-truncated filenames** as the delay-experiment PNGs saved to disk missing their `.png` extension and (for the longer filename) part of the name itself (`... tau40.png` became `... tau4`), almost certainly a Windows `MAX_PATH` (260-character) limit hit by this project's deeply nested folder path. Worth shortening `save_plot()`'s output filenames or moving `interesting_plots/` closer to the drive root before it silently clips something less recoverable than a plot.\n",
    "supporting": [
      "2026-07-10-day-twenty-five_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}