{
  "hash": "aabd3195667fdba1a43874646a290a36",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 34: Recreating the Anchovy Oscillation, and Does Fishing Actually Ease It?\"\nauthor: \"Samia\"\ndate: \"2026-07-23\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, anchovy, bifurcation-diagram, fishing-schedule, blog]\ndescription: \"Recreates a genuine anchovy limit cycle, then asks whether fishing eases it. Constant effort turns out to dominate everything tested (including a second, effort-side bifurcation that collapses the oscillation outright) but a mean-effort diagnostic built to explain an odd arc in the results reveals why: yield only cares how much you fish, amplitude cares when.\"\n---\n\n## Where Day 33 Left Us\n\nSix levers thrown at cod's calibration all came back flat. There was no genuine limit cycle anywhere, most likely because cod's own parameterisation doesn't sit near an oscillatory regime at all. Day 33 queued up going back to the anchovy parameterisation that *did* oscillate earlier in this project, as a sanity check on the sweep machinery itself. It grew into a bigger question: given a real oscillation, does fishing actually ease it, or just move it around?\n\n------------------------------------------------------------------------\n\n## Recreating the Oscillation\n\nReusing Day 18/20's own anchovy setup below, then sweeping `resource_decrease` directly with the same forward/backward, max/min bifurcation convention every cod sweep since Day 30 has used (40 points, log-spaced 0.0001-0.5, `tr_bdf2`, warm-started):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer); library(dplyr); library(tidyverse); library(ggplot2)\n\nmake_params <- function(lambda = 2.05, resource_decrease = 0.001, balance = TRUE) {\n  a0 <- 100; kappa <- a0 * exp(-6.9 * (lambda - 1))\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\", w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = round(log(66.5 / 0.0003) / 0.1), lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n  r <- getResourceRate(params) * resource_decrease\n  setResource(params, resource_rate = r, resource_dynamics = \"resource_semichemostat\", balance = balance)\n}\n\nmake_fishing_params <- function(resource_decrease = 0.001) {\n  p  <- make_params(resource_decrease = resource_decrease)\n  gp <- p@gear_params\n  gp$sel_func <- \"knife_edge\"; gp$knife_edge_size <- p@species_params$w_mat; gp$catchability <- 1\n  gear_params(p) <- gp\n  p\n}\n```\n:::\n\n\nThe actual sweep: forward and backward passes across `resource_decrease`, warm-started (every point after the first inherits the previous point's own final `(n, n_pp)` state), recording max and min biomass separately in a late window rather than collapsing straight to a single amplitude number. Branches that fan apart mean a real limit cycle, branches that collapse onto one curve mean a fixed point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_bifurcation_sweep_rd <- function(rd_seq, params_fn, effort, metric_fn,\n                                     t_run = 300, lambda = 2.05) {\n  run_one_direction <- function(seq_vals, init_n = NULL, init_n_pp = NULL) {\n    out       <- data.frame(value = seq_vals, max_metric = NA_real_, min_metric = NA_real_)\n    state_n   <- init_n\n    state_npp <- init_n_pp\n\n    for (i in seq_along(seq_vals)) {\n      p <- params_fn(lambda = lambda, resource_decrease = seq_vals[i])\n      if (!is.null(state_n)) {\n        p@initial_n[]    <- state_n\n        p@initial_n_pp[] <- state_npp\n      }\n\n      result <- tryCatch({\n        sim  <- project(p, t_max = t_run, dt = 0.1, t_save = 0.5,\n                        progress_bar = FALSE, effort = effort, method = \"tr_bdf2\")\n        mv   <- metric_fn(sim)\n        tv   <- as.numeric(names(mv))\n        late <- mv[tv > t_run * 0.6]\n        last <- dim(sim@n)[1]\n        list(max_metric = max(late), min_metric = min(late), error = NA_character_,\n            n = sim@n[last, , ], npp = sim@n_pp[last, ])\n      }, error = function(e) {\n        list(max_metric = NA_real_, min_metric = NA_real_, error = conditionMessage(e),\n            n = state_n, npp = state_npp)\n      })\n\n      if (!is.na(result$error)) {\n        warning(sprintf(\"resource_decrease=%.5g: %s\", seq_vals[i], result$error))\n      }\n\n      state_n   <- result$n\n      state_npp <- result$npp\n      out$max_metric[i] <- result$max_metric\n      out$min_metric[i] <- result$min_metric\n    }\n    list(df = out, n_final = state_n, npp_final = state_npp)\n  }\n\n  fwd    <- run_one_direction(rd_seq)\n  bwd    <- run_one_direction(rev(rd_seq), init_n = fwd$n_final, init_n_pp = fwd$npp_final)\n  bwd_df <- bwd$df[order(bwd$df$value), ]\n\n  bind_rows(\n    data.frame(value = fwd$df$value, metric = fwd$df$max_metric, direction = \"Forward\",  branch = \"max\"),\n    data.frame(value = fwd$df$value, metric = fwd$df$min_metric, direction = \"Forward\",  branch = \"min\"),\n    data.frame(value = bwd_df$value, metric = bwd_df$max_metric, direction = \"Backward\", branch = \"max\"),\n    data.frame(value = bwd_df$value, metric = bwd_df$min_metric, direction = \"Backward\", branch = \"min\")\n  )\n}\n\nplot_bifurcation_rd <- function(df, y_label, title, subtitle = NULL) {\n  ggplot(df, aes(x = value, y = metric, color = direction, linetype = branch)) +\n    geom_line(linewidth = 1) +\n    geom_point(size = 1.2) +\n    scale_x_log10() +\n    labs(x = \"resource_decrease\", y = y_label, title = title, subtitle = subtitle) +\n    theme_minimal()\n}\n\n# Log-spaced, 0.0001 to 0.5 -- same range Day 20 used\nrd_seq_bif <- exp(seq(log(0.0001), log(0.5), length.out = 40))\n\nbif_biomass_df <- run_bifurcation_sweep_rd(\n  rd_seq_bif, params_fn = make_params, effort = 0, t_run = 300,\n  metric_fn = function(sim) getBiomass(sim)[, \"Anchovy\"]\n)\n\nbif_biomass_plot <- plot_bifurcation_rd(\n  bif_biomass_df, \"Biomass\",\n  \"Anchovy bifurcation diagram: biomass vs. resource_decrease\",\n  \"effort=0 (unfished), swept forward and backward, log-spaced 0.0001-0.5 -- branches collapsing onto one curve = fixed point, fanning apart = limit cycle\"\n)\nbif_biomass_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/bifurcation-sweep-function-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## What the sweep found\n\n- **A real, sharp bifurcation around `resource_decrease` ≈ 0.012-0.015:** Below it, forward/backward branches fan apart into genuine oscillation (`rel_amplitude` up to \\~1.7); above it, `rel_amplitude` collapses to numerical noise and stays there to 0.5. Confirms the sweep machinery that read flat six times against cod actually detects a real cycle when one exists.\n- **Biomass is pinned at exactly 0.0869 across the entire non-oscillating half of the range:** `resource_decrease` only scales the resource's replenishment *rate*, not its *capacity*, so past some rate the resource just sits at capacity regardless.\n:::\n\n------------------------------------------------------------------------\n\n## Fishing Only at Peaks vs. Only at Troughs\n\nThe project's central question, applied to a genuine limit cycle for the first time: does fishing relieve the \"jam,\" or worsen it, depending on *when* in the cycle it happens?\n\nOne real bug caught along the way: the first version forked into peaks-only/troughs-only/constant branches at `t = 300`, but the oscillation doesn't actually settle into a regular cycle until roughly `t = 400,` so that both the detected events and the state every branch continued from were contaminated by a still-settling transient. Fixed by pushing the fork out to `t = 500`.\n\nSettle-and-kick recipe reused unchanged from Day 18/20 (10yr unfished settle, then a 1000x knock-down of the mature `w` range at `t = 10`, then run forward), then a fork at `t = t_fork` that peaks/troughs are detected off of, followed by peaks-only/troughs-only/constant branches all sharing that same pre-fork state:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_limit_cycle_sim <- function(params, t_total = 600, effort = 0, perturbation = 1e3) {\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim_init <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0,\n                      method = \"tr_bdf2\")\n  idx  <- params@w >= 10 & params@w <= 100\n  last <- dim(sim_init@n)[1]\n  sim_init@n[last, , idx] <- sim_init@n[last, , idx] / perturbation\n\n  project(sim_init, t_max = t_total - 10, dt = 0.1, t_save = 0.2,\n          progress_bar = FALSE, effort = effort,\n          method = \"tr_bdf2\")\n}\n\nrun_focus_yield_comparison <- function(resource_decrease, window, fish_level, regime_label,\n                                       t_fork, post_fork_years, summary_window,\n                                       schedules = c(\"Peaks only\", \"Troughs only\", \"Constant\")) {\n  p_focus   <- make_fishing_params(resource_decrease = resource_decrease)\n  gp_focus  <- gear_params(p_focus)\n  gear_name <- gp_focus$gear[gp_focus$species == \"Anchovy\"][1]\n\n  sim_fork <- make_limit_cycle_sim(p_focus, t_total = t_fork, effort = 0)\n  sim_ref  <- project(sim_fork, t_max = post_fork_years, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n\n  all_times <- as.numeric(dimnames(sim_ref@n)[[1]])\n  keep      <- all_times >= t_fork\n  t_p       <- all_times[keep]\n  time_lbls <- dimnames(sim_ref@n)[[1]][keep]\n\n  needs_events <- any(c(\"Peaks only\", \"Troughs only\") %in% schedules)\n  peak_times   <- numeric(0)\n  trough_times <- numeric(0)\n\n  if (needs_events) {\n    # Local maxima/minima of the regular (t >= t_fork) unfished biomass trajectory.\n    bm <- getBiomass(sim_ref)[, \"Anchovy\"][time_lbls]\n    n  <- length(bm)\n\n    is_peak   <- logical(n)\n    is_trough <- logical(n)\n    is_peak[2:(n - 1)]   <- bm[2:(n - 1)] > bm[1:(n - 2)] & bm[2:(n - 1)] > bm[3:n]\n    is_trough[2:(n - 1)] <- bm[2:(n - 1)] < bm[1:(n - 2)] & bm[2:(n - 1)] < bm[3:n]\n\n    peak_times   <- t_p[is_peak]\n    trough_times <- t_p[is_trough]\n  }\n\n  build_schedule <- function(event_times) {\n    ev <- rep(0, length(t_p))\n    for (et in event_times) {\n      ev[t_p >= et - window / 2 & t_p <= et + window / 2] <- fish_level\n    }\n    matrix(ev, ncol = 1, dimnames = list(time_lbls, gear_name))\n  }\n\n  sims <- list()\n  if (\"Peaks only\" %in% schedules) {\n    sims[[\"Peaks only\"]] <- project(sim_fork, t_max = post_fork_years, dt = 0.1, t_save = 0.2,\n                                    progress_bar = FALSE, effort = build_schedule(peak_times),\n                                    method = \"tr_bdf2\")\n  }\n  if (\"Troughs only\" %in% schedules) {\n    sims[[\"Troughs only\"]] <- project(sim_fork, t_max = post_fork_years, dt = 0.1, t_save = 0.2,\n                                      progress_bar = FALSE, effort = build_schedule(trough_times),\n                                      method = \"tr_bdf2\")\n  }\n  if (\"Constant\" %in% schedules) {\n    sims[[\"Constant\"]] <- project(sim_fork, t_max = post_fork_years, dt = 0.1, t_save = 0.2,\n                                  progress_bar = FALSE, effort = fish_level, method = \"tr_bdf2\")\n  }\n\n  sim_to_df <- function(metric_fn, value_name) {\n    bind_rows(lapply(names(sims), function(nm) {\n      v <- metric_fn(sims[[nm]])\n      setNames(data.frame(as.numeric(dimnames(sims[[nm]]@n)[[1]]), v, nm),\n              c(\"time\", value_name, \"schedule\"))\n    }))\n  }\n\n  biomass_df <- bind_rows(\n    data.frame(time = as.numeric(dimnames(sim_ref@n)[[1]]),\n              biomass = getBiomass(sim_ref)[, \"Anchovy\"], schedule = \"Unfished reference\"),\n    sim_to_df(function(s) getBiomass(s)[, \"Anchovy\"], \"biomass\")\n  ) %>% filter(time >= t_fork) %>% mutate(regime = regime_label)\n\n  yield_df <- sim_to_df(function(s) getYield(s)[, \"Anchovy\"], \"yield\") %>%\n    filter(time >= t_fork) %>% mutate(regime = regime_label)\n\n  summary_t_cut <- t_fork + post_fork_years - summary_window\n  summary_df <- yield_df %>%\n    filter(time > summary_t_cut) %>%\n    group_by(schedule) %>%\n    summarise(mean_yield = mean(yield), .groups = \"drop\") %>%\n    mutate(regime = regime_label, n_peaks = length(peak_times), n_troughs = length(trough_times))\n\n  list(biomass_df = biomass_df, yield_df = yield_df, summary_df = summary_df,\n      peak_times = peak_times, trough_times = trough_times)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwindow          <- 3\nfish_level      <- 0.5\nt_fork          <- 500\npost_fork_years <- 300\nsummary_window  <- 50\nrd_focus        <- 0.005\n\ncomparison_oscillating <- run_focus_yield_comparison(\n  rd_focus, window, fish_level, regime_label = \"Oscillating (resource_decrease=0.005)\",\n  t_fork = t_fork, post_fork_years = post_fork_years, summary_window = summary_window\n)\n\nsummary_t_cut <- t_fork + post_fork_years - summary_window\n\n# rel_amplitude of biomass itself, per schedule, over the settled t>summary_t_cut window\nosc_amplitude_df <- comparison_oscillating$biomass_df %>%\n  filter(schedule %in% c(\"Unfished reference\", \"Constant\", \"Peaks only\", \"Troughs only\"),\n        time > summary_t_cut) %>%\n  group_by(schedule) %>%\n  summarise(\n    max_biomass   = max(biomass), min_biomass = min(biomass),\n    rel_amplitude = (max_biomass - min_biomass) / ((max_biomass + min_biomass) / 2),\n    .groups = \"drop\"\n  )\nosc_amplitude_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  schedule           max_biomass min_biomass rel_amplitude\n  <chr>                    <dbl>       <dbl>         <dbl>\n1 Constant                 0.105      0.0498         0.714\n2 Peaks only               0.111      0.0460         0.831\n3 Troughs only             0.110      0.0501         0.749\n4 Unfished reference       0.112      0.0493         0.779\n```\n\n\n:::\n:::\n\n\nAgainst a real baseline (the unfished reference, `rel_amplitude = 0.779`), at `resource_decrease = 0.005`:\n\n| Schedule     | rel_amplitude | vs. unfished             |\n|--------------|---------------|--------------------------|\n| Constant     | 0.714         | eases it, -8.3%          |\n| Troughs only | 0.749         | eases it slightly, -3.9% |\n| Peaks only   | 0.831         | **worsens it, +6.7%**    |\n\nA 6x5 `window`/`fish_level` scan settled it further. The settle-and-detect step (expensive, independent of `window`/`fish_level`) runs once; only the post-fork branches repeat per grid point, and `mean_effort`, the time-averaged effort actually applied, whatever its timing, is recorded per point for later use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_window_effort_scan <- function(resource_decrease, fish_level_seq, t_fork,\n                                   scan_post_fork_years, scan_summary_window,\n                                   window_seq = NULL,\n                                   schedules = c(\"Peaks only\", \"Troughs only\", \"Constant\")) {\n  scan_t_cut <- t_fork + scan_post_fork_years - scan_summary_window\n\n  p_scan    <- make_fishing_params(resource_decrease = resource_decrease)\n  gp_scan   <- gear_params(p_scan)\n  gear_name <- gp_scan$gear[gp_scan$species == \"Anchovy\"][1]\n\n  sim_fork <- make_limit_cycle_sim(p_scan, t_total = t_fork, effort = 0)\n\n  needs_events <- any(c(\"Peaks only\", \"Troughs only\") %in% schedules) && !is.null(window_seq)\n  peak_times   <- numeric(0)\n  trough_times <- numeric(0)\n\n  if (needs_events) {\n    sim_ref <- project(sim_fork, t_max = scan_post_fork_years, dt = 0.1, t_save = 0.2,\n                       progress_bar = FALSE, effort = 0, method = \"tr_bdf2\")\n\n    all_times <- as.numeric(dimnames(sim_ref@n)[[1]])\n    keep      <- all_times >= t_fork\n    t_p       <- all_times[keep]\n    time_lbls <- dimnames(sim_ref@n)[[1]][keep]\n\n    bm <- getBiomass(sim_ref)[, \"Anchovy\"][time_lbls]\n    n  <- length(bm)\n    is_peak   <- logical(n)\n    is_trough <- logical(n)\n    is_peak[2:(n - 1)]   <- bm[2:(n - 1)] > bm[1:(n - 2)] & bm[2:(n - 1)] > bm[3:n]\n    is_trough[2:(n - 1)] <- bm[2:(n - 1)] < bm[1:(n - 2)] & bm[2:(n - 1)] < bm[3:n]\n    peak_times   <- t_p[is_peak]\n    trough_times <- t_p[is_trough]\n\n    build_schedule <- function(event_times, window, fish_level) {\n      ev <- rep(0, length(t_p))\n      for (et in event_times) {\n        ev[t_p >= et - window / 2 & t_p <= et + window / 2] <- fish_level\n      }\n      matrix(ev, ncol = 1, dimnames = list(time_lbls, gear_name))\n    }\n  }\n\n  scan_metrics <- function(sim) {\n    bmv <- getBiomass(sim)[, \"Anchovy\"]\n    ylv <- getYield(sim)[, \"Anchovy\"]\n    tv  <- as.numeric(names(bmv))\n    bm_late <- bmv[tv > scan_t_cut]\n    yl_late <- ylv[tv > scan_t_cut]\n    data.frame(\n      rel_amplitude = (max(bm_late) - min(bm_late)) / ((max(bm_late) + min(bm_late)) / 2),\n      mean_yield    = mean(yl_late)\n    )\n  }\n\n  out <- list()\n\n  if (\"Constant\" %in% schedules) {\n    out$constant <- bind_rows(lapply(fish_level_seq, function(fl) {\n      sim <- project(sim_fork, t_max = scan_post_fork_years, dt = 0.1, t_save = 0.2,\n                    progress_bar = FALSE, effort = fl, method = \"tr_bdf2\")\n      cbind(scan_metrics(sim), window = NA_real_, fish_level = fl, schedule = \"Constant\",\n           mean_effort = fl)\n    }))\n  }\n\n  if (needs_events) {\n    out$events <- bind_rows(lapply(fish_level_seq, function(fl) {\n      bind_rows(lapply(window_seq, function(w) {\n        rows <- list()\n        if (\"Peaks only\" %in% schedules) {\n          effort_p <- build_schedule(peak_times, w, fl)\n          sim_p <- project(sim_fork, t_max = scan_post_fork_years, dt = 0.1, t_save = 0.2,\n                           progress_bar = FALSE, effort = effort_p, method = \"tr_bdf2\")\n          rows$peaks <- cbind(scan_metrics(sim_p), window = w, fish_level = fl, schedule = \"Peaks only\",\n                              mean_effort = mean(effort_p))\n        }\n        if (\"Troughs only\" %in% schedules) {\n          effort_t <- build_schedule(trough_times, w, fl)\n          sim_t <- project(sim_fork, t_max = scan_post_fork_years, dt = 0.1, t_save = 0.2,\n                           progress_bar = FALSE, effort = effort_t, method = \"tr_bdf2\")\n          rows$troughs <- cbind(scan_metrics(sim_t), window = w, fish_level = fl, schedule = \"Troughs only\",\n                                mean_effort = mean(effort_t))\n        }\n        bind_rows(rows)\n      }))\n    }))\n  }\n\n  bind_rows(out) %>%\n    mutate(resource_decrease = resource_decrease, n_peaks = length(peak_times), n_troughs = length(trough_times))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwindow_seq     <- seq(0.5, 3, by = 0.5)\nfish_level_seq <- seq(0.2, 1, by = 0.2)\n\nscan_df <- run_window_effort_scan(\n  rd_focus, fish_level_seq = fish_level_seq, window_seq = window_seq,\n  t_fork = t_fork, scan_post_fork_years = 100, scan_summary_window = 30\n)\n\n# Best available combinations: event-triggered points at or below Constant's\n# own median amplitude, ranked by yield.\nconstant_scan_df <- scan_df %>% filter(schedule == \"Constant\")\nconstant_median_amplitude <- median(constant_scan_df$rel_amplitude)\n\nevent_scan_df <- scan_df %>% filter(schedule != \"Constant\")\n\namplitude_heatmap <- ggplot(event_scan_df, aes(x = window, y = fish_level, fill = rel_amplitude)) +\n  geom_tile() +\n  facet_wrap(~schedule) +\n  scale_fill_viridis_c() +\n  labs(x = \"Window (years either side of event)\", y = \"fish_level (effort)\",\n       fill = \"Relative\\namplitude\",\n       title = \"Oscillation amplitude across window x fish_level\",\n       subtitle = sprintf(\"resource_decrease=%.4g -- darker = lower amplitude = more eased\", rd_focus)) +\n  theme_minimal()\namplitude_heatmap\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/window-effort-scan-run-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntradeoff_plot <- ggplot(scan_df, aes(x = rel_amplitude, y = mean_yield, color = schedule, size = fish_level)) +\n  geom_point(alpha = 0.7) +\n  labs(x = \"Relative amplitude of biomass (lower = more eased)\",\n       y = \"Mean yield (higher = better)\",\n       title = \"Amplitude vs. yield trade-off across the window x fish_level scan\",\n       subtitle = sprintf(\"resource_decrease=%.4g -- ideal points sit toward the top-left; point size = fish_level\", rd_focus)) +\n  theme_minimal()\ntradeoff_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/window-effort-scan-run-2.png){width=672}\n:::\n:::\n\n\n**Constant dominates outright**, improving on both amplitude and yield together with no trade-off. Peaks-only has a genuine resonance-like hot spot (moderate window + high effort actively pumps the cycle, worse than not fishing at all); Troughs-only never does this, but still never beats Constant.\n\n------------------------------------------------------------------------\n\n## Pushing Constant Effort Further\n\nConstant was still improving on both axes at the top of the range tested (`fish_level = 1`). Extending the constant-effort scan out to `fish_level = 4` (same settle recipe, `schedules = \"Constant\"` so it skips peak/trough detection entirely) finds something new:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfish_level_seq_constant_ext <- seq(0.2, 4, by = 0.2)\n\nconstant_ext_df <- run_window_effort_scan(\n  rd_focus, fish_level_seq = fish_level_seq_constant_ext,\n  t_fork = t_fork, scan_post_fork_years = 100, scan_summary_window = 30,\n  schedules = \"Constant\"\n)\n\nconstant_ext_long <- bind_rows(\n  data.frame(fish_level = constant_ext_df$fish_level, value = constant_ext_df$rel_amplitude, metric = \"Relative amplitude\"),\n  data.frame(fish_level = constant_ext_df$fish_level, value = constant_ext_df$mean_yield,   metric = \"Mean yield\")\n)\n\nconstant_ext_plot <- ggplot(constant_ext_long, aes(x = fish_level, y = value)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  geom_point(size = 1.5, color = \"steelblue\") +\n  facet_wrap(~metric, scales = \"free_y\") +\n  labs(x = \"fish_level (constant effort)\", y = NULL,\n       title = \"Constant fishing: amplitude and yield across a wider effort range\",\n       subtitle = sprintf(\"resource_decrease=%.4g -- does the amplitude-down/yield-up trend from fish_level<=1 continue, plateau, or reverse?\", rd_focus)) +\n  theme_minimal()\nconstant_ext_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/constant-extended-scan-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## A second bifurcation, on the effort axis this time\n\nAmplitude doesn't just ease gradually, it **collapses**: 0.76 at `fish_level=0.2` down through a steep fall between 1.2 and 2.2, to essentially zero by 2.2 and flat there to 4.0. Sufficiently hard constant fishing doesn't just dampen the cycle - it appears to eliminate it outright, pushing the population back to a fixed point from the *effort* side, mirroring Section 1's own resource-side bifurcation.\n\nYield, meanwhile, keeps climbing the entire way to `fish_level=4` (8x baseline) with no turnover. The shape is concave, diminishing returns visibly setting in, but no peak found in this range.\n:::\n\n------------------------------------------------------------------------\n\n## Does the Pattern Hold Across resource_decrease? (And a Correction)\n\nA densified scan (12 `resource_decrease` values, log-spaced 0.0005-0.011, coarse 3x3 window/effort grid at each) pins the amplitude crossover precisely: `resource_decrease = 0.00357` to `0.00473`. Below that, event-triggered fishing has *some* foothold on amplitude; above it, Constant wins outright everywhere.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrd_scan_seq <- exp(seq(log(0.0005), log(0.011), length.out = 12))\n\nwindow_seq_coarse     <- c(0.5, 1.5, 3)\nfish_level_seq_coarse <- c(0.2, 0.6, 1)\n\nrd_scan_df <- bind_rows(lapply(rd_scan_seq, function(rd) {\n  run_window_effort_scan(\n    rd, fish_level_seq = fish_level_seq_coarse, window_seq = window_seq_coarse,\n    t_fork = t_fork, scan_post_fork_years = 100, scan_summary_window = 30\n  )\n}))\n\nrd_scan_tradeoff_plot <- ggplot(rd_scan_df, aes(x = rel_amplitude, y = mean_yield, color = schedule, size = fish_level)) +\n  geom_point(alpha = 0.7) +\n  facet_wrap(~sprintf(\"resource_decrease=%.4g\", resource_decrease), scales = \"free\", ncol = 4) +\n  labs(x = \"Relative amplitude of biomass (lower = more eased)\",\n       y = \"Mean yield (higher = better)\",\n       title = \"Amplitude vs. yield trade-off across resource_decrease\",\n       subtitle = \"Coarse 3x3 window x fish_level grid at each resource_decrease -- does Constant stay dominant everywhere?\") +\n  theme_minimal()\nrd_scan_tradeoff_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/rd-densified-scan-1.png){width=1536}\n:::\n\n```{.r .cell-code}\n# The direct generalisation check: for each resource_decrease, does ANY\n# event-triggered point beat Constant's own best on amplitude, and separately\n# on yield?\nrd_scan_verdict <- rd_scan_df %>%\n  group_by(resource_decrease) %>%\n  summarise(\n    constant_best_amplitude = min(rel_amplitude[schedule == \"Constant\"]),\n    constant_best_yield     = max(mean_yield[schedule == \"Constant\"]),\n    any_event_beats_constant_amplitude = any(rel_amplitude[schedule != \"Constant\"] < constant_best_amplitude),\n    any_event_beats_constant_yield     = any(mean_yield[schedule != \"Constant\"] > constant_best_yield),\n    .groups = \"drop\"\n  )\nrd_scan_verdict\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 5\n   resource_decrease constant_best_amplitude constant_best_yield\n               <dbl>                   <dbl>               <dbl>\n 1          0.0005                 1.68                0.0000380\n 2          0.000662               1.65                0.0000408\n 3          0.000877               1.61                0.0000391\n 4          0.00116                1.55                0.0000365\n 5          0.00154                1.47                0.0000357\n 6          0.00204                1.35                0.0000329\n 7          0.00270                1.19                0.0000318\n 8          0.00357                0.972               0.0000309\n 9          0.00473                0.657               0.0000289\n10          0.00627                0.284               0.0000286\n11          0.00831                0.00983             0.0000281\n12          0.0110                 0.0000280           0.0000278\n# ℹ 2 more variables: any_event_beats_constant_amplitude <lgl>,\n#   any_event_beats_constant_yield <lgl>\n```\n\n\n:::\n:::\n\n\nThe interesting part is what happened when the two amplitude \"wins\" at the bottom of that range got rechecked with Section 3's own longer, more careful settle (`post_fork_years=300` vs. the scan's `100`) instead of trusted at face value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nverify_points <- data.frame(\n  resource_decrease = c(0.001, 0.0025),\n  window             = c(0.5, 3),\n  fish_level         = c(0.6, 0.6)\n)\n\nverify_df <- bind_rows(lapply(seq_len(nrow(verify_points)), function(i) {\n  rd <- verify_points$resource_decrease[i]\n  w  <- verify_points$window[i]\n  fl <- verify_points$fish_level[i]\n\n  comparison <- run_focus_yield_comparison(\n    rd, window = w, fish_level = fl, regime_label = sprintf(\"resource_decrease=%.4g\", rd),\n    t_fork = t_fork, post_fork_years = post_fork_years, summary_window = summary_window\n  )\n\n  comparison$biomass_df %>%\n    filter(time > summary_t_cut) %>%\n    group_by(schedule) %>%\n    summarise(\n      max_biomass   = max(biomass), min_biomass = min(biomass),\n      rel_amplitude = (max_biomass - min_biomass) / ((max_biomass + min_biomass) / 2),\n      .groups = \"drop\"\n    ) %>%\n    mutate(resource_decrease = rd, window = w, fish_level = fl)\n}))\n\nverify_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 7\n  schedule        max_biomass min_biomass rel_amplitude resource_decrease window\n  <chr>                 <dbl>       <dbl>         <dbl>             <dbl>  <dbl>\n1 Constant              0.198      0.0214          1.61            0.001     0.5\n2 Peaks only            0.195      0.0226          1.58            0.001     0.5\n3 Troughs only          0.190      0.0197          1.62            0.001     0.5\n4 Unfished refer…       0.183      0.0237          1.54            0.001     0.5\n5 Constant              0.139      0.0308          1.27            0.0025    3  \n6 Peaks only            0.127      0.0312          1.21            0.0025    3  \n7 Troughs only          0.131      0.0336          1.18            0.0025    3  \n8 Unfished refer…       0.134      0.0319          1.23            0.0025    3  \n# ℹ 1 more variable: fish_level <dbl>\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## The coarse scan wasn't just imprecise - it was wrong about *which* schedule wins\n\n- **At `resource_decrease = 0.001`**: Peaks-only still beats Constant (1.584 vs. 1.610). But the *unfished* reference is 1.542, lower than both. Neither fished schedule actually eases anything here; Constant is worse by 4.4%, Peaks-only \"only\" 2.7%. Peaks-only isn't easing the oscillation, it's just losing least.\n- **At `resource_decrease = 0.0025`**: the coarse scan flagged Peaks-only as the winner. Under the careful methodology, **Troughs-only wins instead** (1.182 vs. Peaks-only's 1.211 and Constant's 1.275), and both beat the unfished baseline here. The short scan didn't just get the margin wrong, it named the wrong schedule.\n:::\n\nLesson: the amplitude-beats-Constant phenomenon below `resource_decrease ≈ 0.004` is real, but a coarse scan can't be trusted to say *which* strategy is responsible for it, only that something is going on worth rechecking properly.\n\n------------------------------------------------------------------------\n\n## The Circle in the Trade-off Plot\n\nThe amplitude-vs-yield scatter, faceted across all twelve `resource_decrease` values, had a visible structure: points tracing an arc rather than scattering randomly, suggestive of one hidden variable driving both axes rather than `window` and `fish_level` acting independently. `mean_effort`, the time-averaged effort actually applied, however it's distributed in time, already recorded per point by `run_window_effort_scan()` above, is the natural thing to test that against: plot `rel_amplitude` and `mean_yield` each directly against `mean_effort`, faceted by `resource_decrease`, colored by schedule, instead of against each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_effort_amplitude_plot <- ggplot(rd_scan_df, aes(x = mean_effort, y = rel_amplitude, color = schedule)) +\n  geom_point(alpha = 0.6) +\n  facet_wrap(~sprintf(\"resource_decrease=%.4g\", resource_decrease), ncol = 4, scales = \"free\") +\n  labs(x = \"Mean effort actually applied over the post-fork run\",\n       y = \"Relative amplitude of biomass\",\n       title = \"Amplitude vs. mean effort actually applied -- one curve, or separate by schedule?\",\n       subtitle = \"Peaks-only/Troughs-only points overlapping Constant's own curve here would mean window/fish_level only matter through how much they raise mean effort\") +\n  theme_minimal()\nmean_effort_amplitude_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/mean-effort-plots-1.png){width=1536}\n:::\n\n```{.r .cell-code}\nmean_effort_yield_plot <- ggplot(rd_scan_df, aes(x = mean_effort, y = mean_yield, color = schedule)) +\n  geom_point(alpha = 0.6) +\n  facet_wrap(~sprintf(\"resource_decrease=%.4g\", resource_decrease), ncol = 4, scales = \"free\") +\n  labs(x = \"Mean effort actually applied over the post-fork run\",\n       y = \"Mean yield\",\n       title = \"Yield vs. mean effort actually applied -- one curve, or separate by schedule?\",\n       subtitle = \"Same test as the amplitude version above, applied to yield\") +\n  theme_minimal()\nmean_effort_yield_plot\n```\n\n::: {.cell-output-display}\n![](2026-07-23-day-thirty-four_files/figure-html/mean-effort-plots-2.png){width=1536}\n:::\n:::\n\n\n::: callout-note\n## Yield collapses onto one curve. Amplitude does not.\n\n- **Yield**: Constant, Peaks-only, and Troughs-only all sit on the *same* tight, near-linear curve against `mean_effort`, in every panel. Total catch is essentially indifferent to *when* the effort lands but cares only about how much of it there is on average.\n- **Amplitude**: no such collapse. At low `resource_decrease` there's real scatter (window's specific value matters, not just its average effort). At higher `resource_decrease`, the separation is stark: Constant sits on a visibly lower curve than either event-triggered schedule, for the *same or even less* average effort.\n:::\n\nThat resolves the circle: yield is pinned to a single curve in one variable, while amplitude depends on *two* - effort and timing. Varying window and fish_level slides points along yield's fixed backbone while fanning them out vertically in amplitude by schedule, which is exactly the \"one axis pinned, one forking\" shape that reads as an arc.\n\nIt also sharpens the whole day into one sentence: **fishing's effect on yield is timing-indifferent (you get what your average effort buys you) but its effect on easing the oscillation is not, and spreading effort evenly beats concentrating it in bursts by a widening margin the closer the system sits to its own bifurcation boundary.**\n\n------------------------------------------------------------------------\n\n## What's Next\n\n1.  **Rerun the `resource_decrease = 0.0005`, Peaks-only yield \"win\" through Section 3's careful methodology** (`t_fork = 500`, `post_fork_years = 300`, `summary_window = 50`) before trusting it. The two amplitude wins that got this same recheck both flipped or lost their margin, and this yield claim has had no recheck at all yet, so it's next in line, not a nice-to-have.\n2.  **Load the calibrated cod params and rerun the `mean_effort` diagnostic (Section 4d's two plots) against it.** If yield still collapses onto one curve regardless of schedule there too, that's a general mizer result worth stating as one; if it doesn't, that's just as informative, since it would mean anchovy's collapse was a feature of this particular calibration and not fishing dynamics in general.\n3.  **Extend the constant-effort scan past `fish_level = 4`**, in `fish_level` steps of 1 up to at least 8, and check specifically whether yield actually turns over or keeps climbing indefinitely, since the current data only shows it still climbing at the edge of the range tested.\n",
    "supporting": [
      "2026-07-23-day-thirty-four_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}