{
  "hash": "4201c94872af18268a3320c8f9d011aa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 16: The Unstable Fixed Point, the Limit-Cycle Advantage, and What Fishing Does to It\"\nauthor: \"Samia\"\ndate: \"2026-06-29\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, steady-state, bifurcation, limit-cycle, newton-solver, fishing, peak-fishing, blog]\ndescription: \"Predictor-corrector integrator shows limit-cycle biomass is ~1.23× the unstable fixed point at λ=2.0 (vs ~1.94× from Euler); bifurcation occurs at λ≈2.08, with the advantage ranging from ~1.28 at λ=1.925 to zero at λ≥2.1. The limit cycle is a cohort wave (2.5× recruits, 0.5× juveniles, 1.5× large adults), persists under all tested fishing effort (0–0.5), and mean biomass drops only 6% while yield scales linearly with no collapse threshold.\"\n---\n\n## Where Day 15 Left Us\n\nThe \"What's Next\" section of Days 14–15 flagged a concrete question raised by Gustav: at the bifurcation from a stable fixed point to a limit cycle, does productivity decrease? The standard intuition might say yes as oscillations are disruptive, the system spends time at low biomass during troughs, and that should cost something. The question was whether the numbers bore that out.\n\nAnswering it required finding the unstable fixed point that the oscillating system orbits around, which ordinary time-integration never converges to. Gustav also flagged to me that the dev version of mizer includes a new function `steadyNewton()` that solves the steady-state equation directly via a Newton solver, independent of stability. Today was spent testing it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Setting Up\n\nAll the experiments below use a single helper that builds the standard single-species Anchovy params:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_params <- function(lambda = 2.05, resource_decrease = 0.001) {\n  a0    <- 100\n  kappa <- a0 * exp(-6.9 * (lambda - 1))\n  no_w  <- round(log(66.5 / 0.0003) / 0.1)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = 0.0003, w_max = 66.5, w_mat = 10,\n    no_w = no_w, lambda = lambda, kappa = kappa,\n    alpha = 0.1, gamma = 750, ks = 0\n  )\n  r      <- getResourceRate(params) * resource_decrease\n  params <- setResource(params, resource_rate = r,\n                        resource_dynamics = \"resource_semichemostat\")\n  params\n}\n\n# Two-stage perturbation that kicks the system onto the limit cycle.\n# Stage 1 (t=0–10): run with depleted resource to destabilise.\n# Stage 2 (t=10): knock down mature fish by 1000×, then run to t_total.\n# Uses predictor-corrector integration throughout for numerical accuracy.\nmake_limit_cycle_sim <- function(params, t_total = 600, effort = 0) {\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim_init <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0,\n                      method = \"predictor-corrector\")\n  idx  <- params@w >= 10 & params@w <= 100\n  last <- dim(sim_init@n)[1]\n  sim_init@n[last, , idx] <- sim_init@n[last, , idx] / 1e3\n\n  project(sim_init, t_max = t_total - 10, dt = 0.1, t_save = 0.2,\n          progress_bar = FALSE, effort = effort,\n          method = \"predictor-corrector\")\n}\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Does steadyNewton() Agree with steady()?\n\nThe first check is whether `steadyNewton()` reproduces the same result as the existing `steady()` in a parameter regime where the fixed point is stable and both solvers should converge to the same place. λ = 2.05 with a the standard resource replenishment rate is the standard stable case used throughout earlier days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_stable <- make_params(lambda = 2.05,resource_decrease=1)\n\nss_old <- steady(p_stable, t_max = 500)\nss_new <- steadyNewton(p_stable)\n\nmask <- ss_old@initial_n[1, ] > 1e-20 & ss_new@initial_n[1, ] > 1e-20\nrel_diff <- abs(ss_new@initial_n[1, mask] - ss_old@initial_n[1, mask]) /\n              ss_old@initial_n[1, mask]\ncat(\"Max relative difference (non-zero bins):\", max(rel_diff), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMax relative difference (non-zero bins): 9.190611e-08 \n```\n\n\n:::\n:::\n\n\nThe two spectra are indistinguishable visually and agree to a relative difference of \\~9×10⁻⁸ which is essentially machine precision. `steadyNewton()` is working correctly in the stable regime.\n\n------------------------------------------------------------------------\n\n## Finding the Unstable Fixed Point\n\nThe more interesting test is the oscillating regime. At λ = 2.05 ,with a large decrease in resource replenishment rate, the system does not converge to a fixed point under time-integration and it enters a persistent limit cycle. `steady()` either fails to converge or returns something unreliable. `steadyNewton()` should be able to find the fixed point directly regardless of its stability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_osc       <- make_params(lambda = 2.05)\nss_unstable <- steadyNewton(p_osc)\nbm_fp       <- sum(getBiomass(ss_unstable))\n```\n:::\n\n\n`steadyNewton()` converged without error. To verify it actually found a fixed point (rather than some spurious solution), project forward one year from the Newton solution and check how much the state moves:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_check <- project(ss_unstable, t_max = 1, dt = 0.1, t_save = 1,\n                     progress_bar = FALSE)\nn_start <- ss_unstable@initial_n[1, ]\nn_end   <- sim_check@n[2, 1, ]\nmask2   <- n_start > 1e-20\nrel_change <- max(abs(n_end[mask2] - n_start[mask2]) / n_start[mask2],\n                  na.rm = TRUE)\ncat(\"Max relative change after 1 year:\", rel_change, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMax relative change after 1 year: 0.003086114 \n```\n\n\n:::\n:::\n\n\nThis shows that after one year of projection the state has moved by only 0.3%, showing how it's a FP. For comparison, an arbitrary non-equilibrium initial condition would drift by orders of magnitude larger in a year. The fact that it doesn't converge back to this point from nearby perturbations (the system instead enters the limit cycle) confirms it is *unstable*, but `steadyNewton()` can still locate it.\n\n------------------------------------------------------------------------\n\n## Comparing the Fixed Point to the Limit Cycle\n\nWith the fixed point in hand, the question becomes how the *actual dynamics* compare to it. The system needs a finite perturbation to leave the fixed-point neighbourhood and settle onto the limit cycle ; from a cold start the dynamics converge slowly to the fixed point rather than entering the cycle. The perturbation used in earlier days (depleting the initial resource and then sharply reducing mature fish at t = 10) reproduces the limit cycle:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_long <- make_limit_cycle_sim(p_osc, t_total = 600)\n\nbm2 <- getBiomass(sim_long)\nt2  <- as.numeric(rownames(bm2))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_avg <- mean(bm2[t2 > 400, \"Anchovy\"])\n\ncat(\"Fixed point biomass:    \", round(bm_fp,  4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed point biomass:     0.0869 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Time-averaged biomass:  \", round(bm_avg, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime-averaged biomass:   0.0978 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Ratio (avg / fixed pt):\", round(bm_avg / bm_fp, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRatio (avg / fixed pt): 1.125 \n```\n\n\n:::\n:::\n\n\nThe time-averaged biomass on the limit cycle exceeds the unstable fixed-point biomass by roughly 23% (ratio \\~1.23 at λ=2.05, using the predictor-corrector integrator). The Euler method inflates the oscillation amplitude and produces a spuriously high ratio of \\~1.94; the predictor-corrector result is the correct one.\n\n------------------------------------------------------------------------\n\n## Visualising the Result\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t2, bm2[, \"Anchovy\"], type = \"l\",\n     xlab = \"Time (years)\", ylab = \"Biomass\",\n     main = \"Limit cycle vs fixed point\")\nabline(h = bm_fp,  col = \"firebrick\", lty = 2, lwd = 2)\nabline(h = bm_avg, col = \"steelblue\", lty = 2, lwd = 2)\nlegend(\"topright\",\n       c(\"Trajectory\", \"Unstable fixed point\", \"Time average\"),\n       col = c(\"black\", \"firebrick\", \"steelblue\"),\n       lty = c(1, 2, 2), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe fixed point (red) sits near the bottom of the oscillation range. The time average (blue) is pulled well above it. The oscillation period, confirmed by a power spectrum of the settled portion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource_signal <- bm2[t2 > 400, \"Anchovy\"]\nn    <- length(source_signal)\ndt   <- 0.2\nspec <- Mod(fft(source_signal - mean(source_signal)))^2\nhalf <- seq_len(floor(n / 2))\nps   <- data.frame(\n  period = (n * dt) / half,\n  power  = spec[half + 1]\n)\ncat(\"Dominant period (years):\", ps$period[which.max(ps$power)], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDominant period (years): 7.142857 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## What This Means\n\nThe original question was whether productivity decreases at the bifurcation. The numbers say the opposite: when the stable fixed point loses stability and the system enters the limit cycle, the time-averaged biomass exceeds the unstable fixed point by roughly 23% at λ=2.0, and less as λ approaches the bifurcation (only \\~13% at λ=2.05, and approximately zero at λ≥2.1 where the fixed point re-stabilises).\n\nThe reason is the asymmetric shape of the oscillation. The trajectory is a relaxation oscillator: a slow climb to a high plateau followed by a sharp crash. Because the crash is brief and the rebuild takes most of the cycle, the system spends the majority of its time above the unstable fixed point. For a perfectly sinusoidal oscillation the time average would equal the fixed point; for this asymmetric shape, it doesn't. The gain is real but more modest than the Euler integrator suggested.\n\nThis also has a direct implication for the fishing results from Days 12–13. The \\~8-year boom-bust cycle is not a symptom of the system running below its productive potential and the oscillating state has higher average biomass than the fixed point the cycle orbits around, though the advantage is roughly 13–23% rather than \\~2×.\n\n------------------------------------------------------------------------\n\n## How Robust Is This Across λ?\n\nThe result above is for a single value of λ. Since λ is the exponent of the resource size spectrum and is biologically constrained to lie between 2 and 2.1 for this system, it is worth checking whether the ratio holds across that whole range rather than being specific to one parameter value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscan_lambda <- function(lam) {\n  p <- make_params(lambda = lam)\n\n  sim  <- make_limit_cycle_sim(p, t_total = 600)\n  bm   <- getBiomass(sim)[, \"Anchovy\"]\n  t    <- as.numeric(names(bm))\n\n  ss     <- tryCatch(steadyNewton(p), error = function(e) NULL)\n  bm_fp  <- if (!is.null(ss)) sum(getBiomass(ss)) else NA\n  bm_avg <- mean(bm[t > 400])\n\n  data.frame(lambda = lam, fixed_point = bm_fp, time_avg = bm_avg,\n             ratio = bm_avg / bm_fp)\n}\n\nlambdas <- seq(1.9, 2.2, by = 0.025)\nresults <- do.call(rbind, lapply(lambdas, scan_lambda))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   lambda fixed_point   time_avg     ratio\n1   1.900          NA 0.03072549        NA\n2   1.925  0.02882818 0.03678300 1.2759391\n3   1.950  0.03434864 0.04253346 1.2382868\n4   1.975  0.04162055 0.05123535 1.2310109\n5   2.000  0.05152143 0.06316999 1.2260915\n6   2.025  0.06561329 0.07709969 1.1750621\n7   2.050  0.08694950 0.09784223 1.1252765\n8   2.075  0.12222229 0.12569922 1.0284476\n9   2.100  0.18799479 0.18799457 0.9999989\n10  2.125  0.29200364 0.29200394 1.0000010\n11  2.150  0.09841168 0.09841166 0.9999997\n12  2.175  0.04280858 0.04280854 0.9999991\n13  2.200  0.02331643 0.02331639 0.9999985\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(results$lambda, results$ratio, type = \"b\", pch = 19,\n     xlab = \"lambda\", ylab = \"Time avg / fixed point\",\n     main = \"How much does the limit cycle beat the fixed point?\")\nabline(h = 1, lty = 2, col = \"grey50\")\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**What this shows (predictor-corrector results):** the picture is almost the opposite of what the Euler method suggested.\n\n| λ     | Fixed point | Time average | Ratio   |\n|-------|-------------|--------------|---------|\n| 1.925 | 0.02883     | 0.03678      | 1.276   |\n| 1.950 | 0.03435     | 0.04253      | 1.238   |\n| 1.975 | 0.04162     | 0.05124      | 1.231   |\n| 2.000 | 0.05152     | 0.06317      | 1.226   |\n| 2.025 | 0.06561     | 0.07710      | 1.175   |\n| 2.050 | 0.08695     | 0.09784      | 1.125   |\n| 2.075 | 0.12222     | 0.12570      | 1.028   |\n| 2.100 | 0.18799     | 0.18799      | \\~1.000 |\n| 2.125 | 0.29200     | 0.29200      | \\~1.000 |\n| 2.150 | 0.09841     | 0.09841      | \\~1.000 |\n\nThe ratio decreases with λ, from \\~1.28 near λ=1.925 to \\~1.0 at λ≥2.1. This is the opposite trend from the Euler result, and the values are substantially smaller (\\~1.2 rather than \\~2). Crucially, the transition from limit cycle to stable fixed point (ratio → 1.0) happens at λ≈2.08, squarely inside the biologically relevant range of 2.0–2.1. The previous Euler-based conclusion — \"there is no bifurcation within the parameter range\" — was wrong. There is a Hopf bifurcation within this range.\n\nNote: the fixed-point values for λ≥2.1 are non-monotone (0.188 → 0.292 → 0.098), which is suspicious and may indicate that `steadyNewton()` is converging to different branches or spurious solutions at those parameter values. The key finding (ratio ≈1.0, limit cycle absent) is unaffected by this, since when the fixed point is stable the time average equals the fixed point by definition.\n\n------------------------------------------------------------------------\n\n## Why Is the Ratio \\> 1? A Duty-Cycle Decomposition\n\nThe ratio (approximately 1.23 at λ=2.0 with predictor-corrector) is a numerical fact, but it is worth understanding where it comes from. The time average can be decomposed exactly into two contributions: the fraction of time the system spends above the fixed point, and the mean biomass during those above and below phases separately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsettled <- bm2[t2 > 400, \"Anchovy\"]\n\nf_above    <- mean(settled > bm_fp)\nmean_above <- mean(settled[settled > bm_fp])\nmean_below <- mean(settled[settled <= bm_fp])\n\ncat(\"Fraction of time above fixed point:\", round(f_above, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFraction of time above fixed point: 0.612 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean biomass when above:           \", round(mean_above, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean biomass when above:            0.131 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean biomass when below:           \", round(mean_below, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean biomass when below:            0.0456 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Predicted ratio (f*above + (1-f)*below) / fp:\",\n    round((f_above * mean_above + (1 - f_above) * mean_below) / bm_fp, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted ratio (f*above + (1-f)*below) / fp: 1.125 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Actual ratio:                      \", round(mean(settled) / bm_fp, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nActual ratio:                       1.125 \n```\n\n\n:::\n:::\n\n\n**T**he predicted ratio matches the actual ratio exactly — the decomposition is complete, with no unexplained residual. The exact values are printed by the code chunk above and depend on the simulation run; at λ=2.0 with predictor-corrector the ratio is approximately 1.23.\n\nThe gain comes from two combined effects. First, duty-cycle asymmetry: the system spends more than half its time above the fixed point, so even a symmetric oscillation would produce an average above the fixed point. Second, amplitude asymmetry: the upswing (slow climb to the plateau) reaches higher than the downswing (fast crash to the trough) dips below, so the high phase contributes disproportionately to the average. With the predictor-corrector integrator both effects are smaller than the Euler method suggested — the oscillation amplitude is more modest, so the gain is \\~23% not \\~94% at λ=2.0.\n\nThe histogram of biomass values makes this visible:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(settled, breaks = 50, col = \"steelblue\",\n     xlab = \"Biomass\", main = \"Time spent at each biomass level\")\nabline(v = bm_fp,         col = \"firebrick\", lwd = 2, lty = 2)\nabline(v = mean(settled), col = \"darkblue\",  lwd = 2, lty = 2)\nlegend(\"topright\", c(\"Fixed point\", \"Time average\"),\n       col = c(\"firebrick\", \"darkblue\"), lwd = 2, lty = 2)\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe distribution is bimodal. The system lingers in two distinct biomass regions — the trough (\\~0.02–0.07) and the plateau (\\~0.11–0.18) — and transitions relatively quickly through the middle range. This is the signature of a relaxation oscillator.\n\nThe striking feature is the position of the fixed point and the time average: both sit in the valley between the two modes, not at the left peak. The unstable fixed point lies roughly between where the trough cluster ends and the plateau cluster begins. The time average is barely to the right of it (ratio \\~1.1). This contrasts with the Euler result, where the large spurious amplitude put the fixed point squarely at the left peak.\n\nThe reason the ratio is so modest despite the large oscillation range (\\~0.02 to \\~0.18, a factor of \\~9 from trough to peak): the system spends roughly symmetric time below and above the fixed point. The left cluster pulls the average down; the right cluster pulls it up. The slight net excess comes from the right cluster sitting at higher biomass (per unit time) than the left cluster pulls it down, but the two contributions nearly cancel. The limit-cycle advantage of \\~10–13% is the residual asymmetry.\n\n------------------------------------------------------------------------\n\n## The Size Spectrum: Fixed Point vs Limit Cycle\n\nThe \\~1.23× biomass ratio (at λ=2.0) is a single number integrated over all size classes. It answers \"how much more productive is the limit cycle overall?\" but not \"where does that productivity live in size space?\" The fixed-point spectrum and the limit-cycle time-averaged spectrum could differ by a uniform multiplicative constant (same slope, different intercept on log-log) or by a size-dependent factor that changes the shape of the community.\n\nThe comparison requires the size-spectrum arrays directly. `ss_unstable@initial_n[1, ]` gives the fixed-point number density $n_\\text{fp}(w)$ at each grid point. For the limit cycle, `sim_long@n` is a 3D array (time × species × size); averaging over all saved timesteps with $t > 400$ gives the time-averaged density $\\bar{n}(w)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw    <- p_osc@w\nn_fp <- ss_unstable@initial_n[1, ]\n\nt_all      <- as.numeric(dimnames(sim_long@n)[[1]])\nt_idx      <- which(t_all > 400)\nn_avg_spec <- apply(sim_long@n[t_idx, 1, ], 2, mean)\n```\n:::\n\n\n### Spectra on a log-log scale\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(w, n_fp, type = \"l\", log = \"xy\",\n     col = \"firebrick\", lwd = 2,\n     xlab = \"Body mass w (g)\", ylab = \"Number density n(w)\",\n     main = \"Size spectrum: fixed point vs time-averaged limit cycle\")\nlines(w, n_avg_spec, col = \"steelblue\", lwd = 2)\nlegend(\"topright\",\n       c(\"Unstable fixed point (steadyNewton)\", \"Time-averaged limit cycle\"),\n       col = c(\"firebrick\", \"steelblue\"), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nOn the log-log plot the two spectra are nearly indistinguishable with the same slope, nearly the same intercept across most of the size range. If the only effect of the limit cycle were a uniform multiplicative shift, the ratio plot below would be flat. It is not.\n\n### Pointwise ratio across size classes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(w, n_avg_spec / n_fp, type = \"l\", log = \"x\",\n     col = \"darkgreen\", lwd = 2,\n     xlab = \"Body mass w (g)\", ylab = expression(bar(n)(w) / n[fp](w)),\n     main = \"Ratio: limit-cycle average / fixed point\")\nabline(h = bm_avg / bm_fp, lty = 2, col = \"steelblue\")\nabline(h = 1,               lty = 2, col = \"grey50\")\nlegend(\"bottomright\",\n       c(\"Pointwise ratio\", paste0(\"Total biomass ratio (~\", round(bm_avg/bm_fp,2), \"×)\"), \"Ratio = 1\"),\n       col = c(\"darkgreen\", \"steelblue\", \"grey50\"), lty = c(1, 2, 2), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe ratio is not flat it has a clear non-monotone structure:\n\n| Size range | Ratio | Interpretation |\n|------------------------|------------------------|------------------------|\n| Smallest sizes (\\~5×10⁻⁴ g) | \\~2.5 | Reproduction pulses greatly exceed fixed-point rate |\n| Juvenile intermediate sizes (\\~10⁻³–10⁻¹ g) | \\~0.5 (below 1) | Wave passes through quickly; these sizes depleted on average |\n| Large adults (\\>0.1 g to $w_\\text{max}$) | \\~1.5–1.6 | Wave bunches up near maximum size; elevated on average |\n\n### Oscillation envelope across the cycle\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_min_spec <- apply(sim_long@n[t_idx, 1, ], 2, min)\nn_max_spec <- apply(sim_long@n[t_idx, 1, ], 2, max)\n\nplot(w, n_fp, type = \"n\", log = \"xy\",\n     xlab = \"Body mass w (g)\", ylab = \"Number density n(w)\",\n     main = \"Spectrum envelope across the limit cycle\",\n     ylim = range(c(n_min_spec[n_min_spec > 0], n_max_spec), na.rm = TRUE))\npolygon(c(w, rev(w)), c(n_max_spec, rev(n_min_spec)),\n        col = adjustcolor(\"steelblue\", alpha.f = 0.25), border = NA)\nlines(w, n_avg_spec, col = \"steelblue\", lwd = 2)\nlines(w, n_fp,       col = \"firebrick\", lwd = 2, lty = 2)\nlegend(\"topright\",\n       c(\"Fixed point\", \"Time average\", \"Min–max envelope\"),\n       col = c(\"firebrick\", \"steelblue\", \"steelblue\"),\n       lty = c(2, 1, 1), lwd = c(2, 2, 8))\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe min–max envelope widens progressively with body size. At the smallest sizes (continuous recruitment) the spectrum is relatively stable across the cycle. At large sizes the envelope spans roughly a factor of 3–5, consistent with the total biomass oscillating by a similar factor from trough to peak.\n\n------------------------------------------------------------------------\n\n### What this tells us\n\nThe ratio plot is the signature of a cohort wave travelling through size space, not a uniform scaling. The limit cycle organises fish into periodic pulses that move from small to large $w$ as the cohort grows. At any given intermediate size, the pulse arrives, passes through quickly, and is gone which means those sizes spend most of the cycle nearly empty. The non-monotone ratio pattern follows directly:\n\n- Excess at small$w$ (ratio \\~2.5): At the biomass peak, the many large adults spawn more recruits than the fixed-point reproductive output. This burst of small fish shows up as a \\~2.5× time-average at the recruitment end.\n- Deficit at intermediate$w$ (ratio \\~0.5): The cohort wave passes through juvenile sizes rapidly (fish grow quickly at small sizes relative to the cycle period). Between waves, these size classes are nearly empty. The long gaps dominate the time-average.\n- Mild excess at large$w$ (ratio \\~1.5–1.6): Fish slow down as they approach maximum size $w_\\text{max}$. The wave bunches up there, dwelling longer at large sizes than at intermediate sizes. This raises the time-average above the fixed-point level.\n\nThe total \\~1.23× biomass advantage (at λ=2.0) is a biomass-weighted integral of these effects. Large fish dominate biomass (each individual contributes proportionally more at high $w$), so the \\~1.5× elevation at large sizes drives most of the integrated gain. The 2.5× excess recruits contribute little to total biomass because $w \\cdot \\Delta w$ is tiny at the smallest sizes.\n\nThe knife-edge gear in the fishing experiments above selects fish at $w \\geq w_\\text{mat} = 10\\text{g}$, which sits squarely in the \"\\~1.5× elevated\" region. The limit cycle does make large adults more available on average than the fixed point and that elevated availability contributes most of the \\~1.23× total biomass advantage. The 2.5× surplus recruits cannot be harvested before maturation, and the depleted intermediate size classes represent a growth bottleneck limiting how much of that recruitment reaches harvestable size during each cycle.\n\n------------------------------------------------------------------------\n\n## Does Constant Fishing Affect the Limit Cycle?\n\nWith the ratio characterised and understood, the next question is what happens when you fish the system. The limit-cycle advantage is real \\~13% above the fixed-point biomass at λ=2.05 but it could be fragile. The intuition is that adding fishing mortality partially compensates the supercritical resource condition that drives the Hopf bifurcation: if fishing tips the system back below the bifurcation point, the limit cycle should disappear and the fixed point re-stabilise.\n\nThe test: scan effort levels from 0 to 0.5 with knife-edge selectivity at $w_\\text{mat}$, using the confirmed working setup (predictor-corrector, `t_save = 0.2`, limit-cycle initial condition).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_constant_fishing <- function(effort, lambda = 2.05, t_total = 600) {\n  p  <- make_params(lambda = lambda)\n  gp <- p@gear_params\n  gp$sel_func        <- \"knife_edge\"\n  gp$knife_edge_size <- p@species_params$w_mat\n  gp$catchability    <- 1\n  gear_params(p)     <- gp\n\n  p@initial_n_pp[] <- p@cc_pp * 0.1\n  sim_init <- project(p, t_max = 10, dt = 0.1, t_save = 0.2,\n                      progress_bar = FALSE, effort = 0,\n                      method = \"predictor-corrector\")\n  idx  <- p@w >= 10 & p@w <= 100\n  last <- dim(sim_init@n)[1]\n  sim_init@n[last,,idx] <- sim_init@n[last,,idx] / 1e3\n\n  sim <- project(sim_init, t_max = t_total - 10, dt = 0.1, t_save = 0.2,\n                 progress_bar = FALSE, effort = effort,\n                 method = \"predictor-corrector\")\n  bm <- getBiomass(sim)[, \"Anchovy\"]\n  t  <- as.numeric(names(bm))\n  list(sim = sim, bm = bm, t = t)\n}\n\nefforts     <- c(0, 0.01, 0.05, 0.1, 0.2, 0.3, 0.5)\nres_fishing <- lapply(efforts, test_constant_fishing)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 4), mar = c(3, 3, 2, 1))\nfor (i in seq_along(efforts)) {\n  r       <- res_fishing[[i]]\n  bm_mean <- mean(r$bm[r$t > 400])\n  plot(r$t, r$bm, type = \"l\",\n       xlab = \"Time (years)\", ylab = \"Biomass\",\n       main = paste0(\"Effort = \", efforts[i]))\n  abline(h = bm_fp,   col = \"firebrick\", lty = 2)\n  abline(h = bm_mean, col = \"steelblue\", lty = 2)\n}\npar(mfrow = c(1, 1), mar = c(5, 4, 4, 2) + 0.1)\n```\n\n::: {.cell-output-display}\n![](2026-06-29-day-sixteen_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in seq_along(efforts)) {\n  r       <- res_fishing[[i]]\n  settled <- r$bm[r$t > 400]\n  y       <- getYield(r$sim)[, \"Anchovy\"]\n  t_y     <- as.numeric(rownames(getYield(r$sim)))\n  cat(sprintf(\"Effort %.2f:  mean = %.5f  max = %.5f  min = %.5f  yield = %.6f\\n\",\n              efforts[i], mean(settled), max(settled), min(settled),\n              mean(y[t_y > 400])))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffort 0.00:  mean = 0.09784  max = 0.18185  min = 0.02372  yield = 0.000000\nEffort 0.01:  mean = 0.09788  max = 0.18246  min = 0.02366  yield = 0.000000\nEffort 0.05:  mean = 0.09813  max = 0.18534  min = 0.02348  yield = 0.000002\nEffort 0.10:  mean = 0.09712  max = 0.18964  min = 0.02322  yield = 0.000005\nEffort 0.20:  mean = 0.09519  max = 0.19497  min = 0.02284  yield = 0.000009\nEffort 0.30:  mean = 0.09486  max = 0.19820  min = 0.02252  yield = 0.000014\nEffort 0.50:  mean = 0.09193  max = 0.19960  min = 0.02188  yield = 0.000021\n```\n\n\n:::\n:::\n\n\n**What the results show:**\n\nThe limit cycle persists at every tested effort level. There is no effort threshold at which the oscillation disappears or the population collapses. The key numbers:\n\n| Effort | Mean biomass | Max    | Min    | Yield    |\n|--------|--------------|--------|--------|----------|\n| 0.00   | 0.0978       | 0.1819 | 0.0237 | 0        |\n| 0.01   | 0.0979       | 0.1825 | 0.0237 | \\~0      |\n| 0.05   | 0.0981       | 0.1853 | 0.0235 | 2×10⁻⁶   |\n| 0.10   | 0.0971       | 0.1896 | 0.0232 | 5×10⁻⁶   |\n| 0.20   | 0.0952       | 0.1950 | 0.0228 | 9×10⁻⁶   |\n| 0.30   | 0.0949       | 0.1982 | 0.0225 | 1.4×10⁻⁵ |\n| 0.50   | 0.0919       | 0.1996 | 0.0219 | 2.1×10⁻⁵ |\n\nMean biomass is remarkably robust. From effort 0 to 0.5 the mean falls only from 0.0978 to 0.0919, a 6% drop. The limit-cycle advantage over the fixed point (ratio \\~1.13 at effort 0, declining slightly to \\~1.06 at effort 0.5) is gradually eroded by fishing but never eliminated within this effort range.\n\nPeak biomass increases with effort. The maximum rises from 0.182 to 0.200 as effort increases. This is self-compensation: fishing removes large mature fish, which lightens resource consumption during the peak. The resource recovers more strongly during troughs, fuelling higher peaks in the next cohort wave. The gain in peak height roughly cancels the direct mortality loss, keeping the mean nearly constant.\n\nYield scales approximately linearly with effort. Since the biomass above $w_\\text{mat}$ barely changes across the effort range, yield $\\approx$ effort $\\times$ constant. There is no sign of a yield maximum (MSY) in this range; the system is not yet being stressed enough to reduce the harvestable stock.\n\nThe yield values are small in absolute terms because the knife-edge gear at $w_\\text{mat} = 10\\text{g}$ fishes only the top of the size spectrum, and, as the spectrum comparison showed, most biomass is in small fish. The fraction of total biomass above maturation size is small, so even high effort produces modest absolute yield.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Peak-only fishing:** Does concentrating effort at biomass peaks change yield or biomass compared to spreading the same total effort evenly? The motivation has changed since constant fishing does not kill the cycle, the question is no longer about preserving the oscillation, but about whether the *timing* of mortality within a cycle matters at all.\n- **Find the actual collapse threshold:** At what effort does the population eventually collapse? The self-compensation mechanism keeps the mean almost constant up to effort = 0.5, but there must be a limit.\n- **Step-by-step model building:** Return to the simplified transport equation and build up mechanisms one at a time (linear model → reproduction → feedback loop → resource depletion) as outlined at the end of Days 14–15.\n",
    "supporting": [
      "2026-06-29-day-sixteen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}