{
  "hash": "8acaed87eecb6effa1684173818a29b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 12 and 13: Learning the Discrete Fourier Transform, Limit Cycles, and a Second Look at Generation Time\"\nauthor: \"Samia\"\ndate: \"2026-06-24\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: flatly\n    code-fold: true\ncategories: [research, mizer, dft, nonlinear-dynamics, waves, fishing-strategy, blog]\ndescription: \"Two days spent mostly off the R console: hunting down good resources for properly learning the discrete Fourier transform, working through limit cycles and into bifurcations in Strogatz, picking group velocity back up in the wave-motion textbook, and continuing the fishing-only-the-peaks investigation. Also revisits generation time: the steady-state calculation gives 2.38, but replacing the fixed growth rate with the real, time-varying growth field and tracking cohorts through it pulls that back up to about 3.27, closer to the original ballpark guess.\"\n---\n\n## Tuesday: Hunting for DFT Resources, and a Second Look at Generation Time\n\nDay 11 used `fft()` as a black box to get a dominant period and a phase argument out of the simulation, with a note left in \"What's Next\" to actually learn what the transform is doing rather than keep treating it as a library call. Tuesday went looking for resources to do that properly, rather than diving straight back into mizer.\n\n### Where to Actually Learn the DFT\n\nThe most useful resources found were:\n\n- [Julius O. Smith III's *Discrete Fourier Transform (DFT)*](https://ccrma.stanford.edu/~jos/st/Discrete_Fourier_Transform_DFT.html), the Stanford CCRMA page on the DFT, which derives the transform itself rather than just stating the formula and lists the standard properties (linearity, the shift and convolution theorems, Parseval's relation) in one place.\n- YouTube explanations from **3Blue1Brown** and **Steve Brunton**, for the geometric \"winding the signal around a circle at different frequencies\" intuition that's harder to get from a written derivation alone.\n\nThe rest of Tuesday's DFT time went into working through that material and starting a proper set of notes rather than anything that produces code or numbers worth showing here.\n\n### Limit Cycles\n\nAlongside the DFT, Tuesday's reading time also went into Strogatz's *Nonlinear Dynamics and Chaos*, picking up the limit-cycle chapter that had been queued since Day 11 (the system's boom-bust oscillation is exactly the kind of self-sustained periodic attractor that chapter is about, and Day 11 had been reasoning about phase and feedback without that theory underneath it).\n\n### Generation Time, Checked Again\n\nThe other piece of Tuesday went back to Day 11's generation-time calculation, re-running the same steady-state age-at-size integral to make sure the number being carried forward was right rather than half-remembered:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mizer)\nlibrary(patchwork)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(dplyr)\nlibrary(mizerExperimental)\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(ggplot2)\n\n# Same single-species Anchovy setup as Day 8/11.\nrun_anchovy <- function(lambda) {\n  p <- list(\n    dt = 0.001, dx = 0.1, w_min = 0.0003, w_max = 66.5,\n    w_mat = 10, alpha = 0.1, gamma = 750, lambda = lambda, a0 = 100\n  )\n  kappa <- p$a0 * exp(-6.9 * (p$lambda - 1))\n  no_w  <- round(log(p$w_max / p$w_min) / p$dx)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\",\n    w_min = p$w_min, w_max = p$w_max, w_mat = p$w_mat,\n    no_w  = no_w,    lambda = p$lambda, kappa = kappa,\n    alpha = p$alpha, gamma  = p$gamma,  ks    = 0\n  )\n  r <- getResourceRate(params) * 0.001\n  params <- setResource(params, resource_rate = r,\n                        resource_dynamics = \"resource_semichemostat\")\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                 progress_bar = FALSE, method = \"predictor-corrector\")\n  idx  <- params@w >= 10 & params@w <= 100\n  last <- dim(sim@n)[1]\n  sim@n[last, , idx] <- sim@n[last, , idx] / 10^3\n\n  sim     <- project(sim, t_max = 90, dt = 0.1, t_save = 0.2,\n                     progress_bar = FALSE, method = \"predictor-corrector\")\n  sim_300 <- project(sim, t_max = 200, dt = 0.1, t_save = 0.2,\n                     progress_bar = FALSE, method = \"predictor-corrector\")\n  sim_600 <- project(sim_300, t_max = 300, dt = 0.1, t_save = 0.2,\n                     progress_bar = FALSE, method = \"predictor-corrector\")\n  list(params = params, sim_600 = sim_600)\n}\n\n# Reused from Day 8/11: power spectrum of a (mean-subtracted) signal.\npower_spectrum <- function(signal, dt) {\n  signal <- signal - mean(signal)\n  n      <- length(signal)\n  freqs  <- (1:(n - 1)) / (n * dt)\n  power  <- Mod(fft(signal))^2\n  half   <- seq_len(floor((n - 1) / 2))\n  data.frame(freq = freqs[half], period = 1 / freqs[half], power = power[half + 1])\n}\n\nrun_2   <- run_anchovy(2)\nparams  <- run_2$params\nsim_600 <- run_2$sim_600\ntimes   <- as.numeric(dimnames(sim_600@n)[[1]])\nbm      <- getBiomass(sim_600)[, \"Anchovy\"]\nps      <- power_spectrum(bm[times > 300], 0.2)\nperiod_dom <- ps$period[which.max(ps$power)]\n\n# age(w) = integral_{w_min}^{w} 1/g(w') dw' under the steady-state growth\n# rate, i.e. how long a fish takes to grow from w_min up to w.\ng  <- getEGrowth(params)[\"Anchovy\", ]\nw  <- params@w\ndw <- params@dw\nintegrand  <- 1 / g\nage        <- c(0, cumsum((integrand[-1] + integrand[-length(integrand)]) / 2 * dw[-length(dw)]))\nage_at_mat <- approx(x = w, y = age, xout = params@species_params$w_mat)$y\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(period_dom = period_dom, age_at_mat = age_at_mat,\n       ratio = period_dom / age_at_mat), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nperiod_dom age_at_mat      ratio \n     8.333      3.497      2.383 \n```\n\n\n:::\n:::\n\n\nThe dominant oscillation period comes out at 8.33 years, age-at-maturity at 3.50 years, giving a period-to-generation-time ratio of 2.38. The earlier working assumption had been \"about 3 generations\" per period; the actual calculated number sits a bit below that, closer to \"two and a bit\" generations than three. Worth flagging honestly: this uses the same fixed, steady-state growth rate as Day 11, not a growth rate that varies with the cycle, so the number is a snapshot to build on rather than a final answer.\n\n### Does the Growth Rate Assumption Hold Up?\n\nDay 11 derived a clean prediction for how phase should depend on growth rate, then checked it against the actual data and found it failed: the measured phase curve didn't fall steadily the way the proof predicted, and the relative phase drop from $w_{min}$ to $w_{mat}$ had the wrong sign and was far too small in magnitude. An assumption behind that proof were flagged as suspect: that growth rate is fixed at its steady-state value when the food supply driving it actually oscillates along with everything else. The generation-time number just calculated rests on that same fixed-growth-rate assumption (`getEGrowth(params)`, evaluated at the steady state), so before moving on to the DFT and limit-cycle reading, it was worth checking directly how much that assumption was costing.\n\n#### Why You Can't Just Separate Variables for $g(w,t)$\n\nThe steady-state version of the age calculation rests on separating variables in $dw/dt = g(w)$:\n\n$$\\frac{dw}{g(w)} = dt \\quad\\Longrightarrow\\quad a(w) = \\int_{w_{min}}^{w} \\frac{dw'}{g(w')}$$\n\nThis works because $g(w)$ depends only on $w$, so all the $w$-stuff can be put on one side and all the $t$-stuff on the other before integrating each side independently. The moment growth rate also depends on time, $g(w,t)$, that move stops being valid:\n\n$$\\frac{dw}{g(w,t)} = dt$$\n\nlooks the same, but the left side still has a $t$ buried inside it, and that $t$ isn't free to integrate away on its own, because $w$ and $t$ are linked along the very trajectory being solved for. Writing $\\int dw/g(w,t)$ in isolation doesn't mean anything yet: you'd need to already know $w(t)$ to know what to plug into $g$ at each step, which is circular.\n\nThere's one case where separation still rescues you: if the time-dependence factors out multiplicatively, $g(w,t) = g_0(w)\\,h(t)$ (e.g. food availability scaling every size class's growth by the same relative amount), then\n\n$$\\frac{dw}{g_0(w)} = h(t)\\,dt \\quad\\Longrightarrow\\quad A(w) = H(t) - H(t_{\\text{birth}})$$\n\nwhere $A(w) = \\int_{w_{min}}^w dw'/g_0(w')$ and $H$ is an antiderivative of $h$. This still gives a closed form, but a cohort-dependent one: $t_{\\text{peak}}(w) = H^{-1}(A(w) + H(t_{\\text{birth}}))$ now depends on $t_{\\text{birth}}$ in a nonlinear way, unlike the steady-state case where every cohort shares the same offset $a(w)$. There was no good reason to expect mizer's actual $g(w,t)$ to factor this cleanly, though, so rather than gamble on that assumption, the honest route is the fully general one: solve $dw/dt = g(w,t)$ as the coupled equation it is, numerically, for each cohort separately. That's what `project()` is already doing internally; the next step just pulls a labelled cohort's trajectory back out of it after the fact.\n\n#### Building $g(w,t)$ From the Simulation's Own History\n\n`getEGrowth()` doesn't have to be evaluated at the steady state. It recomputes growth from whatever population state `n` and resource state `n_pp` you hand it, so feeding each saved time step's actual state back in gives the real, time-varying growth field instead of a single fixed snapshot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recompute growth at every saved time step in the settled window, using\n# that time step's actual (n, n_pp), not the unperturbed steady state.\npost     <- times > 300\nidx_post <- which(post)\nG <- matrix(NA_real_, nrow = length(idx_post), ncol = length(w))\nfor (k in seq_along(idx_post)) {\n  i      <- idx_post[k]\n  n_t    <- array(sim_600@n[i, , , drop = FALSE], dim = dim(sim_600@n)[2:3],\n                  dimnames = dimnames(sim_600@n)[2:3])\n  n_pp_t <- sim_600@n_pp[i, ]\n  G[k, ] <- getEGrowth(params, n = n_t, n_pp = n_pp_t)[\"Anchovy\", ]\n}\ntimes_post <- times[idx_post]\nt_save     <- times_post[2] - times_post[1]   # 0.2, matches the project() calls above\n```\n:::\n\n\nThis shows that `getEGrowth(params, n = n_t, n_pp = n_pp_t)` for a single time step gives a growth profile very close to, but not identical to, the steady-state `getEGrowth(params)` used above. At $t=19.8$ (an early, still-settling point), the smallest-size growth rate was 0.00683 vs. 0.00673 from the steady state, a small difference at that particular moment. The whole point of building `G` across every saved time step is that this difference isn't constant, it swings with the cycle, and the steady-state calculation used only the time-averaged-looking (but actually unperturbed-equilibrium) snapshot.\n\n#### Tracking Real Cohorts Through the Oscillation\n\nWith `G` built, a cohort's trajectory is found by integrating $dw/dt = g(w,t)$ forward from $w_{min}$, looking up the growth rate at the cohort's *current* size and time at every step rather than assuming a fixed function of size alone:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bilinear-style lookup: blend the two bracketing saved time snapshots, then\n# interpolate across size, to get g(w,t) at an arbitrary (t, w).\ng_lookup <- function(t, w_now) {\n  idx   <- floor((t - times_post[1]) / t_save) + 1\n  idx   <- min(max(idx, 1), nrow(G) - 1)\n  frac  <- (t - times_post[idx]) / t_save\n  g_vec <- (1 - frac) * G[idx, ] + frac * G[idx + 1, ]\n  approx(x = w, y = g_vec, xout = w_now, rule = 2)$y\n}\n\n# Forward-integrate a single fish born at t_birth through the real,\n# time-varying growth field (simple Euler stepping; dt_step is fine enough\n# relative to the ~8 year period that finer stepping doesn't change the result).\ntrack_cohort <- function(t_birth, w_min = min(params@w), w_max = max(params@w),\n                         dt_step = 0.02) {\n  t_now <- t_birth; w_now <- w_min\n  t_vec <- t_now;   w_vec <- w_now\n  while (w_now < w_max && t_now < max(times_post) - 1) {\n    g_now <- g_lookup(t_now, w_now)\n    if (is.na(g_now) || g_now <= 0) break\n    w_now <- w_now + g_now * dt_step\n    t_now <- t_now + dt_step\n    t_vec <- c(t_vec, t_now); w_vec <- c(w_vec, w_now)\n  }\n  data.frame(t = t_vec, w = w_vec, age = t_vec - t_birth)\n}\n\n# Track cohorts born at five phases spread across one full cycle, to see how\n# much age-at-size depends on when a cohort happens to be born.\nperiod_dom_check <- period_dom   # 8.333333, the dominant FFT period from above\nbirth_times <- seq(305, 305 + period_dom_check, length.out = 6)[-6]\ncohorts     <- lapply(birth_times, track_cohort)\nnames(cohorts) <- paste0(\"t_birth=\", round(birth_times, 2))\n\ndf_cohorts <- do.call(rbind, lapply(names(cohorts), function(nm) {\n  d <- cohorts[[nm]]; d$cohort <- nm; d\n}))\n\nggplot(df_cohorts, aes(x = w, y = age, colour = cohort)) +\n  geom_line() + scale_x_log10() +\n  labs(x = \"body mass (g)\", y = \"age since birth (years)\",\n       title = \"Age-at-size for cohorts born at different phases\", colour = \"birth time\")\n```\n\n::: {.cell-output-display}\n![](2026-06-23-day-twelve_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nages_at_mat <- sapply(cohorts, function(co)\n  approx(x = co$w, y = co$age, xout = params@species_params$w_mat)$y)\nround(ages_at_mat, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   t_birth=305 t_birth=306.67 t_birth=308.33    t_birth=310 t_birth=311.67 \n         2.464          2.512          2.808          2.490          2.467 \n```\n\n\n:::\n:::\n\n\nThe five cohort curves sit almost exactly on top of each other across the entire size range, the plot doesn't visually distinguish them. Age-at-maturity across the five birth phases comes out as 2.464, 2.512, 2.808, 2.490, and 2.467 years. There is a real spread (the 308.33 cohort takes noticeably longer), but it's modest compared to the gap between *any* of these and the steady-state estimate of 3.50 years above. The dominant effect of switching to a real, time-varying growth rate isn't that different cohorts now disagree with each other, it's that all of them mature faster than the steady-state calculation predicted.\n\n#### What This Does to the \"Generation Time\" Result\n\nThe calculation earlier today reproduced Day 11's period-to-generation-time ratio of 8.33 / 3.50 $\\approx$ 2.38, and treated the original ballpark guess of \"about 3 generations\" as having been a slight overestimate once actually calculated. That conclusion needs to be walked back. Using the cohort-tracked ages instead of the steady-state one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratios <- period_dom / ages_at_mat\nround(ratios, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   t_birth=305 t_birth=306.67 t_birth=308.33    t_birth=310 t_birth=311.67 \n         3.382          3.317          2.968          3.347          3.378 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(ratios), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.278\n```\n\n\n:::\n:::\n\n\nThe ratio per cohort ranges from about 2.97 to 3.38, averaging **3.27**. That's much closer to the original \"about 3 generations\" intuition than the 2.38 figure calculated above, not further from it. The steady-state growth rate was underestimating how fast fish actually grow in this system by roughly 30%, which was dragging the calculated ratio down with it. Once the real, time-varying growth field is used, the rough guess holds up better than the more careful-looking calculation that initially seemed to correct it.\n\n#### Phase Velocity vs Group Velocity: Why the Two Calculations Disagree\n\nThere's a cleaner way to describe what went wrong with the steady-state estimate and what the cohort-tracking above actually fixed, borrowed from how dispersive waves are normally described.\n\nFor a wave built from a single frequency, points of constant phase move through space at the phase velocity, $v_{\\text{phase}} = k/\\kappa$, where $k$ is the (temporal) frequency and $\\kappa$ is the (spatial) wavenumber. A wave *packet*, a localised pulse built from a narrow spread of frequencies, instead moves at the group velocity, $v_g = dk/d\\kappa$. In a non-dispersive medium these are the same number. In a dispersive one, they aren't, and the difference is exactly the gap between \"where the ripples appear to be\" and \"where the actual energy is going.\"\n\nThis system has a direct translation: size $w$ plays the role of space, real time $t$ plays the role of time, and Day 11's $\\kappa(w) = d\\varphi/dw = -k/g(w)$ is a wavenumber computed from a single frequency, the dominant FFT peak. That makes the whole Day 11 derivation a phase-velocity calculation: how fast a surface of constant phase, for one Fourier component, moves through size-space. `track_cohort()` above does something different: it forward-integrates the actual nonlinear $g(w,t)$ that real fish experience, with no decomposition into frequencies at all. That's a direct measurement of how fast the real pulse of fish moves through size-space, which is exactly what **group velocity** means once \"wave packet\" is replaced with \"cohort.\"\n\nThese two only have to agree if the underlying signal is a clean single sinusoid riding a linear, non-dispersive medium. Neither is true here. Day 8 already found the oscillation is a relaxation-oscillator shape (sharp crash, long plateau) loaded with harmonics, not a pure sine wave, and the growth field $g(w,t)$ is itself nonlinear, depending on the very population state being transported through it, which is exactly what makes a medium dispersive rather than uniform. The mismatch between Day 11's phase-velocity calculation and today's cohort-tracked group velocity isn't a separate failure from Day 8's harmonic finding; it's the same fact, met again in a different calculation.\n\nIt also gives a tidier reading of today's cohort-to-cohort spread. If there were one well-defined phase velocity for this system, every cohort would share exactly the same generation time. Instead the five tracked cohorts came out at 2.46 to 2.81 years, and the period-to-generation-time ratio ranged from 2.97 to 3.38 rather than landing on one fixed number. That spread is the sign of their being dispersion. A single \"the\" generation time was never quite the right concept for a system like this; there's a distribution of them, the same way a dispersive pulse doesn't have one well-defined speed once you look closely enough.\n\n------------------------------------------------------------------------\n\n## Wednesday: Closing Out DFT and Limit Cycles, Starting Bifurcations, Back to Waves\n\nWednesday finished off the notes that Tuesday started rather than opening new threads: the discrete Fourier transform notes (covering the CCRMA derivation plus the 3Blue1Brown/Brunton intuition) got finished, and so did the limit-cycle section of Strogatz. With both of those closed out, the next chapter in Strogatz, on bifurcations, got started.\n\nSeparately, Wednesday's reading also went back to waves: a refresher on group velocity from *Waves: A Mathematical Approach to the Common Types of Wave Motion*, and then chapters 15, 16, and 17 of *An Introduction to the Mathematical Theory of Waves*. The group velocity refresher is a useful one to have fresh, since Tuesday's write-up above had already reached for the phase velocity/group velocity distinction (treating a single Fourier component's wavenumber as a phase velocity, and a tracked cohort's actual trajectory through size-space as the group velocity) without having the underlying wave theory freshly in mind at the time.\n\n### Can You Beat Constant Fishing by Fishing Only the Peaks?\n\nThe other Wednesday thread continued an investigation that had been running in parallel this week on the same Anchovy size-spectrum setup: given that biomass oscillates in boom-bust cycles, is it better to fish constantly, or only in pulses timed to the peaks?\n\nAn earlier draft of this used a box-selectivity gear catching only \"sub-adults\" (sizes between half of $w_{mat}$ and $w_{mat}$), i.e. fish that hadn't yet had a chance to reproduce. That's not a realistic fishery, so it was replaced with mizer's built-in knife-edge selectivity at $w_{mat}$: nothing below maturity weight is ever caught, only mature individuals, the standard \"minimum landing size\" idealisation.\n\nSeparately, the first version of \"fish only at the peaks\" found peak times once, in advance, by running the unfished trajectory all the way to $t=600$ and scanning it for local maxima, then baked those fixed times into a constant effort schedule. That's static, and more importantly it's circular for any real use of this model: peak timing isn't knowable in advance without already having run the unfished case to completion first. The fix uses mizer's `setRateFunction()` to swap in a custom fishing-mortality function that detects peaks live, from the actual (fished) trajectory as it's being simulated, with no foreknowledge:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mizer resolves a custom rate function by name via get(), searched from\n# wherever mizer's own internal code calls it -- that lookup never reaches a\n# closure stashed inside another R function's local frame, so this factory\n# (and the name it gets assigned to) has to live at top level, not inside\n# modelling_fishing_at_peaks() below.\nmake_dynamic_peak_FMort <- function(window) {\n  state <- new.env()\n  state$t_prev     <- NA_real_   # time of the last distinct recorded point\n  state$bm_prev1   <- NA_real_   # biomass one recorded step back\n  state$bm_prev2   <- NA_real_   # biomass two recorded steps back\n  state$fish_until <- -Inf       # fishing stays on until this time\n\n  function(params, n, n_pp, n_other, t, effort, e_growth, pred_mort, ...) {\n    bm <- sum(n[1, ] * params@w * params@dw)\n\n    # predictor-corrector calls FMort twice per dt at the same t; only\n    # advance the rolling history once per distinct time point\n    if (is.na(state$t_prev) || t > state$t_prev) {\n      if (!is.na(state$bm_prev2) &&\n          state$bm_prev1 > state$bm_prev2 && state$bm_prev1 > bm) {\n        # bm_prev1, recorded at state$t_prev, was a local peak in the\n        # actual (fished) trajectory -> open/extend the fishing window\n        state$fish_until <- max(state$fish_until, state$t_prev + window)\n      }\n      state$bm_prev2 <- state$bm_prev1\n      state$bm_prev1 <- bm\n      state$t_prev   <- t\n    }\n\n    dynamic_effort <- effort\n    dynamic_effort[] <- if (t <= state$fish_until) effort else 0\n\n    mizerFMort(params, n = n, n_pp = n_pp, n_other = n_other, t = t,\n               effort = dynamic_effort, e_growth = e_growth, pred_mort = pred_mort, ...)\n  }\n}\n\nmodelling_steady_state <- function(resource_decrease = 1, f_effort = 0.3) {\n  p <- list(dt = 0.001, dx = 0.1, w_min = 0.0003, w_max = 66.5, w_mat = 10,\n            alpha = 0.1, gamma = 750, lambda = 2.05, a0 = 100)\n  kappa <- p$a0 * exp(-6.9 * (p$lambda - 1))\n  no_w  <- round(log(p$w_max / p$w_min) / p$dx)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\", w_min = p$w_min, w_max = p$w_max, w_mat = p$w_mat,\n    no_w = no_w, lambda = p$lambda, kappa = kappa, alpha = p$alpha,\n    gamma = p$gamma, ks = 0\n  )\n  r <- getResourceRate(params) * resource_decrease\n  params <- setResource(params, resource_rate = r, resource_dynamics = \"resource_semichemostat\")\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                 effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n  sim <- project(sim, t_max = 90, dt = 0.1, t_save = 0.2,\n                 effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n  sim_300 <- project(sim, t_max = 200, dt = 0.1, t_save = 0.2,\n                     effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n\n  # Constant fishing from t = 300 onwards, same realistic knife-edge gear.\n  params_fished <- sim_300@params\n  gp <- params_fished@gear_params\n  gp$sel_func        <- \"knife_edge\"\n  gp$knife_edge_size <- p$w_mat\n  gp$catchability    <- 1\n  gp$w_low           <- NULL\n  gp$w_high          <- NULL\n  gear_params(params_fished) <- gp\n\n  sim_300_fished        <- sim_300\n  sim_300_fished@params <- params_fished\n\n  project(sim_300_fished, t_max = 300, dt = 0.1, t_save = 0.2,\n         effort = f_effort, progress_bar = FALSE, method = \"predictor-corrector\")\n}\n\nmodelling_fishing_at_peaks <- function(resource_decrease = 0.001, f_effort = 0.3, peak_window = 1) {\n  p <- list(dt = 0.001, dx = 0.1, w_min = 0.0003, w_max = 66.5, w_mat = 10,\n            alpha = 0.1, gamma = 750, lambda = 2.05, a0 = 100)\n  kappa <- p$a0 * exp(-6.9 * (p$lambda - 1))\n  no_w  <- round(log(p$w_max / p$w_min) / p$dx)\n\n  params <- newSingleSpeciesParams(\n    species_name = \"Anchovy\", w_min = p$w_min, w_max = p$w_max, w_mat = p$w_mat,\n    no_w = no_w, lambda = p$lambda, kappa = kappa, alpha = p$alpha,\n    gamma = p$gamma, ks = 0\n  )\n  r <- getResourceRate(params) * resource_decrease\n  params <- setResource(params, resource_rate = r, resource_dynamics = \"resource_semichemostat\")\n  params@initial_n_pp[] <- params@cc_pp * 0.1\n\n  sim <- project(params, t_max = 10, dt = 0.1, t_save = 0.2,\n                 effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n  sim <- project(sim, t_max = 90, dt = 0.1, t_save = 0.2,\n                 effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n  sim_300 <- project(sim, t_max = 200, dt = 0.1, t_save = 0.2,\n                     effort = 0, progress_bar = FALSE, method = \"predictor-corrector\")\n\n  params_fished <- sim_300@params\n  gp <- params_fished@gear_params\n  gp$sel_func        <- \"knife_edge\"\n  gp$knife_edge_size <- p$w_mat\n  gp$catchability    <- 1\n  gp$w_low           <- NULL\n  gp$w_high          <- NULL\n  gear_params(params_fished) <- gp\n\n  # Fish only at peaks, never at troughs, detected live via the FMort hook\n  # above -- selectivity (just set, on params_fished) is never touched again.\n  assign(\"dynamic_peak_FMort\", make_dynamic_peak_FMort(window = peak_window), envir = .GlobalEnv)\n  params_fished_peaks <- setRateFunction(params_fished, \"FMort\", \"dynamic_peak_FMort\")\n\n  sim_300_fished_peaks        <- sim_300\n  sim_300_fished_peaks@params <- params_fished_peaks\n\n  project(sim_300_fished_peaks, t_max = 300, dt = 0.1, t_save = 0.2,\n         effort = f_effort, progress_bar = FALSE, method = \"predictor-corrector\")\n}\n```\n:::\n\n\n`make_dynamic_peak_FMort()` is a closure factory. The environment it creates (`state`) is captured by the function it returns, so that function can read and mutate `t_prev`/`bm_prev1`/`bm_prev2`/`fish_until` across thousands of calls during a single `project()` run without mizer's API giving it any explicit mechanism for that. Peak detection itself is the classic \"is the middle of three points a local max\" test, applied causally: it only confirms `bm_prev1` was a peak once a *later* point (`bm`) shows biomass has already started falling, so this can only react to a peak one step after it happened, not anticipate one in advance, unlike the old offline version. Once confirmed, a `window`-year fishing pulse opens from that point forward; overlapping pulses extend rather than reset (`max(state$fish_until, ...)`). The function never reimplements how selectivity, catchability, and effort combine, it just substitutes a gated `effort` into mizer's own `mizerFMort()`, so only effort changes, never selectivity.\n\n#### Constant Fishing vs. Fishing the Peaks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_const_fish <- modelling_steady_state(0.001)\nsim_peaks      <- modelling_fishing_at_peaks()\n\nplotYield(sim_const_fish, sim_peaks, log = \"x\", tlim = c(550, 600))\n```\n\n::: {.cell-output-display}\n![](2026-06-23-day-twelve_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe first version of this comparison used each function's own default resource scenario (`modelling_steady_state()`'s default is full resource, `modelling_fishing_at_peaks()`'s default is heavily depleted resource), which is not a fair comparison of fishing strategies, it's a comparison of two different ecosystems. Worse, under that mismatch the constant-fishing run produced *exactly* zero yield from $t=300$ onward, while total biomass stayed healthy and oscillating. Checking `range(selectivity)` ruled out a gear bug (it was a proper `[0, 1]`), which narrowed it to either a real population collapse or a structural mismatch between the two resource scenarios. The code above now matches `resource_decrease` between the two calls, which should remove that confound, but a clean re-check of the zero-yield anomaly specifically, biomass-above-$w_{mat}$ over time, with and without fishing, hasn't been re-run since making that fix. Treat the comparison plot as illustrative of the mechanism, not yet a verified result.\n\n#### Hunting for the Best Effort and Window\n\nWith a working dynamic peaks-only model, the next question was what combination of fishing effort and pulse window maximises yield:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_yield_summary <- function(f_effort, peak_window) {\n  sim <- modelling_fishing_at_peaks(f_effort = f_effort, peak_window = peak_window)\n  yt  <- getYield(sim)\n  t   <- as.numeric(rownames(yt))\n  mean(yt[t > 300, ])\n}\n\neffort_grid <- seq(0.1, 1, length.out = 5)\nwindow_grid <- seq(0.5, 5, length.out = 5)\n\ngrid <- expand.grid(f_effort = effort_grid, peak_window = window_grid)\ngrid$mean_yield <- mapply(peak_yield_summary, grid$f_effort, grid$peak_window)\ngrid[order(-grid$mean_yield), ][1:5, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   f_effort peak_window   mean_yield\n5         1       0.500 4.321194e-05\n10        1       1.625 4.008065e-05\n20        1       3.875 3.814550e-05\n15        1       2.750 3.804524e-05\n25        1       5.000 3.745273e-05\n```\n\n\n:::\n:::\n\n\nThe best of this first, coarse grid was effort = 1, window = 0.5 years (mean yield $\\approx 4.32\\times10^{-5}$), with yield rising monotonically across the whole tested effort range and falling off only mildly as the window lengthened. Both of those are edges of the grid, not an interior optimum, so the search was widened:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffort_grid <- c(1, 1.5, 2, 2.5, 3, 4, 5, 7, 10)\nwindow_grid <- c(0.1, 0.25, 0.5, 0.75, 1)\n\ngrid2 <- expand.grid(f_effort = effort_grid, peak_window = window_grid)\ngrid2$mean_yield <- mapply(peak_yield_summary, grid2$f_effort, grid2$peak_window)\ngrid2[order(-grid2$mean_yield), ][1:5, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   f_effort peak_window   mean_yield\n9        10        0.10 0.0004022949\n18       10        0.25 0.0003083597\n8         7        0.10 0.0002840509\n27       10        0.50 0.0002735408\n36       10        0.75 0.0002624430\n```\n\n\n:::\n:::\n\n\nSame story, an order of magnitude further out: best was effort = 10, window = 0.1 years (mean yield $\\approx 4.02\\times10^{-4}$), still sitting on both edges of the grid. Constraining the search to a more operationally plausible range didn't fix this either:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffort_grid <- seq(0.1, 2, length.out = 8)\nwindow_grid <- seq(0.5, 3, length.out = 6)\n\ngrid3 <- expand.grid(f_effort = effort_grid, peak_window = window_grid)\ngrid3$mean_yield <- mapply(peak_yield_summary, grid3$f_effort, grid3$peak_window)\ngrid3[order(-grid3$mean_yield), ][1:5, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   f_effort peak_window   mean_yield\n8  2.000000         0.5 8.144766e-05\n16 2.000000         1.0 7.321432e-05\n7  1.728571         0.5 7.146888e-05\n48 2.000000         3.0 6.880975e-05\n24 2.000000         1.5 6.693908e-05\n```\n\n\n:::\n:::\n\n\nBest again landed on the boundary: effort = 2, window = 0.5. Widening or narrowing the box just relocates the wall; it never produces an interior maximum.\n\nThis shows how raw yield, as an optimisation target, is structurally degenerate here. A pulse removes roughly $1-e^{-F\\cdot\\text{window}}$ of the standing mature biomass, a fraction that climbs toward (but can never exceed) 100% as effort rises and the window shrinks. Because the pulse is brief, it never touches the juveniles driving recruitment, so the stock fully rebuilds before the next peak regardless of how hard a given pulse hit it. Nothing in raw yield penalises \"more effort, less time\", so the optimum is always at whatever the most extreme effort/shortest window in the search range happens to be: take as much of each peak as possible, as fast as possible, and leave the rest of the cycle alone. That's a real result about the biology, no biological mechanism here makes brief, intense harvesting unsustainable, but it also means the search needs a different objective before \"optimal effort and window\" means anything a real fishery could act on.\n\n------------------------------------------------------------------------\n\n## What's Next\n\n- **Chapters 18, 19, and 20 of *An Introduction to the Mathematical Theory of Waves*.** Continuing on from 15–17.\n- **Work through exercises from the textbooks** (Strogatz and the wave-motion books) rather than just reading, to actually solidify the DFT, limit-cycle, bifurcation, and group-velocity material rather than letting it stay passive.\n- **Read over the Mizer Course material on tuning results.** Useful to revisit now, with a live model that needs its own tuning decisions justified rather than just copied from the course examples.\n",
    "supporting": [
      "2026-06-23-day-twelve_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}